### ISSUE TITLE
Bor fails on start up. 

### ISSUE THREAD

**Issue by philip-morlier** [maticnetwork/bor#1011]
From the head of the master branch, after building the binary, the application fails to launch with the following error:

geth flag redefined: goerli
panic: geth flag redefined: goerli

This was true for `v0.5.0` as well.

**Comment by maoueh** [comment]
Use `make bor`, the CLI entrypoint has changed and it's not `cmd/geth` anymore (the new one is `cmd/cli`, so installing from source could be done as before with:

```
go build -o `go env GOPATH`/bin/bor ./cmd/cli
```

(This above is more or less what `make bor` does)

**Comment by philip-morlier** [comment]
Thank you

**Comment by temaniarpit27** [comment]
Closing this.
Please reopen if required
