### ISSUE TITLE
core.TxPool.truncateQueue() chucks out newer rather than older transactions when queue is too long

### ISSUE THREAD

**Issue by svenski123** [maticnetwork/bor#1016]
The eviction ordering in truncateQueue() is reversed so that newer transactions are erroneously discarded instead of older transactions when the global queue limit is exceeded.

This bug was corrected in upstream geth last year - it would be worthwhile merging or cherry picking into bor.

https://github.com/ethereum/go-ethereum/issues/24907
https://github.com/ethereum/go-ethereum/issues/24908

```
commit 2bfd9a28d11714c7880243ea28169d5f3e8fff11
Author: zhaochonghe <41711151+zhaochonghe@users.noreply.github.com>
Date:   Thu May 19 15:25:22 2022 +0800

    core: fix the order of address in queue (#24907)

    reverse the order of address in queue
```

**Comment by manav2401** [comment]
Seems answered, closing for now.
