### ISSUE TITLE
Unable to sync a bor node from scratch

### ISSUE THREAD

**Issue by bgiegel** [maticnetwork/bor#1019]
Hi !

I’m currently trying to start a new polygon node. I successfully synced heimdall.

Now I’m trying to start bor but I have trouble finding peers. The node logs something like this : 

```
Starting bor server...
INFO [10-03|03:08:24.023] GRPC Server started                      addr=[::]:3131
INFO [10-03|03:08:24.024] Set global gas cap                       cap=50,000,000
INFO [10-03|03:08:24.024] Allocated trie memory caches             clean=153.00MiB dirty=256.00MiB
INFO [10-03|03:08:24.024] Allocated cache and file handles         database=/home/polygon/.bor/bor/chaindata cache=512.00MiB handles=524,288
INFO [10-03|03:08:24.036] Opened ancient database                  database=/home/polygon/.bor/bor/chaindata/ancient readonly=false
INFO [10-03|03:08:24.036] Writing custom genesis block
INFO [10-03|03:08:24.037] Persisted trie from memory database      nodes=12 size=1.86KiB time="79.354µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [10-03|03:08:24.038] Initialised chain configuration          config="{ChainID: 137 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Arrow Glacier: <nil>, MergeFork: <nil>, Terminal TD: <nil>, Engine: bor}"
INFO [10-03|03:08:24.039] Gasprice oracle is ignoring threshold set threshold=2
INFO [10-03|03:08:24.039] Initialising Ethereum protocol           network=137 dbversion=<nil>
INFO [10-03|03:08:24.039] Loaded most recent local header          number=0 hash=a9c28c..97de1b td=1 age=3y4mo2w
INFO [10-03|03:08:24.039] Loaded most recent local full block      number=0 hash=a9c28c..97de1b td=1 age=3y4mo2w
INFO [10-03|03:08:24.039] Loaded most recent local fast block      number=0 hash=a9c28c..97de1b td=1 age=3y4mo2w
WARN [10-03|03:08:24.039] Failed to load snapshot, regenerating    err="missing or corrupted snapshot"
INFO [10-03|03:08:24.039] Rebuilding state snapshot
INFO [10-03|03:08:24.039] Resuming state snapshot generation       root=654f28..1527c8 accounts=0 slots=0 storage=0.00B elapsed="169.676µs"
INFO [10-03|03:08:24.040] Generated state snapshot                 accounts=10 slots=0 storage=551.00B elapsed="548.886µs"
INFO [10-03|03:08:24.040] Regenerated local transaction journal    transactions=0 accounts=0
WARN [10-03|03:08:24.040] Error reading unclean shutdown markers   error="leveldb: not found"
INFO [10-03|03:08:24.040] Starting peer-to-peer node               instance=bor/v0.4.0/linux-amd64/go1.20.4
INFO [10-03|03:08:24.041] Stored checkpoint snapshot to disk       number=0 hash=a9c28c..97de1b
INFO [10-03|03:08:24.041] Commit Interrupt. Pre-committing the current block block=1
INFO [10-03|03:08:24.045] New local node record                    seq=1,696,302,504,044 id=110bc11488bf11b9 ip=127.0.0.1 udp=30303 tcp=30303
INFO [10-03|03:08:24.046] Started P2P networking                   self=enode://0a71b3e9e55bd74ee1741216a16027167cb9c5b96921c1e17f829c50e4c0bd7a5dc4a62e24408ea03ef396994f6d2ff42ea15da95f41464cf43b28deb1c0cd05@127.0.0.1:30303
INFO [10-03|03:08:24.046] IPC endpoint opened                      url=/home/polygon/.bor/bor.ipc
INFO [10-03|03:08:24.047] HTTP server started                      endpoint=127.0.0.1:8545 auth=false prefix= cors=localhost vhosts=localhost
INFO [10-03|03:08:24.047] TxFetcher                                txArrivalWait=500ms
WARN [10-03|03:08:24.051] unable to whitelist checkpoint - first run err="missing checkpoint blocks"
INFO [10-03|03:08:34.563] Looking for peers                        peercount=0 tried=0 static=0
INFO [10-03|03:08:59.046] Looking for peers                        peercount=0 tried=2 static=0
WARN [10-03|03:10:04.054] unable to whitelist checkpoint           err="missing checkpoint blocks"
WARN [10-03|03:11:44.054] unable to whitelist checkpoint           err="missing checkpoint blocks"
```
and then continues forever with the `unable to whitelist checkpoint` and `Looking for peers`.

I followed the documentation here : https://wiki.polygon.technology/docs/pos/operate/node/full-node-docker/

I tried to setup the bootnodes listed at the end of the page for the mainnet network. Here is the config.toml file : 

```
datadir = "/var/lib/polygon/bor"

[p2p]
  [pep.discovery]
    bootnodes = ["enode://b8f1cc9c5d4403703fbf377116469667d2b1823c0daf16b7250aa576bacf399e42c3930ccfcb02c5df6879565a2b8931335565f0e8d3f8e72385ecf4a4bf160a@3.36.224.80:30303", "enode://8729e0c825f3d9cad382555f3e46dcff21af323e89025a0e6312df541f4a9e73abfa562d64906f5e59c51fe6f0501b3e61b07979606c56329c020ed739910759@54.194.245.5:30303"]
# Because we're running inside docker, we'll likely need to change the way we connect to heimdall
[heimdall]
  url = "http://localhost:1317"

# Assuming you want to access the RPC, you'll need to make a change here as well
[jsonrpc]
  [jsonrpc.http]
    enabled = true
    host = "0.0.0.0"
```

and here is the command I use to start the server : 

```
/usr/bin/bor server \
          --chain=mainnet \
          --port=30303 \
          --http=true \
          --http.port=8545 \
          --http.vhosts=* \
          --gcmode=archive \
          --cache=8192 \
          --config=/var/lib/polygon/bor/config.toml
```
          
Heimdall version : v0.3.4
Bor version : v0.4.0

any idea what is wrong with my setup. I’m really stuck. I even tried a snapshot restore and after downloading almost 3 TB of data it failed with an error saying that a file was missing in the ancients/ directory...

**Comment by bgiegel** [comment]
OK I had to post a comment to realize my version was actually pretty old and that a new release come up recently. So I’ve updated to heimdall v1.0.1 and bor v1.0.4.

And now the bor node seems to sync. But it seems very slow with errors and warning in the logs about communication issues with heimdall: 

```
INFO [10-03|07:14:58.170] Fetching state updates from Heimdall     fromID=358 to=2020-08-05T07:14:26Z
INFO [10-03|07:14:58.170] Fetching state sync events               queryParams="from-id=358&to-time=1596611666&limit=50"
INFO [10-03|07:14:58.172] StateSyncData                            gas=0       number=2,790,592 lastStateID=357 "total records"=0 "fetch time"=4   "process time"=0
WARN [10-03|07:14:58.180] Synchronisation failed, dropping peer    peer=54fc26a06ed2ad2e140b144cf5bc71cae2eec5ca42f432be6ca0645abe593b9c err="retrieved hash chain is invalid: invalid validator list on sprint end block"
WARN [10-03|07:14:58.180] Synchronisation failed, retrying         peer=54fc26a06ed2ad2e140b144cf5bc71cae2eec5ca42f432be6ca0645abe593b9c err="peer is unknown or unhealthy"
INFO [10-03|07:14:58.180] Commit Interrupt. Pre-committing the current block block=2,790,655
INFO [10-03|07:14:58.180] StateSyncData                            gas=0       number=2,790,592 lastStateID=357 "total records"=0 "fetch time"=11  "process time"=0
INFO [10-03|07:14:58.614] Retrying again in 5 seconds to fetch data from Heimdall path=/milestone/latest                  attempt=3
INFO [10-03|07:15:03.614] Retrying again in 5 seconds to fetch data from Heimdall path=/milestone/latest                  attempt=4
INFO [10-03|07:15:06.341] Writing clean trie cache to disk         path=/var/lib/polygon/bor/bor/triecache threads=1
INFO [10-03|07:15:06.344] Persisted the clean trie cache           path=/var/lib/polygon/bor/bor/triecache elapsed=2.621ms
INFO [10-03|07:15:06.364] Regenerated local transaction journal    transactions=0 accounts=0
INFO [10-03|07:15:06.399] Got new checkpoint from heimdall         start=48,266,918 end=48,267,173 rootHash=0x48634c27eaa3c3301d5c2bd95bb5ec41d34d626d992c27211d0f27868e61a52b
WARN [10-03|07:15:06.399] Failed to whitelist checkpoint           err="missing blocks"
WARN [10-03|07:15:06.399] unable to handle whitelist checkpoint    err="missing blocks"
WARN [10-03|07:15:08.614] an error while trying fetching from Heimdall attempt=5 error="error while fetching data from Heimdall: response code 500"
INFO [10-03|07:15:08.614] Retrying again in 5 seconds to fetch data from Heimdall path=/milestone/latest                  attempt=5
WARN [10-03|07:15:12.474] Synchronisation failed, dropping peer    peer=82e2eca1069dd62d0aa4039d7cfe5de615076797687411ebd116e94cd9d9be67 err=timeout
INFO [10-03|07:15:13.614] Retrying again in 5 seconds to fetch data from Heimdall path=/milestone/latest                  attempt=6
ERROR[10-03|07:15:18.611] Failed to fetch latest milestone for whitelisting err="context deadline exceeded"
WARN [10-03|07:15:18.611] unable to handle whitelist milestone     err="failed to fetch latest milestone"
WARN [10-03|07:15:18.612] an error while trying fetching from Heimdall attempt=1 error="error while fetching data from Heimdall: response code 500"
```

any idea on how to improve that ?

**Comment by pitbred2** [comment]
Are you trying to synchronize a bor without a snapshots?
I couldn't even synchronize with snapshots. Synchronization is very slow and constantly lags behind the blockchain. The developers cannot answer anything. Good luck to you.

**Comment by bgiegel** [comment]
Actually I’m trying to get answers :)

That’s my next try restoring the snapshot.

**Comment by anshalshukla** [comment]
@pitbred2 @bgiegel for update list of bootnodes please refer to [this](https://wiki.polygon.technology/docs/pos/operate/node/full-node-docker/#seed-nodes-and-bootnodes). Whitelisting errors can be safely ignored for now as the milestone service will kick-in post HF scheduled for next week. Using [snapshots](https://snapshots.polygon.technology/) is the easiest way to get the node to sync so I'll suggest to try that.

**Comment by bgiegel** [comment]
Ok thanx for the answer. I’m currently trying to download the snapshots. I still have 2 questions : 

- how fast the size of the snapshots is expected to grow ? Because last week I saw it was 4.2TB. Now it’s 4.7TB. So it’s growing super fast. We were running our nodes by doing a very frequent prune to keep it under 3TB. But now due to the size of the snapshot it seems impossible to run a node with less than 6TB SSD. 

- Is possible somehow to shrink the size of the "ancients" folder. Some of the nodes we run are there since 2021, and now the ancients dir is 1.5TB. I now that it’s recommended to mount the ancients dir on a slow HDD disk. But currently our cloud provider doesn’t allow this (we have dedicated HV), So I’m a bit stuck I can’t increase the disk size because I’m constrained in size and I can’t remove that ancients dir, and I can’t restore a snapshot because it’s too big... And syncing from scratch takes an infinit amount of time...

**Comment by lcgogo** [comment]
I try the snapshot download https://snapshots.polygon.technology/ these days again (I did it at about 4 months ago, and it was 2.8TB).
Now, need at least 7.5TB for the download and extract the bor-mainnet-snapshot zst file.

I only watch the latest block information and send transaction.
Can bor provide some light node mode to quick sync the latest block information?

> Ok thanx for the answer. I’m currently trying to download the snapshots. I still have 2 questions :
> 
>     * how fast the size of the snapshots is expected to grow ? Because last week I saw it was 4.2TB. Now it’s 4.7TB. So it’s growing super fast. We were running our nodes by doing a very frequent prune to keep it under 3TB. But now due to the size of the snapshot it seems impossible to run a node with less than 6TB SSD.
> 
>     * Is it possible somehow to shrink the size of the "ancients" folder ? Some of the nodes we run are there since 2021, and now the ancients dir is 1.5TB. I know that it’s recommended to mount the ancients dir on a slow HDD disk. But currently our cloud provider doesn’t allow this (we have dedicated HV), So I’m a bit stuck I can’t increase the disk size because I’m constrained in size to 3.2TB on this cluster and I can’t remove that ancients dir, and I can’t restore a snapshot because it’s too big... And syncing from scratch takes an infinit amount of time...

**Comment by manav2401** [comment]
Hey @lcgogo @bgiegel, apologies for the delay. I'll try to answer all the questions posted above. 

1. Regarding issues with communicating with heimdall. Could you please make sure that your heimdall is well in sync and is upgraded to the latest version which is [v1.0.2](https://github.com/maticnetwork/heimdall/releases/tag/v1.0.2) in this case. Also, same for bor. You might want to use the latest [v1.0.6](https://github.com/maticnetwork/bor/releases/tag/v1.0.6) version. It says there's an error fetching milestone with this error: `error while fetching data from Heimdall: response code 500` and seems like heimdall isn't working correctly. 
2. Your configurations looks incorrect. Until v1.0.6 in bor, we don't support cli args when a config file is provided. We're aware that this is counter intuitive from a general flag behaviour and this support has been added in v1.1.x versions and should be available soon in the latest stable release. Until then you might want to move the cli args/flags you're passing to the toml config. Currently, none of the flags you've provided are being applied. It'll still work as most of them are default (e.g. chain=mainnet). But, some other params like `gcmode` and `cache` won't get applied. I recommend moving them to config.toml. You might find more details about this [here](https://github.com/maticnetwork/bor/tree/master/docs). 
3. A quick suggestion - if you're running archive mode with bor, it might take months to sync from scratch. We don't have snapshots for that as it has reached to 40TB+ in size. We recommend using [erigon](https://github.com/ledgerwatch/erigon) instead which fully supports polygon mainnet and testnet and is comparatively less in size as compared to bor (note that it's just archive mode - for full mode, bor might have less size). 
4. Re. snapshots, yes they grow pretty fast due to increase in state and historical data. As you mentioned, yes you might have to move the ancients folder to a normal HDD (or a different partition) if possible. Another option, which is not fully recommended is ancient data pruning. We've a branch (which might not updated with the latest release currently) which has additional functionality to prune ancient data and only keep the recent state and block data. This way you can get rid of the ancient data. But, note that as it opens up some data availability concerns, we do not recommend it and would suggest you to maintain the branch if you're using planning to use it. 
5. Re. the recommended size of snapshot of 7.5 TB, it's generally an upper bound because the snapshots get's downloaded first, then they're extracted and the initial downloaded files will be deleted. If you want to save some space, you might have to attach 2 disks - 1 for download, 1 for extract. Delete the download one once you're done extracting. 
6. Regarding the geth release you mentioned, yes, we're already testing that internally and also have a node fully synced on mainnet. You can expect a release with `PBSS (Path based storage scheme)` enabled which will significantly reduce the size required to run a mainnet node. 
7. And finally coming to the slow sync, it might be great if you can share some more details how the node's working after doing step (1) and (2). Moreover, lot of factors play in during syncing and one of the major ones is the p2p configurations. It will be great if you can share some details on how many peers your node is connected to. 

Hope this clarifies, thank you!

Hope I was able to ans

**Comment by lcgogo** [comment]
> Hey @lcgogo @bgiegel, apologies for the delay. I'll try to answer all the questions posted above.
> 
>     1. Regarding issues with communicating with heimdall. Could you please make sure that your heimdall is well in sync and is upgraded to the latest version which is [v1.0.2](https://github.com/maticnetwork/heimdall/releases/tag/v1.0.2) in this case. Also, same for bor. You might want to use the latest [v1.0.6](https://github.com/maticnetwork/bor/releases/tag/v1.0.6) version. It says there's an error fetching milestone with this error: `error while fetching data from Heimdall: response code 500` and seems like heimdall isn't working correctly.
> 
>     2. Your configurations looks incorrect. Until v1.0.6 in bor, we don't support cli args when a config file is provided. We're aware that this is counter intuitive from a general flag behaviour and this support has been added in v1.1.x versions and should be available soon in the latest stable release. Until then you might want to move the cli args/flags you're passing to the toml config. Currently, none of the flags you've provided are being applied. It'll still work as most of them are default (e.g. chain=mainnet). But, some other params like `gcmode` and `cache` won't get applied. I recommend moving them to config.toml. You might find more details about this [here](https://github.com/maticnetwork/bor/tree/master/docs).
> 
>     3. A quick suggestion - if you're running archive mode with bor, it might take months to sync from scratch. We don't have snapshots for that as it has reached to 40TB+ in size. We recommend using [erigon](https://github.com/ledgerwatch/erigon) instead which fully supports polygon mainnet and testnet and is comparatively less in size as compared to bor (note that it's just archive mode - for full mode, bor might have less size).
> 
>     4. Re. snapshots, yes they grow pretty fast due to increase in state and historical data. As you mentioned, yes you might have to move the ancients folder to a normal HDD (or a different partition) if possible. Another option, which is not fully recommended is ancient data pruning. We've a branch (which might not updated with the latest release currently) which has additional functionality to prune ancient data and only keep the recent state and block data. This way you can get rid of the ancient data. But, note that as it opens up some data availability concerns, we do not recommend it and would suggest you to maintain the branch if you're using planning to use it.
> 
>     5. Re. the recommended size of snapshot of 7.5 TB, it's generally an upper bound because the snapshots get's downloaded first, then they're extracted and the initial downloaded files will be deleted. If you want to save some space, you might have to attach 2 disks - 1 for download, 1 for extract. Delete the download one once you're done extracting.
> 
>     6. Regarding the geth release you mentioned, yes, we're already testing that internally and also have a node fully synced on mainnet. You can expect a release with `PBSS (Path based storage scheme)` enabled which will significantly reduce the size required to run a mainnet node soon.
> 
>     7. And finally coming to the slow sync, it might be great if you can share some more details how the node's working after doing step (1) and (2). Moreover, lot of factors play in during syncing and one of the major ones is the p2p configurations. It will be great if you can share some details on how many peers your node is connected to.
> 
> 
> Hope this clarifies, thank you!

Thanks for your apply. Hope the PBSS (Path based storage scheme) release coming soon.

**Comment by 0xKrishna** [comment]
Closing this for now, Please reopen if needed.
