### ISSUE TITLE
What are the use-cases for noprefetch flag?

### ISSUE THREAD

**Issue by Aracki** [maticnetwork/bor#1033]
For both geth and bor there is similar explanations:
```
 -cache.noprefetch
    Disable heuristic state prefetch during block import (less CPU and disk IO, more time waiting for data) (default: false)
```

I am running archive nodes and would like to lower RPC latency as much as I can. Everyone out there is using default false for this flag. 

What does that exactly mean? How would node behave with this flag set to true?

**Comment by 0xKrishna** [comment]
Hi @Aracki, This flag is not related to RPC latency.
Also it works the same in bor as it works in geth, In default false config it will allow the heuristic state prefetching for followup blocks, If you change it to true it will disable that.

**Comment by Aracki** [comment]
Thanks for explanation!
