### ISSUE TITLE
invalid opcode: PUSH0

### ISSUE THREAD

**Issue by tab00** [maticnetwork/bor#1036]
I'm unable to deploy my contract to Polygon / Mumbai. I get the error message in the title.
It works fine on zkEVM though. So what's wrong with Polygon / Mumbai?
Please fix it ASAP.
Thank you.

**Comment by Doc-Pixel** [comment]
What EVM version are you compiling on? 

As you can read on the bor repo:

Bor is the Official Golang implementation of the Polygon PoS blockchain. It is a fork of [geth](https://github.com/ethereum/go-ethereum) and is EVM compatible **`(upto London fork)`**.

**Comment by tab00** [comment]
> What EVM version are you compiling on?

The latest.

So is bor no longer EVM equivalent?

**Comment by tab00** [comment]
OK thanks, that's good to hear, we're watiing patiently. So when can we expect it to start working on Mumbai (so that we can run tests) and then mainnet?

**Comment by marcello33** [comment]
@tab00 we don't have official dates yet, but I believe it'd happen on Mumbai within one month

**Comment by tab00** [comment]
Thank you @marcello33 , we're eagerly looking forward to it.
