### ISSUE TITLE
Snapshot broken

### ISSUE THREAD

**Issue by kaber2** [maticnetwork/bor#1040]
Unpacking the latest snapshot, I receive an error on the very last part (ct). Checksums are correct, zstd fails on incomplete block and the entire snapshot is unusable.

Could you please verify the snapshot? Thanks.

**Comment by kaber2** [comment]
Just an additional note: its possible that this was caused by a prematurely closed pipe. Before you waste any time on this, let me verify.

**Comment by rebelArtists** [comment]
hey @kaber2, sg, have the original bulk .tar.zst (that we split) and unpacking now to verify if any root issue

**Comment by rebelArtists** [comment]
@kaber2 you're right, corrupt tar at very end of unpacking, thanks for raising this and your patience here

in the mean time, we've reverted bor-mainnet-parts.txt to last working version so if you run script again you should be unblocked

we'll be investigating and update here once valid latest pruned snapshot is live

**Comment by kaber2** [comment]
Thank you for investigating. Given that a resaync from last months state would take ages, please update this issue once you fixed the problem.

Thanks!

**Comment by kaber2** [comment]
As an additional note, I have 14 nodes which are down due to a premature expecation of this working out fine. So the sooner you can give the green light, the better my blood pressure will be :)

**Comment by rebelArtists** [comment]
hey @kaber2 resync would be from just a few days ago (2023-10-09 since we have daily incremental snaps) if you decide to move forward with existing data. i'd expect you'd fully sync in less than a day

we are actively working on the latest pruned version fix and will keep you posted

**Comment by rebelArtists** [comment]
@kaber2 new bor-mainnet pruned snapshot has landed. the snapshot is 1.9TB compressed ==> 2.5T decompressed. previous tar.zst must have been corrupted from cmd interruption/etc, and we'll finetune our alarms to catch this next time

# evidence of success this round

before:
$ pv bor-mainnet-snapshot-bulk-2023-10-11.tar.zst | tar -I zstd -xf - -C .
1.76TiB 3:24:45 [ 149MiB/s] [====================================================>] 100%            
/*stdin*\ : Read error (39) : premature end 
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

after:
$ pv bor-mainnet-snapshot-bulk-2023-10-12.tar.zst | tar -I zstd -xf - -C .
1.86TiB 3:51:28 [ 140MiB/s] [====================================================>] 100%


if you could please try again and lmk if you run into any more issues

**Comment by rebelArtists** [comment]
closing as complete
