### ISSUE TITLE
Untraceable Transaction of 76.86737159498533 MATIC from Address 0x59342f5d6ef3d09d148547cf43c0f297a90fdfd3

### ISSUE THREAD

**Issue by medvedev1088** [maticnetwork/bor#1041]
Hello,

I have been investigating a transaction on the Polygon blockchain and encountered an issue where a certain amount of MATIC seems to have been moved from an address without a corresponding transaction or internal transaction that credits the address with the said amount. Below are the details of the transaction and the address:

- Address: [0x59342f5d6ef3d09d148547cf43c0f297a90fdfd3](https://polygonscan.com/address/0x59342f5d6ef3d09d148547cf43c0f297a90fdfd3)
- Transaction: [0x03e64d51b33bc8eeb2cfe2f64150cca57d3736b4a6611cded2e36300eb124588](https://polygonscan.com/tx/0x03e64d51b33bc8eeb2cfe2f64150cca57d3736b4a6611cded2e36300eb124588) (76.86737159498533 MATIC)

The address 0x59342f5d6ef3d09d148547cf43c0f297a90fdfd3 has only one transaction associated with it, which is the withdrawal of 76.86737159498533 MATIC. However, I am unable to find any related transaction or internal transaction that moves the MATIC to the address before this withdrawal. 

I believe this might be indicative of an underlying issue, and it could potentially affect other addresses and transactions as well. Any assistance in understanding or resolving this issue would be greatly appreciated.

**Comment by 0xsharma** [comment]
Hey @medvedev1088 ,

This address received the MATIC amount from L1(Ethereum) chain through state-sync. The corresponding transaction on Ethereum is [0x9ccf8b585b704a443872c0be4d921c725afcef414e2e3bb15b7a556b2bd42c44](https://etherscan.io/tx/0x9ccf8b585b704a443872c0be4d921c725afcef414e2e3bb15b7a556b2bd42c44). 

This transaction bridges the MATIC amount from L1(Ethereum) to L2(Polygon PoS). 

Closing this issue. Feel free to reopen it if there is a follow-up. 
Thank you 💜
