### ISSUE TITLE
/bor/chaindata/ancient/headers.0000.cdat: no such file or directory

### ISSUE THREAD

**Issue by yuanwj210** [maticnetwork/bor#1043]
In order to use the snapshot file save synchronization time use
`curl -L https://raw.githubusercontent.com/maticnetwork/install/main/heimdall.sh | bash -s -- <heimdall_version> <network_type> <node_type>; `
Download snapshot bor, result have to restart again and again, the log shows/bor/chaindata/ancient/headers. 0000. cdat: no to the file or directory,Is there a solution?

**Comment by pratikspatil024** [comment]
Hi @yuanwj210 - did the snap downloading finish without any errors?

**Comment by yuanwj210** [comment]
> 你好@yuanwj210- 快照下载完成后是否没有任何错误？

There was no error in the download. The snapshot contained incremental synchronization content, which caused the file to be overwritten. The problem was resolved after the latest snapshot without incremental snapshot was downloaded.

**Comment by marcello33** [comment]
Ok, thanks @yuanwj210
