### ISSUE TITLE
typo in code core/types/tx_dynamic_fee.go

### ISSUE THREAD

**Issue by brainswa** [maticnetwork/bor#1047]
https://github.com/maticnetwork/bor/blob/06f29851a30f346ba26ca3713ea976ffc33b87e1/core/types/tx_dynamic_fee.go#L137

```
func (tx *DynamicFeeTx) gasPriceU256() *uint256.Int {
	if tx.gasFeeCapUint256 != nil {
		// return tx.gasTipCapUint256
		return tx.gasFeeCapUint256
	}

	tx.gasFeeCapUint256, _ = uint256.FromBig(tx.GasFeeCap)

	return tx.gasFeeCapUint256
}
```

**Comment by pratikspatil024** [comment]
Hi @brainswa - can you please explain a bit more?

**Comment by brainswa** [comment]
@pratikspatil024 function gasPriceU256 need to return tx.gasFeeCapUint256, instead that it's return gasTipCapUint256 when the value has already cached

**Comment by 0xsharma** [comment]
Thank you @brainswa for bringing this to light! We have merged the fix and should be included in upcoming releases.
