### ISSUE TITLE
call returned result of length 312928 exceeding limit 100000

### ISSUE THREAD

**Issue by lxgn** [maticnetwork/bor#1048]
How to start node with worked zero limit

  -rpc.returndatalimit
    Maximum size (in bytes) a result of an rpc request could have (default=100000, use 0 for no limits) (default: 100000)

I'm added in config.toml next line
rpc.returndatalimit = 0
rpc.batchlimit = 0
and add in command line 
ps ax | grep bor
34332 pts/5    Ssl+  10:58 ./bor server -rpc.returndatalimit=0 -rpc.batchlimit=0 -config ../config.toml

But I still get the error
            [error] => Array
                (
                    [code] => -32000
                    [message] => call returned result of length 312928 exceeding limit 100000
                )

How to configure the server so that there are no restrictions?

**Comment by pratikspatil024** [comment]
Hi @lxgn - can you try setting this value to 0 in the `../config.toml` file?

**Comment by lxgn** [comment]
./bor version
Version: 1.0.6
GitCommit: d521b8e266b97efe9c8fdce8167e9dd77b04637d

**Comment by lxgn** [comment]
> Hi @lxgn - can you try setting this value to 0 in the `../config.toml` file?

how to solve a problem?

**Comment by lxgn** [comment]
"rpc.batchlimit" = 0
"rpc.returndatalimit" = 500000
We need to quickly release an update and are too lazy to make a normal config parser.

Adding quotes to the config solves the problem.

**Comment by pratikspatil024** [comment]
Hi @lxgn - yes, as mention in the example config [here](https://github.com/maticnetwork/bor/blob/master/docs/cli/example_config.toml#L13-L14), as well as the [packaging/templates](https://github.com/maticnetwork/bor/tree/master/packaging/templates), quotes is the correct way pass this flag in the TOML file.
