### ISSUE TITLE
snapshot import error

### ISSUE THREAD

**Issue by sukichan-bb** [maticnetwork/bor#1059]
hi, i have tried to down snapshot via your script but it fails. thanks
```
Join parts for bulk-2023-10-12 then extract
/*stdin*\ : Decoding error (36) : Corrupted block detected ============>                                                                                                                             ] 26% ETA 3:18:58
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
 496GiB 1:10:06 [ 120MiB/s] [==========================================>
```

**Comment by cshintov** [comment]
You should add `-v true` to checksum the parts!

**Comment by manav2401** [comment]
Yeah, please try running again with checksum verification.

**Comment by okmrs** [comment]
Anyway it seems to be stale(latest update 2023-10-19) and not completely generated.

**Comment by okmrs** [comment]
Anyway it seems to be stale(last updated 2023-10-19).
It will take a long time to sync fully.

**Comment by manav2401** [comment]
Thanks for the update. Closing this for now.
