### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by kosmosM** [maticnetwork/bor#1071]
#### **System information**

Bor client version: v1.0.4

Heimdall client version: v1.0.1

OS & Version: Linux

Environment: Polygon Mainnet

Type of node: Sentry

#### **Overview of the problem**
Bor sometimes terminates suddenly because of "fatal error: concurrent map iteration and map write".
This error causes "Unclean shutdown" and results in rollback of block synhronization.

Current version of my bor is v1.0.4. I wonder if [Added locks to the tracer #1022](https://github.com/maticnetwork/bor/pull/1022) in v1.0.5 would solve the problem.

#### **Logs / Traces / Output / Error Messages**
 Note: full error logs are too long, so I post part of the logs.

Imported new chain segment               number=49,568,099 hash=63529e..93620c blocks=1    txs=51      mgas=26.483  elapsed=897.977ms   mgasps=29.492   dirty=1.99GiB
fatal error: concurrent map iteration and map write
goroutine 1521834595 [running]:
github.com/ethereum/go-ethereum/trie.(*tracer).copy(...)
/go/src/github.com/maticnetwork/bor/trie/tracer.go:109
github.com/ethereum/go-ethereum/trie.(*Trie).Copy(0xc07dc046c0)
/go/src/github.com/maticnetwork/bor/trie/trie.go:68 +0x196
github.com/ethereum/go-ethereum/trie.(*StateTrie).Copy(...)
/go/src/github.com/maticnetwork/bor/trie/secure_trie.go:261
github.com/ethereum/go-ethereum/core/state.(*cachingDB).CopyTrie(0xc1ae99dc38?, {0x362a668?, 0xc07dc046c0?})
/go/src/github.com/maticnetwork/bor/core/state/database.go:188 +0x4a
github.com/ethereum/go-ethereum/core/state.(*StateDB).Copy(0xc07a5674a0)
/go/src/github.com/maticnetwork/bor/core/state/statedb.go:1130 +0x49
github.com/ethereum/go-ethereum/core/txpool.newNoncer(...)
/go/src/github.com/maticnetwork/bor/core/txpool/noncer.go:38
github.com/ethereum/go-ethereum/core/txpool.(*TxPool).reset(0xc0002a8a00, 0xc1f832efc0, 0xc0103f06c0)
/go/src/github.com/maticnetwork/bor/core/txpool/txpool.go:1890 +0x8f4
github.com/ethereum/go-ethereum/core/txpool.(*TxPool).runReorg.func1.4.1({0xc00d673560?, 0x26b4980?}, {0xc13446e530?, 0xde1a12?})
/go/src/github.com/maticnetwork/bor/core/txpool/txpool.go:1664 +0x28
github.com/ethereum/go-ethereum/common/tracing.ElapsedTime({0x3617c28?, 0xc2947f7890?}, {0x36282e0?, 0xc00581abe0?}, {0x299cce9, 0x1a}, 0xc13446e660?)
/go/src/github.com/maticnetwork/bor/common/tracing/context.go:91 +0xd1
github.com/ethereum/go-ethereum/core/txpool.(*TxPool).runReorg.func1.4({0xdac96843c1f99387?, 0xc13446e920?}, {0x36282e0?, 0xc00581abe0?})
/go/src/github.com/maticnetwork/bor/core/txpool/txpool.go:1663 +0xc5
github.com/ethereum/go-ethereum/common/tracing.ElapsedTime({0x3617c28?, 0xc2947f7890?}, {0x36282e0?, 0xc00581abe0?}, {0x2984dee, 0x13}, 0xc13446ec10?)
/go/src/github.com/maticnetwork/bor/common/tracing/context.go:91 +0xd1
github.com/ethereum/go-ethereum/core/txpool.(*TxPool).runReorg.func1({0x3617c28, 0xc2947f7890}, {0x36282e0?, 0xc00581abe0?})
/go/src/github.com/maticnetwork/bor/core/txpool/txpool.go:1661 +0x2df
github.com/ethereum/go-ethereum/common/tracing.Exec({0x3617bb8, 0xc000118050}, {0x2970d78, 0xb}, {0x2974341, 0xc}, {0xc1feaa9f50, 0x1, 0xc2199149a0?})
/go/src/github.com/maticnetwork/bor/common/tracing/context.go:70 +0x223
github.com/ethereum/go-ethereum/core/txpool.(*TxPool).runReorg(0xc0d40d4900?, {0x3617bb8?, 0xc000118050?}, 0xc2570c0690?, 0xc13446efd0?, 0xd0c62a?, 0xa?)
/go/src/github.com/maticnetwork/bor/core/txpool/txpool.go:1633 +0xb2
created by github.com/ethereum/go-ethereum/core/txpool.(*TxPool).scheduleReorgLoop
/go/src/github.com/maticnetwork/bor/core/txpool/txpool.go:1570 +0x1f3
goroutine 1 [chan receive, 4727 minutes]:
github.com/ethereum/go-ethereum/internal/cli/server.(*Command).handleSignals(0xc000e36fc0)
/go/src/github.com/maticnetwork/bor/internal/cli/server/command.go:161 +0xdc
github.com/ethereum/go-ethereum/internal/cli/server.(*Command).Run(0xc000e36fc0, {0xc000120020?, 0x5?, 0x1?})
/go/src/github.com/maticnetwork/bor/internal/cli/server/command.go:154 +0x1d0
github.com/mitchellh/cli.(*CLI).Run(0xc000ef0dc0)
/root/go/pkg/mod/github.com/mitchellh/cli@v1.1.2/cli.go:262 +0x5f8
github.com/ethereum/go-ethereum/internal/cli.Run({0xc000120010, 0x3, 0x3})
/go/src/github.com/maticnetwork/bor/internal/cli/command.go:51 +0x1cb
main.main()
/go/src/github.com/maticnetwork/bor/cmd/cli/main.go:10 +0x4e
goroutine 5 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0xc00032a000?)
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:64 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:55 +0x75
goroutine 6 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:64 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:55 +0x75
goroutine 7 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:64 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:55 +0x75
goroutine 8 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:64 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:55 +0x75
goroutine 9 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:64 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:55 +0x75
goroutine 10 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:64 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:55 +0x75
goroutine 11 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:64 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:55 +0x75
goroutine 12 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:64 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:55 +0x75
goroutine 13 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:64 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:55 +0x75
goroutine 14 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:64 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:55 +0x75
goroutine 15 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:64 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:55 +0x75
goroutine 16 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:64 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:55 +0x75
goroutine 50 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:64 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:55 +0x75
goroutine 51 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:64 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:55 +0x75
goroutine 52 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:64 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:55 +0x75
goroutine 53 [chan receive]:
github.com/ethereum/go-ethereum/core.(*txSenderCacher).cache(0x0?)
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:64 +0x3b
created by github.com/ethereum/go-ethereum/core.newTxSenderCacher
/go/src/github.com/maticnetwork/bor/core/sender_cacher.go:55 +0x75
goroutine 61 [chan receive]:
github.com/ethereum/go-ethereum/metrics.(*meterArbiter).tick(0x4dd0a60)
/go/src/github.com/maticnetwork/bor/metrics/meter.go:314 +0x65
created by github.com/ethereum/go-ethereum/metrics.NewMeterForced
/go/src/github.com/maticnetwork/bor/metrics/meter.go:79 +0xc5
goroutine 62 [select]:
github.com/ethereum/go-ethereum/consensus/ethash.(*remoteSealer).loop(0xc0000de1e0)
/go/src/github.com/maticnetwork/bor/consensus/ethash/sealer.go:292 +0x205
created by github.com/ethereum/go-ethereum/consensus/ethash.startRemoteSealer
/go/src/github.com/maticnetwork/bor/consensus/ethash/sealer.go:275 +0x319
goroutine 63 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000063800)
/root/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:276 +0xad
created by go.opencensus.io/stats/view.init.0
/root/go/pkg/mod/go.opencensus.io@v0.23.0/stats/view/worker.go:34 +0x96
goroutine 40 [IO wait, 4727 minutes]:
internal/poll.runtime_pollWait(0x7f5cb89b20a8, 0x72)
/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc0011280c0?, 0xc00118fed0?, 0x1)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc0011280c0, {0xc00118fed0, 0x10000, 0x10000})
/usr/local/go/src/internal/poll/fd_unix.go:167 +0x299
os.(*File).read(...)
/usr/local/go/src/os/file_posix.go:31
os.(*File).Read(0xc00011c048, {0xc00118fed0?, 0x0?, 0x0?})
/usr/local/go/src/os/file.go:118 +0x5e
github.com/fsnotify/fsnotify.(*Watcher).readEvents(0xc001130000)
/root/go/pkg/mod/github.com/fsnotify/fsnotify@v1.6.0/backend_inotify.go:356 +0xdf
created by github.com/fsnotify/fsnotify.NewWatcher
/root/go/pkg/mod/github.com/fsnotify/fsnotify@v1.6.0/backend_inotify.go:150 +0x1b0
goroutine 65 [IO wait, 4727 minutes]:
internal/poll.runtime_pollWait(0x7f5cb89b2198, 0x72)
/usr/local/go/src/runtime/netpoll.go:306 +0x89
internal/poll.(*pollDesc).wait(0xc000e29a00?, 0xc0010a4000?, 0x0)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc000e29a00)
/usr/local/go/src/internal/poll/fd_unix.go:614 +0x2bd
net.(*netFD).accept(0xc000e29a00)
/usr/local/go/src/net/fd_unix.go:172 +0x35
net.(*TCPListener).accept(0xc000e40c90)
/usr/local/go/src/net/tcpsock_posix.go:148 +0x25
net.(*TCPListener).Accept(0xc000e40c90)
/usr/local/go/src/net/tcpsock.go:297 +0x3d
google.golang.org/grpc.(*Server).Serve(0xc0002650e0, {0x3616070?, 0xc000e40c90})
/root/go/pkg/mod/google.golang.org/grpc@v1.51.0/server.go:823 +0x475
github.com/ethereum/go-ethereum/internal/cli/server.(*Server).gRPCServerByListener.func1()
/go/src/github.com/maticnetwork/bor/internal/cli/server/server.go:445 +0x2d
created by github.com/ethereum/go-ethereum/internal/cli/server.(*Server).gRPCServerByListener
/go/src/github.com/maticnetwork/bor/internal/cli/server/server.go:444 +0x1d0
goroutine 98 [select, 4727 minutes]:
github.com/ethereum/go-ethereum/accounts.(*Manager).update(0xc000382a80)
/go/src/github.com/maticnetwork/bor/accounts/manager.go:139 +0x14d
created by github.com/ethereum/go-ethereum/accounts.NewManager
/go/src/github.com/maticnetwork/bor/accounts/manager.go:96 +0x4dc
goroutine 99 [select, 4727 minutes]:
github.com/ethereum/go-ethereum/accounts.(*Manager).update(0xc000382b60)
/go/src/github.com/maticnetwork/bor/accounts/manager.go:139 +0x14d
created by github.com/ethereum/go-ethereum/accounts.NewManager
/go/src/github.com/maticnetwork/bor/accounts/manager.go:96 +0x4dc
goroutine 100 [select, 4727 minutes]:
github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).loop(0xc000e410f8)
/go/src/github.com/maticnetwork/bor/accounts/keystore/watch.go:111 +0x5f8
created by github.com/ethereum/go-ethereum/accounts/keystore.(*watcher).start
/go/src/github.com/maticnetwork/bor/accounts/keystore/watch.go:57 +0x76
goroutine 101 [select]:
github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).updater(0xc000401b30)
/go/src/github.com/maticnetwork/bor/accounts/keystore/keystore.go:217 +0x85
created by github.com/ethereum/go-ethereum/accounts/keystore.(*KeyStore).Subscribe
/go/src/github.com/maticnetwork/bor/accounts/keystore/keystore.go:203 +0x116
goroutine 114 [select, 1 minutes]:
github.com/syndtr/goleveldb/leveldb.(*session).refLoop(0xc000400ff0)
/root/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session_util.go:189 +0x59b
created by github.com/syndtr/goleveldb/leveldb.newSession
/root/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/session.go:93 +0x2e5
goroutine 102 [select, 56 minutes]:
github.com/syndtr/goleveldb/leveldb.(*DB).compactionError(0xc000a7cfc0)
/root/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db_compaction.go:91 +0x137
created by github.com/syndtr/goleveldb/leveldb.openDB
/root/go/pkg/mod/github.com/syndtr/goleveldb@v1.0.1-0.20210819022825-2ae1ddf74ef7/leveldb/db.go:148 +0x4ea

**Comment by pratikspatil024** [comment]
Hi @kosmosM - please use the latest stable release ([v1.0.6](https://github.com/maticnetwork/bor/releases/tag/v1.0.6)). This issue was already fixed in v1.0.5.
