### ISSUE TITLE
Need to set some geth flags, related to ethConfig

### ISSUE THREAD

**Issue by baptiste-b-pegasys** [maticnetwork/bor#1073]
Hello,

Is there a way to setup some ethconfig settings, like `FilterLogCacheSize`, with bor?

If not, why it is not possible?

**Comment by manav2401** [comment]
Hi @baptiste-b-pegasys, bor uses a new-cli based in `internal/cli` module of the repository. We'll look into this flag and add it if possible in new-cli. Keeping this open until someone from our team picks up. Thanks!

**Comment by 0xKrishna** [comment]
Closing as it's implemented in the above mentioned PR.
