### ISSUE TITLE
Reorg Insanity

### ISSUE THREAD

**Issue by web-dev100** [maticnetwork/bor#1081]
#### Unusable Chain
Some high level statistics for Polygon:
- ~3M transactions per day, 3B+ since genesis
- Days of uptime: 1,263
- 8.4B market cap
- Partnerships w/ Blue Chip companies: Nike, Starbucks, Mastercard, Adobe, Disney
- Polygon Ventures: $450M+ AUM, 20+ portfolio companies
- **Progress made towards fixing the comical reorg problem: 0**

How has truly fixing reorgs on polygon not been prioritized by the core development team? The work that has been done so far really hasn't made a noticeable difference. What is shown in polygonscan doesn't remotely reflect the degree of the issue which has been going on for years with this chain. It is a horrible user experience where transactions that were confirmed don't have a guaranteed finality even 5+ minutes later. All other competing chains have solved this issue and Polygon will fade into obscurity if this isn't figured out (whether people want to admit it or not). All these flashy partnerships mean nothing if some end user/company can't definitively know their transaction did indeed go through. Even joke chains like BSC that are seemingly being run by interns have somehow figured out this problem. Maybe a renewed focus on core engineering issues would give polygon a more permanent moat over the long term? The core work is being done by the talented geth team upstream, figuring out a more durable consensus architecture that prevents reorgs should be the top priority for this chain.

**Comment by HowardCsie** [comment]
@web-dev100 Doesn't the milestone approach solve the problem of reorgs?
https://forum.polygon.technology/t/proposal-improved-ux-with-milestones-for-polygon-pos/11534

**Comment by kaber2** [comment]
Apparently not. Besides causing block processing stalls on all of my nodes, I still see a lot of reorgs. In the past 90 minutes, I count a total of 11 reorgs, all of depth 1.

**Comment by web-dev100** [comment]
I concur with @kaber2 . the reorg issue is far from solved and still happens very frequently. I wish it was just one validator who is constantly having issues but it very widespread and clearly a consensus mechanism issue.

**Comment by paulgoleary** [comment]
OK to be fair I do have to chuckle a bit at saying 'Unusable Chain' and '~3M transactions per day' in the same message. Clearly there's some logical inconsistency there. Also, I use Polygon all the time. :)

More seriously tho, we (devs + validators + community) have actually made immense progress on the health of the chain in the past 12-18 months. And we continue to work diligently on it and have a roadmap for further improvements.

However, re-orgs are definitely still an issue *but* may be harder to address than you think. The tl;dr is that you're likely discounting how difficult it is to consistently process 30M gas blocks with full EVM compliance at *2 second intervals* on a massively distributed, heterogenous network.  ETH mainnet is 30M gas at 12 second blocks, for example.

Someone do me a favor: we're trying to push more convos over to the Polygon Developer Discord (https://discord.gg/0xpolygondevs). This is intended to be a developer-focused server with more signal and less noise than the 'main' server. If someone wants to start this convo again in the #polygon-pos channel over there I would be happy to expand on these points as much as y'all like. :)

**Comment by ngotchac** [comment]
> The tl;dr is that you're likely discounting how difficult it is to consistently process 30M gas blocks with full EVM compliance at 2 second intervals on a massively distributed, heterogenous network. 

Shouldn't the parameters then be tweaked in order to have a stable(r) network?

As for discussing issues in Discord, it's really not ideal to make issues and discussions searchable sadly...

**Comment by kaber2** [comment]
> instead of the usual geth fork's approach of turning all params up to proverbial 11 with no thought for repercussions

Amen to that. Even BSC got their act together after their constant node meltdowns a year or two ago. Just increasing some constants is not enough to achieve scalability.

Polygon additionally makes life extra hard for node operators by applying random junk reformatting to upstream code so merging upstream or own optimizations is a constant hassle.
