### ISSUE TITLE
When will bor suppopt leveldb metrics?

### ISSUE THREAD

**Issue by Aracki** [maticnetwork/bor#1090]
Geth implemented metrics like tables_level.*, eth_db_chaindata_tables_level.*,...

Can bor support these as well? Or we are gonna eventually all move to pebble so this is not needed?

**Comment by temaniarpit27** [comment]
We constantly upgrade our codebase with the upstream codebase and will have these metrics eventually.
We have upgraded till v1.12.2 geth version and in under testing. So all metrics till then will be available soon
Let me know if this answers your question

**Comment by Aracki** [comment]
Good to know, thanks!
