### ISSUE TITLE
An Inquiry Regarding the Use of the Amoy Testnet

### ISSUE THREAD

**Issue by LilChen1998** [maticnetwork/bor#1096]
Hello，

I would like to inquire whether the Mumbai Testnet will also become unusable with the [deprecation plan for the Goerli Testnet](https://github.com/eth-clients/goerli). If this speculation is true, do I need to set up the amoy node before the Goerli Testnet is deprecated in January 2024? It would be immensely helpful if you could provide me with some information about the plans and details regarding the test network migration in advance.

Additionally, in order to build connecting with the Amoy Testnet, will there be any differences in the node startup process compared to the previous procedure?

Thank you.

**Comment by temaniarpit27** [comment]
Hi,
We are currently working on Amoy Testnet and work is in progress.
The community will be informed as and when we have updates.
Please follow the official discord channel for more updates
