### ISSUE TITLE
Request for release notes

### ISSUE THREAD

**Issue by fatminer** [maticnetwork/bor#1097]
Please include the hard fork schedule in the release notes.
Announcements on Discord are closed.

**Comment by fatminer** [comment]
sorry. I'm not good at English.

Until v0.4.0, the block numbers for hard forks were listed in the release notes.
https://github.com/maticnetwork/bor/releases/tag/v0.4.0

I think the hard fork schedule should be mentioned in the release notes.

**Comment by MaticParvez** [comment]
Thanks for pointing it out we missed it on this hardfork so will ensure we add it in future hardforks
