### ISSUE TITLE
Bor doesn`t sync after block 50523000

### ISSUE THREAD

**Issue by Pyxic** [maticnetwork/bor#1099]
After block 50523000 bor stoped syncing.
# bor logs:
```
WARN [11-30|11:10:27.352] Synchronisation failed, dropping peer    peer=1673b28af0061121f1ec941aae813b2c5907d3b7fcde0746aee66d28ce2e8247 err="retrieved hash chain is invalid: invalid merkle root (remote: 55f9a3e801a05d3330f06aa1a9ba9a09fe7979230d50846bb9d886c96383755e local: e18a8fbe060ebefdc86cd2f2a5d0c14f70f6dfcc7252efe232c4c867ef37a01f) dberr: %!w(<nil>)"
WARN [11-30|11:10:27.352] Synchronisation failed, retrying         peer=1673b28af0061121f1ec941aae813b2c5907d3b7fcde0746aee66d28ce2e8247 err="peer is unknown or unhealthy"
INFO [11-30|11:10:34.342] Got new milestone from heimdall          start=50,570,307 end=50,570,319 hash=0xf1d3d69bd5d203c84d9e697a47ef078b91bea1b230508f3e6013aefde6a6aa1f
WARN [11-30|11:10:34.343] unable to handle whitelist milestone     err="missing blocks"
INFO [11-30|11:10:46.343] Got new milestone from heimdall          start=50,570,307 end=50,570,319 hash=0xf1d3d69bd5d203c84d9e697a47ef078b91bea1b230508f3e6013aefde6a6aa1f
WARN [11-30|11:10:46.343] unable to handle whitelist milestone     err="missing blocks"
INFO [11-30|11:10:58.343] Got new milestone from heimdall          start=50,570,307 end=50,570,319 hash=0xf1d3d69bd5d203c84d9e697a47ef078b91bea1b230508f3e6013aefde6a6aa1f
WARN [11-30|11:10:58.343] unable to handle whitelist milestone     err="missing blocks"
```

# start command:
```
set -e

INSTALL_DIR=/var/opt/coins/nodes/polygon_bor
DATA_DIR=/var/opt/snapshots

BOR_BIN=$INSTALL_DIR/bor

$BOR_BIN server \
  --chain $INSTALL_DIR/genesis.json \
  --syncmode full \
  --datadir $DATA_DIR \
  --bor.heimdall http://127.0.0.1:8171 \
  --bootnodes enode://76316d1cb93c8ed407d3332d595233401250d48f8fbb1d9c65bd18c0495eca1b43ec38ee0ea1c257c0abb7d1f25d649d359cdfe5a805842159cfe36c5f66b7e8@52.78.36.216:30303,enode://b8f1cc9c5d4403703fbf377116469667d2b1823c0daf16b7250aa576bacf399e42c3930ccfcb02c5df6879565a2b8931335565f0e8d3f8e72385ecf4a4bf160a@3.36.224.80:30303,enode://8729e0c825f3d9cad382555f3e46dcff21af323e89025a0e6312df541f4a9e73abfa562d64906f5e59c51fe6f0501b3e61b07979606c56329c020ed739910759@54.194.245.5:30303,enode://681ebac58d8dd2d8a6eef15329dfbad0ab960561524cf2dfde40ad646736fe5c244020f20b87e7c1520820bc625cfb487dd71d63a3a3bf0baea2dbb8ec7c79f1@34.240.245.39:30303 \
  --port 38370 \
  --http \
  --http.addr 127.0.0.1 \
  --http.port 8170 \
  --http.api eth,net,web3,debug,txpool,bor \
  --http.vhosts '*' \
  --http.corsdomain '*' \
  --ws \
  --ws.addr 127.0.0.1 \
  --ws.port 8070 \
  --ws.api eth,net,web3,debug,txpool,bor \
  --ws.origins '*' \
  --txlookuplimit 0 \
  --cache 4096 \
  --ipcdisable \
  --nat none 
```

# heimdall logs:
```
ERROR[2023-11-30|11:13:02.458] Stopping peer for error                      module=p2p peer="Peer{MConn{199.19.77.106:26656} d564962fc4a592bbc3f8c7c0d256be357d14c22c out}" err=EOF
ERROR[2023-11-30|11:13:02.568] Stopping peer for error                      module=p2p peer="Peer{MConn{64.140.164.242:26656} 02d005bc312b7ca1020c511821e5d5a151dbb28b out}" err=EOF
ERROR[2023-11-30|11:13:02.823] Stopping peer for error                      module=p2p peer="Peer{MConn{208.91.107.188:26656} 8bfaceecab2e8516a1ba1626db6a28e6132f6cff out}" err=EOF
ERROR[2023-11-30|11:13:03.090] dialing failed (attempts: 3): dial tcp 54.243.187.108:26656: i/o timeout module=pex addr=0c56b1edb9bb29707bb13d0373b31282ae6ea227@54.243.187.108:26656
ERROR[2023-11-30|11:13:03.090] dialing failed (attempts: 2): dial tcp 34.230.90.209:30303: i/o timeout module=pex addr=1989b4ff1ac275d8a2e66774d3037c1442aa9d8c@34.230.90.209:30303
ERROR[2023-11-30|11:13:03.090] dialing failed (attempts: 3): dial tcp 54.198.138.217:26656: i/o timeout module=pex addr=d44956017b84d1fd4bad0a0820c304a756bdcd59@54.198.138.217:26656
ERROR[2023-11-30|11:13:03.090] dialing failed (attempts: 2): dial tcp 3.80.62.115:26656: i/o timeout module=pex addr=76f25226fdcf5a34d3a5d52d102abe601738bde2@3.80.62.115:26656
ERROR[2023-11-30|11:13:03.090] dialing failed (attempts: 1): dial tcp 54.156.135.213:26656: i/o timeout module=pex addr=e46014d6f4e6de3f6d2d720b7dde94a444909c7d@54.156.135.213:26656
INFO [2023-11-30|11:13:04.342] Served RPC HTTP response                     module=rest-server method=GET url=/milestone/lastNoAck status=200 duration=0 remoteAddr=127.0.0.1:34344
INFO [2023-11-30|11:13:08.527] Executed block                               module=state height=16574223 validTxs=0 invalidTxs=0
INFO [2023-11-30|11:13:08.540] Committed state                              module=state height=16574223 txs=0 appHash=69D82E10CA298C4065474CDE85D91062AFCF2B474A79A8D8CC0F00C2BBEDC88C
INFO [2023-11-30|11:13:10.342] Served RPC HTTP response                     module=rest-server method=GET url=/milestone/latest status=200 duration=0 remoteAddr=127.0.0.1:34344
INFO [2023-11-30|11:13:10.342] Served RPC HTTP response                     module=rest-server method=GET url=/milestone/lastNoAck status=200 duration=0 remoteAddr=127.0.0.1:60808
ERROR[2023-11-30|11:13:15.894] Invalid Milestone Timeout msg                module=Milestone lastMilestoneTime=2023-11-30T11:08:55Z currenttime=2023-11-30T11:13:07.943019165Z bufferTime=4m16s
INFO [2023-11-30|11:13:15.895] Executed block                               module=state height=16574224 validTxs=0 invalidTxs=1
INFO [2023-11-30|11:13:15.909] Committed state                              module=state height=16574224 txs=1 appHash=72268139A22909B83CB0DBC6D90447C25C4E988AFB734288B6C3705AA7576F0C
INFO [2023-11-30|11:13:16.343] Served RPC HTTP response                     module=rest-server method=GET url=/milestone/lastNoAck status=200 duration=0 remoteAddr=127.0.0.1:60808
```

# heimdall start command:
```
set -e

INSTALL_DIR=/usr/bin
DATA_DIR=/var/opt/coins/data/polygon_heimdall/backend

HEIMDALL_BIN=$INSTALL_DIR/heimdalld
HOME_DIR=/var/lib/heimdall
CONFIG_DIR=/var/lib/heimdall/config

$HEIMDALL_BIN start \
  --home $HOME_DIR \
  --rpc.laddr tcp://127.0.0.1:8071 \
  --p2p.laddr tcp://0.0.0.0:38371 \
  --laddr tcp://127.0.0.1:8171 \
  --p2p.seeds "f4f605d60b8ffaaf15240564e58a81103510631c@159.203.9.164:26656,4fb1bc820088764a564d4f66bba1963d47d82329@44.232.55.71:26656,2eadba4be3ce47ac8db0a3538cb923b57b41c927@35.199.4.13:26656,3b23b20017a6f348d329c102ddc0088f0a10a444@35.221.13.28:26656,25f5f65a09c56e9f1d2d90618aa70cd358aa68da@35.230.116.151:26656,4cd60c1d76e44b05f7dfd8bab3f447b119e87042@54.147.31.250:26656,b18bbe1f3d8576f4b73d9b18976e71c65e839149@34.226.134.117:26656,1500161dd491b67fb1ac81868952be49e2509c9f@52.78.36.216:26656,dd4a3f1750af5765266231b9d8ac764599921736@3.36.224.80:26656,8ea4f592ad6cc38d7532aff418d1fb97052463af@34.240.245.39:26656,e772e1fb8c3492a9570a377a5eafdb1dc53cd778@54.194.245.5:26656,6726b826df45ac8e9afb4bdb2469c7771bd797f1@52.209.21.164:26656" \
  --node tcp://127.0.0.1:8071 \
  --bor_rpc_url http://127.0.0.1:8170 \
  --eth_rpc_url http://127.0.0.1:8136 \
  --rest-server 
```

# bor version 1.2.0
# heimdall 1.0.3

**Comment by fatminer** [comment]
I was also confused.
It looks like there was a hard fork at 50523000.
You can synchronize by updating to v1.1.0 or higher.

**Comment by Pyxic** [comment]
I updated bor to v1.2.0 but it`s not helped me

**Comment by temaniarpit27** [comment]
Please use the latest bor version released.
Add correct bootnodes and peers and rewind the block by few hundreds and you should be able to sync

**Comment by pratikspatil024** [comment]
```
bor attach /var/lib/bor/data/bor.ipc
debug.setHead("<block-number-in-hex>")
```

**Comment by marcello33** [comment]
Has this been solved?

Please use the recommended peer settings (you can find them [here](https://forum.polygon.technology/t/recommended-peer-settings-for-mainnet-nodes/13018), including updated bootnodes), bump `bor` to latest version, rewind the chain by few hundreds blocks using command 
```
bor attach /var/lib/bor/data/bor.ipc
debug.setHead("<block-number-in-hex>")
``` 
And `bor` should be able to sync.

**Comment by zyx0355** [comment]
> Has this been solved?这个问题解决了吗？
> 
> Please use the recommended peer settings (you can find them [here](https://forum.polygon.technology/t/recommended-peer-settings-for-mainnet-nodes/13018), including updated bootnodes), bump `bor` to latest version, rewind the chain by few hundreds blocks using command请使用推荐的对等设置（你可以在这里找到它们，包括更新的引导节点），升级到 `bor` 最新版本，使用命令将链倒回几百个块
> 
> ```
> bor attach /var/lib/bor/data/bor.ipc
> debug.setHead("<block-number-in-hex>")
> ```
> 
> And `bor` should be able to sync.并且 `bor` 应该能够同步。

I have tried, waiting for the results, I wish me good luck

**Comment by zyx0355** [comment]
heimdall logs
ERROR[2023-12-08|05:06:22.456] Stopping peer for error                      module=p2p peer="Peer{MConn{69.162.111.30:26656} f9a890029263b6bfdeb109470faee7c1adbfe8b3 out}" err="read tcp 172.21.0.3:42184->69.162.111.30:26656: read: connection reset by peer"
ERROR[2023-12-08|05:06:22.727] Stopping peer for error                      module=p2p peer="Peer{MConn{67.209.54.145:26656} f79ee869a7ba9563143e7b66707b06d68816d879 out}" err=EOF
ERROR[2023-12-08|05:06:22.830] Stopping peer for error                      module=p2p peer="Peer{MConn{158.140.145.111:26656} d53fd69b1665647e8dbac331c0aac627cd957673 out}" err=EOF
ERROR[2023-12-08|05:06:22.999] Stopping peer for error                      module=p2p peer="Peer{MConn{3.81.98.57:26656} 9b4e75a8ab8b92848d7171880c241e1a54502aca out}" err=EOF
ERROR[2023-12-08|05:06:23.369] Connection failed @ recvRoutine (reading byte) module=p2p peer=5a63a6a1a3b397a19ae9d1c5b27ba7570cbe3671@144.76.155.222:26656 conn=MConn{144.76.155.222:26656} err="read tcp 172.21.0.3:43914->144.76.155.222:26656: read: connection reset by peer"
ERROR[2023-12-08|05:06:23.369] Stopping peer for error                      module=p2p peer="Peer{MConn{144.76.155.222:26656} 5a63a6a1a3b397a19ae9d1c5b27ba7570cbe3671 out}" err="read tcp 172.21.0.3:43914->144.76.155.222:26656: read: connection reset by peer"
ERROR[2023-12-08|05:06:24.784] Stopping peer for error                      module=p2p peer="Peer{MConn{141.94.142.226:26656} a7a29f8a83bfefe82bac2fd7835e6e004eee43a6 out}" err=EOF
INFO [2023-12-08|05:06:25.955] Executed block                               module=state height=16675480 validTxs=0 invalidTxs=0
INFO [2023-12-08|05:06:25.988] Committed state                              module=state height=16675480 txs=0 appHash=2B23B058AF06ECE61060FA1A850ACA516D4429A50713AF12F2C2C5684C65E134
INFO [2023-12-08|05:06:32.686] Executed block                               module=state height=16675481 validTxs=1 invalidTxs=0
INFO [2023-12-08|05:06:32.742] Committed state                              module=state height=16675481 txs=1 appHash=6282C3882D1904AB51D7173F73FDDC993BE6B112001A10973753D78B06C48D6E

**Comment by zyx0355** [comment]
### **heimdall logs**
ERROR[2023-12-08|05:06:22.456] Stopping peer for error                      module=p2p peer="Peer{MConn{69.162.111.30:26656} f9a890029263b6bfdeb109470faee7c1adbfe8b3 out}" err="read tcp 172.21.0.3:42184->69.162.111.30:26656: read: connection reset by peer"
ERROR[2023-12-08|05:06:22.727] Stopping peer for error                      module=p2p peer="Peer{MConn{67.209.54.145:26656} f79ee869a7ba9563143e7b66707b06d68816d879 out}" err=EOF
ERROR[2023-12-08|05:06:22.830] Stopping peer for error                      module=p2p peer="Peer{MConn{158.140.145.111:26656} d53fd69b1665647e8dbac331c0aac627cd957673 out}" err=EOF
ERROR[2023-12-08|05:06:22.999] Stopping peer for error                      module=p2p peer="Peer{MConn{3.81.98.57:26656} 9b4e75a8ab8b92848d7171880c241e1a54502aca out}" err=EOF
ERROR[2023-12-08|05:06:23.369] Connection failed @ recvRoutine (reading byte) module=p2p peer=5a63a6a1a3b397a19ae9d1c5b27ba7570cbe3671@144.76.155.222:26656 conn=MConn{144.76.155.222:26656} err="read tcp 172.21.0.3:43914->144.76.155.222:26656: read: connection reset by peer"
ERROR[2023-12-08|05:06:23.369] Stopping peer for error                      module=p2p peer="Peer{MConn{144.76.155.222:26656} 5a63a6a1a3b397a19ae9d1c5b27ba7570cbe3671 out}" err="read tcp 172.21.0.3:43914->144.76.155.222:26656: read: connection reset by peer"
ERROR[2023-12-08|05:06:24.784] Stopping peer for error                      module=p2p peer="Peer{MConn{141.94.142.226:26656} a7a29f8a83bfefe82bac2fd7835e6e004eee43a6 out}" err=EOF
INFO [2023-12-08|05:06:25.955] Executed block                               module=state height=16675480 validTxs=0 invalidTxs=0
INFO [2023-12-08|05:06:25.988] Committed state                              module=state height=16675480 txs=0 appHash=2B23B058AF06ECE61060FA1A850ACA516D4429A50713AF12F2C2C5684C65E134
INFO [2023-12-08|05:06:32.686] Executed block                               module=state height=16675481 validTxs=1 invalidTxs=0
INFO [2023-12-08|05:06:32.742] Committed state                              module=state height=16675481 txs=1 appHash=6282C3882D1904AB51D7173F73FDDC993BE6B112001A10973753D78B06C48D6E

**Comment by temaniarpit27** [comment]
@Pyxic Please reach out to support team on official discord channel and they will be able to help out in a better way. Closing this for now
