### ISSUE TITLE
Is there a way to add default go client prometheus metrics?

### ISSUE THREAD

**Issue by Aracki** [maticnetwork/bor#1101]
For Heimdall we have default metrics like:
```
process_virtual_memory_bytes
process_resident_memory_bytes
go_threads
... 
```

Can we add a feature to Bor to enable these kind of metrics as well?

**Comment by temaniarpit27** [comment]
https://geth.ethereum.org/docs/monitoring/metrics
You can refer to the metrics enabled in go-ethereum codebase and similarly all metrics are present in bor.
It wont be possible to enable more metrics but the user can enable/add more metrics if they wish to on their end following this doc.
There maybe a chance that these metrics will be present with some other name.
Closing this for now. Feel free to reopen if required

**Comment by Aracki** [comment]
Ok thanks, I've opened an issue on go-ethereum side: https://github.com/ethereum/go-ethereum/issues/28647
