### ISSUE TITLE
Failed to prune, v1.1.0 and v1.2.1 err="no snapshot paired state"

### ISSUE THREAD

**Issue by kompotkot** [maticnetwork/bor#1117]
#### **System information**

Bor client version: 

```bash
Version: 1.1.0
GitCommit: cf18eccee65ab339facbdc5a69a91be0fadd9d39
```

```bash
Version: 1.2.1
GitCommit: 2ee39192bd5c60f9fd6baa946ae774c6d629e714
```

Heimdall client version: 

```bash
1.0.3
INFO [2023-12-28|10:11:48.819] Heimdall services stopped                    module=cmd/heimdalld
```

OS & Version: Linux Ubuntu 20.04

Environment: Polygon Mainnet

Type of node: Sentry

#### **Overview of the problem**

Raised exception by bor client during prune workflow. Tried with `v1.2.0`, upgrade to `v1.2.1` and downgrade to `v1.1.0` not helped. Before prune after upgrades and downgrades node synced for a while (~12 hours).

#### **Reproduction Steps**

1. Start prune with command:

```bash
sudo -u bor /usr/bin/bor snapshot prune-state --datadir /mnt/disks/polygon/bor/data
```

#### **Logs / Traces / Output / Error Messages**
 
 Prune:
 
![v1.1.0_prune](https://github.com/maticnetwork/bor/assets/7047457/7a84f0bc-9c4a-42b9-990e-9dee70c78d8c)

![v1.2.1_prune](https://github.com/maticnetwork/bor/assets/7047457/68c6edfc-770f-410a-b327-5c4c1ad00889)

Node shutdown:

![bor_shutdown](https://github.com/maticnetwork/bor/assets/7047457/f22db157-0418-4a62-a133-5a6f684bd34d)

Node start:

![node_start_1](https://github.com/maticnetwork/bor/assets/7047457/c77b58d3-7508-4075-84aa-0558e174c820)

![node_start_2](https://github.com/maticnetwork/bor/assets/7047457/78648dd1-dc5f-49cf-8374-7eeadd34ca40)

**Comment by kompotkot** [comment]
Described solutions in Issue https://github.com/maticnetwork/bor/issues/1104 not helped.

**Comment by temaniarpit27** [comment]
We will be releasing out a fix soon. Thanks for your patience

**Comment by icculp** [comment]
Same on 1.2.1 with fresh snapshot download.

**Comment by kompotkot** [comment]
I tried with
```
Version: 1.2.2
GitCommit: 70bebc933555439afa6b24b61b39c1303bbf2f1f
```
Same result :(

**Comment by temaniarpit27** [comment]
Can you please let your node sync to the tip with v1.2.2 and then stop the bor node and then try pruning? @kompotkot

**Comment by kompotkot** [comment]
> Can you please let your node sync to the tip with v1.2.2 and then stop the bor node and then try pruning? @kompotkot

It started working!
```
INFO [01-15|15:06:48.449] Initialized state bloom                  size=2.00GiB
INFO [01-15|15:07:03.985] Selecting bottom-most difflayer as the pruning target root=44cc7a..f10ded height=52,355,828
INFO [01-15|15:07:03.990] Iterating state snapshot                 accounts=0 slots=0 elapsed=1.114ms
INFO [01-15|15:07:11.991] Iterating state snapshot                 accounts=127,754 slots=609,292 elapsed=8.002s  eta=5h4m54.551s
INFO [01-15|15:07:19.991] Iterating state snapshot                 accounts=326,654 slots=1,257,110 elapsed=16.002s eta=3h59m20.504s
...
```

I can confirm, it solved my issue with next steps:
- Updated node with `maticnetwork/install/main/bor.sh` script to `v1.2.2` with GitCommit `70bebc933555439afa6b24b61b39c1303bbf2f1f`.
- Synchronized node for 1-2 hours.
- Gracefully shutdown `bor` and `heimdalld`, no errors notices, confirmed `Writing snapshot state to disk` in log.
- Started prune workflow as before.

Thank you!

**Comment by temaniarpit27** [comment]
Closing this issue for now.
