### ISSUE TITLE
Snapshot broken

### ISSUE THREAD

**Issue by kaber2** [maticnetwork/bor#1119]
It appears the latest snapshot is broken again, after extraction the size is 1.3TB, the ancient directory is empty except for metadata and geth complains about "ancient chain segments already extracted, please set --datadir.ancient to the correct path".

Can someone verify the snapshot please?

**Comment by kaber2** [comment]
This appears to have been caused by a local filesystem corruption. Another attempt worked fine.

Closing.

**Comment by nebojsa-ristovic** [comment]
@kaber2, just to double check - you just downloaded again snapshot using script and that fixed the issue?

**Comment by kaber2** [comment]
Yes, and I also verified that the filesystem in question was actually returning corrupted data.

**Comment by nebojsa-ristovic** [comment]
tnx for prompt response!
