### ISSUE TITLE
debug_traceTx poor performance and huge disk consumption

### ISSUE THREAD

**Issue by barryz** [maticnetwork/bor#112]
HI, team:

I have built an archived (`--gcmode=archive`) node to implement trace functionality and have encountered several problems: 
1. The trace performance is not good and is far from implementing the trace API by Parity.
2. The archive node has a lot of disk consumption.

Do you have any plans to optimize the performance of the trace module? Or introduce a Parity version of bor?

**Comment by freddieee** [comment]
Hi @barryz , I found the same issue, the call for trace module is super time consuming. Did you get it fixed or find other tricks to optimize it?

**Comment by barryz** [comment]
> Hi @barryz , I found the same issue, the call for trace module is super time consuming. Did you get it fixed or find other tricks to optimize it?

Hopes [this pr](https://github.com/ethereum/go-ethereum/pull/23016)  can help you.
