### ISSUE TITLE
Some questions about Amoy testnet

### ISSUE THREAD

**Issue by LilChen1998** [maticnetwork/bor#1123]
Hello,

Thanks to your meticulous work, I have successfully set up the Amoy test network, which is currently syncing. At the same time, I have a few questions:

First, when will the services for the Mumbai test network be stopped? My project needs this information to determine when to formally migrate to the Amoy test network.

Second, could you provide me with the Explorer and Faucet available for the Amoy test network? They are crucial for my testing work.

Thank you.

**Comment by 0xsharma** [comment]
Hey @LilChen1998 ,

We will be releasing a blog post with the required information very soon. Stay tuned for that !
Explorer is : [oklink](https://www.oklink.com/amoy)

Faucet info will be provided with the blogpost ✅ 

Thank you 💜

**Comment by LilChen1998** [comment]
Thank you!
