### ISSUE TITLE
Unable to Prune even on v1.2.2 - URGENT

### ISSUE THREAD

**Issue by zainirfan13** [maticnetwork/bor#1125]
Bor Version: 1.2.2
Heimdalld Version: 1.0.3

Prune hasn't been working since 2 months for me now. I have already faced data corruption once and it was a nightmare to get all snapshots with mainnet up again. 

Now Pruning is not going forward. This is really frustrating because we are not running nodes on supercomputers or NASA internet. Its a time taking hectic process. 

I have 342 GBs of free space and I dont want to go at that point where I can no longer prune because of less storage space. 

The error that I am facing is 
INFO [01-13|10:41:03.269] Using pebble as the backing database 
INFO [01-13|10:41:03.269] Allocated cache and file handles         database=/mnt/ssd/node_data/data/bor/chaindata cache=1024.00MiB handles=524,288
INFO [01-13|10:41:03.287] Opened ancient database                  database=/mnt/ssd/node_data/data/bor/chaindata/ancient/chain readonly=false
ERROR[01-13|10:41:03.287] Failed to open snapshot tree             err="failed to load head block"

I am not sending any snapshot flag when running bor so it should be as default that is true. 
My node is synced to latest block and timestamp. 

Any help would be appreciated.

<img width="1144" alt="Screenshot 2024-01-13 at 2 41 18 PM" src="https://github.com/maticnetwork/bor/assets/48196604/08c09f4b-5c42-455a-8178-1b50e52d2624">

**Comment by zainirfan13** [comment]
@temaniarpit27

**Comment by temaniarpit27** [comment]
Can you please upgrade your node to v1.2.2, let it resync and then try pruning?

**Comment by temaniarpit27** [comment]
Also, we haven't officially announced v1.2.2 and is undergoing some tests.
We have also announced that whoever is facing pruning issues with v1.2.0, can downgrade the node to v1.1.0 and do pruning.

**Comment by zainirfan13** [comment]
> Can you please upgrade your node to v1.2.2, let it resync to tip, stop your node, and then try pruning? In case it doesn't work, please send the logs when you stop your node and then logs when pruning fails.

I tried that but it didn't work.

**Comment by zainirfan13** [comment]
> Also, we haven't officially announced v1.2.2 and is undergoing some tests. We have also announced that whoever is facing pruning issues with v1.2.0, can downgrade the node to v1.1.0 and do pruning. We do appreciate the feedback though on v1.2.2

Thanks, I'll do that hopefully it will work.

**Comment by temaniarpit27** [comment]
> > Can you please upgrade your node to v1.2.2, let it resync to tip, stop your node, and then try pruning? In case it doesn't work, please send the logs when you stop your node and then logs when pruning fails.
> 
> I tried that but it didn't work.

Can you please share logs?

**Comment by zainirfan13** [comment]
> > > Can you please upgrade your node to v1.2.2, let it resync to tip, stop your node, and then try pruning? In case it doesn't work, please send the logs when you stop your node and then logs when pruning fails.
> > 
> > 
> > I tried that but it didn't work.
> 
> Can you please share logs as mentioned?

I shared 4 lines that appeared when i tried pruning, can you check the image attached with the issue. Incase you need any more logs let me know.

**Comment by temaniarpit27** [comment]
When your node syncs to tip, after that you stop, please share bor logs when it stops.

**Comment by zainirfan13** [comment]
On version v1.2.2

My node was synced to tip, and then i stopped it. it stopped gracefully. But still prune failed.
@temaniarpit27 

<img width="1373" alt="Screenshot 2024-01-13 at 8 41 34 PM" src="https://github.com/maticnetwork/bor/assets/48196604/0eb903c7-c072-435c-bffd-9ffd130b28e7">
<img width="1378" alt="Screenshot 2024-01-13 at 8 41 55 PM" src="https://github.com/maticnetwork/bor/assets/48196604/60da0d16-2abb-4ec8-971e-37f5edc0d5c4">

**Comment by temaniarpit27** [comment]
@zainirfan13 
https://github.com/maticnetwork/bor/issues/1117
Please refer to this issue
I think your node has some other issue as the pruning error is different and there is one more error while stopping the node
`Dangling trie nodes after full cleanup`
We tried reproducing the error above but werent able to.
Can you try restoring your node from latest snapshot and give it a try again?

**Comment by zainirfan13** [comment]
@temaniarpit27  It takes some next level engineering to run from the snapshots as when i download them they are in chunks, then they have to be joined then have to be extracted. this all is almost impossible or very time taking to do since i only have 4TB disk and 1.7 TB disk

Is there any easier way i can download and extract at the same time ?

**Comment by pratikspatil024** [comment]
@zainirfan13 - 

```
curl -L https://snapshot-download.polygon.technology/snapdown.sh | bash -s -- --network {{ network }} --client {{ client }} --extract-dir {{ extract_dir }} --validate-checksum {{ true / false }}
```

This command will download and extract. For more information, checkout [this](https://docs.polygon.technology/pos/reference/snapshot-instructions-heimdall-bor/) page.

**Comment by temaniarpit27** [comment]
Closing this for now. Please feel free to reopen if required
