### ISSUE TITLE
Bor 1.2.0 stuck at block 52410400

### ISSUE THREAD

**Issue by jonathanudd** [maticnetwork/bor#1128]
#### **System information**

Bor client version: 1.2.0

Heimdall client version: 1.0.3

OS & Version: Linux

Environment: Polygon Mainnet

Type of node: Archive

#### **Overview of the problem**

At 2024-01-17 00:40 GMT+1 our both nodes stopped syncing at block 52410400

#### **Logs / Traces / Output / Error Messages**
 
There where a lot of these logs
```
Jan 17 05:39:49 juju-0bf3b5-1 bor[767933]: WARN [01-17|05:39:49.343] Network response id collision            have=a23f9cd6bcacfd4231b342e17c349023537fa02c2a00b5c33c17d547fc6f221d:eth/68:5 want=a23f9cd6bcacfd4231b342e17c349023537fa02c2a00b5c33c17d547fc6f221d:eth/68:6
```
And
```
Jan 17 05:41:10 juju-0bf3b5-1 bor[767933]: WARN [01-17|05:41:10.913] Synchronisation failed, dropping peer    peer=19aab4c03f01bd6066adc4c7b6daf9c90baed468c71d172d2821c4a8d0afbc96 err="retrieved hash chain is invalid: invalid merkle root (remote: c162268f4727450825f12e5e49f03cddd3cff2338a722842f853d1be49945c4f local: 009eb98b8d498a8ce266f4ed7d2517e65167efdc6e6319b8466b0e330c4d6250) dberr: %!w(<nil>)"
Jan 17 05:41:10 juju-0bf3b5-1 bor[767933]: WARN [01-17|05:41:10.913] Synchronisation failed, retrying         peer=19aab4c03f01bd6066adc4c7b6daf9c90baed468c71d172d2821c4a8d0afbc96 err="peer is unknown or unhealthy"
```

### Additional information

After downgrading to 1.1.0 the nodes started working again.

**Comment by YuXiaoCoder** [comment]
The solution is as follows:
1. first restart the service, you will see the BAD BLOCK logs
2. Back to the block
```bash
. /bor attach /mnt/maticmain/node/bor/bor.ipc

debug.setHead(web3.toHex(52410000))
``
3. Wait a little while for the synchronisation to start

**Comment by PeaStew** [comment]
I requested 27 days ago that the latest tag be removed from 1.2.0 and it wasn't done

**Comment by zainirfan13** [comment]
thanks, downgrading to 1.1.0 fixed it.

**Comment by temaniarpit27** [comment]
Closing this issue as v1.1.0 downgrade fixed it
Will look into detail why this happened

**Comment by temaniarpit27** [comment]
Closing this issue as v1.1.0 downgrade fixed it
Will look into detail why this happened
