### ISSUE TITLE
hash = sha256(abi.encode(text)) fails on Polygon zkEVM (1101) - works on other EVM chains

### ISSUE THREAD

**Issue by monique-baumann** [maticnetwork/bor#1138]
Hi Polygon zkEVM Team. 

This might sound strange but please try it. 

hash = sha256(abi.encode(text))

fails e.g. when using remix with the typical wild card guess error message: 
```
execution reverted
	The transaction has been reverted to the initial state.
Note: The called function should be payable if you send value and the value you send should be less than your current balance.
Debug the transaction to get more information. 
```

detail: hash is typed bytes32

**Comment by PeaStew** [comment]
@monique-baumann you want this one https://github.com/0xPolygonHermez/zkevm-node

**Comment by monique-baumann** [comment]
thanks.
