### ISSUE TITLE
Go mod doesn't use correct path

### ISSUE THREAD

**Issue by af-afk** [maticnetwork/bor#116]
#### Expected behaviour

`go.mod` declaring the repo's path as `github.com/maticnetwork/bor`.

#### Actual behaviour

`go.mod` declares the repo's path as `github.com/ethereum/go-ethereum`.

#### Steps to reproduce the behaviour

Use the repo in a Go project with `go.mod` enabled.

**Comment by af-afk** [comment]
#115

**Comment by af-afk** [comment]
#117 (Neglected to change the rest of the imports)

**Comment by nnqq** [comment]
Why it ignored? This fix should be in `master` as the first thing after the fork. Now there is no way to `go get github.com/maticnetwork/bor`

**Comment by ssandeep** [comment]
@nnqq @af-afk , there are few merge conflicts. Can you raise a fresh PR?

**Comment by ferranbt** [comment]
Hi @nnqq. Why do you need to do ```go get github.com/maticnetwork/bor``` exactly?

**Comment by ssandeep** [comment]
Since we do not do `go get github.com/maticnetwork/bor` and considering that there will be too many merge conflicts every time we need to get changes from upstream geth, we will be sticking to geth imports.

**Comment by af-afk** [comment]
It should be noted that due to the misnaming no-one can have a Go dependency on here without maintaining a fork now...
