### ISSUE TITLE
how to cut Polygon Bor (truncate), Reduce disk space usage

### ISSUE THREAD

**Issue by myuniswap2000** [maticnetwork/bor#1163]
Hello everyone, may I ask how to cut Polygon Bor(truncate).  Reduce disk space usage.
####The disk space I am using is 5.9T   :
/var/lib/bor# ls
bor.ipc  config.toml  data
/var/lib/bor# du -sh .
5.9T	.
####my version:
# bor version --long
Version: 1.1.0
GitCommit: cf18eccee65ab339facbdc5a69a91be0fadd9d39
# heimdalld version --long
name: heimdall
server_name: heimdalld
client_name: heimdallcli
version: 1.0.3
commit: 56299da7f073b9a26f109397bc6162c628dc891c
go: go version go1.20.10 linux/amd64
INFO [2024-02-19|15:00:41.249] Heimdall services stopped                    module=cmd/heimdalld

**Comment by myuniswap2000** [comment]
please help me, thank you!

**Comment by Raneet10** [comment]
Hey @myuniswap2000 , you can choose to prune your node in case you are not running an archive node. The operation is pretty similar to how it's [done in Geth](https://geth.ethereum.org/docs/fundamentals/pruning)

**Comment by myuniswap2000** [comment]
Do you have specific documentation and commands? thanks

**Comment by Raneet10** [comment]
You can check the steps here: https://forum.polygon.technology/t/bor-offline-pruning/9230#steps-6

**Comment by myuniswap2000** [comment]
thank you
