### ISSUE TITLE
Mainnet bor program settings heimdall.url bug

### ISSUE THREAD

**Issue by rayn316** [maticnetwork/bor#1164]
#### **System information**

Bor client version: v1.2.3
OS & Version: Linux 
Environment: Polygon Mainnet
Type of node: Sentry
Additional Information: 

#### **Overview of the problem**
Set the configuration to the http://doamin:8880/heimdalld/http path, and the remote is nignx reverse proxy. `heimdalld/http` will be removed and sent to the backend.
However, the node cannot obtain data after starting with this configuration. The erigon node obtains data and runs normally. After investigation, it was found that bor will truncate the URL path and only use the domain name and port. For example, just use `http://doamin:8880` + query path. to domain

**Comment by rayn316** [comment]
Configuration files and command line parameters have the same effect and will truncate the url path.

**Comment by anshalshukla** [comment]
This has been already fixed on newer beta versions. We will be rolling out a stable version soon.
