### ISSUE TITLE
Bor sync issue

### ISSUE THREAD

**Issue by martinboehm** [maticnetwork/bor#1172]
Our Bor v1.2.3 entered a strange state. It is reporting that it is syncing (see the log), however RPC call `eth_getBlockByNumber latest` returns the last block number 54068002. We run 2 instances and both exhibit the same behavior, stuck on the same block. Our Heimdall instances seem to be in sync, call to Heimdall status returns `"catching_up": false`.
```
INFO [03-01|14:21:50.274] Imported new chain segment               number=54,139,125 hash=912c70..c06bb3 blocks=1  txs=95    mgas=16.580  elapsed=1.446s      mgasps=11.460  dirty=0.00B
INFO [03-01|14:21:50.275] Commit Interrupt. Pre-committing the current block block=54,139,126
WARN [03-01|14:21:50.366] Tx Level Interrupt
INFO [03-01|14:21:50.378] Imported new chain segment               number=54,139,126 hash=9518e8..2ea64d blocks=1  txs=102   mgas=7.804   elapsed=102.424ms   mgasps=76.196  dirty=0.00B
INFO [03-01|14:21:50.378] Commit Interrupt. Pre-committing the current block block=54,139,127
WARN [03-01|14:21:50.421] Tx Level Interrupt
```
Any idea what to do to fix the issue?

**Comment by yt-everstake** [comment]
We have the same problems several times with bor version 1.2.3. Restart bor helps.

**Comment by martinboehm** [comment]
We restarted bor several times, without any success.

**Comment by martinboehm** [comment]
Ok, several additional restarts fixed the problem, closing.
