### ISSUE TITLE
Snapshots outdated

### ISSUE THREAD

**Issue by kaber2** [maticnetwork/bor#1199]
Hello. The snapshots haven't been updated since first of February. and thus take ages to sync. Any plans to publish fresh ones?

**Comment by 0xsajal** [comment]
Hey,

Moving forward the community will provide snapshots, you can find them here:

https://snapshots.vaultstaking.com/guides/

https://docs.stakepool.dev.br/snapshots

Hope this helps.

Thanks.

**Comment by bgiegel** [comment]
i’m also having issues starting a new node from a snapshot. Did you tried the snapshot mentioned by @0xsajal @kaber2 ? Does it work ?

**Comment by marcello33** [comment]
Please refer to @0xsajal answer.
Thank you.

**Comment by sammy007** [comment]
> Hey,
> 
> Moving forward the community will provide snapshots, you can find them here:
> 
> https://snapshots.vaultstaking.com/guides/
> 
> https://docs.stakepool.dev.br/snapshots
> 
> Hope this helps.
> 
> Thanks.

Is it compatible with path scheme?

**Comment by kaber2** [comment]
Not to belittle the efforts of the community to step up where Polygon fails, but both of these are located near Frankfurt, Germany and use no CDN. This works well for Germany and the surrounding countries, but due to latencies is pretty much useless for the U.S. and Asia.

From my perspective, the effort to keep Polygon running is not worth it anymore. Exploding storage, no usable snapshots, and more. I'll deactivate my nodes and use the space to run different blockchains. So long.

**Comment by sammy007** [comment]
It's really odd why polygon can't upload snapshots to Cloudflare R2 which they announced so laud in [this blog post](https://polygon.technology/blog/empowering-the-blockchain-community-automated-snapshot-optimization-and-ecosystem-advancements) this year. You upload it once, then just add fragments. There is eager demand for PBSS snapshots and writing it off on community is basically "passing the buck". Tried to use soft language here.
