### ISSUE TITLE
Explore using a more performant alternative to LevelDB

### ISSUE THREAD

**Issue by jdkanani** [maticnetwork/bor#12]

**Comment by pkieltyka** [comment]
One storage engine impl to check out once you're on this task is: https://github.com/cockroachdb/pebble

**Comment by Uttam-Singhh** [comment]
Some alternatives of LevelDB could be -
* Boltdb - https://github.com/boltdb/bolt
* Rocksdb - https://github.com/facebook/rocksdb

They are also used by Erigon(Turbogeth)

**Comment by kenriortega** [comment]
Other alternative could be:

- BadgerDb - https://github.com/dgraph-io/badger

**Comment by temaniarpit27** [comment]
Closing this as we are not looking to change the DB
