### ISSUE TITLE
Disk usage - Full node

### ISSUE THREAD

**Issue by jerrybb** [maticnetwork/bor#1201]
Hi, we are running Full node bor 1.2.7 - mainnet for couple of months now. I would like to know if our disk usage is normal.

Current disk usage: 
 - chaindata: 4TB (1.214.000 ldb files) 
    - ancient: 1.8TB (1.000 cdb files)

<img width="1562" alt="image" src="https://github.com/maticnetwork/bor/assets/44587704/8ed79bb0-de90-4f9f-916f-fd126a5d0885">

Heimdall is using 400GB disk space.

Any feedback would be very welcome.

**Comment by cffls** [comment]
Hi there, the disk usage looks normal. For comparison, there is a list of chain snapshots under [this page](https://snapshot.polygon.technology/).

**Comment by jerrybb** [comment]
Hi @cffls thank you for confirmation.
