### ISSUE TITLE
Bor sync stuck at block 54875999

### ISSUE THREAD

**Issue by zyx0355** [maticnetwork/bor#1210]
Hello, my current bor client is also stuck in a certain block. The block is 54875999. I rolled back the bor client blocks to 500, 2000, and 15000 and still the problem has not been solved.
My client situation is as follows:
bor version 1.1.0 and heimdall v1.0.3
The situation of heimdall is as follows:
![a48abc49f5884eb063e768157fc9022](https://github.com/maticnetwork/bor/assets/83073234/5f1a12fe-e244-44fa-ba34-75412e5adb53)

The situation of bor client is as follows:
![8055eefe0e3ba8aacbb16dda44a5f4c](https://github.com/maticnetwork/bor/assets/83073234/33a489ac-9fd5-44bd-9c8d-784b66bc121e)

When the bor client just started, it kept looking for peer nodes. After that, the following situation would always occur, and the data could not be synchronized forward.
![95a127267a87a14029763e13a6b9916](https://github.com/maticnetwork/bor/assets/83073234/5d28e903-c60e-4454-bb19-190372e3ce92)
I tried rolling back the bor client:
$ bor attach ~/.bor/data/bor.ipc`
debug.setHead("0x3451cc7")
I tried going back 500, 1000, and 15000 blocks, but the final data block was stuck at block 54875999, and the data could not be synchronized forward.

**Comment by zyx0355** [comment]
Hello, no error occurred on my side, but the bor client just kept looking for peer nodes, but peercount=0, and could never find a good peer node, resulting in data being unable to be synchronized.
@ameerrah

**Comment by zyx0355** [comment]
Do you have any other solutions?

**Comment by manav2401** [comment]
Hi, I believe you're running on a very old bor version. Could you please upgrade it and let us know how it goes? As there was a HF few weeks back, it might be the reason for bor stuck at some block. Thanks!
