### ISSUE TITLE
Failed to fetch latest no-ack milestone  err="context deadline exceeded"

### ISSUE THREAD

**Issue by srvint** [maticnetwork/bor#1212]
Setup a new node, Heimdall is fully synced.

When I start bor I receive the following message.

WARN [04-08|16:57:10.020] an error while trying fetching from Heimdall path=/milestone/lastNoAck attempt=1 error="Get \"http://localhost:1317/milestone/lastNoAck\": dial tcp 127.0.0.1:1317: connect: connection refused"
ERROR[04-08|16:57:14.020] Failed to fetch latest no-ack milestone  err="context deadline exceeded"
WARN [04-08|16:57:14.020] unable to start the no-ack-milestone service service - first run err="failed to fetch latest milestone"

How to resolve this?

**Comment by lat1992** [comment]
I have same issues when doing a fresh sync.

**Comment by srvint** [comment]
Still an issue.
