### ISSUE TITLE
Gas price is super high on Amoy testnet

### ISSUE THREAD

**Issue by thi-investax** [maticnetwork/bor#1213]
Hello everyone.

We are migrating smart contracts from Mumbai to Amoy. However i got this error  `contract creation code storage out of gas`

![image](https://github.com/maticnetwork/bor/assets/118243127/664bd3b0-624c-44a6-8ba0-d63230a33d87)

RPC node i used: https://rpc-amoy.polygon.technology

The strange things is that the same code I used works fine for Mumbai, Polygon, other networks but it doesn't work for Amoy.

This is the deployment code
![image](https://github.com/maticnetwork/bor/assets/118243127/2809537f-a75e-454a-b848-c753b5ebc143)

I need help to resolve this one as Mumbai is deprecating. Appreciate any helps. Thanks!

**Comment by thi-investax** [comment]
just figured out that gas price is ridiculously high on Amoy
![image](https://github.com/maticnetwork/bor/assets/118243127/89627e49-f054-4590-94c8-cff4903f012d)



500000000015 -> 500 gwei

**Comment by vmidyllic** [comment]
+1 from testing transaction on Amoy

**Comment by krasteva-ro** [comment]
+ 1 same issue

**Comment by thi-investax** [comment]
Here is my temporary solution until the team can resolve it.

I used a fixed gas price and it should work `3200000000`. 

```
func getGasPrice() {
    if (this.provider.network == 'amoy') {
      return BigNumber.from(3200000000);
    }
    return this.provider.send('eth_gasPrice', []);
  }

```

**Comment by bryandidur** [comment]
+1. Same issue here. Impossible to get available balance at [polygon faucet](https://faucet.polygon.technology/) to deploy a Smart Contract. Ultra very high gas price.

**Comment by carreiradotdev** [comment]
+1 here. 0.5 matic lasted me for 1 week of testing.
I'm using ethers.parseUnits("3200000000", "wei").

**Comment by emmajane1313** [comment]
+1 it's almost impossible to deploy contracts and the faucet doesn't give sufficient test tokens

**Comment by s4nghun** [comment]
+1 lmao 302 for standard

**Comment by pacman21** [comment]
Glad to see this issue isn't just me. I am having the same issue. Can't deploy or even interact with contracts because the gas price is so high. "transaction underpriced: tip needed 30000000000, tip permitted 1000000000"

We have any news on why this is so?

**Comment by thi-investax** [comment]
hi  Polygon team @0xsharma 0. Could we have some people to reopen this ticket and resolve this issue please?

**Comment by s4nghun** [comment]
seems like there's an issue with the amoy gas station api

**Comment by slmatthiesen** [comment]
Running into all the same: transaction underpriced: issue all of a sudden as well.

**Comment by HNHK-Poon** [comment]
+1 it's almost impossible to deploy contracts and the faucet doesn't give sufficient test tokens

**Comment by vrajasekaran** [comment]
Still this is an issue, TX fee ranging from 1 to 12 ethers

**Comment by asciitohex** [comment]
Same here, impossible to use amoy testnet to test SC, TX fee are too high and faucet too low.

**Comment by nickz-t3** [comment]
same issue here. Even a smallish transaction can not be run on Amoy

**Comment by junqueror** [comment]
Same here. Poor developer experience...

I'm using Polygon Amoy Faucet to send a few tokens to different accounts and then sending them to the deployer account

It is even easier to test in main Polygon network
