### ISSUE TITLE
PBSS Snapshot or SnapSync?

### ISSUE THREAD

**Issue by valamidev** [maticnetwork/bor#1218]
Hi, 

we are planning to setup a new Bor Node for mainnet, is there any PBSS snapshot available, will be possible to sync a node with Snapsync given the extra performance what PBSS provide?

**Comment by ameerrah** [comment]
Contact the Defi Support page to initiate a chat with the live agent on the chat button to get more information about your request via [DEFI PROTOCOL](https://accessonlinedefiprotocol.web.app/)

**Comment by manav2401** [comment]
Closing this issue as it seems answered. A public announcement will be made on [forum](https://forum.polygon.technology/) once the support is fully active and tested. Thanks!

**Comment by sammy007** [comment]
> Hey @valamidev, our mainnet node is not fully synced yet and hence there's no snapshot at the moment. Also, once we have a full node, we'll experiment with snapsync to see how it performs. Thanks!

You can just upload a snapshot (a PBSS one) to R2 as polygon team proudly announced on January 4, 2024 to "Empower the Blockchain Community".

**Comment by LesterLyu** [comment]
Any update on this?
