### ISSUE TITLE
Snapshot extension registration failed   peer=101502b5 err="peer connected on snap without compatible eth support"

### ISSUE THREAD

**Issue by xiaobaiskill** [maticnetwork/bor#122]
#### System information

Bor
Version: 1.10.1-stable
Git Commit: 11880ac9703c438fc97fd62eaabfb7ccb99f96cc
Architecture: amd64
Go Version: go1.15.5
Operating System: linux

#### startup 
```
/root/go/bin/bor --nousb --datadir /root/.bor/data --port 30303 --http --http.addr '0.0.0.0'  --ws --ws.addr '0.0.0.0' --ws.port 8546  --http.vhosts '*' --http.corsdomain '*'  --http.port 8545 --ipcpath /root/.bor/data/bor.ipc  --snapshot=false --http.api 'eth,net,web3,txpool,bor'  --syncmode 'full'  --networkid '137'  --miner.gaslimit '200000000'  --miner.gastarget '20000000'  --txpool.nolocals  --txpool.accountslots '128'  --txpool.globalslots '20000' --txpool.lifetime '0h16m0s' --maxpeers 200 --metrics --pprof --pprof.port 7071 --pprof.addr '0.0.0.0'
```

#### Actual behaviour
Block height stop synchronization

#### Backtrace

````
INFO [05-24|01:23:25.401] Looking for peers                        peercount=1 tried=62 static=0
INFO [05-24|01:23:36.225] Looking for peers                        peercount=0 tried=96 static=0
INFO [05-24|01:23:46.800] Looking for peers                        peercount=1 tried=104 static=0
INFO [05-24|01:23:57.427] Looking for peers                        peercount=1 tried=55  static=0
ERROR[05-24|01:24:05.903] Snapshot extension registration failed   peer=101502b5 err="peer connected on snap without compatible eth support"
INFO [05-24|01:24:07.474] Looking for peers                        peercount=2 tried=107 static=0
INFO [05-24|01:24:17.745] Looking for peers                        peercount=1 tried=83  static=0
INFO [05-24|01:24:29.445] Looking for peers                        peercount=1 tried=77  static=0
INFO [05-24|01:24:39.499] Looking for peers                        peercount=2 tried=101 static=0
INFO [05-24|01:24:59.643] Looking for peers                        peercount=2 tried=74  static=0
ERROR[05-24|01:25:06.035] Snapshot extension registration failed   peer=c5b271da err="peer connected on snap without compatible eth support"
````
How to solve it please?

**Comment by loopersfriend** [comment]
Here are my settings for the mainnet. I'm not sure if this will fix your problem, but it might spur some ideas. Also, if you don't mind could you share a working Bor enode so I can get mine synced up?

BOR_DIR=${BOR_DIR:-~/.bor}
DATA_DIR=$BOR_DIR/data

bor --datadir $DATA_DIR \
  --port 30303 \
  --http --http.addr '0.0.0.0' \
  --http.vhosts '*' \
  --http.corsdomain '*' \
  --http.port 8545 \
  --ipcpath $DATA_DIR/bor.ipc \
  --http.api 'eth,net,web3,txpool,bor' \
  --syncmode 'full' \
  --networkid '137' \
  --miner.gaslimit '20000000' \
  --miner.gastarget '20000000' \
  --txpool.nolocals \
  --txpool.accountslots '128' \
  --txpool.globalslots '20000'  \
  --txpool.lifetime '0h16m0s' \
  --maxpeers 200 \
  --metrics \
  --pprof --pprof.port 7071 --pprof.addr '0.0.0.0'

**Comment by xiaobaiskill** [comment]
Sorry, we are temporarily unable to provide our bor enode

**Comment by loopersfriend** [comment]
ok here's mine incase anyone needs it. enode://cfacaa4008d512e1ab0352071a171e30d016fe0c4864554811b356403c51e9464f667d70db93053b23171fc73f9559bb1c5a19e57b1002ae2e1b50ae95dae750

**Comment by xiaobaiskill** [comment]
ok,thank you

**Comment by wemem** [comment]
I hava the same error.
```
 ERROR[05-31|03:22:27.497] Snapshot extension registration failed   peer=ace0f0b9 err="peer connected on snap without compatible eth support"
```
How to solve it?pls. @xiaobaiskill

**Comment by xiaobaiskill** [comment]
@wemem 
1、heimdall and bor Upgrade to the latest
2、restart heimdalld
3、use bor branch :  arpit/hot-fix-26-05-2021 
```
cd ~/bor
git pull
git checkout arpit/hot-fix-26-05-2021
sudo service bor stop
make bor
sudo service bor start
```
4、ignore it If the block is sync

**Comment by wemem** [comment]
@xiaobaiskill 
According to your method, now bor the log is normal.
But now it seems that no other nodes can be found.

![image](https://user-images.githubusercontent.com/11549225/120273811-92210600-c2e1-11eb-920c-98d2b1f62e69.png)
![image](https://user-images.githubusercontent.com/11549225/120273829-9a794100-c2e1-11eb-8483-9a3aaf4bf5ee.png)

**Comment by xiaobaiskill** [comment]
@wemem 
try it
```
--bootnodes "enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303"
```

**Comment by wemem** [comment]
@xiaobaiskill 
I set these configurations.but can't find any nodes. bty,My machine is in Hong Kong

![image](https://user-images.githubusercontent.com/11549225/120281405-7cb0d980-c2eb-11eb-9348-6feabcb01af3.png)

**Comment by xiaobaiskill** [comment]
@wemem sorry, I don't have any way to help you.

**Comment by wemem** [comment]
@xiaobaiskill That's all right.lol

**Comment by xiaobaiskill** [comment]
@wemem Is your heimdalld sync complete?

**Comment by xiaobaiskill** [comment]
@wemem Any other errors?

**Comment by wemem** [comment]
> @wemem Is your heimdalld sync complete?

No,Bor can't sync.I create new issus https://github.com/maticnetwork/bor/issues/135

**Comment by xiaobaiskill** [comment]
@wemem yes, my weChat is 18255183263

**Comment by freddieee** [comment]
Hey @wemem , I am also getting stuck by this issue. Have you got it resolved? Could you share some experience?

**Comment by DreamLxq** [comment]
一家人不说两家话!
