### ISSUE TITLE
Snapshot delivery speed

### ISSUE THREAD

**Issue by VSGic** [maticnetwork/bor#1236]
Since I have not enough rights to ask in Discord, I place question here : Is there is any update for snapshot node restore? Docs have links on old snapshots from Febriary, while advised community snapshots have very slow download speed. So sync of blocks from blockchain with old official snapshot and downloading snapshots from community links, that supposed should give advantage in sync speed, consume too much time. What is the fastest and recomended way for node restore?

**Comment by 0xsajal** [comment]
Hey, the fastest way to download the snapshots is using the community snapshots itself. If you are facing any issues, you can reach out to the aggregator directly. Read more here: https://forum.polygon.technology/t/stakecraft-introduces-a-new-service-for-polygon-community-all4nodes-io-aggregator-service/13694
If you are unable to reach out to them, please let us know what aggregator you are trying to connect to and we can help you reach out to them. Or you can post the exact issue here and I can take it up with the respective team.
Thanks.

**Comment by VSGic** [comment]
Ok, I have issue with download speed from snapshot sources, and searching the way to get snapshot within 3-4 hours like it was from Polygon network sources. In this cases to restore node within 1-2 days after fault becomes not possible.

**Comment by 0xsajal** [comment]
Hey can you please tell me which snapshot you tried to download?

**Comment by koraykoska** [comment]
@0xsajal I am trying to download the one from StakeCraft and it seems pretty limited in DL speed. Need a faster access for recovering a node. Is there any way to access the StakeCraft one faster? Maybe whitelist my IP for faster access?

(using aria2c of course)

**Comment by sammy007** [comment]
It would be great if there is access to at least one fresh snapshot which is utilizing PBSS.

**Comment by 0xsajal** [comment]
Hey, there are multiple options available for bor snapshots https://all4nodes.io/Polygon, did you try vaultstaking or stakepool snapshots?
