### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by lat1992** [maticnetwork/bor#1248]
#### **System information**

Bor client version: v1.3.2

Go version: 1.22.3

OS & Version: Linux arm

#### **Overview of the problem**

I cannot compile bor.

#### **Reproduction Steps**

clone the repo, then compile it, it shows an error.

#### **Logs / Traces / Output / Error Messages**
 
```
go build -o /home/lat/Projects/bor/build/bin/bor ./cmd/cli/main.go
# github.com/maticnetwork/heimdall/auth/types
../../go/pkg/mod/github.com/maticnetwork/heimdall@v1.0.4/auth/types/txbuilder.go:312:19: undefined: ethCrypto.Sign
../../go/pkg/mod/github.com/maticnetwork/heimdall@v1.0.4/auth/types/txbuilder.go:318:19: undefined: ethCrypto.RecoverPubkey
```

**Comment by cffls** [comment]
Could you please show the full command you used and the full log output?

**Comment by cffls** [comment]
Can you try `CGO_ENABLED=1 go build -o build/bin/bor ./cmd/cli/main.go`?
