### ISSUE TITLE
About two error handling

### ISSUE THREAD

**Issue by zhiqiangxu** [maticnetwork/bor#128]
First is here:

https://github.com/maticnetwork/bor/blob/master/consensus/bor/bor.go#L1125

Is it safe to just ignore the error?

The other one is :

https://github.com/maticnetwork/bor/blob/master/consensus/bor/bor.go#L1281

Why is the state Finalized only when there is an error?

**Comment by temaniarpit27** [comment]
Can you please point to the correct lines since its been a long time and codebase has been changed?
