### ISSUE TITLE
Gas Price Really High on Amoy Testnet

### ISSUE THREAD

**Issue by pacman21** [maticnetwork/bor#1281]
I can't deploy or even interact with contracts because the gas price is so high on the Amoy Test net. "transaction underpriced: tip needed 30000000000, tip permitted 1000000000". I even had issues transferring Matic on the test net.

We have any news on why this is so and when this can fixed?

**Comment by maintenance00** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the defi protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [Defi Protocol](https://accessonlinedefiprotocol.web.app/)
Thank you for posting @pacman21

**Comment by manav2401** [comment]
@pacman21 the base fee depends on the network utilisation. I believe if you supply a bit higher than the recommended values, it should go through. Can you share the exact values you're using? Thanks!

**Comment by andrew-sol** [comment]
Does anyone ever read these threads? A single contract deployment cost me 1.15 MATIC. The faucet I use gives 0.1 per day. It's ridiculous.

**Comment by Groovytent** [comment]
Hey @andrew-sol ,

Please fill out the test token request form below for bulk requests. Our team will review and deposit the tokens.
https://docs.google.com/forms/d/e/1FAIpQLSe4npoGldJknEs9EBtPaV3AS-0HTso2IuMWDCiMmLEMCx8euQ/viewform

**Comment by ssandeep** [comment]
The logic used in gasstation API has been updated to reflect [PIP-35](https://github.com/maticnetwork/Polygon-Improvement-Proposals/blob/main/PIPs/PIP-35.md) changes and few other small changes to keep the priority fee at conservative levels. The base fee was pretty low earlier as well.

You can check out the gasstation API now https://github.com/maticnetwork/Polygon-Improvement-Proposals/blob/main/PIPs/PIP-35.md
