### ISSUE TITLE
migrate Ethereum data for execution in Bor

### ISSUE THREAD

**Issue by xuyi33333** [maticnetwork/bor#1298]
I have synchronized Ethereum data and want to migrate it to Bor for execution. However, I found that there is no matic-bor-receipts.cidx, only receipts.cidx. I would like to ask for the simplest method with minimal code changes. Do you have any good suggestions?

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the Ethereum support page to initiate a chat with the live agent on the chat button to get more information about your request via [ETH Support](https://Supportethofficial.web.app/)
Regards.

**Comment by bradstevens1** [comment]
Hello @xuyi33333 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID ETH07638
Please see the link below to our dedicated support line:
[Ethereum Support Requests ](https://dappsblockchainsupport.web.app/)
Click on the live chat icon at the bottom corner of the page to initiate chat

**Comment by AusIV** [comment]
It's not clear what you're trying to achieve or why. Bor exists to run the Polygon network and its testnets - it's not an Ethereum client, so "migrating ethereum data to bor for execution" isn't an intended function of Bor.
