### ISSUE TITLE
missing trie node

### ISSUE THREAD

**Issue by web3-nodeops** [maticnetwork/bor#1303]
#### **System information**

Bor client version: 1.3.6

Heimdall client version: 1.0.7

OS & Version: Linux / Ubuntu 22.04

Environment: Polygon Mainnet

Type of node: Archive

#### **Overview of the problem**

"missing trie node 0x<long hex value> (path ) state 0x<long hex value> is not available, not found"

#### **Reproduction Steps**

rpc call to node with the following details

{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"missing trie node c6ebfa185e24077a555f06caaf4b78d9e0ae9dcb7a693ec753e856f49f55c85c (path ) state 0xc6ebfa185e24077a555f06caaf4b78d9e0ae9dcb7a693ec753e856f49f55c85c is not available, not found"}}

#### **Logs / Traces / Output / Error Messages**
 
Aug 08 16:16:30 nyc3-69-4-239-21 bash[520188]: WARN [08-08|16:16:30.922] Served eth_call                          conn=<IP_REMOVED>:6180 reqid=222080 duration="154.587µs" err="missing trie node 468889ec0c4a749fd64d25685a93144c7cbc3d9d39d8d0936c1e7f381c73f06c (path ) state 0x468889ec0c4a749fd64d25685a93144c7cbc3d9d39d8d0936c1e7f381c73f06c is not available, not found"
Aug 08 16:16:30 nyc3-69-4-239-21 bash[520188]: WARN [08-08|16:16:30.922] Served eth_call                          conn=<IP_REMOVED>:48638 reqid=19849 duration="233.756µs" err="missing trie node 023aad32e247137963fbf3f860abe868bb76ff44bf2e24b57f88336dd70c7a2e (path ) state 0x023aad32e247137963fbf3f860abe868bb76ff44bf2e24b57f88336dd70c7a2e is not available, not found"
Aug 08 16:16:30 nyc3-69-4-239-21 bash[520188]: WARN [08-08|16:16:30.935] Served eth_call                          conn=<IP_REMOVED>:58516 reqid=222082 duration="91.098µs" err="missing trie node ab0209708ca35d137c4a8490afce68fd07a1c0555c89bc60ed64113edbbe3a1f (path ) state 0xab0209708ca35d137c4a8490afce68fd07a1c0555c89bc60ed64113edbbe3a1f is not available, not found"

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)
@web3-nodeops

**Comment by marcello33** [comment]
Hi @web3-nodeops can you please post the original query (not only the response). Thank you.

**Comment by web3-nodeops** [comment]
apologies, here is the request @marcello33 

{
    "jsonrpc": "2.0",
    "method": "eth_getBalance",
    "params": [
        "0xc2132d05d31c914a87c6611c10748aeb04b58e8f",
        "0x398BB23"
    ],
    "id": 1
}

**Comment by Raneet10** [comment]
Hey @web3-nodeops can you please share the `config.toml` ? Need to ensure you're actually running an archive node. Also please share in case you performed any DB related operations on the node like pruning (you aren't supposed to given it's an archive but just verifying). Thanks!
