### ISSUE TITLE
Support compilation with Go 1.23

### ISSUE THREAD

**Issue by yorickdowne** [maticnetwork/bor#1307]
# Feature

Compilation with Go 1.23 currently fails. Go 1.22 works

```
26.20 go: downloading go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.49.0
26.22 go: downloading github.com/felixge/httpsnoop v1.0.4
84.03 # command-line-arguments
84.03 link: github.com/fjl/memsize: invalid reference to runtime.stopTheWorld
84.18 make: *** [Makefile:28: bor] Error 1
```

**Comment by yorickdowne** [comment]
Upstream: https://github.com/fjl/memsize/issues/5

**Comment by yorickdowne** [comment]
Go team rejected the memsize author’s proposal to make memsize work with Go 1.23.

Upstream go-ethereum fixed this by removing memsize in this patch: https://github.com/ethereum/go-ethereum/commit/e4675771eda550e7eeb63a8884816982c1980644

**Comment by klestrong** [comment]
@yorickdowne 
Thank you! Your post is much appreciated. I can confirm specifying Go 1.22 successfully completed the build for me and has resolved my issue in the previous ticket I posted.
https://github.com/maticnetwork/bor/issues/1306#issue-2464851265

**Comment by marcello33** [comment]
We applied the same patch from go-ethereum [here](https://github.com/maticnetwork/bor/pull/1308)
It will be eventually merged and released with the next release.
In the meantime, you can apply the workaround by changing the version in the Dockerfile.
Thank you.
