### ISSUE TITLE
bor sync error log

### ISSUE THREAD

**Issue by wemem** [maticnetwork/bor#131]
Hello.
When I start launching the ```sudo service bor start``` directive.the log hava error.

```journalctl -u bor.service -f```
![image](https://user-images.githubusercontent.com/11549225/120134979-da68f700-c201-11eb-8a82-095abba06aa9.png)

```curl localhost:26657/status```
![image](https://user-images.githubusercontent.com/11549225/120134928-ba393800-c201-11eb-8147-7a22a5c6783d.png)

How to resolve these errors?

btw.How to check the synchronization of bor service.

**Comment by delroybosco** [comment]
Hey @wemem You can add a flag `--snapshot=false` in your `start.sh` file and restart your Bor service until you Bor completely syncs. Once is it synced, you can remove this flag and restart your Bor service.

In order to get the latest block height on Bor you can run the following commands

`bor attach ./.bor/data/bor.ipc`
`> eth.syncing`

**Comment by wemem** [comment]
@delroybosco  
Hi.Through your way, the bor error log did not appear.
But now it seems that no other nodes can be found. How to solve it pls.
![image](https://user-images.githubusercontent.com/11549225/120274167-09ef3080-c2e2-11eb-9c0f-6b3727e7f4ad.png)
![image](https://user-images.githubusercontent.com/11549225/120274178-107da800-c2e2-11eb-9d23-6d168347bb9b.png)
![image](https://user-images.githubusercontent.com/11549225/120274199-17a4b600-c2e2-11eb-95cb-329e116622e6.png)

**Comment by delroybosco** [comment]
Try restarting the Bor service. It should work. It has worked normally with similar cases as well.

**Comment by wemem** [comment]
> Try restarting the Bor service. It should work. It has worked normally with similar cases as well.

@delroybosco  I have restarted the service many times and waited all night, but still the synchronization did not start.

now I upgrade bor.
```bor version```
Architecture: amd64
Go Version: go1.13
Operating System: linux

![image](https://user-images.githubusercontent.com/11549225/120422360-ae34ae00-c39a-11eb-87f8-6689f0ffc17c.png)
![image](https://user-images.githubusercontent.com/11549225/120422415-c73d5f00-c39a-11eb-9464-fc7259317d76.png)

**Comment by wardbradt** [comment]
@wemem Were you able to solve this?

**Comment by wardbradt** [comment]
> latest_block_height is 5322111
I think that this is for the heimdall chain and is accurate. I think I am having the same error, but when I look at `journalctl -u heimdalld.service -f`, I see that the bor blocks on Heimdall are up to date.

**Comment by wardbradt** [comment]
Following this seems to have helped my node. https://forum.matic.network/t/matic-mainnet-bor-upgrade-v0-2-6/990

It seems that for me, bor stopped syncing on some block from May 21. After updating the `genesis.json` file, it is now catching up again

**Comment by wemem** [comment]
> Following this seems to have helped my node. https://forum.matic.network/t/matic-mainnet-bor-upgrade-v0-2-6/990
> 
> It seems that for me, bor stopped syncing on block 14749999 from May 21. After updating the `genesis.json` file, it is now catching up again
> 
> Edit: my bor version is `1.10.3-stable` by the way.

I solved it!
