### ISSUE TITLE
Failed to read headers from freezer      err="out of bounds"

### ISSUE THREAD

**Issue by 1aBcD1234aBcD1** [maticnetwork/bor#1317]
Hi everyone.

So Im trying to sync a node using one snapshot and I have tried some of the recommended snapshots. During the syncing process to the latest block Im getting the following error:
```
2024-08-27T10:19:50.672326985Z ERROR[08-27|10:19:50.672] Failed to read headers from freezer      err="out of bounds"
2024-08-27T10:19:51.725009578Z ERROR[08-27|10:19:51.724] Failed to read headers from freezer      err="out of bounds"
```

**Comment by summerly01** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@1aBcD1234aBcD1
