### ISSUE TITLE
bor stop sync after catch the latest block

### ISSUE THREAD

**Issue by lcgogo** [maticnetwork/bor#132]
#### System information

Geth version: `geth version`
OS & Version: linux
Commit hash : arpit/hot-fix-26-05-2021

#### Expected behaviour

bor continue sync with latest block

#### Actual behaviour

bor stop sync after catch up the latest block

#### Backtrace

````
curl -v -H "Content-Type: application/json" -X POST -d '{"jsonrpc":"2.0","id":"curltext","method":"eth_syncing"}' localhost:8545
{"jsonrpc":"2.0","id":"curltext","result":{"currentBlock":"0xe72792","highestBlock":"0xe727da","knownStates":"0x6cc97a4","pulledStates":"0x6cc97a4","startingBlock":"0x0"}}

{"log":"INFO [05-31|09:35:56.718] Retrying again in 5 seconds for next Heimdall span path=bor/span/2368\n","stream":"stderr","time":"2021-05-31T09:35:56.718335613Z"}
{"log":"INFO [05-31|09:36:01.721] Retrying again in 5 seconds for next Heimdall span path=bor/span/2368\n","stream":"stderr","time":"2021-05-31T09:36:01.72116917Z"}
````

When submitting logs: please submit them as text and not screenshots.

**Comment by lcgogo** [comment]
I use the hotfix of https://github.com/maticnetwork/bor/issues/119

**Comment by delroybosco** [comment]
Can you check if your Heimdall instance is syncing and running correctly? Also are you running a full node or a validator node?

**Comment by lcgogo** [comment]
> Can you check if your Heimdall instance is syncing and running correctly? Also are you running a full node or a validator node?

Thanks for reply.

My heimdalld node is still syncing like below

I[2021-06-01|03:07:37.323] Committed state                              module=state height=1871971 txs=0 appHash=8ECCE1ACCDFA5D40BC4F15A0998B05CF7E0AFF01342581190F87DA080ECC346C
I[2021-06-01|03:07:37.341] Executed block                               module=state height=1871972 validTxs=0 invalidTxs=0
I[2021-06-01|03:07:37.389] Committed state                              module=state height=1871972 txs=0 appHash=8ECCE1ACCDFA5D40BC4F15A0998B05CF7E0AFF01342581190F87DA080ECC346C
I[2021-06-01|03:07:37.406] Executed block                               module=state height=1871973 validTxs=0 invalidTxs=0
I[2021-06-01|03:07:37.453] Committed state                              module=state height=1871973 txs=0 appHash=8ECCE1ACCDFA5D40BC4F15A0998B05CF7E0AFF01342581190F87DA080ECC346C

I want to run a full node, however, the bor can not find peers if heimdall is not running.

I followed this guide ( https://chasewright.com/how-to-run-a-polygon-matic-mainnet-node/ )  to run all 4 containers:
heimdalld, heimdallr, rabbitmq and bor.

**Comment by lcgogo** [comment]
Think may caused by heimdalld not full synced.

I can get
curl localhost:1317/bor/span/10
but not
curl localhost:1317/bor/span/1000
and also
curl localhost:1317/bor/span/2368

`# curl localhost:1317/bor/span/1000
{"error":"{\"codespace\":\"sdk\",\"code\":1,\"message\":\"could not get span; span not found for id\"}"}root@ip-172-30-0-26:/data/matic#

# curl localhost:1317/bor/span/10
{"height":"1949967","result":{"span_id":10,"start_block":57856,"end_block":64255,"validator_set":{"validators":[{"ID":6,"startEpoch":0,"endEpoch":0,"nonce":1,"power":10000,"pubKey":"0x0447ed13442b485dd6990efc01d4297d798e90d3fa8467dd9c2f50ffe3238c8bf722f6c774f584b5fe91364b7b430c5a24fe57aca48665cf778030266f2c452bd9","signer":"0x0375b2fc7140977c9c76d45421564e354ed42277","last_updated":"","jailed":false,"accum":-16466},{"ID":7,"startEpoch":0,"endEpoch":0,"nonce":1,"power":10000,"pubKey":"0x043522a004012c9740703f676b95b5121edd7237fb0f182c3c45e7c7a77eaa67a20e6d0ac025d5bd96295bf95e2e875ab2a9da5c0e547b7d00ca7ede33c1b03893","signer":"0x42eefcda06ead475cde3731b8eb138e88cd0bac3","last_updated":"","jailed":false,"accum":-20964},{"ID":1,"startEpoch":0,"endEpoch":0,"nonce":2,"power":14498,"pubKey":"0x043c53ea6e1964e0670dc9ac72b3224207885d4c5f08cabe1e1080c662fdec278e7e833798757cb5cf121447dcd02a15f010eb4aa87cceecb23daa4bf904112e77","signer":"0x5973918275c01f50555d44e92c9d9b353cadad54","last_updated":"1016887000143","jailed":false,"accum":46788},{"ID":5,"startEpoch":0,"endEpoch":0,"nonce":1,"power":10000,"pubKey":"0x0479efe8c50b1f9923f48a467ecac0a64c2d6bcaa9ae67e135df84cac5aed5321f9cbb29c115f26dc84f2ef0e5fea29615848c79d690cb205cc10d688324ae8bce","signer":"0x7fcd58c2d53d980b247f1612fdba93e9a76193e6","last_updated":"","jailed":false,"accum":-20964},{"ID":4,"startEpoch":0,"endEpoch":0,"nonce":1,"power":10000,"pubKey":"0x04b4e1d56b3429f7756452426be611e595debcb858d59f47d29ec9dd6e4b547dce1539f9b7144420bc309de496b70d6dc5f13345eee85e6b7fb332cd9f364ef12f","signer":"0xb702f1c9154ac9c08da247a8e30ee6f2f3373f41","last_updated":"","jailed":false,"accum":-20964},{"ID":2,"startEpoch":0,"endEpoch":0,"nonce":1,"power":10000,"pubKey":"0x04d6b06c725f5410e4ccbd65906ece180364ebea4902b21232c1fb5892a76be7eec22480397d6bf653e9abe7ac50435ee472b59364fe78b17acb2be2116f92a76f","signer":"0xb8bb158b93c94ed35c1970d610d1e2b34e26652c","last_updated":"","jailed":false,"accum":-20964},{"ID":3,"startEpoch":0,"endEpoch":0,"nonce":1,"power":10000,"pubKey":"0x040600efda73e1404b0c596e08c78c5ed51631fc173e5f39d21deeddd5712fcd7d6d440c53d211eb48b03063a05b2c0c0eb084053dfcf1c6540def705c8e028456","signer":"0xf84c74dea96df0ec22e11e7c33996c73fcc2d822","last_updated":"","jailed":false,"accum":53534}],"proposer":{"ID":2,"startEpoch":0,"endEpoch":0,"nonce":1,"power":10000,"pubKey":"0x04d6b06c725f5410e4ccbd65906ece180364ebea4902b21232c1fb5892a76be7eec22480397d6bf653e9abe7ac50435ee472b59364fe78b17acb2be2116f92a76f","signer":"0xb8bb158b93c94ed35c1970d610d1e2b34e26652c","last_updated":"","jailed":false,"accum":-20964}},"selected_producers":[{"ID":6,"startEpoch":0,"endEpoch":0,"nonce":1,"power":10000,"pubKey":"0x0447ed13442b485dd6990efc01d4297d798e90d3fa8467dd9c2f50ffe3238c8bf722f6c774f584b5fe91364b7b430c5a24fe57aca48665cf778030266f2c452bd9","signer":"0x0375b2fc7140977c9c76d45421564e354ed42277","last_updated":"","jailed":false,"accum":-60000},{"ID":7,"startEpoch":0,"endEpoch":0,"nonce":1,"power":10000,"pubKey":"0x043522a004012c9740703f676b95b5121edd7237fb0f182c3c45e7c7a77eaa67a20e6d0ac025d5bd96295bf95e2e875ab2a9da5c0e547b7d00ca7ede33c1b03893","signer":"0x42eefcda06ead475cde3731b8eb138e88cd0bac3","last_updated":"","jailed":false,"accum":10000},{"ID":1,"startEpoch":0,"endEpoch":0,"nonce":2,"power":14498,"pubKey":"0x043c53ea6e1964e0670dc9ac72b3224207885d4c5f08cabe1e1080c662fdec278e7e833798757cb5cf121447dcd02a15f010eb4aa87cceecb23daa4bf904112e77","signer":"0x5973918275c01f50555d44e92c9d9b353cadad54","last_updated":"1016887000143","jailed":false,"accum":10000},{"ID":5,"startEpoch":0,"endEpoch":0,"nonce":1,"power":10000,"pubKey":"0x0479efe8c50b1f9923f48a467ecac0a64c2d6bcaa9ae67e135df84cac5aed5321f9cbb29c115f26dc84f2ef0e5fea29615848c79d690cb205cc10d688324ae8bce","signer":"0x7fcd58c2d53d980b247f1612fdba93e9a76193e6","last_updated":"","jailed":false,"accum":10000},{"ID":4,"startEpoch":0,"endEpoch":0,"nonce":1,"power":10000,"pubKey":"0x04b4e1d56b3429f7756452426be611e595debcb858d59f47d29ec9dd6e4b547dce1539f9b7144420bc309de496b70d6dc5f13345eee85e6b7fb332cd9f364ef12f","signer":"0xb702f1c9154ac9c08da247a8e30ee6f2f3373f41","last_updated":"","jailed":false,"accum":10000},{"ID":2,"startEpoch":0,"endEpoch":0,"nonce":1,"power":10000,"pubKey":"0x04d6b06c725f5410e4ccbd65906ece180364ebea4902b21232c1fb5892a76be7eec22480397d6bf653e9abe7ac50435ee472b59364fe78b17acb2be2116f92a76f","signer":"0xb8bb158b93c94ed35c1970d610d1e2b34e26652c","last_updated":"","jailed":false,"accum":10000},{"ID":3,"startEpoch":0,"endEpoch":0,"nonce":1,"power":10000,"pubKey":"0x040600efda73e1404b0c596e08c78c5ed51631fc173e5f39d21deeddd5712fcd7d6d440c53d211eb48b03063a05b2c0c0eb084053dfcf1c6540def705c8e028456","signer":"0xf84c74dea96df0ec22e11e7c33996c73fcc2d822","last_updated":"","jailed":false,"accum":10000}],"bor_chain_id":"137"}}

# curl localhost:1317/bor/span/2368
{"error":"{\"codespace\":\"sdk\",\"code\":1,\"message\":\"could not get span; span not found for id\"}"}root@ip-172-30-0-26:/data/matic#
`

**Comment by 0xKrishna** [comment]
@lcgogo Let you heimdall node sync completely. Then only start the bor.

**Comment by nuliknol** [comment]
> @lcgogo Let you heimdall node sync completely. Then only start the bor.

and what if we are running with the flag `--bor.withoutheimdall` ??? There will be no heimdall node to sync.

**Comment by nuliknol** [comment]
@0xKrishna 
and what if we are running with the flag --bor.withoutheimdall ??? There will be no heimdall node to sync.

**Comment by lcgogo** [comment]
> @lcgogo Let you heimdall node sync completely. Then only start the bor.

After heimdalld synced and the bor continue sync. Many thanks.

**Comment by laurelgithub** [comment]
Which node node you use, the two official addresses in my bor configuration file are invalid
