### ISSUE TITLE
Block-STM code implementation

### ISSUE THREAD

**Issue by xuyi33333** [maticnetwork/bor#1329]
func (task *ExecutionTask) Execute(mvh *blockstm.MVHashMap, incarnation int) (err error) {
	**task.statedb = task.cleanStateDB.Copy()**
	task.statedb.SetTxContext(task.tx.Hash(), task.index)
....
}

I would like to understand why each execution requires "task.statedb = task.cleanStateDB.Copy()." Is it to ensure determinism?"

**Comment by xuyi33333** [comment]
I believe that if the statedb is large, such copying could lead to significant performance overhead. Can parallel execution really compensate for this overhead and surpass serial execution? Also, I don't quite understand why copying is necessary in this case. I look forward to your response.

**Comment by cffls** [comment]
> I would like to understand why each execution requires "task.statedb = task.cleanStateDB.Copy()." Is it to ensure determinism?"

This is to prevent a task from modifying the state from another.

> I believe that if the statedb is large, such copying could lead to significant performance overhead.

Copying happens in memory, it is insignificant compared to other operations, such as loading data from database.

> start includes the time spent on copying, and not just the actual execution time.

Yes, it includes the time of copying.

**Comment by xuyi33333** [comment]
I am currently trying to port the block-stm implementation to the EVM. After syncing Ethereum's data and executing its transactions, I noticed that parallel execution is not faster than serial execution. Could you please share some insights into potential reasons for this based on the implementation? Thank you very much!
