### ISSUE TITLE
Bor upgrade version 1.4.0 is out of sync

### ISSUE THREAD

**Issue by okogie** [maticnetwork/bor#1334]
* Bor Version: v1.4.0

* Description
The bor log keeps outputting Whitelisting milestone deferred. When bor is restarted, it will catch up with the latest block and then get stuck at Whitelisting milestone deferred.

* Logs 
![Image20240916171647](https://github.com/user-attachments/assets/e48af524-58bc-443d-852f-470a9b580405)

**Comment by wangjiangw** [comment]
we found this issue too in amoy testnet

**Comment by okogie** [comment]
> we found this issue too in amoy testnet

Is there any solution?

**Comment by AmardeepSambaru** [comment]
Hi,
Good morning.

Iam a node operator, am also facing the same issue in one of my polygon node. have you been able to a find a solution for this?

Thanks.


**ep 19 00:50:15 polygon-sentry-01 bor[706971]: INFO [09-19|00:50:15.856] Commit Interrupt. Pre-committing the current block block=61,984,255
Sep 19 00:50:15 polygon-sentry-01 bor[706971]: WARN [09-19|00:50:15.948] Tx Level Interrupt                       hash=000000..000000
Sep 19 00:50:19 polygon-sentry-01 bor[706971]: INFO [09-19|00:50:19.914] Whitelisting milestone deferred          err="chain out of sync"
Sep 19 00:50:31 polygon-sentry-01 bor[706971]: INFO [09-19|00:50:31.915] Whitelisting milestone deferred          err="chain out of sync"
Sep 19 00:50:43 polygon-sentry-01 bor[706971]: INFO [09-19|00:50:43.915] Whitelisting milestone deferred          err="chain out of sync"
Sep 19 00:50:55 polygon-sentry-01 bor[706971]: INFO [09-19|00:50:55.915] Whitelisting milestone deferred          err="chain out of sync"
Sep 19 00:51:07 polygon-sentry-01 bor[706971]: INFO [09-19|00:51:07.916] Whitelisting milestone deferred          err="chain out of sync"
Sep 19 00:51:19 polygon-sentry-01 bor[706971]: INFO [09-19|00:51:19.915] Whitelisting milestone deferred          err="chain out of sync"**

**Comment by adamf-sendblocks** [comment]
We're also seeing exactly the same behavior as described, we've just upgraded to v1.4.1 and that hasn't made any difference.

**Comment by AmardeepSambaru** [comment]
Yes, I updated to v1.4.1 version but same errors. it worked fine for 30 minutes to an hour, but then I started encountering the error mentioned above.

**Comment by okogie** [comment]
I upgraded two nodes in total, and each node had the same problem. The first node automatically recovered after running for a few days, but the other node still had the same problem

**Comment by wangjiangw** [comment]
> ut the other node still had the same problem

our node have been normal after a few hours, and in that time i have tried to remove the node key info, but i don't know if it makes the node normally.

**Comment by AmardeepSambaru** [comment]
Hi,

Can you please follow the steps mentioned below?

1. Increase the maxpeer to 400.
2. Add "enode://429bb1c348c769218ecf2b400dc16b86045f3eec89780a8d8d73913f6c9dc184a8d3d3bfcb7197092065c2ebbad4fd177aa8d9053f5051e5db518f541144268a@46.4.95.132:30303" under bootnodes param.
3. Add all the enodes mentioned in the bootnodes to static-nodes and trusted-nodes. 

After making the changes, please restart the node and wait for sometime for the node to catch. Make sure you are on latest bor version v1.4.1.
 
Thanks.

**Comment by yuanwj210** [comment]
> 你好，
> 
> 您能否按照下面提到的步骤操作？它会起作用。我尝试了同样的方法。
> 
> 1. 将 maxpeer 增加到 400。
> 2. 在bootnodes参数下添加“enode://429bb1c348c769218ecf2b400dc16b86045f3eec89780a8d8d73913f6c9dc184a8d3d3bfcb7197092065c2ebbad4fd177aa8d9053f5051e5db518f541144268a@46.4.95.132:30303”。
> 3. 将 bootnodes 中提到的所有 enodes 添加到 static-nodes 和 Trusted-nodes 中。
> 
> 进行更改后，请重新启动节点并等待一段时间以便节点捕获。确保您使用的是最新版 bor v1.4.1。
> 
> 像下面这样
> 
> **[p2p] maxpeers = 400 port = 30303 # maxpendpeers = 50 # bind = "0.0.0.0" # nodiscover = false # nat = "any" # netrestrict = "" # nodekey = "" # nodekeyhex = "" # txarrivalwait = "500ms" [p2p.discovery] # v4disc = true # v5disc = false bootnodes = ["enode://429bb1c348c769218ecf2b400dc16b86045f3eec89780a8d8d73913f6c9dc184a8d3d3bfcb7197092065c2ebbad4fd177aa8d9053f5051e5db518f541144268a@46.4.95.132:30303", “enode://b8f1cc9c5d4403703fbf377116469667d2b1823c0daf16b7250aa576bacf399e42c3930ccfcb02c5df6879565a2b8931335565f0e8d3f8e72385ecf4a4bf160a@3.36.224.80:30303”， “enode://8729e0c825f3d9cad382555f3e46dcff21af323e89025a0e6312df541f4a9e73abfa562d64906f5e59c51fe6f0501b3e61b07979606c56329c020ed739910759@54.194.245.5:30303”] #bootnodesv4 = [] #bootnodesv5 = [] 静态节点= ["enode://429bb1c348c769218ecf2b400dc16b86045f3eec89780a8d8d73913f6c9dc184a8d3d3bfcb7197092065c2ebbad4fd177aa8d9053f5051e5db518f541144268a@46.4.95.132:30303", “enode://b8f1cc9c5d4403703fbf377116469667d2b1823c0daf16b7250aa576bacf399e42c3930ccfcb02c5df6879565a2b8931335565f0e8d3f8e72385ecf4a4bf160a@3.36.224.80:30303”， “enode://8729e0c825f3d9cad382555f3e46dcff21af323e89025a0e6312df541f4a9e73abfa562d64906f5e59c51fe6f0501b3e61b07979606c56329c020ed739910759@54.194.245.5:30303”] 受信任节点 = ["enode://429bb1c348c769218ecf2b400dc16b86045f3eec89780a8d8d73913f6c9dc184a8d3d3bfcb7197092065c2ebbad4fd177aa8d9053f5051e5db518f541144268a@46.4.95.132:30303", “enode://b8f1cc9c5d4403703fbf377116469667d2b1823c0daf16b7250aa576bacf399e42c3930ccfcb02c5df6879565a2b8931335565f0e8d3f8e72385ecf4a4bf160a@3.36.224.80:30303”， "enode://8729e0c825f3d9cad382555f3e46dcff21af323e89025a0e6312df541f4a9e73abfa562d64906f5e59c51fe6f0501b3e61b07979606c56329c020ed739910759@54.194.245.5:30303"] # 使用 sentry 的推荐设置 <> 验证器架构 # dns = []**
> 
> 谢谢。

I do this and it's still stuck
INFO [09-24|09:30:14.589] Whitelisting milestone deferred          err="chain out of sync"

**Comment by xass1on** [comment]
> Hi,
> 
> Can you please follow the steps mentioned below. it will work. i tried the same way.
> 
>     1. Increase the maxpeer to 400.
> 
>     2. Add "enode://429bb1c348c769218ecf2b400dc16b86045f3eec89780a8d8d73913f6c9dc184a8d3d3bfcb7197092065c2ebbad4fd177aa8d9053f5051e5db518f541144268a@46.4.95.132:30303" under bootnodes param.
> 
>     3. Add all the enodes mentioned in the bootnodes to static-nodes and trusted-nodes.
> 
> 
> After making the changes, please restart the node and wait for sometime for the node to catch. Make sure you are on latest bor version v1.4.1.
> 
> like below
> 
> **[p2p] maxpeers = 400 port = 30303 # maxpendpeers = 50 # bind = "0.0.0.0" # nodiscover = false # nat = "any" # netrestrict = "" # nodekey = "" # nodekeyhex = "" # txarrivalwait = "500ms" [p2p.discovery] # v4disc = true # v5disc = false bootnodes = ["enode://429bb1c348c769218ecf2b400dc16b86045f3eec89780a8d8d73913f6c9dc184a8d3d3bfcb7197092065c2ebbad4fd177aa8d9053f5051e5db518f541144268a@46.4.95.132:30303", "enode://b8f1cc9c5d4403703fbf377116469667d2b1823c0daf16b7250aa576bacf399e42c3930ccfcb02c5df6879565a2b8931335565f0e8d3f8e72385ecf4a4bf160a@3.36.224.80:30303", "enode://8729e0c825f3d9cad382555f3e46dcff21af323e89025a0e6312df541f4a9e73abfa562d64906f5e59c51fe6f0501b3e61b07979606c56329c020ed739910759@54.194.245.5:30303"] # bootnodesv4 = [] # bootnodesv5 = [] static-nodes = ["enode://429bb1c348c769218ecf2b400dc16b86045f3eec89780a8d8d73913f6c9dc184a8d3d3bfcb7197092065c2ebbad4fd177aa8d9053f5051e5db518f541144268a@46.4.95.132:30303", "enode://b8f1cc9c5d4403703fbf377116469667d2b1823c0daf16b7250aa576bacf399e42c3930ccfcb02c5df6879565a2b8931335565f0e8d3f8e72385ecf4a4bf160a@3.36.224.80:30303", "enode://8729e0c825f3d9cad382555f3e46dcff21af323e89025a0e6312df541f4a9e73abfa562d64906f5e59c51fe6f0501b3e61b07979606c56329c020ed739910759@54.194.245.5:30303"] trusted-nodes = ["enode://429bb1c348c769218ecf2b400dc16b86045f3eec89780a8d8d73913f6c9dc184a8d3d3bfcb7197092065c2ebbad4fd177aa8d9053f5051e5db518f541144268a@46.4.95.132:30303", "enode://b8f1cc9c5d4403703fbf377116469667d2b1823c0daf16b7250aa576bacf399e42c3930ccfcb02c5df6879565a2b8931335565f0e8d3f8e72385ecf4a4bf160a@3.36.224.80:30303", "enode://8729e0c825f3d9cad382555f3e46dcff21af323e89025a0e6312df541f4a9e73abfa562d64906f5e59c51fe6f0501b3e61b07979606c56329c020ed739910759@54.194.245.5:30303"] # Recommended setting with sentry <> validator architecture # dns = []**
> 
> Thanks.

Hello, 

I was having exact same issues when trying to sync from snapshot. Thought there might be an issue with the snapshot, pruned all bor data. Delete bor. Reinstalled bor v1.4.1. Started syncing from the scratch. Nothing at all.

Cannot connect to a single peer. Getting following error 

`Sep 25 07:19:05 polygon-node bor[517422]: TRACE[09-25|07:19:05.911] Failed RLPx handshake                    addr=148.251.110.179:30313 conn=dyndial    err="read tcp 10.10.0.175:51994->148.251.110.179:30313: read: connection reset by peer"`

`eth.syncing
false
admin.peers
[]
eth.blockNumber
0`

**Comment by adamf-sendblocks** [comment]
> After one night, the block automatically caught up

@yuanwj210 please elaborate: do you mean that you had the same syncing issue as described, and that eventually it went away by itself?

**Comment by Brindrajsinh-Chauhan** [comment]
faces the same issue as well with Bor nodes on version v1.4.1. It seems to resolved after some time but keeps happening making the node go in and out of sync. Any fixes / cause of the issue yet?

**Comment by malingzhao** [comment]
did you resolve this err ?

**Comment by malingzhao** [comment]
WARN [09-26|11:05:48.086] Synchronisation failed, dropping peer    peer=511e8cca94a7938d97ca9da7a62269c923802c612cb49837525dae9300e31ab3 err="retrieved hash chain is invalid: invalid merkle root (remote: 517cd7ae0f87b99a42c188a25c6c6c0219d979e3ce9105acc375f5a7b5d51192 local: 45e8f67a9f86c5c9ff42a03c623e7dfec39ab904676be8603d88d5c7ab8cce2e) dberr: %!w(<nil>)"

**Comment by derostenlebt** [comment]
> faces the same issue as well with Bor nodes on version v1.4.1. It seems to resolved after some time but keeps happening making the node go in and out of sync. Any fixes / cause of the issue yet?

facing exactly the same issue.

**Comment by 0x1un** [comment]
> > faces the same issue as well with Bor nodes on version v1.4.1. It seems to resolved after some time but keeps happening making the node go in and out of sync. Any fixes / cause of the issue yet?
> 
> facing exactly the same issue.

+1

**Comment by maximdogonov** [comment]
the same issue

**Comment by ssandeep** [comment]
This seems to be because of the lack of peers. What is the peer count in the node?

For Mainnet, can you try using this config option to get connected to more peers?

```
[p2p]
    maxpeers = 200
    # Discovery settings for finding other nodes
    [p2p.discovery]
        dns = ["enrtree://AKUEZKN7PSKVNR65FZDHECMKOJQSGPARGTPPBI7WS2VUL4EGR6XPC@pos.polygon-peers.io"] 
```

**Comment by andreyvg** [comment]
Thank you @ssandeep.
This dns setting has solved my issue with peers. Before applying this I had about 1-8 peers.

**Comment by Creamers158** [comment]
Same here, tried above but seems not adding more peers.
After restart it will connect to other peers but not increasing.

When it stall the log says:

```
INFO [10-10|11:55:12.402] Imported new chain segment               number=62,864,405 hash=d58f11..1aa10c blocks=8  txs=608  mgas=109.164 elapsed=1.473s    mgasps=74.083  snapdiffs=7.46MiB triediffs=149.84MiB triedirty=32.23MiB
INFO [10-10|11:55:12.402] Commit Interrupt. Pre-committing the current block block=62,864,406
INFO [10-10|11:55:15.561] Whitelisting new milestone from heimdall block=62,864,377 hash=1ae761..62d10f
INFO [10-10|11:55:39.561] Whitelisting new milestone from heimdall block=62,864,390 hash=b43b6c..9b5537
INFO [10-10|11:56:15.560] Whitelisting milestone deferred          err="chain out of sync"
INFO [10-10|11:56:27.561] Whitelisting milestone deferred          err="chain out of sync"
```

**Comment by yuanwj210** [comment]
> This seems to be because of the lack of peers. What is the peer count in the node?
> 
> For Mainnet, can you try using this config option to get connected to more peers?
> 
> ```
> [p2p]
>     maxpeers = 200
>     # Discovery settings for finding other nodes
>     [p2p.discovery]
>         dns = ["enrtree://AKUEZKN7PSKVNR65FZDHECMKOJQSGPARGTPPBI7WS2VUL4EGR6XPC@pos.polygon-peers.io"] 
> ```

After adding DNS, I still can't keep up, and I get stuck every time I keep up
Whitelisting checkpoint deferred err="chain out of sync"

**Comment by pratikspatil024** [comment]
@yuanwj210 - did you restart your node after updating the config file?
Also how many peers your node is connected with?

**Comment by yuanwj210** [comment]
> @yuanwj210 - did you restart your node after updating the config file? Also how many peers your node is connected with?

After each reboot, it catches up with the latest block and stops moving, and again,Here is my configuration as follows
```
[p2p.discovery]
        # v5disc = false
bootnodes = ["enode://b8f1cc9c5d4403703fbf377116469667d2b1823c0daf16b7250aa576bacf399e42c3930ccfcb02c5df6879565a2b8931335565f0e8d3f8e72385ecf4a4bf160a@3.36.224.80:30303", "enode://8729e0c825f3d9cad382555f3e46dcff21af323e89025a0e6312df541f4a9e73abfa562d64906f5e59c51fe6f0501b3e61b07979606c56329c020ed739910759@54.194.245.5:30303","enode://429bb1c348c769218ecf2b400dc16b86045f3eec89780a8d8d73913f6c9dc184a8d3d3bfcb7197092065c2ebbad4fd177aa8d9053f5051e5db518f541144268a@46.4.95.132:30303"]

static-nodes = ["enode://429bb1c348c769218ecf2b400dc16b86045f3eec89780a8d8d73913f6c9dc184a8d3d3bfcb7197092065c2ebbad4fd177aa8d9053f5051e5db518f541144268a@46.4.95.132:30303", "enode://b8f1cc9c5d4403703fbf377116469667d2b1823c0daf16b7250aa576bacf399e42c3930ccfcb02c5df6879565a2b8931335565f0e8d3f8e72385ecf4a4bf160a@3.36.224.80:30303", "enode://8729e0c825f3d9cad382555f3e46dcff21af323e89025a0e6312df541f4a9e73abfa562d64906f5e59c51fe6f0501b3e61b07979606c56329c020ed739910759@54.194.245.5:30303"]

trusted-nodes = ["enode://429bb1c348c769218ecf2b400dc16b86045f3eec89780a8d8d73913f6c9dc184a8d3d3bfcb7197092065c2ebbad4fd177aa8d9053f5051e5db518f541144268a@46.4.95.132:30303", "enode://b8f1cc9c5d4403703fbf377116469667d2b1823c0daf16b7250aa576bacf399e42c3930ccfcb02c5df6879565a2b8931335565f0e8d3f8e72385ecf4a4bf160a@3.36.224.80:30303", "enode://8729e0c825f3d9cad382555f3e46dcff21af323e89025a0e6312df541f4a9e73abfa562d64906f5e59c51fe6f0501b3e61b07979606c56329c020ed739910759@54.194.245.5:30303"]

dns = ["enrtree://AKUEZKN7PSKVNR65FZDHECMKOJQSGPARGTPPBI7WS2VUL4EGR6XPC@pos.polygon-peers.io"]```

How do I check how many peers are connected?

**Comment by Raneet10** [comment]
Hey @yuanwj210 you can find out the number of peers using `admin.peers.length` in the bor ipc. Also please try upgrading your node to the new release.

**Comment by yuanwj210** [comment]
> Hey @yuanwj210 you can find out the number of peers using `admin.peers.length` in the bor ipc. Also please try upgrading your node to the new release.

It has been resolved with an updated version

**Comment by xass1on** [comment]
> > Hey @yuanwj210 you can find out the number of peers using `admin.peers.length` in the bor ipc. Also please try upgrading your node to the new release.
> 
> It has been resolved with an updated version

What version did you update to?

**Comment by xass1on** [comment]
@pratikspatil024 
Updated to v1.5.2 and it is syncing at the moment.
