### ISSUE TITLE
Block-stm implementation

### ISSUE THREAD

**Issue by xuyi33333** [maticnetwork/bor#1337]
Hello, I noticed that the verification phase of block-stm is supposed to be multi-threaded. However, after looking at the code, it seems that the verification phase of block-stm has not yet implemented multi-threaded validation.

**Comment by xuyi33333** [comment]
I’m still following this issue.

**Comment by cffls** [comment]
Yes, the verification is performed in sequence. We haven't parallelize the verification because it only takes a very small amount of time compared to execution.

**Comment by Raneet10** [comment]
Hey @xuyi33333 closing this issue for now; feel free to reopen in case if you have any more queries. Thanks!
