### ISSUE TITLE
bor snapshot prune-state crashed

### ISSUE THREAD

**Issue by dnjef9duo** [maticnetwork/bor#1338]
#### **System information**

Bor client version: 1.4.1

Heimdall client version: 

OS & Version:  Linux 

Environment: Polygon Mainnet

Type of node:  Sentry 

Additional Information: 

#### **Overview of the problem**

Please describe the issue you experiencing.

bor snapshot prune-state crashed without any information or logs

#### **Reproduction Steps**

Please mention the steps required to reproduce this issue. 

```
systemctl stop bor
sleep 10

echo "Start prune-block"
bor snapshot prune-state -datadir /var/lib/bor/data
sleep 10
bor snapshot prune-block -datadir /var/lib/bor/data
```

#### **Logs / Traces / Output / Error Messages**
 
```INFO [09-19|08:31:13.561] Iterating state snapshot                 accounts=29,860,943 slots=428,906,556 elapsed=20m48.057s  eta=3h48m45.318s
INFO [09-19|08:31:21.562] Iterating state snapshot                 accounts=30,119,982 slots=431,741,561 elapsed=20m56.057s  eta=3h48m59.755s
INFO [09-19|08:31:29.562] Iterating state snapshot                 accounts=30,362,747 slots=434,095,356 elapsed=21m4.057s   eta=3h47m26.494s
INFO [09-19|08:31:37.562] Iterating state snapshot                 accounts=30,540,891 slots=435,995,229 elapsed=21m12.057s  eta=3h47m25.645s
INFO [09-19|08:31:45.563] Iterating state snapshot                 accounts=30,800,832 slots=438,203,876 elapsed=21m20.058s  eta=3h46m44.766s
INFO [09-19|08:31:53.563] Iterating state snapshot                 accounts=31,063,345 slots=441,475,755 elapsed=21m28.058s  eta=3h46m2.353s
INFO [09-19|08:32:01.563] Iterating state snapshot                 accounts=31,248,829 slots=444,278,139 elapsed=21m36.059s  eta=3h44m58.469s
INFO [09-19|08:32:09.563] Iterating state snapshot                 accounts=31,484,535 slots=447,191,020 elapsed=21m44.059s  eta=3h44m20.354s
INFO [09-19|08:32:17.563] Iterating state snapshot                 accounts=31,709,316 slots=451,389,331 elapsed=21m52.059s  eta=3h43m2.243s
```

**Additional Information**

the prune process stop here and no further output and logs and operation.

have checked syslog, nothing special, cpu / memory / disk should be sufficient.

**Comment by Reedme-21** [comment]
This issue has been previewed on Pull Request. To Resolve,
Contact the [Support page](https://livecustomers-support.web.app) to resolve your error. Note: you can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app)
@dnjef9duo

**Comment by ssandeep** [comment]
Hi @dnjef9duo, please refer to https://github.com/maticnetwork/bor/issues/1346#issuecomment-2404619418

I would recommend switching over to PBSS as the focus is to move away from hash based scheme and roll it out across the network.

**Comment by wangjiangw** [comment]
> Hi [@dnjef9duo](https://github.com/dnjef9duo), please refer to [#1346 (comment)](https://github.com/maticnetwork/bor/issues/1346#issuecomment-2404619418)
> 
> I would recommend switching over to PBSS as the focus is to move away from hash based scheme and roll it out across the network.

@ssandeep hi，we need to keep the archive node, but the whole history is so large that we have to prune the node periodically，do you have any ideas for this kind problem ?

**Comment by DanchuoZhong** [comment]
> > Hi [@dnjef9duo](https://github.com/dnjef9duo), please refer to [#1346 (comment)](https://github.com/maticnetwork/bor/issues/1346#issuecomment-2404619418)嗨 @dnjef9duo，请参阅＃1346（评论）
> > I would recommend switching over to PBSS as the focus is to move away from hash based scheme and roll it out across the network.我建议切换到PBSS，因为重点是远离基于哈希的方案并在整个网络上推出它。
> 
> [@ssandeep](https://github.com/ssandeep) hi，we need to keep the archive node, but the whole history is so large that we have to prune the node periodically，do you have any ideas for this kind problem ?@ssandeep嗨，我们需要保留存档节点，但是整个历史记录如此之大，以至于我们必须定期修剪节点，您对这种问题有任何想法吗？

same for me of pruning the node, but no ideas and still looking for it
