### ISSUE TITLE
bor's main network synchronization slow

### ISSUE THREAD

**Issue by noonyait** [maticnetwork/bor#1353]
Why is the synchronization of the BOR mainnet so slow? I tried adding the following DNS, and while the number of peers increased, the speed didn't improve.

"enrtree://AKUEZKN7PSKVNR65FZDHECMKOJQSGPARGTPPBI7WS2VUL4EGR6XPC@pos.polygon-peers.io"

bor version
Version: 1.4.1
GitCommit: 0b28bb5e2fde74a0bdaad83bdcca7822e1b1b715
[bor.log.gz](https://github.com/user-attachments/files/17348646/bor.log.gz)

**Comment by yuanwj210** [comment]
After adding DNS, I still can't keep up, and I get stuck every time I keep up
Whitelisting checkpoint deferred         err="chain out of sync"

**Comment by Raneet10** [comment]
Hey @noonyait @yuanwj210 it'd be great if you can share some logs so we can look into this further and also your p2p configs might help. Thanks!

**Comment by CanutoIX** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by yuanwj210** [comment]
> Hey @noonyait @yuanwj210 it'd be great if you can share some logs so we can look into this further and also your p2p configs might help. Thanks!

It has been resolved with an updated version

**Comment by marcello33** [comment]
Can we close this @noonyait ? Thank you

**Comment by manav2401** [comment]
Seems resolved, closing this for now. Feel free to reopen if required. Thanks!
