### ISSUE TITLE
decentralized sequencers 

### ISSUE THREAD

**Issue by spinGreekGod** [maticnetwork/bor#1358]
# Rationale

The motivation behind the feature and why should this feature exist?
make the network completely decentralize
What are the use-cases?
decentralization of the layer 1 

# Implementation
Use IPFS and a DHT for storing ledger and decentralizing a sequencer 
Do you have ideas regarding the implementation of this feature? (Mention reference links if any)
i thought of it when i realized sequencers were centralized 
Any alternative solutions or features you've considered?
nope
Are you willing to implement this feature?
I need help

**Comment by pratikspatil024** [comment]
Hi @spinGreekGod - this is a very good feature to have, and the team is considering to have decentralised sequencers. But it is still in very early phase.
We were thinking of utilising the consensus layer of Polygon PoS chain (that is the [heimdall](https://github.com/maticnetwork/heimdall) chain) for this.

Let us know what are your thoughts. Thank you.

**Comment by spinGreekGod** [comment]
This sounds good I’m just contributing my ideas since I hold eth

**Comment by Raneet10** [comment]
Hey @spinGreekGod thanks for raising this! Closing this for now and you'll hear more from us when we plan on implementing this. Thanks!
