### ISSUE TITLE
RPC method eth_getLogs crashed: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Dragon-six** [maticnetwork/bor#137]
my problem is RPC method eth_getLogs crashed: runtime error: invalid memory address or nil pointer dereference:

goroutine 840 [running]:
github.com/ethereum/go-ethereum/rpc.(*callback).call.func1(0xc00023d293, 0xb, 0xc00a5bfd50)
	github.com/ethereum/go-ethereum/rpc/service.go:200 +0xba
panic(0x1214ca0, 0x1ebb540)
	runtime/panic.go:969 +0x175
github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).GetLogs(0xc0014faae0, 0x15e1920, 0xc0015e6380, 0x0, 0xc0038092e0, 0xc003809300, 0xc00a85a0a0, 0x1, 0x1, 0xc0005eb4a0, ...)
	github.com/ethereum/go-ethereum/eth/filters/api.go:344 +0x50
reflect.Value.call(0xc00048d900, 0xc000489aa8, 0x13, 0x13a1ced, 0x4, 0xc00018c5a0, 0x3, 0x3, 0xc00018c5d0, 0xc003809060, ...)
	reflect/value.go:475 +0x8c7
reflect.Value.Call(0xc00048d900, 0xc000489aa8, 0x13, 0xc00018c5a0, 0x3, 0x3, 0x16, 0x0, 0x0)
	reflect/value.go:336 +0xb9
github.com/ethereum/go-ethereum/rpc.(*callback).call(0xc001edb4a0, 0x15e1920, 0xc0015e6380, 0xc00023d293, 0xb, 0xc003809060, 0x1, 0x1, 0x0, 0x0, ...)
	github.com/ethereum/go-ethereum/rpc/service.go:206 +0x2c5
github.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0xc0015be990, 0x15e1920, 0xc0015e6380, 0xc0033aa000, 0xc001edb4a0, 0xc003809060, 0x1, 0x1, 0x1)
	github.com/ethereum/go-ethereum/rpc/handler.go:389 +0x8a
github.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0xc0015be990, 0xc0005eb440, 0xc0033aa000, 0xc001568ec0)
	github.com/ethereum/go-ethereum/rpc/handler.go:337 +0x294
github.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0xc0015be990, 0xc0005eb440, 0xc0033aa000, 0x15ccb01)
	github.com/ethereum/go-ethereum/rpc/handler.go:298 +0x1be
github.com/ethereum/go-ethereum/rpc.(*handler).handleMsg.func1(0xc0005eb440)
	github.com/ethereum/go-ethereum/rpc/handler.go:139 +0x46
github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1(0xc0015be990, 0xc0038084e0)
	github.com/ethereum/go-ethereum/rpc/handler.go:226 +0xd2
created by github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc
	github.com/ethereum/go-ethereum/rpc/handler.go:222 +0x66
 
WARN [06-03|21:51:55.899] Served eth_getLogs                       conn=192.168.1.17:61357 reqid=4366892086736830 t="891.712µs" err="method handler crashed"

**Comment by Uttam-Singhh** [comment]
@gao-zilong Are you still facing this issue?

**Comment by aman-rac** [comment]
@Uttam-Singhh , I am facing this issue after updating to  v0.2.14, I'm using the docker image.

**Comment by bailantaotao** [comment]
@Uttam-Singhh hi, I am facing this issue after updating to v0.2.14, I'm using the docker image.

```


Feb 28, 2022 @ 06:56:58.177 | - |  
-- | -- | --

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/rpc/handler.go:222 +0x92

  | Feb 28, 2022 @ 06:56:58.177 | - | created by github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/rpc/handler.go:226 +0xc5

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1()

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/rpc/handler.go:139 +0x35

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/rpc.(*handler).handleMsg.func1(0xc1e24e0420)

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/rpc/handler.go:298 +0xd1

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0xc02d0a0900, 0xc062a57000, 0xc137a2d180)

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/rpc/handler.go:337 +0x239

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0xc02d0a0900, 0xc1e24e0420, 0xc137a2d180)

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/rpc/handler.go:389 +0x45

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0xc063b5f1d0, {0x17881b8, 0xc1317b5f40}, 0xc137a2d180, 0x6, {0xc13894f350, 0x5e9e5d3085f5, 0xc07f1e4e8839828f})

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/rpc/service.go:206 +0x3f0

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/rpc.(*callback).call(0xc00fab8540, {0x17881b8, 0xc1317b5f40}, {0xc14f0f0390, 0x16}, {0xc13894f350, 0x1, 0x4dfd97})

  | Feb 28, 2022 @ 06:56:58.177 | - | reflect/value.go:339 +0xc5

  | Feb 28, 2022 @ 06:56:58.177 | - | reflect.Value.Call({0xc008eaf500, 0xc008eb7610, 0x57b7c8}, {0xc0a8c0e2d0, 0x3, 0x3})

  | Feb 28, 2022 @ 06:56:58.177 | - | reflect/value.go:556 +0x845

  | Feb 28, 2022 @ 06:56:58.177 | - | reflect.Value.call({0xc008eaf500, 0xc008eb7610, 0x7f4541e3b108}, {0x14db71f, 0x4}, {0xc0a8c0e2d0, 0x3, 0xc05dce88c0})

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/eth/api.go:638 +0x54f

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/eth.(*PrivateDebugAPI).GetBlockReceipts(0xc005426408, {0x17881b8, 0xc1317b5f40}, {0xba, 0xf3, 0x73, 0x2c, 0x99, 0x21, 0x39, ...})

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/internal/ethapi/api.go:1742 +0xe7

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/internal/ethapi.ToTransactionReceipt({0x17881b8, 0xc1317b5f40}, {0x17c1240, 0xc01773b4a0}, 0x0, 0xc067e0dc00, {0xba, 0xf3, 0x73, 0x2c, ...}, ...)

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/core/types/transaction_signing.go:132 +0x4e

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/core/types.Sender({0x178f198, 0xc0ef11f6e0}, 0x0)

  | Feb 28, 2022 @ 06:56:58.177 | - | runtime/panic.go:1038 +0x215

  | Feb 28, 2022 @ 06:56:58.177 | - | panic({0x1315ec0, 0x209d080})

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/rpc/service.go:200 +0x89

  | Feb 28, 2022 @ 06:56:58.177 | - | github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()

  | Feb 28, 2022 @ 06:56:58.177 | - | goroutine 181446380 [running]:



```

**Comment by 0xKrishna** [comment]
https://github.com/maticnetwork/bor/issues/321#issuecomment-1039942046
