### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by vipwzw** [maticnetwork/bor#138]
gopkg.in/olebedev/go-duktape.v3
# gopkg.in/olebedev/go-duktape.v3
../gop/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200619000410-60c24ae608a6/dbgsockettransport.go:14:16: undefined: Context
../gop/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200619000410-60c24ae608a6/dbgsockettransport.go:16:15: undefined: DebugRequestFunc
../gop/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200619000410-60c24ae608a6/dbgsockettransport.go:17:15: undefined: DebugDetachedFunc
../gop/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200619000410-60c24ae608a6/dbgsockettransport.go:31:30: undefined: Context
../gop/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200619000410-60c24ae608a6/dbgsockettransport.go:33:14: undefined: DebugRequestFunc
../gop/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200619000410-60c24ae608a6/dbgsockettransport.go:34:15: undefined: DebugDetachedFunc
../gop/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200619000410-60c24ae608a6/timers.go:11:10: undefined: Context
../gop/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200619000410-60c24ae608a6/timers.go:30:10: undefined: Context
../gop/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200619000410-60c24ae608a6/timers.go:37:20: undefined: Context
../gop/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200619000410-60c24ae608a6/timers.go:63:22: undefined: Context
../gop/pkg/mod/gopkg.in/olebedev/go-duktape.v3@v3.0.0-20200619000410-60c24ae608a6/timers.go:63:22: too many errors

root@ecs-fbcd:~/bor# go version
go version go1.16.4 linux/amd64

root@ecs-fbcd:~/bor# uname -a
Linux ecs-fbcd 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vipwzw** [comment]
root@ecs-fbcd:~/bor# git status
HEAD detached at v0.2.6
nothing to commit, working tree clean

**Comment by vipwzw** [comment]
v0.2.5 build is ok
github.com/ethereum/go-ethereum/internal/jsre
github.com/ethereum/go-ethereum/internal/jsre/deps
github.com/ethereum/go-ethereum/internal/web3ext
github.com/ethereum/go-ethereum/console
golang.org/x/crypto/ed25519
github.com/jedisct1/go-minisign
github.com/shirou/gopsutil/mem
github.com/ethereum/go-ethereum/eth/tracers
github.com/ethereum/go-ethereum/cmd/utils
github.com/ethereum/go-ethereum/cmd/geth
mkdir -p /root/gop/bin/
cp ./build/bin/geth ./build/bin/bor
cp ./build/bin/* /root/gop/bin/

**Comment by laurelgithub** [comment]
Which node node you use, the two official addresses in my bor configuration file are invalid
