### ISSUE TITLE
Package: EnvironmentFile in bor.service points to wrong path

### ISSUE THREAD

**Issue by kvdv80** [maticnetwork/bor#14]
In the current package : _matic-bor_1.0.0_amd64.deb_ the bor.service points to the wrong path for the EnvironmentFile. it points to _/home/ubuntu/metadata_ 

The service will fail to start with the error
_Error: bor.service: Failed to load environment files: No such file or directory_

I changed the path to /etc/bor/metadata to fix the problem.

**Comment by imewish** [comment]
@kvdv80 This issue has been resolved. Please download the latest bor installer and replace the existing installation. You can uninstall Bor using `sudo dpkg -r matic-bor`.
