### ISSUE TITLE
Archival mode is not working

### ISSUE THREAD

**Issue by nuliknol** [maticnetwork/bor#140]
Problem: The 'archive' mode is reported as enabled, but the datadir is of the same size as of a Full node and 'missing trie node' error is shown on accessing balances of first blocks.

#### System information

Geth version: 

Bor
```
Version: 1.10.1-stable
Architecture: amd64
Go Version: go1.16.4
Operating System: linux
GOPATH=
GOROOT=/usr/local/go
```

OS & Version: Ubuntu 20

Command executed:

`./bor --datadir /home/matic/mumbai-chain --gcmode archive --port 33001 --bootnodes enode://320553cda00dfc003f499a3ce9598029f364fbb3ed1222fdc20a94d97dcc4d8ba0cd0bfa996579dcc6d17a534741fb0a5da303a90579431259150de66b597251@54.147.31.250:30303 --networkid 80001 --bor.heimdall http://127.0.0.1:1317 --http --http.addr XX.XX.XX.XX --http.port 38546 --http.vhosts * --http.corsdomain * --http.api eth,net,web3,txpool,bor`

#### Expected behaviour
No error when getting balance of an account using past blocks.

#### Actual behaviour
Seeing this error:
```
Error: missing trie node ffcb834d62706995e9e7bf10cc9a9e42a82fea998d59b3a5cfad8975dbfe3f87 (path )
	at web3.js:6347:37(47)
	at web3.js:5081:62(37)
	at <eval>:1:15(5)

```
Test example:

`INFO [06-16|02:46:53.053] Enabling recording of key preimages since archive mode is used `

```
> eth.getBalance('0x1b2E85De21C7CF4bD1787c6Ac4bd505e83b62Ba5',0)
0
> eth.getBalance('0x1b2E85De21C7CF4bD1787c6Ac4bd505e83b62Ba5',1)
0
> eth.getBalance('0x1b2E85De21C7CF4bD1787c6Ac4bd505e83b62Ba5',2)
0
> eth.getBalance('0x1b2E85De21C7CF4bD1787c6Ac4bd505e83b62Ba5',3)
0
> eth.getBalance('0x1b2E85De21C7CF4bD1787c6Ac4bd505e83b62Ba5',4)
0
> eth.getBalance('0x1b2E85De21C7CF4bD1787c6Ac4bd505e83b62Ba5',5)
0
> eth.getBalance('0x1b2E85De21C7CF4bD1787c6Ac4bd505e83b62Ba5',10)
0
> eth.getBalance('0x1b2E85De21C7CF4bD1787c6Ac4bd505e83b62Ba5',100)
Error: missing trie node ffcb834d62706995e9e7bf10cc9a9e42a82fea998d59b3a5cfad8975dbfe3f87 (path )
	at web3.js:6347:37(47)
	at web3.js:5081:62(37)
	at <eval>:1:15(5)

> eth.syncing
{
  currentBlock: 346688,
  highestBlock: 15156663,
  knownStates: 874894,
  pulledStates: 841883,
  startingBlock: 0
}
> 
```

With archival node, there should be never errors of type "missing trie node"

**Comment by ssandeep** [comment]
As you have reported, your node is not completely synced yet. Can you try after it syncs completely?

**Comment by d10r** [comment]
still the same after synced:
```
> eth.syncing
false
> eth.blockNumber
23067892
> eth.getBalance('0x1b2E85De21C7CF4bD1787c6Ac4bd505e83b62Ba5',100)
Error: missing trie node 01b797385461764bd56336dd5e810f3d57529d47bcbf3260c7d9c770bf6c5af4 (path )
        at web3.js:6357:37(47)
        at send (web3.js:5091:62(35))
        at <eval>:1:15(5)
```
