### ISSUE TITLE
Why transactions are never executed in next block ?

### ISSUE THREAD

**Issue by CryptoVader** [maticnetwork/bor#141]
Hello,

I did experimentations running my bor node and I found out that when I send a transaction, it is never included in the next block, but always in the block after. (Even when I send the transaction immediately once I get a "newblock" callback.)

Any reason for that ? Is there a way to make my dapp more responsive ?

**Comment by red-0ne** [comment]
We are experiencing the same issue. I would love to understand why it's happening. Sometimes it's stuck for many blocks before being included. Even if we fire it right after a block n is detected (we pay a good amount of gas and listen to new blocks using websocket) it never lends on block n+1 (n+2) at best.

**Comment by yoongyy** [comment]
I am facing the same issue too, sometime the TX totally not found after I sent it to my node. I guess this is because the nature of ETH (which similar to Polygon now), many of the transactions are stuck there and re-arrange by the validators.

**Comment by bifot** [comment]
have a similar issue when analysing pending transactions, using Tokyo region on AWS (two machines in same subnet) and have a big latency (vs. blocknative for example)

**Comment by algotradingstrategies** [comment]
Hi, was this resolved/explained? What is the reason transactions are never excecuted in the next block (n+2 at best, often also only n+3) and/or how can one tweak one's bor node ?

**Comment by soloblack** [comment]
anyone solved this?
