### ISSUE TITLE
inconsistent value returned by eth_blockNumber

### ISSUE THREAD

**Issue by drortirosh** [maticnetwork/bor#142]
#### System information

`bor/v1.10.3-stable-d33ce83c/linux-amd64/go1.15.5`

#### Expected behaviour

block number shiould be monotonically increasing
that is, repeated calls should either return the same value, or higher value (by 1)

#### Actual behaviour
MOST of the time, we get the expected behaviour.
SOME times, we get smaller values (-1, -3) and sometimes its over 8000 blocks INTO THE PAST

#### Steps to reproduce the behaviour

The script below is expected to return mostly "0" (same block number as last iteration) or "1" (new block number is 1 above last)

But occasionally it returns huge NEGATIVE number (e.g. -10506) - which means there is probably one node which is stuck few hours behind all others.

```
const Web3=require('web3')

async function run() {
  web3 = new Web3('rpc-mainnet.maticvigil.com')

  counter=0;
  let last;
  while (true) {
    counter++;
    n = await web3.eth.getBlockNumber()
    console.log(counter, n-last)
    last=n
  }
}

run()
```

**Comment by shahafn** [comment]
Is there any update to this issue?

**Comment by temaniarpit27** [comment]
This depends upon RPC to RPC and this can vary if the RPC provider's node is not consistent/synced with the latest chain.
Closing this for now
Reopen if required
