### ISSUE TITLE
Fix documentation typo

### ISSUE THREAD

**Issue by raulillo82** [maticnetwork/bor#15]
Step 9 seems to be wrong:

$ sudo vi  /etc/bor/metadata

// eg: add the address in following format "VALIDATOR_ADDRESS=0xasdasklhemwlmasdsad3ewwew" 

The quotation marks should be after the equal sign. It didn't work for me till I wrote it like this (service wouldn't start in the next step):
VALIDATOR_ADDRESS="0xasdasklhemwlmasdsad3ewwew"

**Comment by imewish** [comment]
@raulillo82 Thanks for pointing out the issue. you don't need to add any quotation marks with the text. it should be just `VALIDATOR_ADDRESS=0xasdasklhemwlmasdsad3ewwew` is fine. Will update this in the doc. 

Thanks you.
