### ISSUE TITLE
ICON <> Polygon BTP Interoperability: Implementation on the contract level or the client level?

### ISSUE THREAD

**Issue by shikamarumind** [maticnetwork/bor#151]
As a requirement of implementation for ICON's interoperability technology BTP, integrated chains need to add pre-compilation functions for sha3 and erecover.

Om Parikh mentioned that it would be great if the integration is done at the contract level instead of the client level. Pre-compiles would likely be cheaper, but if this is cheap enough to execute at the contract level the ICON team is fine with it. It has been added as a precompile to Substrate SDK Frontier pallet and is in PR on BSC waiting for their next hard fork.

As long as the solution is feasible from a cost perspective, the ICON team is open to either option.

BTP Documentation: https://drive.google.com/file/d/1SP5i6zE9SrVufRh_PnBrM5TyCPZjoShm/view?usp=sharing

**Comment by temaniarpit27** [comment]
Closing this as no updates on this
