### ISSUE TITLE
Docker build returns with error "Operation not permitted"

### ISSUE THREAD

**Issue by seranidy01** [maticnetwork/bor#152]
#### System information

Geth version: 1.10.3
OS & Version: Linux - Ubuntu 

#### Expected behaviour
Docker finishes building bor with no errors

#### Actual behaviour
Docker starts building and ends up erorring with "operation not permitted"

#### Steps to reproduce the behaviour
Create a new directory called bor
clone the git for bor
docker build --tag bor:latest .

**Comment by noah40povis** [comment]
try running `docker build -t dockerfile --target builder .` This will build the dockerfile in the directory.

**Comment by Khurana-Tarun** [comment]
Is there any update on this issue? 
I tried it also `docker build -t dockerfile --target builder .`

Still not working @noah40povis

**Comment by Uttam-Singhh** [comment]
@Khurana-Tarun Can you please provide some screenshots of the error?

**Comment by Khurana-Tarun** [comment]
@Uttam-Singhh 

I followed the below steps: (I tried with different versions as well)

```
git clone https://github.com/maticnetwork/bor.git
cd bor
git checkout v0.2.8
docker build --tag bor:latest .
```

**Error in Docker build command** 
```
Sending build context to Docker daemon  181.1MB
Step 1/11 : FROM golang:1.17-alpine as builder
 ---> da4596da1948
Step 2/11 : RUN apk add --no-cache make gcc musl-dev linux-headers git bash
 ---> Using cache
 ---> 45a1ca6f7b5f
Step 3/11 : ADD . /bor
 ---> 77fee8da39d2
Step 4/11 : CMD ["echo $GOPATH"]
 ---> Running in c071fb26908c
Removing intermediate container c071fb26908c
 ---> 7f3ab6a84711
Step 5/11 : RUN cd /bor && make bor-all
 ---> Running in 45d15ad651f3
make: go: Operation not permitted
make: go: Operation not permitted
make: go: Operation not permitted
make: echo: Operation not permitted
make: *** [Makefile:23: bor-all] Error 127
The command '/bin/sh -c cd /bor && make bor-all' returned a non-zero code: 2
```

![image](https://user-images.githubusercontent.com/17018485/133969057-587659e9-ccf6-43f9-a6e2-bbbd561a3208.png)

**Comment by Khurana-Tarun** [comment]
Steps I followed:
```
git clone https://github.com/maticnetwork/bor.git
cd  bor
git checkout v0.2.8
docker build --tag bor:latest .
```


Error on building docker image:

![image](https://user-images.githubusercontent.com/17018485/133970121-101df296-f918-43b6-9633-42ee1ce57f07.png)

**Comment by Khurana-Tarun** [comment]
@Uttam-Singhh @seranidy01  I fixed this issue by updating docker client.
`sudo apt-get upgrade docker-ce`

**Comment by temaniarpit27** [comment]
Closing this as no updates on this
