### ISSUE TITLE
It's a bug ?   

### ISSUE THREAD

**Issue by climb-yang** [maticnetwork/bor#155]
https://github.com/maticnetwork/bor/blob/436ed45548f5c7eda3e6c8a6719f1b420cdf075e/consensus/bor/bor.go#L1252

why?  
if err != nil  {
    state.Finalise(true)
}

**Comment by nuliknol** [comment]
what happens in the EVM stays in the EVM. Would it be erroneous or not

**Comment by jdkanani** [comment]
Works as intended.
