### ISSUE TITLE
Bor transactions are intermittently not returned

### ISSUE THREAD

**Issue by azf20** [maticnetwork/bor#156]
#### Expected behaviour
While running [graph-node](https://github.com/graphprotocol/graph-node) to index contracts on Polygon, we call `getBlockByHash` to fetch all transactions for a given block, so that transaction information is available while processing a given event.

#### Actual behaviour
Our Polygon RPC providers intermittently do not return one of the transactions, which breaks subgraph indexing for events contained within those transactions, as they expect to find a transaction for all the triggers identified in a block. The missing transactions are always transactions from 0x0000000000000000000000000000000000000000 to 0x0000000000000000000000000000000000000000 ([example](https://polygonscan.com/tx/0x4641fb604c8b6b9d515f57f364e8039fb600ed0471a7dcb7f16f2bd1314501f1))

#### Steps to reproduce the behaviour
We have seen this behaviour intermittently while indexing multiple subgraphs, reported by users of the hosted service here: https://github.com/graphprotocol/graph-node/issues/2552. We have not been able to isolate a consistent test case. If we clear our block cache (so that we call `getBlockByHash` again), the second attempt is successful and indexing can continue.

**Comment by azf20** [comment]
We are still seeing this issue from our Polygon node provider https://github.com/graphprotocol/graph-node/issues/2552#issuecomment-883861985

**Comment by reddyismav** [comment]
Hey! Yep! 

So, does it make sense to compare the transactions array from getBlockByHash and then comparing it with eth_transactions count before caching them in the Database ?

**Comment by azf20** [comment]
Sure we could potentially do that, but it would be a Polygon-specific hack in our general EVM codebase which isn't preferred - ideally we rely on the client to respond deterministically, so depends a bit on the timeframe for a fix, if that makes sense?

**Comment by reddyismav** [comment]
Yep! We havent zeroed in on the problem yet!! Will keep you updated.

**Comment by nuliknol** [comment]
@azf20 
> Our Polygon RPC providers intermittently do not return one of the transactions, 

I just filled this issue few hours ago about missing transactions, might be related: https://github.com/maticnetwork/bor/issues/158

**Comment by ssandeep** [comment]
@azf20 @nuliknol please reopen if you are still observing this issue.

**Comment by azf20** [comment]
We are still seeing this issue on the Hosted Service

**Comment by ssandeep** [comment]
Hey @azf20 , can you confirm if you are seeing this for new blocks (post September 1st)?

**Comment by azf20** [comment]
Hey @ssandeep we have not observed any since then, thanks!

**Comment by c2h5oh** [comment]
@ssandeep we've just encountered the same bug for txn `0xf763de447766d00f5c53f4dffec0562cda4c89319221ae51a1a28c0ac75d6772`:

We run 2 sets of heimdall + bor on separate VMs for internal use - both heimdall and bor unmodified and built from source on each of VMs.

For both nodes 
```
curl -X 'POST' -d '{"jsonrpc":"2.0","id":1,"method":"eth_getTransactionByHash","params":["0xf763de447766d00f5c53f4dffec0562cda4c89319221ae51a1a28c0ac75d6772"]}' -H 'Content-Type: application/json' -H 'User-Agent: Go-http-client/1.1' http://our.node.address/

{"jsonrpc":"2.0","id":1,"result":null}
```

but

curl -X 'POST' -d '{"jsonrpc":"2.0","id":1,"method":"eth_getBlockByHash","params":["0x93af4d75a1739a085ed0f2ee3b602e1a8e83e9aa9b55dd964e214306a12def4e", false]}' http://our.node.address/ | json_pp | grep 0xf763de447766d00f5c53f4dffec0562cda4c89319221ae51a1a28c0ac75d6772

         "0xf763de447766d00f5c53f4dffec0562cda4c89319221ae51a1a28c0ac75d6772",
