### ISSUE TITLE
invalid merkle root

### ISSUE THREAD

**Issue by nuliknol** [maticnetwork/bor#157]
I am getting "invalid merkle root" error periodically on Matic Production chain (chain id 137) . It syncs, then it gets this error after a few minutes. I have downloaded Bor from master repository today to ensure I am using updated code but the error doesn't go away despite using latest sources:

Bor
Version: 1.10.3-stable
Architecture: amd64
Go Version: go1.16.4
Operating System: linux
GOPATH=
GOROOT=/usr/local/go

Error: invalid merkle root (remote: 0b947bfaaed605cad3027c331ad662eabf8a3e5cb1b705815f9ecf6fd26847c3 local: 9ed0666e5d127f14503b8c9c1bce224d0d16a9c4ff76edb6db41f5d12a4b6401)
##############################
 
INFO [07-16|16:44:02.480] Skip duplicated bad block                number=16,929,536 hash=62ef13..5b1675
ERROR[07-16|16:44:02.484] 
########## BAD BLOCK #########
Chain config: {ChainID: 137 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, YOLO v3: <nil>, Engine: bor}
.................
Number: 16929536
Hash: 0x62ef135cea59b06d585d1a4dd1dbc71f9ea159b7943cb056f8640b20985b1675

WARN [07-16|16:42:14.083] Synchronisation failed, dropping peer    peer=8588fa01ebc737bc9803f849027cba642ce031cd09276d117c8c5858bb510343 err="retrieved hash chain is invalid: invalid merkle root (remote: 0b947bfaaed605cad3027c331ad662eabf8a3e5cb1b705815f9ecf6fd26847c3 local: 9ed0666e5d127f14503b8c9c1bce224d0d16a9c4ff76edb6db41f5d12a4b6401)"
ERROR[07-16|16:42:14.083] Ethereum peer removal failed             peer=8588fa01 err="peer not registered"

**Comment by ssandeep** [comment]
Hi @nuliknol ,

You will have to rewind your chain to a few blocks behind `16929536` and sync. To do this,
```
$ bor attach ~/.bor/data/bor.ipc`
> debug.setHead("0x10250E8")
```

This will rewind your blockchain to block no `16929000` or a little behind.

Also, can you use the latest version available here: https://github.com/maticnetwork/bor/releases/tag/v0.2.6 since master might have a few breaking changes while we are still working on them.

**Comment by Scumwong** [comment]
> Hi @nuliknol ,
> 
> You will have to rewind your chain to a few blocks behind `16929536` and sync. To do this,
> 
> ```
> $ bor attach ~/.bor/data/bor.ipc`
> > debug.setHead("0x10250E8")
> ```
> 
> This will rewind your blockchain to block no `16929000` or a little behind.
> 
> Also, can you use the latest version available here: https://github.com/maticnetwork/bor/releases/tag/v0.2.6 since master might have a few breaking changes while we are still working on them.

hi i met the same problem and i want to konw how do you get "0x10250E8",mine is stucked at 18,450,368 ,how can i rewind my blockchain? thank you

**Comment by Scumwong** [comment]
> Hi @nuliknol ,
> 
> You will have to rewind your chain to a few blocks behind `16929536` and sync. To do this,
> 
> ```
> $ bor attach ~/.bor/data/bor.ipc`
> > debug.setHead("0x10250E8")
> ```
> 
> This will rewind your blockchain to block no `16929000` or a little behind.
> 
> Also, can you use the latest version available here: https://github.com/maticnetwork/bor/releases/tag/v0.2.6 since master might have a few breaking changes while we are still working on them.

i get the same problem and i tried this way ,but it did not help,still stucked at the same block...

**Comment by ssandeep** [comment]
@Scumwong , can you paste the logs here?

**Comment by devops-kine** [comment]
haha ,i have resloved that problem with rewinding blockchain.But before i rewind blockchain i reduced version to 1.10.3 and when bad block synced i updated version to 1.10.8.. the node is synced normal now .thank you anyway

**Comment by Scumwong** [comment]
> @Scumwong , can you paste the logs here?
haha ,i have sloved that problem with rewinding blockchain.But before i rewind blockchain i reduced version to 1.10.3 and when bad block synced i updated version to 1.10.8.. the node is synced normal now .thank you anyway

**Comment by Scumwong** [comment]
> @Scumwong , can you paste the logs here?

I got another problem，my full node Data takes up too much disk，how can i compress the date ?

**Comment by ssandeep** [comment]
You can follow this https://forum.matic.network/t/bor-offline-pruning/1830

**Comment by Scumwong** [comment]
> You can follow this https://forum.matic.network/t/bor-offline-pruning/1830

ok ,thanks very much!!!
