### ISSUE TITLE
Impossible reorg

### ISSUE THREAD

**Issue by zscole** [maticnetwork/bor#162]
#### System information

Geth Version: `1.10.3-stable`
Git Commit: `d33ce83cba5e1a1078e339882c048b9a8b210c69`
Architecture: `amd64`
Go Version: `go1.16.5`

#### Expected behaviour
Possible reorg

#### Actual behaviour
Impossible reorg

#### Steps to reproduce the behaviour
Running a node for a prolonged period of time.

#### Backtrace

````
Aug 04 18:32:56 delta bash\[2753609\]: ERROR\[08-04|18:32:56.507\] Impossible reorg, please file an issue oldnum=17,607,939 oldhash=bd9f1b..ff12b1 newnum=17,607,939 newhash=bd9f1b..ff12b1
````

**Comment by ssandeep** [comment]
Can you try rewinding the chain to say block no 17,600,000 and let it sync?
You can do it by attaching bor.ipc and using `debug.setHead(<block_num_in_hex>)`
