### ISSUE TITLE
Very high memory usage and OOM kill

### ISSUE THREAD

**Issue by yorickdowne** [maticnetwork/bor#179]
#### System information

Bor version: `1.10.8-stable-045e5c2c`
OS & Version: Linux

#### Behaviour

Bor uses a quickly increasing amount of memory, like upstream Geth but worse, and gets OOM killed in about 3 days on a 32 GiB machine. This is with default `--cache`.

That this grows faster than upstream Geth suggests that the issue might be with blocks, since they are faster on Bor.

This issue has been encountered upstream since (at least) 1.10.4 and Geth devs have not found a root cause.

**Comment by mrf000** [comment]
I am experiencing the same. Same bor version on linux as OP and default --cache on a full node. 

Bor is currently using 32 GiB of RAM out of 64 GiB total. My uptime is also roughly 3 days.

**Comment by ssandeep** [comment]
We are investigating the root cause of the memory leaks and will get back soon with our findings. For now, we have seen that this is happening in the p2p and only a few nodes in the entire network are encountering memory bloats.

**Comment by hdiass** [comment]
I had 3 nodes running and all of them had same issue. 
![image](https://user-images.githubusercontent.com/29974003/131893619-c79320df-b1d8-4116-ad21-eb7ee16d726a.png)

**Comment by ferranbt** [comment]
Can you send the logs from the Bor node?

**Comment by yorickdowne** [comment]
Yes can. Note Geth team says they didn't see a smoking gun in pprof. Maybe with Bor it'll be more visible.

**Comment by yorickdowne** [comment]
The dot png has blocks instead of text, attaching dot txt. The main thing I am noticing is that bor uses 24.5 ish GiB, `polygon-main_bor_1         1186.82%   24.46GiB / 31.14GiB` , but accounts for only 12 - 13 GiB in the mem.txt. So it's using memory somewhere that's not shown by pprof.

[Bor-logs-mem.gz](https://github.com/maticnetwork/bor/files/7203730/Bor-logs-mem.gz)
[mem.txt](https://github.com/maticnetwork/bor/files/7203732/mem.txt)
![mem](https://user-images.githubusercontent.com/71337066/134186543-2ad56159-2878-4bf5-8797-1663b0fca881.png)

**Comment by yorickdowne** [comment]
Testing https://github.com/maticnetwork/bor/tree/feature-hot-fix-memory now with a source build docker image.

**Comment by ferranbt** [comment]
I am not sure if the hotfix will solve this issue, at least from the logs you do not seem to have the same problem. Is there any reason why the memory map does not show the names? 

Could you try this script https://gist.github.com/ferranbt/e58c3f5032941a4b3550ff009afdb859
Lets see if there is any difference.

**Comment by yorickdowne** [comment]
I may not have run this long enough, I am currently restarting Bor daily. I've disabled that restart and will let it run for a bit. I have one instance on the current released version and one instance on the hotfix. I'll see how they do in another 24 hours.

**Comment by ferranbt** [comment]
If the issue is the one we are addressing in the hot fix, the instance should restart really fast. Lets see if we are lucky.

**Comment by hdiass** [comment]
24 days since this issue was created, and the problem is getting bigger and bigger. We are securing billions of dollars in this network, can we please get some final solution for this ? I seek for stability

**Comment by yorickdowne** [comment]
Bear with me @ferranbt , my automated OS patching regime restarted the servers and we're back to 11 hours in. I'll monitor over the next 2-3 days again and update this issue.

**Comment by ferranbt** [comment]
No problem, take your time please. Memory issues with complex software like this are really hard to debug so I appreciate your effort filling this issue and sharing with us the data.

**Comment by yorickdowne** [comment]
I'm running one node on 0.2.8 and two on the just-released memory hotfix. The 0.2.8 has 150 max peers and the memory hotfix 200. Will continue to observe - no conclusive results so far.

**Comment by ferranbt** [comment]
Can you share the trace output with this script? [https://gist.github.com/ferranbt/e58c3f5032941a4b3550ff009afdb859
](https://gist.github.com/ferranbt/e58c3f5032941a4b3550ff009afdb859
)Make sure that you have pprof enabled and you trace bor and not heimdall.

**Comment by ferranbt** [comment]
Hi! Could you try #201. It fixes this issue in our infra.
