### ISSUE TITLE
Incorrect block hash

### ISSUE THREAD

**Issue by nnqq** [maticnetwork/bor#183]
#### System information

Geth version: `v1.10.8`
OS & Version: OSX 11.5.2

#### Expected behaviour

https://mumbai.polygonscan.com/block/18373929
Correct block `18373929` hash as in polygonscan: `0x6a2564f4116b0e62c2bdbd38a8188b8d350a28b8025217376d79affc7dc23134`

#### Actual behaviour

Unknown block `18373929` hash from go-ethereum: `0x5ac6f7535b90af3b401d72a1e2962eba92243576c39f483c59fa921c94726518`

#### Steps to reproduce the behaviour

1. Clone https://github.com/nnqq/matic-bug
2. Run `go run main.go`
3. See stdout:
```
block number        : 18373929
expected block hash : 0x6a2564f4116b0e62c2bdbd38a8188b8d350a28b8025217376d79affc7dc23134
actual block hash   : 0x5ac6f7535b90af3b401d72a1e2962eba92243576c39f483c59fa921c94726518
```

**Comment by ssandeep** [comment]
Thanks for reporting this, it is most likely related to an issue in geth v1.10.8 for which a hotfix was provided later. We have asked chainstacklabs team to upgrade to the latest bor that contains the fix.

**Comment by nnqq** [comment]
@ssandeep Thank you, it resolves after node upgrading
