### ISSUE TITLE
memory leak 

### ISSUE THREAD

**Issue by EchoLavender** [maticnetwork/bor#188]
#### System information

Geth version: `geth version`
OS & Version: 

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

Commit hash : 

```
Version: 1.10.8-stable
Git Commit: 045e5c2c4c373c4fd565afea6ea65812566a6542
Architecture: amd64
Go Version: go1.15.5
Operating System: linux
GOPATH=/root/go
GOROOT=/root/.go
```

#### Expected behaviour

It can execute stably for a long time 

#### Actual behaviour

memory leak

#### Steps to reproduce the behaviour

no reprodut.

more than once, there are four or five times, only through reboot to solve

#### Backtrace
![2021-09-08 13 29 33](https://user-images.githubusercontent.com/22935085/132451917-4563d7b3-6372-4fcb-855d-9c9e8433bd4b.jpg)
````
[backtrace]

VPS configure 
vcpu: 10 core
memory: 60G
disk: 1.4TB SSD

````

When submitting logs: please submit them as text and not screenshots.

**Comment by ssandeep** [comment]
Can you upgrade to https://github.com/maticnetwork/bor/releases/tag/v0.2.8 and reduce maxpeers to 25 and observe the memory usage for a day?

**Comment by EchoLavender** [comment]
> Can you upgrade to https://github.com/maticnetwork/bor/releases/tag/v0.2.8 and reduce maxpeers to 25 and observe the memory usage for a day?

will have an impact on the current Sentry node synchronization as this is in a production environment ?

**Comment by ssandeep** [comment]
No, this version is tested and there will be no impact.

**Comment by n0ndual** [comment]
I have seen the same memory leak problem, geth version is also the same. I will try to upgrade and test.

**Comment by PanJ** [comment]
I have upgraded to `v0.2.8` and still experiencing the issue.

![image](https://user-images.githubusercontent.com/1797879/133955192-c852d8ea-0712-4191-b58e-c974612c6e1f.png)


```
Bor
Version: 1.10.9-unstable
Git Commit: 0a9bd7befd47f78f6ddd9104c5508ecdda726452
Architecture: amd64
Go Version: go1.15.5
Operating System: linux
```

**Comment by ferranbt** [comment]
Could you send the logs from the Bor node?

**Comment by PanJ** [comment]
@ferranbt My node just died from out of memory. I'll wait for the memory usage to build up and send you the pprof image.

**Comment by ferranbt** [comment]
Thank you! Please send me the result of the command and if it does not work or the png does not show any text you can try this script https://gist.github.com/ferranbt/e58c3f5032941a4b3550ff009afdb859
Also, It would be nice if you can send us the logs.

**Comment by PanJ** [comment]
@ferranbt  Here is the image

![image](https://user-images.githubusercontent.com/1797879/134453162-d6903cc4-84a4-4d16-9909-f5d248205103.png)
![image](https://user-images.githubusercontent.com/1797879/134454692-72a167b1-1b1a-4d0a-8ab7-9d204e3fd9ae.png)

All the other files can be found here https://github.com/PanJ/bor-debug-files

**Comment by ferranbt** [comment]
Thank you for the info. We have identified a similar problem in some of our machines as well. This problem is a bit tricky to debug but we are trying to find a solution.

**Comment by hdiass** [comment]
This is so bad that we are securing billions of dollars on this network, and this problem has been arising for more than 2 weeks and no solution whatsoever.

**Comment by PanJ** [comment]
I've reached over 80% memory utilization and have captured the pprof and logs (updated in the repo above)

![mem](https://user-images.githubusercontent.com/1797879/134769997-a22669c7-6740-4fe3-b305-28f7d2f592de.png)

**Comment by EchoLavender** [comment]
I recently heard from `sunil` that a branch was committed to fix it, but it hasn't been officially merged yet, any help needed? 
- https://github.com/maticnetwork/bor/tree/feature-hot-fix-memory

**Comment by ferranbt** [comment]
A new release with that hot fix is planned, it fixes a special case were the node would crash due to OOM shortly (less than 1min) after start. The problem described here is not that one as far as I can tell.
