### ISSUE TITLE
removed events hinting at chain reorgs

### ISSUE THREAD

**Issue by d10r** [maticnetwork/bor#189]
During the debugging of a background service I noticed that Polygon RPCs quite frequently remove log events after reporting them.  
Observable both with Alchemy and Quicknode RPC.  
According to https://geth.ethereum.org/docs/rpc/pubsub#logs this happens on chain re-orgs.

Since Polygon is (afaik) using Tendermint consensus, I expected it to have instant finality. Is that an incorrect understanding or is something in the implementation buggy, leading to not-yet-final blocks being treated as final too early?

**Comment by ssandeep** [comment]
Bor is based on geth and heimdall is based on cosmos (that uses tendermint consensus). So no, there is no instant finality in bor. For more info, please refer https://docs.matic.network/docs/home/architecture/matic-architecture/
