### ISSUE TITLE
Bor cannot connect to any node

### ISSUE THREAD

**Issue by fwhappy** [maticnetwork/bor#190]
#### System information

Geth version: `geth version`

```
Bor
Version: 1.10.8-stable
Architecture: amd64
Go Version: go1.15.5
Operating System: linux
GOPATH=/home/ubuntu/go
GOROOT=/home/ubuntu/.go
```

OS & Version: Windows/Linux/OSX

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```

The heimdalld status

```
"sync_info": {
      "latest_block_hash": "92C1A0DFC76BB2F1E2ABBE26C5B3648FFA8EB867BB51FEC66DC0110FD567DF9A",
      "latest_app_hash": "8F331CCFCB97B242490D11A51C4D924607B8F0353B8DA1989216B8986679B0C7",
      "latest_block_height": "6474331",
      "latest_block_time": "2021-09-15T01:11:40.100370879Z",
      "catching_up": false
    },

```

**After the heimdalld sync is complete, the Bor sync is started, but it cannot connect to any Bor node**

logs:
```
Sep 15 01:10:29 matic-node-us2.techxmind.com bash[610248]: INFO [09-15|01:10:29.974] Looking for peers                        peercount=0 tried=189 static=66
Sep 15 01:10:35 matic-node-us2.techxmind.com bash[610248]: ERROR[09-15|01:10:35.439] Snapshot extension registration failed   peer=c2340321 err="peer connected on snap without compatible eth support"
Sep 15 01:10:40 matic-node-us2.techxmind.com bash[610248]: INFO [09-15|01:10:40.297] Looking for peers                        peercount=0 tried=170 static=66
Sep 15 01:10:50 matic-node-us2.techxmind.com bash[610248]: INFO [09-15|01:10:50.320] Looking for peers                        peercount=0 tried=85  static=66
Sep 15 01:10:53 matic-node-us2.techxmind.com bash[610248]: ERROR[09-15|01:10:53.344] Snapshot extension registration failed   peer=78e19f52 err="peer connected on snap without compatible eth support"
Sep 15 01:11:00 matic-node-us2.techxmind.com bash[610248]: INFO [09-15|01:11:00.622] Looking for peers                        peercount=0 tried=83  static=66
Sep 15 01:11:03 matic-node-us2.techxmind.com bash[610248]: INFO [09-15|01:11:03.577] deleteAllExpiredTxs                      total=0   expried=0 deleted=0
Sep 15 01:11:21 matic-node-us2.techxmind.com bash[610248]: INFO [09-15|01:11:21.596] Looking for peers                        peercount=0 tried=33  static=66
Sep 15 01:11:21 matic-node-us2.techxmind.com bash[610248]: ERROR[09-15|01:11:21.598] Snapshot extension registration failed   peer=c2340321 err="peer connected on snap without compatible eth support"
Sep 15 01:11:32 matic-node-us2.techxmind.com bash[610248]: INFO [09-15|01:11:32.986] Looking for peers                        peercount=0 tried=195 static=66
```

**Comment by ssandeep** [comment]
Have you configured the bootnodes? Please post the contents of your `start.sh` file here.

**Comment by fwhappy** [comment]
@ssandeep 

cat ~/node/bor/start.sh

#!/usr/bin/env sh

set -x #echo on

BOR_DIR=${BOR_DIR:-~/.bor}
DATA_DIR=$BOR_DIR/data

/home/ubuntu/go/bin/bor --datadir $DATA_DIR \
  --port 30303 \
  --http --http.addr '0.0.0.0' \
  --http.vhosts '*' \
  --http.corsdomain '*' \
  --http.port 8845 \
  --ipcpath $DATA_DIR/bor.ipc \
  --http.api 'eth,net,rpc,web3,txpool,personal,debug,bor' \
  --syncmode 'fast' \
  --networkid '137' \
  --miner.gaslimit '20000000' \
  --miner.gastarget '20000000' \
  --txpool.nolocals \
  --txpool.accountslots 16 \
  --txpool.globalslots 131072 \
  --txpool.accountqueue 64 \
  --txpool.globalqueue 131072 \
  --txpool.lifetime '1h30m0s' \
  --maxpeers 200 \
  --metrics \
  --pprof --pprof.port 7071 --pprof.addr '0.0.0.0' \
  --ws --ws.port 8846 --ws.addr 0.0.0.0 --ws.origins '*' \
  --bootnodes "enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303"

**Comment by ssandeep** [comment]
I think the config is not being read properly as you are missing `\` at the end of each line in the bor invocation command (while passing the params).

**Comment by fwhappy** [comment]
The \ missed is the display error.
The real config file is:

![image](https://user-images.githubusercontent.com/8510606/133428956-f1aeb67f-797b-4088-915f-71cf59f05f2f.png)

**Comment by fwhappy** [comment]
@ssandeep 

Do you have any other suggestions?

**Comment by ssandeep** [comment]
I don't see any problems in the `start.sh`. Can you try with `--syncmode snap`?

**Comment by fwhappy** [comment]
> I don't see any problems in the `start.sh`. Can you try with `--syncmode 'snap'`?

Let me try, Thank you very much!

**Comment by fwhappy** [comment]
@ssandeep 
After I change the syncmode to snap, I am always 100 blocks behind in sync, is there any solution?

```
> eth.syncing
{
  currentBlock: 19196107,
  highestBlock: 19196190,
  knownStates: 422537029,
  pulledStates: 422537029,
  startingBlock: 19192942
}
```

**Comment by ssandeep** [comment]
Can you now change it to `--syncmode 'full'` and restart?

**Comment by fwhappy** [comment]
@ssandeep 

No, Bor will automatically switch to fast mode

`Sep 17 08:42:56 ip-10-0-3-140 bash[1954377]: WARN [09-17|08:42:56.415] Switch sync mode from full sync to fast sync`

**Comment by ssandeep** [comment]
That's strange, not sure if a node has to be started with `full` sync mode right from the beginning for it to stay in full sync mode.

**Comment by mirkojvc** [comment]
Hey guys any luck with this? I've been struggling for a couple of days, to get my bor to connect to pairs...
<img width="792" alt="Screenshot 2021-10-03 at 11 42 38" src="https://user-images.githubusercontent.com/18366380/135748218-bffaef72-17ef-4ebe-9b05-e3845eb3c2a7.png">
I've tried "snap" and "full" nothing works.
All I get in my logs is:
`INFO [10-03|11:42:44.790] Looking for peers                        peercount=0 tried=72  static=0
INFO [10-03|11:42:56.719] Looking for peers                        peercount=0 tried=50  static=0
ERROR[10-03|11:43:04.942] Snapshot extension registration failed   peer=2c657826 err="peer connected on snap without compatible eth support"
INFO [10-03|11:43:06.758] Looking for peers                        peercount=0 tried=83  static=0
INFO [10-03|11:43:16.877] Looking for peers                        peercount=1 tried=145 static=0
INFO [10-03|11:43:26.911] Looking for peers                        peercount=0 tried=28  static=0
ERROR[10-03|11:43:27.154] Snapshot extension registration failed   peer=925ab3ac err="peer connected on snap without compatible eth support"
ERROR[10-03|11:43:34.351] Snapshot extension registration failed   peer=a4da81c9 err="peer connected on snap without compatible eth support"
ERROR[10-03|11:43:34.508] Snapshot extension registration failed   peer=a6c868a1 err="peer connected on snap without compatible eth support"
INFO [10-03|11:43:36.941] Looking for peers                        peercount=0 tried=143 static=0
`

**Comment by unek** [comment]
also no luck syncing, either looking for peers continuously or 
```Error: invalid merkle root (remote: 31b14671fb6d1e4402147f75b215747e2f0b375d0d3fd6371b4d7cf342232b3f local: 95cb3b2e57e0f2b2ba4b1a564fc3d65e1e12fa842d3be4df463d57b623c8a710)```

**Comment by osizadmin** [comment]
No peer sync with the server end. Kindly check and advise us. We have lot of token to integrate to our exchange.

**Comment by unek** [comment]
I've managed to run bor after fully syncing heimdall, and running bor with the `--bor-mainnet` toggle (which seems to be required after 0.2.9 update but not documented outside the changelog?)

**Comment by ssandeep** [comment]
@osizadmin @mirkojvc , yes you can try using `--bor-mainnet` instead of passing all the flags.
Also, @unek , the `--bor-mainnet` toggle can be used but it's not **required** to be used.

**Comment by osizadmin** [comment]
Yes we are using --bor-mainnet. Sometimes peercount showing 0 and also it take more storage size.
When you will release the light peer or pruning method package.

**Comment by osizadmin** [comment]
We have started the --bor-mainnet before 2 days still we got this 
> eth.syncing;
{
  currentBlock: 15345075,
  highestBlock: 21475038,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 15344675

Is it any way to increase the block count and sync. could you share the static peer details here.

**Comment by unek** [comment]
@osizadmin is your heimdall fully synced?

**Comment by osizadmin** [comment]
@unek We using --bor-mainnet

**Comment by osizadmin** [comment]
Is there any update for my issue @ssandeep

**Comment by kevinengel** [comment]
What's your enode set to? There should be a log entry like this:

`Nov 24 12:57:47 ns1000647 bash[99268]: INFO [11-24|12:57:47.682] Started P2P networking                   self=enode://ba5479889ede2930564a4c7597c6892965f7f00830abe5f66f805c23f73441e94a18542553b7af3c10027a9223bfb69c652c18cbba944a1541f6d7c7c71625b8@127.0.0.1:30303`

I had the same problem as you, but noticed that my enode here was being set to localhost.

No idea why it didn't get properly resolved to my external ip, but you can force this by adding flag `--nat="extip:<your IP address>"`

**Comment by PeaStew** [comment]
@ssandeep is there any update here? I started 6 RPC nodes with identical setups, same hardware, same everything, one node got in sync with snap sync, the other 5 all have the same problem as described above by others. This needs to be sorted out quickly, you cannot ignore such an issue for 5 months!

**Comment by 0xgobinath** [comment]
@PeaStew since @fwhappy has reported the initial issue, I like to start checking with them first and then will come to yours next. Or you both have the same issue/same node?
This is not an issue with bor overall; could be something specific with your node configuration.

**Comment by PeaStew** [comment]
> @PeaStew since @fwhappy has reported the initial issue, I like to start checking with them first and then will come to yours next. Or you both have the same issue/same node? This is not an issue with bor overall; could be something specific with your node configuration.

It's not the same node, but it is the exact same issue that plagues many nodes, just check all the reports of RPC issues on twitter with RPC, the vast majority are caused by this issue. People keep adding nodes and not being able to sync. You may not think this is 'an overall bor issue' but I think you are wrong.

**Comment by PeaStew** [comment]
> @PeaStew since @fwhappy has reported the initial issue, I like to start checking with them first and then will come to yours next. Or you both have the same issue/same node? This is not an issue with bor overall; could be something specific with your node configuration.

If you are concerned about people's settings, then perhaps check your own settings in your docs because I am using the exact same settings as described there, and the nodes will not sync. As I said previously, I started 6 nodes syncing, all with the same settings, and hardware, only 1/6 managed to get to sync and stay there. You have an issue with your network/software and you are not addressing it.

**Comment by 0xKrishna** [comment]
> 

You said here that you are using `snap` sync, AFAIK this is not recommended by us in any of our docs, So please don't claim that you are using the same settings described there.

**Comment by 0xKrishna** [comment]
> > @PeaStew since @fwhappy has reported the initial issue, I like to start checking with them first and then will come to yours next. Or you both have the same issue/same node? This is not an issue with bor overall; could be something specific with your node configuration.
> 
> If you are concerned about people's settings, then perhaps check your own settings in your docs because I am using the exact same settings as described there, and the nodes will not sync. As I said previously, I started 6 nodes syncing, all with the same settings, and hardware, only 1/6 managed to get to sync and stay there. You have an issue with your network/software and you are not addressing it.

We have 500+ nodes running overall including devs and testing network and all of them are able to use the same software, So I don't think we have anything to fix/address here in general.

**Comment by 0xKrishna** [comment]
Also this is the explanation to your situation
https://github.com/ethereum/go-ethereum/issues/15001#issuecomment-370732526
So please use only `full` mode.

**Comment by PeaStew** [comment]
Snap or full it makes no difference

**Comment by 0xKrishna** [comment]
> Snap or full it makes no difference

Please clean and restart your nodes with `full` only, Don't switch b/w `snap` and `full`.
`snap` is still not optimized for bor network as there is way more than data compared to `geth`.

**Comment by PeaStew** [comment]
Have done this multiple times

**Comment by koraykoska** [comment]
Any updates? This seems to happen to any new node without an address list. I think this is a real issue.

**Comment by Comolli** [comment]
same one

**Comment by temaniarpit27** [comment]
Please join the discord server: https://discord.gg/epsBG3Yf and post your queries in #full-node channel and our team will help you resolve the issue.

**Comment by PeaStew** [comment]
Typical behaviour, not closed with a fix

**Comment by blissend** [comment]
@ssandeep @temaniarpit27 The problem is that nobody can see what the fix is when you resolve on discord. This promotes repeated requests. I can't even join that link above since invite is invalid or expired.

**Comment by rebelArtists** [comment]
in my experience, this can be resolved by adding additional bootnodes in ~/node/bor/start.sh

..or by manually adding peers via the console, as shown here for mainnet:

```
# cursor to datadir where bor.ipc exists, launch bor console
bor attach bor.ipc

# add additional mainnet peers to assist with syncing
admin.addPeer("enode://c5cccebb5e02a7ab51eb5404285e39122c14cb2e85b618ca571156ef854f019e53805d6eb7ce8b3f82857464af24ddc8fa0507ec6dcc9c5a0f0ae5a24ef83ff5@18.167.91.48:37452")
admin.addPeer("enode://ca654f68b00c5f0c52c15cd0c8460be7f9912fed0d4b6e4de7a95aad290cd9a28c3acc2b9a1ce68c4552598310169aab7ee9340b6453d62964842847a8bbdfe6@142.132.208.76:42158")
admin.addPeer("enode://395064bcc952e62f3fe4721484889bcfe3fd0802a94463d3e6c038c0711630961168768aa05a42ca7f85b9f7c2eaa298f53c23624b605a407536d3f31bd894c3@145.239.87.224:33296")
admin.addPeer("enode://4bb08b5e83b807a8bf54f034fb0a57d0fbfe04e619799b3400f2bde20d8dd51d7e6197c1cd02f841aefa87e4e707a528c0f16710a525675db24f1b6413965681@142.132.136.130:30303")
admin.addPeer("enode://90d822abc806a21e08c31053b35b048a11df592bde114d30248cd83ab507bde2c3e12679960352008b8d62fa4d5ed84e81b8c930b1dcb1119ed732d5fba55fc5@3.81.163.171:59218")
admin.addPeer("enode://650484102cd9c5a9cb1089229447a445aa4a5f8e5bdc4f895544f687c31d8af9d9ca224c86f7b2b270a90d9d9d688996c0c955e0214b57dd1143f881dec96deb@144.126.151.197:6050")
admin.addPeer("enode://33c4ce4c88bb0f3984405c5786242d44bc84e3115d90ac9259a9098da08ccb70342fbbea72d715eba2f7940457f6f4af38e4b54ed9196609779bb45bc1c711a1@3.21.244.208:30303")
admin.addPeer("enode://2ba49053fb5c799d7d24c82170a4f3bf0b8967b75453458e9f395185c8e57e174179fee9fda7746451e87c29df8c44d6baed8461511e193c0ba54c01f058db78@3.231.45.212:45082")
admin.addPeer("enode://0241ecc8152c8c4e565e6d1b62f11e8e26825a33eb01ede0b60baf31a6623c3de1be6ec9b167c393324067ff556dbb5e2bcb506263fcbf336659700fb1bc3c3a@139.99.68.228:30303")
admin.addPeer("enode://beb29d6a97582de07559ec8361e544352e7f4efcb7b27cb8a7b69ecdee142f79296bae155304aea0cd283bd0c2ff7eef13365de3bb1e27ffdd242fdcb7f61ca3@45.77.206.242:54980")
admin.addPeer("enode://0add335d37cca0c3c5aaa5b76481f368324f9a84ef879e48319ad2dc19cd6b0282a46e0e19e60ecc29b82b6325a81b34ae924fe2b7e526429a795d48e9ac85e2@114.32.12.70:30303")
admin.addPeer("enode://cacde49ff714769fd376e0ef329459052fca283d6d2e9728bbfc59758a8e44c74a45c4d5a618beca7749a21c3f189e8ea8c05d99910c7cd3f37049444607b110@15.164.14.127:50550")
admin.addPeer("enode://d1964a514c3f5dfa17c23e408a69e8ea907c80dff1f8f3492e37ce23987792034e47b4d0d99e5a1c86e5b6cf15e0b6c2baaa5df80ca1b162c4cb90e972be8506@92.119.129.86:6050")
admin.addPeer("enode://5d19d61fa7cdd4cad7feba2c27bdf05407189d7dfc0fa7d70a8ea76e6594d0fa92adebde2496b08ba53c26ef0e5018777a9dd019eb52a79b4e3faaf8da5958ed@18.179.23.25:30303")
admin.addPeer("enode://831f1aa4b0089d5bd65fa4b150fbe0f28a6347c0953d0d7e0f6853bd2b1ebeb0608ed10c0d6545283c119e12c3b5d22d9a759433a9c616d93f524913fc27f960@130.61.224.242:36810")
admin.addPeer("enode://38d771261d3fc5b07b9fecc002e15407438ab8eee85d0e69227a5d8b1c529a267c17b9102bf931dc6306cd540c749201e0441ac6c8388a440e2b5378328e9e97@18.222.63.45:39050")
admin.addPeer("enode://de1a6ecec7495617007501e645f5a22efd84eaa15a04402e15b56de273035dc65bf61372f55cf01015e6d2d4d2a7f3706f59b3222099f79fffeb4000d592c06c@154.53.63.145:34708")
admin.addPeer("enode://576e5fc381826a7ab43af2fe096257c5d2761fc94b0efe76c13602d702aa9f8918b855f8ac81a5486a78795f6faabb161fbbe1140284d5ac03112f62cf3b669f@54.36.163.147:59064")
admin.addPeer("enode://597ab43633b3a84cabd93b898122e02b1e880bde17b511e42ffe4a70902c2a34a2075762f8ee03055192f214a1c6c91eab56c4a05d9f92722010d34c6ec318b1@3.219.14.119:30303")
admin.addPeer("enode://a4c8bb65b3ae7b29c1341787b476f3d58a0115ac370ebacb4a513c2c8646c758c29857fcae33aa9361b17c6d22e6d5a9b14ef90201f104f4efd828b4fa3f78be@172.96.15.76:48040")
admin.addPeer("enode://30db67fe9cf6a7f94f762d80b209e24cdf0bb6f7138cc0d6c716b222f2c558eb138627ab578b4ea194cbd8f220b7c3b48b6d71d767af20f243ab9736172b990d@13.214.86.135:36257")
admin.addPeer("enode://00b81daf3ead285e4382df55907dff4442254c3ee7f826b8a96aabbe208a8bafe43b93bcc091fbde3892ead558f70ff914bc3d8211d68ab5ef11f9aad73ebf2b@173.244.194.21:60740")
admin.addPeer("enode://5530d0b18fad7190c4c7d134d264df46f189bdbc0a4aaca16a7e2271938ffcc1be8c57216db5cd7a2f1c84d7b734b42f7f226f35918c539cdca3e7ae25d530d4@18.142.33.213:35020")
admin.addPeer("enode://5581591e582d03e16e89e5d9a8752eb503f651d78eadb241e3cc1c15badcc6d89c0371709c5ac7f6811ebb3507b66e637aacadcdb57c6aa6fc8887a06fd52353@130.61.85.57:30303")
admin.addPeer("enode://d046d8a3fd6de6d6ed9367604d5e34c550e5f4c904011273c3ea5589ad29a1783ebcfa926ba248037a19c9f4e82b6bc4a3b53c9f51d1b0ec9fa324ba9a4e8c5d@144.76.80.34:41340")
admin.addPeer("enode://cb6d9a7359d2d349316434752f14c2cdb051a8252f1a278d14011f664c80a5916af898f9a1beced1a0598005b493acd716c1b9fe7fc39f49d39c0b494d4b5985@50.16.21.213:51016")
admin.addPeer("enode://1e9b7eae482174d0f2f37a1604793a971d073e4285876dc9735dc3b1fe16078a09706dc994c94bced239d82697bc2f57d759c0e1076007fd0e47868e45bd8413@185.252.232.133:41048")
admin.addPeer("enode://86e6cae3c4155ac83c2c14d69537c5bd959166990f24126836c1e0f1d6a6051390acd35db9ca2de8c8379cbb809c7c9d869724f459a075d827a1006072a8e76b@144.76.81.149:30303")
admin.addPeer("enode://d318cbdbf129a51e8a4672fb9abe4146b6e050b8586dfac5d0abf91d162fe4443ebee15029582b181948cd7a3da3fc3fb80eaebf68a5e2a9061bb21fe6730b96@3.85.62.172:44392")
admin.addPeer("enode://9b1796b750eff8f40ba4d4571113e96fd7103294d4673eedd4c1550e074cfcaf45d62022da5e8df68f48b4abddd22c168640f0ca46d75bda48ce5043a88f0eca@54.66.251.127:49754")
admin.addPeer("enode://803e62e8cd9eac0ea4c14ea2eb8df09ee7afd8d80613616329a9be0c7b192b756f21938e80f48231efe0a17d5e34539e863d183a6287f8da506162b41e0eb7ec@150.136.250.212:58072")
admin.addPeer("enode://10a47ea6a78717947743fb52fb7649c16f142b7e08069528639c65aac0630dcfedfc3f1c69cc1971ac8b670c9c35f1a9a3baa13b502a1d82f22ca91b1522a54e@157.90.134.197:48872")
admin.addPeer("enode://cb6d0d01883b31e7814e56dc18176e88e51c06f16d6f57a65761cbdde12c4b937da490d1c724fcad62ea7f5aabf4140fe41a306baa7db122c402426238e4541a@51.77.215.43:47882")
admin.addPeer("enode://be865fc36521e14d1d29bbbe8cb273196dbd460bb5409896dc38a8630ff3e4dd905704df937a144ed2389fed49ce5aeaafafb999a98500f5a0bb7db67b816346@142.132.207.114:30303")
admin.addPeer("enode://be6554fed66a193562c1530add528a19b8632c6c3c246b701c6210a2354019612325fd82845901a924a096d52c62789df741214671a29645593339281c20c39d@65.108.101.176:37146")
admin.addPeer("enode://b43d6afd9834e053621c5b92e0916f1c02b598e85cb9057d622b3e0b6c657c1a3665b24b3ddd30b5835ef8de566981a2c30494e2999dd3737bc1588222e61f8a@51.77.159.140:6050")
admin.addPeer("enode://65fb94fc51811b5cb5fadfb47babf9afb32da062362ec4602555d918b6481c3cf94ec72e42b1c8979a71a195b74215b76cc9e8ad4ee2654bcea7e4dd2817cc4d@52.23.35.172:61160")
admin.addPeer("enode://d660e8566c3bdfd86e3057699af82b1df0f146cb886f801142c340fe2b8c9818ff56c36bb76a4a22afdf30b5e2bc330cb1059c753321e3b803e2c67b27e320e4@5.9.104.204:30303")
admin.addPeer("enode://12dcac8d259a4acb798f08386896cce20bb012ee78c3a74ec7b47a850dd5c7765411c32d29d0d74b354d4d415d9ed58409d09983445bc7650d1e9d000855c888@212.102.36.229:32668")
admin.addPeer("enode://dbce8e48a5cd5f5f9a37130f66c78896c59411452888e50507448be2d5965222a6a1867f39d25f2c84975ab0ce6102c1deaa5a475438fe04f641bc3a0dde8167@35.182.147.162:49804")
admin.addPeer("enode://eafb9b2a1761a09e21d92a696b6233bae51df54d8af5b4ac72b737ba5338eec0cb60ff25892e941492b17455769275ea3209e75430a0f948b7fc7c05e3c5f48e@142.132.133.156:46792")
admin.addPeer("enode://95a376a86c103da42835e0d24fd3d88a1dd4a48fb9e48d5c47f2d744f33ad941694575afe5a0070f71d44210a6c5458b48e31add45684b2323617afa424f54dc@18.197.142.24:45126")
admin.addPeer("enode://57dd97170b948f217328ed460df22e874d107aec7ee98d7cf30286a021b91e947d6b85c4bc5cda357098e726fadcd51d5db8438837698319ab9d5798b14fcc1b@3.70.83.133:61162")
admin.addPeer("enode://c1c96a0f57df25beec0631b41ab814d1b2125c8d87108b624e00e42f2a21c95f7600b01e0f419456498ef5d9be0b8861f150424180a95def0a941b82bbea7997@3.236.38.156:42956")
admin.addPeer("enode://97045f43070287ae3e4c427ab44cfd5b0ae47c53244d1ea961c0853378508b3ca230eceb94375bb5d6886158091f23959ecbcb45d205a29e3b91819a0c455d25@89.58.50.234:30303")
admin.addPeer("enode://043fe98c57c8d9cf850c372acbb9239e5d76d8ec74bcf4bee55520983cff303ff241767c632ddd1977a9fd911e071c21ec676e6b29a3a774075980bed1382e93@54.161.207.69:30303")
admin.addPeer("enode://417bc76547ea3699c227b3cc823017f457e9404828b096ca58b8b578e81a77ba6dcdc59d2751f5c897a6805d4a2229c209e0fa2f238ba8b60a299efd23ce0b13@45.250.252.11:34422")
admin.addPeer("enode://4ccf493bceead65b56bd5e8a9a20dd59bf4c72a83a19062ebf8b64b05bf32b407f685b4542f3b97e5b93a62dc726d1abbd49cf24c27ed0d4d47c32ff29b4dc80@54.226.180.68:58494")
admin.addPeer("enode://f03734597ed4de6067b676d56b5e06c665cd5b5d999e8b350e972a9a994d5456952df40a73550c949a4da7fd41204da29c676aa162015739fdc6f4e73d16e42d@20.49.154.238:21504")
admin.addPeer("enode://ea77e7590ce596e29d9c138b504e4fe23f9e1d17af411b9fd5c8fcd38429221c824f5c39f73934af6fcf3a6163019e4a0969edec0e06a5f20dda5068fb02f3a7@51.79.55.57:60340")
```
