### ISSUE TITLE
How to purne the data?

### ISSUE THREAD

**Issue by Scumwong** [maticnetwork/bor#195]
My full matic node is 5TB ,How to purne the data ?

**Comment by ssandeep** [comment]
Hey @Scumwong , archive nodes cannot be pruned as the process of pruning removes the archive data and makes it a full node. So the only way to reduce size in archive nodes is to setup a new one and sync them from the beginning.
However, you can prune a full node with good results. Refer: https://forum.matic.network/t/bor-offline-pruning/1830
