### ISSUE TITLE
Bor shutting down stucked in Heimdall retry

### ISSUE THREAD

**Issue by ferranbt** [maticnetwork/bor#207]
#### Expected behaviour

The operator can stop the client at any time with "Ctrl-C".

#### Actual behaviour

If Heimdall is not available, [this](https://github.com/maticnetwork/bor/blob/master/consensus/bor/rest.go#L100) loop never finishes and it cannot even stop with "Ctlr-C" since it does not have any safe check.

#### Steps to reproduce the behaviour

Run Bor without Heimdall running.

**Comment by ko0f** [comment]
Stuck in this endlessly -
```
INFO [03-11|06:31:01.420] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
INFO [03-11|06:31:03.104] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
INFO [03-11|06:31:06.421] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
INFO [03-11|06:31:08.105] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
INFO [03-11|06:31:11.220] Looking for peers                        peercount=0 tried=104 static=1
INFO [03-11|06:31:11.422] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
INFO [03-11|06:31:13.106] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
INFO [03-11|06:31:16.423] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
INFO [03-11|06:31:18.107] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
INFO [03-11|06:31:21.424] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
INFO [03-11|06:31:23.108] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
INFO [03-11|06:31:24.250] Looking for peers                        peercount=0 tried=22  static=1
```

**Comment by foxbupt** [comment]
> This is especially an issue when bor + heimdall runs fine, then bor can't access heimdall for some reason, you can't shutdown bor gracefully, which corrupts the database, having to endure long recovery afterwards.
> 
> Stuck in this endlessly -
> 
> ```
> INFO [03-11|06:31:01.420] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
> INFO [03-11|06:31:03.104] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
> INFO [03-11|06:31:06.421] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
> INFO [03-11|06:31:08.105] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
> INFO [03-11|06:31:11.220] Looking for peers                        peercount=0 tried=104 static=1
> INFO [03-11|06:31:11.422] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
> INFO [03-11|06:31:13.106] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
> INFO [03-11|06:31:16.423] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
> INFO [03-11|06:31:18.107] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
> INFO [03-11|06:31:21.424] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
> INFO [03-11|06:31:23.108] Retrying again in 5 seconds for next Heimdall span path=bor/span/4034
> INFO [03-11|06:31:24.250] Looking for peers                        peercount=0 tried=22  static=1
> ```

I had encountered with this log again,  it's crazy。Could anyone has solved this, maybe give some suggestions?

**Comment by temaniarpit27** [comment]
Closing this as no further updates on this

**Comment by afanasy** [comment]
Still an issue

**Comment by afanasy** [comment]
@temaniarpit27 Thank you! I've joined the discord, but it says I have no permissions to join #full-node-queries.

**Comment by temaniarpit27** [comment]
@gobinat-h

**Comment by acovabo** [comment]
What is your Validator Node name @afanasy?

**Comment by afanasy** [comment]
@acovabo I don't have it.

**Comment by acovabo** [comment]
Okay. The issue has been addressed in the latest version of Bor. Have you by chance updated your node to the latest Bor version? @afanasy

**Comment by afanasy** [comment]
@acovabo Thank you! I think I was seeing this on the latest 0.2.16 version, but I'm not sure 100%, I'll test more.
