### ISSUE TITLE
Sort same-priced transactions by arrival time

### ISSUE THREAD

**Issue by moneyoriented** [maticnetwork/bor#209]
# Rationale

Currently, same-priced transactions are not sorted. Because of this, back-run arbitrators have to send thousands of transactions for one arbitrage opportunity. This is the main reason why there are too many spams in the Polygon network.

ETH had the same problem and it has been solved since go-ethereum v1.9.19. I think Polygon can also have this feature to reduce the spams.

@ssandeep @Uttam-Singhh

**Comment by ferranbt** [comment]
Hi! Thank you for opening the issue. Could you point me where go-ethereum implements this change? We usually upstream from the main repo so we should have the change applied too.

**Comment by moneyoriented** [comment]
close this issue since no one care about this.

**Comment by ajb** [comment]
The reason that the expected "first in first out" behavior doesn't work on Polygon is because of the sentry / validator architecture.
