### ISSUE TITLE
what is the machine requirementes to run the blockchain node 

### ISSUE THREAD

**Issue by malingzhao** [maticnetwork/bor#213]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by ferranbt** [comment]
Hi! Thank you for opening the issue. Here you can find the minimum requirements we advise to run Bor https://docs.polygon.technology/docs/validate/technical-requirements/
