### ISSUE TITLE
Add metadata.json to debug command

### ISSUE THREAD

**Issue by ferranbt** [maticnetwork/bor#216]
# Rationale

Why should this feature exist?

The ```bor debug``` command is used to return pprof traces from the running client. However, we could extend the behaviour to include more contextual information about the client. Add a new metadata.json file that includes the version and commit of the client.

# Implementation

Do you have ideas regarding the implementation of this feature?

Do not modify the current pprof Grpc endpoints but include a new endpoint that returns general status information about the client. Use that info to fill the metadata file.

**Comment by Udit-takkar** [comment]
Can I work on this one?

**Comment by dougrchamberlain** [comment]
I would like to take a stab at this. I need to learn somethings first. What guidance is there for creating a new endpoint?

**Comment by dougrchamberlain** [comment]
I believe you are asking for some modifications in this folder? `internal\debug` I'm walking the code to understand it better and I'd really like to contribute. I'm thinking I'll add something in the trace file to output to the new file (metadata.json)

**Comment by temaniarpit27** [comment]
Closing this as no further updates on this
