### ISSUE TITLE
how to deploy a full node 

### ISSUE THREAD

**Issue by malingzhao** [maticnetwork/bor#221]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by ferranbt** [comment]
Can you provide more information?

**Comment by Leon-Africa** [comment]
@malingzhao Please refer to https://docs.polygon.technology/docs/validate/polygon-overview for details on full node deployment process.

**Comment by yorickdowne** [comment]
The eth-docker clone-chains branch also supports Polygon, if you prefer something dockerized. There's a polygon-mainnet.env that needs to be copied to .env, adjust variables in .env, and then just `./ethd start`. https://github.com/yorickdowne/eth-docker/tree/clone-chains

**Comment by oneusdt** [comment]
> eth-docker clone-chains 分支也支持 Polygon，如果你更喜欢 dockerized。有一个polygon-mainnet.env 需要复制到.env，在.env 中调整变量，然后只需.env 即可`./ethd start`。https://github.com/yorickdowne/eth-docker/tree/clone-chains

help me . How change mainnet.env?

**Comment by vcastellm** [comment]
Refer to https://docs.polygon.technology/docs/integrate/full-node-deployment/ to deploy a full node
