### ISSUE TITLE
syncmode light nit working

### ISSUE THREAD

**Issue by osizadmin** [maticnetwork/bor#230]
We faced the issue while start the light syncmode.

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xd51db4]

goroutine 1 [running]:
github.com/ethereum/go-ethereum/les.(*LightEthereum).APIs(0xc0000c3760, 0xc00048b310, 0x0, 0x4b)
	github.com/ethereum/go-ethereum/les/client.go:289 +0x94
github.com/ethereum/go-ethereum/les.New(0xc0003cb6c0, 0xc000478700, 0xc00044dc20, 0xc0004a8aa0, 0xc5a4f0)
	github.com/ethereum/go-ethereum/les/client.go:181 +0x108a
github.com/ethereum/go-ethereum/cmd/utils.RegisterEthService(0xc0003cb6c0, 0xc000478700, 0xf, 0x0, 0x3)
	github.com/ethereum/go-ethereum/cmd/utils/flags.go:1746 +0x5c
main.makeFullNode(0xc0000c3600, 0x15b1bd8, 0x1, 0x0)
	github.com/ethereum/go-ethereum/cmd/geth/config.go:175 +0x125
main.geth(0xc0000c3600, 0x0, 0x0)
	github.com/ethereum/go-ethereum/cmd/geth/main.go:330 +0xf4
gopkg.in/urfave/cli%2ev1.HandleAction(0x1372ce0, 0x16b4618, 0xc0000c3600, 0xc000454ae0, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:490 +0x82
gopkg.in/urfave/cli%2ev1.(*App).Run(0xc00034cd00, 0xc0000320f0, 0xf, 0xf, 0x0, 0x0)
	gopkg.in/urfave/cli.v1@v1.20.0/app.go:264 +0x5f5
main.main()
	github.com/ethereum/go-ethereum/cmd/geth/main.go:267 +0x55

Kindly check and guide us.

**Comment by ssandeep** [comment]
Please use `--syncmode=full` as that is the only syncmode which is tested. We are already working on supporting snap mode and it will be available in future versions.

**Comment by osizadmin** [comment]
--syncmode=full - It was took more storage size. when you will release the new updated version.

**Comment by ssandeep** [comment]
We are working on supporting `snap` syncmode currently and will look at other sync modes in future.
