### ISSUE TITLE
bor run problem?

### ISSUE THREAD

**Issue by qinxg** [maticnetwork/bor#240]
I just need bor, Deploy RPC node
not need heimdall
Can not run heimdall? Just compile bor and run it

Do the two services depend on each other? Do they need to run together ?

In addition, does syncmode support fastsync?

**Comment by lcgogo** [comment]
As I know, bor needs hermdall.

**Comment by ssandeep** [comment]
Bor depends on heimdall to be running, so you will have to run heimdall as well. Currently, we only support `full` sync and will be adding support for `snap` sync mode soon.
