### ISSUE TITLE
Archive node reports missing trie nodes

### ISSUE THREAD

**Issue by d10r** [maticnetwork/bor#257]
I'm running bor 0.2.12 in archive node, was synced from the latest snapshot at https://snapshots.matic.today/.
The bor process is running with `--gcmode=archive --txlookuplimit=0`.  

On startup, it reports
```
Dec 06 10:18:45 buck-1 bash[4025553]: INFO [12-06|10:18:45.895] Enabling recording of key preimages since archive mode is used
```
The data directory has a size of ~6.5 TB.

So, it does indeed suggest to be running in archive mode.

However, despite that queries for old state report missing trie nodes. E.g.
```
> eth.getBalance("0x30B125d5Fc58c1b8E3cCB2F1C71a1Cc847f024eE", 10000000)
Error: missing trie node e2dde2847483bba2146fbaba80780ea12317384acd0aa6b6f87aa08a58efa7db (path )
        at web3.js:6357:37(47)
        at send (web3.js:5091:62(35))
        at <eval>:1:15(5)
```

I can query back to approx. block 17000000, but not much beyond.  
Is that snapshot incomplete or am I missing something?

**Comment by ssandeep** [comment]
You could be right, the snapshot file might be corrupt or incomplete. Did you check that the archive extraction completed in your machine?
@sreevalsanmr @brixial can you please provide the checksum for the archive node snapshot file so that @d10r can verify?

**Comment by sreevalsanmr** [comment]
`sha1sum bor-archive-node-snapshot-2021-11-11.tar.gz
5636bc3a9eceafe4e78328e10dd8df6a bor-archive-node-snapshot-2021-11-11.tar.gz`

**Comment by d10r** [comment]
thx for the answer. Unfortunately, I deleted the file a few days ago in order to not run out of storage.
I'm now waiting for a new snapshot to try again.

**Comment by d10r** [comment]
fyi: I re-downloaded the archive snapshot and am now syncing. Still having the same error when querying.  
When doing the same query on a mumbai archive node which was still syncing, it worked without error for blocks already synced.  
Can tell you if full sync helps once it's sync - probably in a month or so :-(

Getting an up-to-date snapshot would be great - the current one is > 2 months old.

**Comment by d10r** [comment]
fully synced now. Still the same error.
