### ISSUE TITLE
Documentation how to run bor full node

### ISSUE THREAD

**Issue by miohtama** [maticnetwork/bor#263]
# Rationale

There is no official documentation on how to run Bor full node. [The only official documentation there is is incomplete and missing full node part](https://docs.polygon.technology/docs/integrate/full-node-deployment). The current documentation is pointing to undocumented/barely documented Ansible notebooks and it is not sufficient for most sysadmin use cases.

Running a blockchain node should be easy and accessible to everyone, otherwise the blockchain network is inaccessible as sysadmins are guessing how the node should be run. 

# Implementation

Task one of the Bor core team members to write high-quality technical documentation that contains all the steps from installing dependencies on a clean Linux server to get the Bor node synced.

* What dependencies are needed
* In which order services must be started
* What are the available diagnostics and debug commands
* What are the command line options
* What are the configuration files
* Where are these files usually located
* What is the needed server spec
* How one can check the server matches the spec
* What options the user should use to tune the `heimdall` and `bor`
* What is the email list to receive information for critical network upgrades

**Comment by adamiss5138** [comment]
I'd also like to run a full node using Bor, but why there is not a single word about how to run it? What's the point of creating / releasing software when there is no documentation how to run it?

**Comment by vcastellm** [comment]
@adamiss5138 did you try this? https://docs.polygon.technology/docs/integrate/full-node-binaries
