### ISSUE TITLE
Document Bor bootnodes

### ISSUE THREAD

**Issue by miohtama** [maticnetwork/bor#264]
# Rationale

Document and maintain the official Bor boot notes. This information is not explicitly available and makes it harder for people to run their own nodes.

This is related to 

* https://github.com/maticnetwork/bor/issues/263

# Implementation

Make a page with a list of official boot nodes and who is maintaining them and how to contact them in the case of Network issues.

**Comment by temaniarpit27** [comment]
Closing this as no further updates on this

**Comment by ashwinkjoseph** [comment]
Is there any alternative source?

**Comment by armmarov** [comment]
Bor 0.5.0 cannot find peer. Please update working peer list !
