### ISSUE TITLE
Provide precompiled static bor binaries

### ISSUE THREAD

**Issue by miohtama** [maticnetwork/bor#265]
# Rationale

Compiling bor with make is an unnecessary complexity for the system administrators. One of the main selling points of Go the language is that distributing static binaries is easy. Distribute bor as a static binary. 

# Implementation

Like every else geth distribution out there: Have a Github continuous delivery job that pushes the binary to the Releases page for different architectures.

**Comment by vcastellm** [comment]
Done in https://github.com/maticnetwork/bor/pull/228
