### ISSUE TITLE
mumbai update bor 0.2.13-beta2

### ISSUE THREAD

**Issue by adremnsk** [maticnetwork/bor#271]
hello, after last bor update to v0.2.13-beta2 i'm can't catch synchronization. 
i tried: 
1. get last network snapshot
2. up to block 22 769 999 with bor v0.2.13-beta1 and update bor
3. run with bor v0.2.13-beta2 after restore from the snapshot

and many other things, nothing helped.
What am I doing wrong?

![Screenshot from 2021-12-19 20-07-01](https://user-images.githubusercontent.com/88728644/146675885-c7aa483b-3052-41a1-a4fa-cba368e39848.png)

**Comment by ssandeep** [comment]
Ensure you refer this post for the steps to upgrade to `v0.2.13-beta2` https://github.com/maticnetwork/bor/issues/273

Once upgraded, if you are beyond the fork block no, try to rewind the blockchain before the fork (in this case to block no `22639000`):
```
$ bor attach ~/.bor/data/bor.ipc
> debug.setHead("0x1597198")
```
