### ISSUE TITLE
v0.2.13-beta2 init error: Fatal: invalid genesis file: json: cannot unmarshal number into Go struct field BorConfig.config.bor.period of type map[string]uint64

### ISSUE THREAD

**Issue by lunzhenw** [maticnetwork/bor#273]
I use v0.2.13-beta2 to run a fullnode, there is a error when I init:

> bash setup.sh
Fatal: invalid genesis file: json: cannot unmarshal number into Go struct field BorConfig.config.bor.period of type map[string]uint64

**Comment by ssandeep** [comment]
As mentioned in the release notes (https://github.com/maticnetwork/bor/releases/tag/v0.2.13-beta2) and in the forum post (https://forum.polygon.technology/t/bor-mumbai-update-v0-2-13-beta2/424), this version is only for the Mumbai Testnet. If you are trying to run a fullnode in Mainnet, please use v0.2.12

If you are trying to run a full node in Mumbai testnet, then ensure you follow steps 5,6,7 in the above forum post.
