### ISSUE TITLE
How to Prune the bor data 

### ISSUE THREAD

**Issue by masayil** [maticnetwork/bor#288]
At present, the data of the main network already has 3T. I want to prune the bor data by myself. Does anyone how I should do?

**Comment by chouandy** [comment]
Hi @masayil, here is the reference https://forum.matic.network/t/bor-offline-pruning/1830.
Or you could download the pruned snapshot and re-run it. It may be faster. https://snapshots.matic.today/

**Comment by acryptosx** [comment]
In case anyone found this page looking for instructions on pruning their node, the link @chouandy posted is broken and can now be found here: https://forum.polygon.technology/t/bor-offline-pruning/9230
