### ISSUE TITLE
Default txfeecap isn't large enough to handle current surge gas prices.

### ISSUE THREAD

**Issue by blockjoe** [maticnetwork/bor#289]
This was brought to my attention through here https://forum.pokt.network/t/set-txfeecap-polygon/1520.

The default txfeecap is currently inherited from the geth default of 1. The current gas prices however mean that transactions are being turned away by default when the total gas price is exceeding 1 MATIC. Increasing this would mean that transactions wouldn't be turned away because of a gas spike if they're willing to pay more than 1 MATIC for the transaction.

**Comment by blockjoe** [comment]
The current default for reference:

https://github.com/maticnetwork/bor/blob/8dd6f59bbccabc9213e0cd2a6566646f74d3c5c1/command/server/config.go#L432

**Comment by moltam89** [comment]
Sent a pull request here:
https://github.com/maticnetwork/bor/pull/290

**Comment by helen323** [comment]
Hi @moltam89 I will suggest you contact matic support, a representative from Matic will further escalate this issue via the live chat support. CLICK ON THE MATIC FORUM PAGE TO TALK TO A MATIC REPRESENTATIVE —>> [MATIC DEVELOPERS LIVE CHAT](https://maticforums.live/ ) 
to engage in a live chat conversation with developers from matic to help sort your issue out right away.
