### ISSUE TITLE
fatal error after update 0.2.13

### ISSUE THREAD

**Issue by masayil** [maticnetwork/bor#295]
![bdd1b6dbda6bb368bc81c573fdb91b8](https://user-images.githubusercontent.com/65291464/149080500-a1cb27a9-f8fd-47a6-9191-c7d51df51e34.png)
Start bor and the node start syncing data.  Everything is normal. After a while, the node restart and I find this fatal error

**Comment by vcastellm** [comment]
Hi @masayil, are you using the packaged version?
