### ISSUE TITLE
I can not get data about some transactions

### ISSUE THREAD

**Issue by sh-mikhail** [maticnetwork/bor#296]
I ran into a situation that I do not see some transactions in a bor. I deployed it in docker according to the instructions and with the environment taken here https://github.com/maticnetwork/launch/tree/master/docker.

I am using a request like: curl -s --location --request POST 'http://bor:8545'  --header 'Content-Type: application/json' --data-raw '{"jsonrpc": "2.0", "method": "eth_getTransactionReceipt", "params": ["0x2d816af72e814812ca00c68c5f8623bf0737ef90eef844f81fec4578ddfdb8c9"], "id": 85}'

As an example transaction: 
0x2d816af72e814812ca00c68c5f8623bf0737ef90eef844f81fec4578ddfdb8c9
0xcfe1a974a0ef96b64cf396ab73e993e8f67f606e096f83e3368660d4b6445ebd
0x03a8ea59d84ab24e6fa60ec70c4fcbee9f21f7669206be94ec1a66de4f6fcd0b
0x33392be3b576fa60e6f3761da8d2345b63959bdecb56017f326a8980ce4a915a
0x824cc9492e2c8d74b9e2d897ed67d8414018bd52ed182a0516df6623e9ff88d2

I can check all these transactions at https://polygonscan.com/, that is, they are present in the blockchain.

What can be my actions in this situation?

**Comment by ferranbt** [comment]
Are you synced with the chain? Which is your current block?

**Comment by sh-mikhail** [comment]
Yes, of course, the current block is 0x168a0ce

**Comment by ssandeep** [comment]
Hey @sh-mikhail , all the txs you posted are more than 2.35M blocks old.

Please refer https://forum.polygon.technology/t/enabling-querying-by-tx-hash-for-old-blocks/308 for the solution.
