### ISSUE TITLE
Q:update 0.2.13 -mainnet

### ISSUE THREAD

**Issue by masayil** [maticnetwork/bor#297]
![image](https://user-images.githubusercontent.com/65291464/149291211-5aaa9936-8de1-417b-80d2-39e79b7155b8.png)
Is the output log normal? 
I can get the same result by using `journalctl -u bor --since today | grep -i london`.
![image](https://user-images.githubusercontent.com/65291464/149291752-a9cd29ed-e715-4247-8135-9c1c3046e5f3.png)

**Comment by ssandeep** [comment]
Yes, it was successful.
