### ISSUE TITLE
Block stops syncing when it reaches 23849999

### ISSUE THREAD

**Issue by fwhappy** [maticnetwork/bor#299]
#### System information

Geth version: `0.2.13`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

{
  currentBlock: 23843068,
  highestBlock: 23849999,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 23843004
}

Block stops syncing when it reaches 23849999

**Comment by suyog-unmarshal** [comment]
Please follow the below docs.
https://forum.polygon.technology/t/eip1559-london-fork-on-mainnet/549

**Comment by slashramin** [comment]
same here ):

**Comment by slashramin** [comment]
> Please follow the below docs. https://forum.polygon.technology/t/eip1559-london-fork-on-mainnet/549

I did what was there but my node still on 23849999 
Synchronisation failed, dropping peer peer=2554925e5e9fc1687db5395584288cd0a8a9e092962aec37e921995549d0beb9 err="retrieved hash chain is invalid: could not apply tx 0 [0x1c770984312e29c76f49949249f4a1aeab15e36919eead204359fb58640a4056]: nonce too high: address 0x674992251A5eF197Be5ad7363e7588d23a18B432, tx: 3975 state: 0"

**Comment by daichuanliang** [comment]
I used https://github.com/maticnetwork/bor/blob/v0.2.13/Dockerfile to build the latest dokcer, but it doesn't work. 
invalid command: "bor"

**Comment by 0xKrishna** [comment]
Guys your node has stopped syncing due to the London fork, Please update to the latest and it should work.

**Comment by suyog-unmarshal** [comment]
> I used https://github.com/maticnetwork/bor/blob/v0.2.13/Dockerfile to build the latest dokcer, but it doesn't work. invalid command: "bor"

You should update the genesis file, not just image

**Comment by ko0f** [comment]
> > I used https://github.com/maticnetwork/bor/blob/v0.2.13/Dockerfile to build the latest dokcer, but it doesn't work. invalid command: "bor"
> 
> You should update the genesis file, not just image

How would updating the genesis file fix unknown docker image executable?

**Comment by 0xKrishna** [comment]
This issue is related to syncing stop at block `23849999` which is due to london fork update.
This will be fixed by genesis update. For any other issue, Please raise separate request.

**Comment by vcastellm** [comment]
> I used https://github.com/maticnetwork/bor/blob/v0.2.13/Dockerfile to build the latest dokcer, but it doesn't work. invalid command: "bor"

What command are you using to run it?

**Comment by ko0f** [comment]
> 

`docker run -it --network matic_default -v /matic/bor:/datadir -p 8545:8545 -p 8546:8546 -p 30324:30324 -p "30324:30324/udp" bor:latest bor --datadir /datadir init /datadir/genesis.json`

**Comment by ko0f** [comment]
Submitted separate issue for the above `invalid command: "bor"` https://github.com/maticnetwork/bor/issues/302

**Comment by 0xKrishna** [comment]
Closing as this is already known, Need to update genesis as per London fork and it should work.
