### ISSUE TITLE
Many transactions in mempool has sender as null

### ISSUE THREAD

**Issue by soltrac** [maticnetwork/bor#300]
I don't know if it is some type of spam or whatever, but if you read the mempool, you will see lots of transactions with sender = 0x0000000000000000000000000000000000000000. The transaction hash never appears on the network.

Why is this happening exactly? I never saw this situation before on polygon. It started happening today.

**Comment by soltrac** [comment]
Just checked and ALL those transactions are in EIP1559, so that's why I never saw this situation.

An example: 

https://i.ibb.co/s3fZtHw/Captura.png

**Comment by soltrac** [comment]
Figured out what is happening. I think my RPC provider has not upgraded their nodes. On my own node, upgraded to support the hardfork, this is not happening. I'm closing this.

**Comment by soltrac** [comment]
Sorry for multiposting, I Reopen this because in my node I cannot find any EIP1559 transactions that are not mine on mempool. If I use a remote RPC, those transactions are received with sender = 0x0000000000000000000000000000000000000000.

This is happening since hardfork

**Comment by ferranbt** [comment]
So is this a problem only when the transaction is on the mempool?

**Comment by soltrac** [comment]
Yes, once they are mined, the sender is ok, but if you read them on mempool, the sender is 0x0000000000000000000000000000000000000000. I've tried other networks and they do it ok, but something in bor is broken, because the sender of many transactions on mempool is 0x0000000000000000000000000000000000000000.

**Comment by ferranbt** [comment]
Hey, thank you for reporting this issue. We have a couple of leads on the possible solution and we will be landing a PR soon.

**Comment by 0xKrishna** [comment]
This is fixed with the above-mentioned PR, Can we close this now?
