### ISSUE TITLE
invalid command: "bor" with Docker build

### ISSUE THREAD

**Issue by ko0f** [maticnetwork/bor#302]
Building from Dockerfile does not work anymore, a message `invalid command: "bor"` is shown when trying to run using docker.

#### System information

Geth version: **v0.2.13** 
OS & Version: Linux / Ubuntu

#### Expected behaviour

bor starts

#### Actual behaviour

invalid command: "bor"   

#### Steps to reproduce the behaviour
```
> git fetch
> git fetch --tags
> git checkout v0.2.13
> docker build --tag bor:latest . --no-cache
... 
> docker run -it --network matic_default -v /matic/bor:/datadir -p 8545:8545 -p 8546:8546 -p 30324:30324 -p "30324:30324/udp" bor:latest bor --datadir /datadir init /datadir/genesis.json
invalid command: "bor"   
```

**Comment by ferranbt** [comment]
Can you run ``help``?

**Comment by vcastellm** [comment]
`bor` is now set as the dockerfile entrypoint so you should not pass explicitly the `bor` command, you can omit it and pass only the flags.

This will work:
`docker run -it --network matic_default -v /matic/bor:/datadir -p 8545:8545 -p 8546:8546 -p 30324:30324 -p "30324:30324/udp" bor:latest --datadir /datadir init /datadir/genesis.json`
