### ISSUE TITLE
Clarify branching strategy?

### ISSUE THREAD

**Issue by ajb** [maticnetwork/bor#310]
@ferranbt  wondering if you can help me out with this -- wondering what the branching strategy for this repo is, and why sometimes there are changes in a release tag (v0.2.24 for example) that do not seem to be reflected in the master branch?

Perhaps this can be clarified in the documentation, too?

Thank you!

**Comment by kaber2** [comment]
Seconded. As someone who builds from git, this is really confusing. IIRC last release contained a commit that could not be found in the repository at all.

**Comment by vcastellm** [comment]
We are working towards standardize our branching strategy, bear with us, we needed to release big changes in latest release, from now on all stable changes will be on the default branch in the repo.
