### ISSUE TITLE
After upgrade to 0.2.13, node returning 0x0 for get balance request on address that has value

### ISSUE THREAD

**Issue by EirikPoloniex** [maticnetwork/bor#320]
#### System information

bor version: 0.2.13
OS & Version: Ubuntu (ubuntu:focal-20210119)

#### Expected behaviour
this curl request against the node:
curl -X POST -H 'Content-Type: application/json' -d '{"jsonrpc":"2.0","id":"id","method":"eth_getBalance","params":["0x06C3cE80f6a7b3c44600739eC6058B2241882DF2","latest"]}' {url}

should return: 
{"jsonrpc":"2.0","id":"id","result":"0x16ad7203579b4681e4cb9"}

#### Actual behaviour
The returned value is:
{"jsonrpc":"2.0","id":"id","result":"0x0"}

#### Steps to reproduce the behaviour
This started happening after upgrading bor version from 0.2.12-beta3 to 0.2.13. The new genesis file was initialized. New blocks and transactions are being read successfully. Not seeing any errors or anything suspicious in the logs. It just is returning zero as the balance when it should be much greater than that

**Comment by temaniarpit27** [comment]
Closing this as no further updates on this
