### ISSUE TITLE
Light bor node.

### ISSUE THREAD

**Issue by kulievvitaly** [maticnetwork/bor#330]
Bor is fork of geth(go-ethereum) project. That is possible to launch a light geth node. This is very convenient for developers because there is no need to download terabytes of data. Is it planned to launch a light node in the polygon?

**Comment by osizadmin** [comment]
We are expecting the light node. Let me know when it will release.

**Comment by timmolter** [comment]
In the mean time, while we're waiting for a light node, is there a way to start bor with a `startingBlock` parameter to skip 99% of the blockchain?

**Comment by sunil0410** [comment]
@kulievvitaly @osizadmin  Thank you for reaching out to us.

Of course, the team has noted the suggestion on the light node.

Our team is working towards this but as of now, we don't have a definite timeline.

**Comment by temaniarpit27** [comment]
Closing this as no further updates on this

**Comment by kooztechkb** [comment]
We are expecting the light node. Let me know when it will release.

**Comment by 7AC** [comment]
@temaniarpit27 @sunil0410 can we keep this open to track progress? I know there's no timeline but would be useful to have something to subscribe to. Thanks

**Comment by 0xsharma** [comment]
Hey @kulievvitaly @osizadmin @timmolter @kooztechkb 

Hi folks, 

To have a better approach on this, it would be great if you could highlight your use-case for the light node. Also, what are the objectives you're not able to achieve using the RPC endpoints? 

Thank you !

**Comment by osizadmin** [comment]
@0xsharma we are not able to spend more storage size for chaindata. 

We don't want to maintain old data. That's why we need light syncmode.

**Comment by 0xsharma** [comment]
Thanks @osizadmin , also if you can please elaborate on what objectives you're not able to achieve using the RPC endpoints but you will be able to do the same with light clients. 

Thank you !

**Comment by shekohex** [comment]
As a Polygon user, I want to be able to start a bor light client, it should sync in a few mins and fast. The main use case is for having a local RPC that I can link to my wallet so that I have a full privacy of my information.

**Comment by tab00** [comment]
@0xsharma @temaniarpit27 @sunil0410 is there any progress with this?

The foundational philosophy of blockchain is decentralization. Enabling light nodes means more people would operate nodes, which leads to more decentralization and a larger network, increasing reliability and security overall.

**Comment by tab00** [comment]
Please fix this link so that the answer appears on the page: [Is there a way to run a light Bor node?](https://wiki.polygon.technology/docs/pos/pos-faqs/#is-there-a-way-to-run-a-light-bor-node)

**Comment by thephilippk** [comment]
A light node would be fantastic
