### ISSUE TITLE
go.mod has incorrect module path

### ISSUE THREAD

**Issue by shrimpyuk** [maticnetwork/bor#334]
Would it be possible to change bor from github.com/ethereum/go-ethereum to github.com/maticnetwork/bor in go.mod?
This creates issues when having software that uses both geth and bor.

**Comment by 0xKrishna** [comment]
Not now since we are dependent on geth and we tried to change that but it created a lot of issues on our end.

For now, you can use the `replace` command in `go.mod` to change your paths locally if you want.
