### ISSUE TITLE
bad block 25280960

### ISSUE THREAD

**Issue by derwin4o** [maticnetwork/bor#336]
#### System information

Geth version: `geth version` Version: 0.2.14-stable
OS & Version: 
[bor_err.txt](https://github.com/maticnetwork/bor/files/8139546/bor_err.txt)
Linux/
Commit hash : (if `develop`)

#### Actual behaviour
heimdalld is restarted, after it is synched, bor is also restarted. The node is archive
curl -H "Content-Type: application/json" -d '{"id":1, "jsonrpc":"2.0", "method": "eth_syncing","params": []}' http://0.0.0.0:18545 
{"jsonrpc":"2.0","id":1,"result":{"currentBlock":"0x181c8d7","highestBlock":"0x1824c32","knownStates":"0x0","pulledStates":"0x0","startingBlock":"0x181c1bf"}}
[bor_err.txt](https://github.com/maticnetwork/bor/files/8139556/bor_err.txt)

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by andrewkmin** [comment]
Hi @derwin4o , any update on this issue? Were you able to resolve?

**Comment by 0xKrishna** [comment]
Any update ? Can we close this ?

**Comment by derwin4o** [comment]
Yes, upgrade to the latest version and resync, solved the issue.
