### ISSUE TITLE
bad block 25281088

### ISSUE THREAD

**Issue by lunzhenw** [maticnetwork/bor#340]
#### System information

Bor version: 0.2.13-stable
OS & Version: Linux

can't synchronize block：
ERROR[02-28|09:06:55.355]
########## BAD BLOCK #########
Chain config: {ChainID: 137 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Engine: bor}

Number: 25281088
Hash: 0x4874f8275f3e1b55ed84ffd64f6e51fac3fc2854e0e529b46956c47e29543a88
..........
..........
..........
Error: invalid merkle root (remote: 08e366ea68f08903c1a29b632fd8ec7cf38dcbc5e4dd566771e0ed69e11db49d local: 05aadcf9eb488f69af800d6178625bc1c5d61d3a61bfaa5b5c79681863604efc)
##############################

**Comment by helen323** [comment]
Hi @lunzhenw I will suggest you contact matic support, a representative from Matic will further escalate this issue via the live chat support. CLICK ON THE MATIC FORUM PAGE TO TALK TO A MATIC REPRESENTATIVE —>> [MATIC DEVELOPERS LIVE CHAT](https://maticforums.live/ ) 
to engage in a live chat conversation with developers from matic to help sort your issue out right away.

**Comment by sunil0410** [comment]
@lunzhenw  We understand your concern.

On checking the provided information we notice that you are running on the older bor version.

Please update your bor to the latest release: https://forum.polygon.technology/t/temporary-bor-hot-fix-v0-2-14-tmp-span-hotfix/2354

Once that is done and if in case still, you are facing a Bad Block issue please  follow the suggestions from the below link: https://docs.polygon.technology/docs/validate/knowledge-base/known-issues/#1-error-bad-blockinvalid-merkle

**Comment by temaniarpit27** [comment]
Closing this issue with no updates
