### ISSUE TITLE
bor slowly consuming entire system memory then OOM crash

### ISSUE THREAD

**Issue by cyrilledec** [maticnetwork/bor#342]
#### System information
```
$ bor version
Bor
Version: 0.2.14-stable
Git Commit: 28963d5ccd3028e0ac6f1915845c747862d649d1
Architecture: amd64
Go Version: go1.17
Operating System: linux
GOPATH=
GOROOT=go
```
```
$ uname -a
Linux ip-10-10-103-129 5.11.0-1022-aws #23~20.04.1-Ubuntu SMP Mon Nov 15 14:03:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
#### Expected behaviour

bor should reserve its memory at its startup and keep using it.

#### Actual behaviour

`bor` starts with a reasonable amount of reserved memory but days after days consumes more and more memory until the system crash.

#### Steps to reproduce the behaviour

here is our `start.sh`
```
#!/usr/bin/env sh

set -x #echo on

BOR_DIR=${BOR_DIR:-~/.bor}
DATA_DIR=$BOR_DIR/data

bor --datadir $DATA_DIR \
  --port 30303 \
  --http --http.addr '127.0.0.1' \
  --http.vhosts '*' \
  --http.corsdomain '*' \
  --http.port 8545 \
  --ipcpath $DATA_DIR/bor.ipc \
  --http.api 'eth,net,web3,txpool,bor' \
  --syncmode 'full' \
  --networkid '137' \
  --miner.gasprice '30000000000' \
  --miner.gaslimit '20000000' \
  --miner.gastarget '20000000' \
  --txpool.nolocals \
  --txpool.accountslots 16 \
  --txpool.globalslots 131072 \
  --txpool.accountqueue 64 \
  --txpool.globalqueue 131072 \
  --txpool.lifetime '1h30m0s' \
  --maxpeers 25 \
  --bootnodes "enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303"
```
reducing `maxpeers` option had an impact : `bor` started to run with a less amount of memory but the behavior is the same, using more and more memory.
we also tried to add more memory on the system but same result.

#### Backtrace

<img width="1019" alt="image" src="https://user-images.githubusercontent.com/46990478/156360590-57561523-f30e-4f8a-b76b-301932ca7888.png">

**Comment by helen323** [comment]
Hi @cyrilledec This looks like a vital issue, I will suggest you contact matic support, a representative from Matic will further escalate this issue via the live chat support. CLICK ON THE MATIC FORUM PAGE TO TALK TO A MATIC REPRESENTATIVE —>> **[MATIC DEVELOPERS LIVE CHAT]** (https://maticforums.live/ ) 
to engage in a live chat conversation with developers from matic to help sort your issue out right away.

**Comment by helen323** [comment]
Hi @cyrilledec I will suggest you contact matic support, a representative from Matic will further escalate this issue via the live chat support. CLICK ON THE MATIC FORUM PAGE TO TALK TO A MATIC REPRESENTATIVE —>> [MATIC DEVELOPERS LIVE CHAT](https://maticforums.live/ ) 
to engage in a live chat conversation with developers from matic to help sort your issue out right away.

**Comment by sunil0410** [comment]
@cyrilledec  We understand your concern.

Please check the below steps with regards to the OOM issue.

1. Ensure that you have met all the system requirements as per the below documentation link

https://docs.polygon.technology/docs/develop/network-details/technical-requirements/

2. Make sure you have set all the below values accordingly

a. Ensure the price limit is set:
--txpool.pricelimit '30000000000'

b. reduce the txpool by setting the below:
  --txpool.nolocals \
  --txpool.accountslots 16 \
  --txpool.globalslots 65536 \
  --txpool.accountqueue 32 \
  --txpool.globalqueue 65536 \
  --txpool.lifetime '1h30m0s' \

3. If incase still you face the issue after meeting all these requirements.

- Then drop us your Heimdall Version.
- Bor Logs.
- Output of the following command  dmesg  | grep -i oom

**Comment by temaniarpit27** [comment]
Closing this as no further updates on this
