### ISSUE TITLE
fix comment of txlookuplimit

### ISSUE THREAD

**Issue by shiziwen** [maticnetwork/bor#343]
# Rationale

The comment of the txlookuplimit show as "Number of recent blocks to maintain transactions index for (default = about one year, 0 = entire chain)". It is correct for the Eth, but for bor, the default time is about 56 days.

# Implementation

The default of txlookuplimit is 2350000, for the bor, the default block period is 2s, and if it is the first block of one sprint, the producerDelay is 6s.
So, the period of one sprint is 2*63 + 6 = 132 s, for 2350000 blocks there will be 2350000 / 64.0 * 132 s, that is 2350000 / 64.0 * 132 / 3600 / 24 = 56 days.

So, we should modify the cmd/utils/flags.go, docs/cli/server.md and internal/cli/server/flags.go.

**Comment by shiziwen** [comment]
I have tried to fix it, refer to my pull request from https://github.com/maticnetwork/bor/pull/344.

**Comment by helen323** [comment]
Hi @shiziwen I will suggest you contact matic support, a representative from Matic will further escalate this issue via the live chat support. CLICK ON THE MATIC DEVELOPERS FORUM PAGE TO TALK TO A MATIC REPRESENTATIVE —>>>[MATIC DEVELOPERS LIVE CHAT]
to engage in a live chat conversation with developers from matic to help sort your issue out right away.

**Comment by helen323** [comment]
Hi @shiziwen I will suggest you contact matic support, a representative from Matic will further escalate this issue via the live chat support. CLICK ON THE MATIC FORUM PAGE TO TALK TO A MATIC REPRESENTATIVE —>>> **[MATIC DEVELOPERS FORUM LIVE CHAT]**(https://maticforums.live/ )
to engage in a live chat conversation with developers from matic to help sort your issue out right away.

**Comment by shiziwen** [comment]
> Hi @shiziwen I will suggest you contact matic support, a representative from Matic will further escalate this issue via the live chat support. CLICK ON THE MATIC FORUM PAGE TO TALK TO A MATIC REPRESENTATIVE —>>> **[MATIC DEVELOPERS FORUM LIVE CHAT]**(https://maticforums.live/ )
> to engage in a live chat conversation with developers from matic to help sort your issue out right away.

Hi, I cannot open https://maticforums.live/ .

**Comment by temaniarpit27** [comment]
Closing this as no further updates on this
