### ISSUE TITLE
v0.2.14-tmp-span-hotfix is ok to apply?

### ISSUE THREAD

**Issue by tn606024** [maticnetwork/bor#350]
I use new bor version v0.2.14-tmp-span-hotfix to fix polygon stop producing block problem, now bor is resume and sync correctly.
but I found like polygon scan, infura, https://polygon-rpc.com/ still stop now, so I'm not sure my bor is on the correct block or wrong fork.

does everyone use this patch sync correctly ?

newest block: 25816963
hash: 0xeb8e05ee7f3afe01f05270fe588204f8cdd73702c7d81cf188b1b4fe103d8cdc

**Comment by masayil** [comment]
https://rpc-mainnet.matic.quiknode.pro
try this public rpc node

**Comment by masayil** [comment]
request:
curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method":"eth_getBlockByNumber", "params": ["0x189EF83",false], "id": 1}' http://0.0.0.0:8545
result:
{"jsonrpc":"2.0","id":1,"result":{"baseFeePerGas":"0xe","difficulty":"0x6","extraData":"0xd482020e83626f7286676f312e3137856c696e7578000000000000000000000043fe36c0f3ec1df04c66d796016dcffd2f49ceae8616ab22074a6e170df4cfe104a01560b17e3bc8cb8475c0fdb6bf54dac77fd4458c4acd7e39280e77d9dd8f01","gasLimit":"0x1c9c380","gasUsed":"0x2e1e19","hash":"0xeb8e05ee7f3afe01f05270fe588204f8cdd73702c7d81cf188b1b4fe103d8cdc","logsBloom":"0x2812810222210205000000020000000a0020a1088000828100021000208020055008110c00810000004a0844000000010001a10284426000a000210048242940801020030a000040080300098038008210000044010c200000d9041202483841800c8200028000000008028900048c1000004000000000228000013401020000000014400a080000000002006284200400110ce40000424000008800040000006610004010022e080940400001042040024012878208080008c8020000000042000098020000002000810000a0a9100048504000c4080010001801180800600460100044020308059000405c01100311c0488048853004030000280401100020","miner":"0x0000000000000000000000000000000000000000","mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000","nonce":"0x0000000000000000","number":"0x189ef83","parentHash":"0x9fc7641825ebbf77c51fb70faf9be710f05f4d8c8fd748f37f98fc2cefc71052","receiptsRoot":"0x28c6d429b6dabbec9a117a19876eb2cef6f871779b8a43719892e2c8c8b6acdc","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x4482","stateRoot":"0x5f57ce96964fa6471fb37c5f7316b90746675efd7f97274c84eaf0eb5c493530","timestamp":"0x622abd91","totalDifficulty":"0x14175b9c","transactions":["0x84f050d6b7a92e67de10873714f643da8aefc1a3e1aea033e96e448a714694cc","0x1ecee474feb58240a05ef29cd89d17b3d9d5a2bff4564cb13985fa8db9d1f3f2","0x3912e3105ca9369ec16a6b4b3af156059a10ec6c549205fe3be9510ec260561b","0x7025836fc53f5d1c952f17dd419b77fdd0865bc4bf7131017a1cb740e71ffebf","0xc459effb2f8aea875050e9cfaf0dc3c9f93f9fb23e0211976f832e81fd1adcd2","0x9c15ea46aed71d8c5a99e63ea2b6b3f2ac13406a6abe6224eb12ce0a707b5aa7","0x2d7b7e1567db94603be7f6bdb50b7651ef946c8136387b7c96408a40fbd094b0","0x9fc20dc5756869dbd69cb8af70cd24687c0ae70384dc4639a51155b0fb28e6d5","0x23569931cbd4b5a899b98171a19819562fbd9a02fbb6d97ffe47b8732c21f9bc","0x84df97d164477812e66a1e20d13449e2a7d7ac53a8ba42395bf18aeb56e5ce02","0xa14c1a82e9131d29e784338b5e84afa747c8d6bc52be93cc9ba11776590d04f6","0x86553bac76881bd66f7f9415bc9b0089db3ea5b6f39beb15ff92af1ae74ad95c","0xe672b39dcce7e274768344a2d562f18284233e8b3b4f23533a8c856bf7d1382c","0xaa08657fe605eb0cf52dbc015c0ffe3afe0813703093feebf5f80ebab7b01c85","0xac2d836658d5e3b0a833734ac7bba61eccee58c1de3334edca5d142b2c80e765","0x6b5dcf3454d8c5904a53b19add8c6c991244467dd8b79fbdc5c18a41a5b11907","0xe5a47319e9b10e3fbf5ee6f60d8966cc17c0d19fbeaab9897be477aa8d5933e4","0xf7f74f51d70db0cd18f675455e37513cd4236cc46f24eaba50df9afd7269db1c","0x24e67bedead63a2c083809257d365862117e3ebd2bc0a858625b0353cd551ef6","0x2bb2f598be9722c26839ab58686fae29098dc2cd1eebbf98706e9a69d4aaca81","0x7d633f311bddd68cb55470c0d3be69503b36ecf173770f29de6afb3cc76b5987","0x374e56343974589e71d2307d127df2a4899f54ede711cca49741f152a750b29a","0xf9206e6684fdc0e4e1d19b4899bc34b091c6b87b9cc89126e8d1e0f59695030d"],"transactionsRoot":"0x7f1ee15e2cdef0980336bf51e19141b3a58943155fb5e2075d32b72a2df07156","uncles":[]}}

**Comment by lcgogo** [comment]
After update to hotfix, the node stop at followed block and without any ipc and rpc method up.
So can not debug.setHead("") any more. 

```shell
INFO [03-11|08:00:59.265] Set global gas cap                       cap=50,000,000
INFO [03-11|08:00:59.265] Allocated trie memory caches             clean=154.00MiB dirty=256.00MiB
INFO [03-11|08:00:59.274] Allocated cache and file handles         database=/data/matic/bor/chaindata cache=512.00MiB handles=524,288
INFO [03-11|08:01:09.098] Opened ancient database                  database=/data/matic/bor/chaindata/ancient readonly=false
INFO [03-11|08:01:09.128] Initialised chain configuration          config="{ChainID: 137 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Engine: bor}"
INFO [03-11|08:01:17.064] Gasprice oracle is ignoring threshold set threshold=2
INFO [03-11|08:01:17.080] Initialising Ethereum protocol           network=137 dbversion=8
INFO [03-11|08:01:17.805] Loaded most recent local header          number=25,811,391 hash=75a8c4..f42a93 td=337,043,805 age=14h7m1s
INFO [03-11|08:01:17.809] Loaded most recent local full block      number=25,811,391 hash=75a8c4..f42a93 td=337,043,805 age=14h7m1s
INFO [03-11|08:01:17.809] Loaded most recent local fast block      number=25,811,391 hash=75a8c4..f42a93 td=337,043,805 age=14h7m1s
WARN [03-11|08:01:17.818] Head state missing, repairing            number=25,811,391 hash=75a8c4..f42a93 snaproot=ffcf9f..3626c1

```

**Comment by masayil** [comment]
add --snapshot=false

**Comment by lcgogo** [comment]
> --snapshot=false
@masayil 
added the option but nothing changes

```shell
root@ip-10-2-1-11:/data/matic# docker logs -f matic_0.2.14-tmp-span-hotfix_1
INFO [03-11|12:10:06.706] Maximum peer count                       ETH=100 LES=0 total=100
INFO [03-11|12:10:06.707] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [03-11|12:10:06.707] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable
INFO [03-11|12:10:06.720] Snap sync requested, enabling --snapshot
INFO [03-11|12:10:06.720] Set global gas cap                       cap=50,000,000
INFO [03-11|12:10:06.720] Allocated trie memory caches             clean=154.00MiB dirty=256.00MiB
INFO [03-11|12:10:06.725] Allocated cache and file handles         database=/data/matic/bor/chaindata cache=512.00MiB handles=524,288
INFO [03-11|12:10:14.958] Opened ancient database                  database=/data/matic/bor/chaindata/ancient readonly=false
INFO [03-11|12:10:15.012] Initialised chain configuration          config="{ChainID: 137 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Engine: bor}"
INFO [03-11|12:10:22.426] Gasprice oracle is ignoring threshold set threshold=2
INFO [03-11|12:10:22.452] Initialising Ethereum protocol           network=137 dbversion=8
INFO [03-11|12:10:23.166] Loaded most recent local header          number=25,811,391 hash=75a8c4..f42a93 td=337,043,805 age=18h16m7s
INFO [03-11|12:10:23.166] Loaded most recent local full block      number=25,811,391 hash=75a8c4..f42a93 td=337,043,805 age=18h16m7s
INFO [03-11|12:10:23.166] Loaded most recent local fast block      number=25,811,391 hash=75a8c4..f42a93 td=337,043,805 age=18h16m7s
WARN [03-11|12:10:23.175] Head state missing, repairing            number=25,811,391 hash=75a8c4..f42a93 snaproot=ffcf9f..3626c1
^C
root@ip-10-2-1-11:/data/matic# ls
INIT_DONE  bor  docker-compose.yml  genesis.json  heimdall  keystore  lost+found
root@ip-10-2-1-11:/data/matic# docker top matic_0.2.14-tmp-span-hotfix_1
UID                 PID                 PPID                C                   STIME               TTY                 TIME                CMD
nobody              1356905             1356885             50                  12:10               ?                   00:33:13            ./bor --datadir /data/matic --maxpeers 100 --nousb --http --http.addr 0.0.0.0 --http.api eth,net,web3,txpool,bor --http.corsdomain=* --http.vhosts=* --ws --ws.addr 0.0.0.0 --ws.api eth,net,web3,txpool,bor --ws.rpcprefix=/ --ws.origins=* --bor.heimdall=http://heimdallr:1317 --networkid 137 **--snapshot=false** --bootnodes enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303
```

**Comment by lcgogo** [comment]
```shell
CMD ["./bor", \
  "--datadir", "/data/matic", \
  "--maxpeers", "100", \
  "--nousb", \
  "--http", \
  "--http.addr", "0.0.0.0", \
  "--http.api", "eth,net,web3,txpool,bor", \
  "--http.corsdomain=*", \
  "--http.vhosts=*", \
  "--ws", \
  "--ws.addr", "0.0.0.0", \
  "--ws.api", "eth,net,web3,txpool,bor", \
  "--ws.rpcprefix=/", \
  "--ws.origins=*", \
  "--bor.heimdall=http://heimdallr:1317", \
  "--networkid", "137", \
  "--snapshot=false", \
  "--bootnodes", \
  "enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303"]
```

**Comment by masayil** [comment]
> ```shell
> CMD ["./bor", \
>   "--datadir", "/data/matic", \
>   "--maxpeers", "100", \
>   "--nousb", \
>   "--http", \
>   "--http.addr", "0.0.0.0", \
>   "--http.api", "eth,net,web3,txpool,bor", \
>   "--http.corsdomain=*", \
>   "--http.vhosts=*", \
>   "--ws", \
>   "--ws.addr", "0.0.0.0", \
>   "--ws.api", "eth,net,web3,txpool,bor", \
>   "--ws.rpcprefix=/", \
>   "--ws.origins=*", \
>   "--bor.heimdall=http://heimdallr:1317", \
>   "--networkid", "137", \
>   "--snapshot=false", \
>   "--bootnodes", \
>   "enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303"]
> ```

It can be reslove  with  `--snapshot=false`  on my nodes. You can go to discord for help

**Comment by 0xKrishna** [comment]
Don't use now, It was a temp fix branch.
