### ISSUE TITLE
v0.2.14 Bor stop sync and stucked

### ISSUE THREAD

**Issue by joslee7410** [maticnetwork/bor#351]
#### System information

Geth version: `v0.2.14`
OS & Version: Linux(Ubuntu 18)

Bor block height stop sync and stuck at `0x189d9bf` which is `25811391` at decimal.

Anyone met this problem? Please assist me, thank you so much.

**Comment by masayil** [comment]
> #### System information
> Geth version: `v0.2.14` OS & Version: Linux(Ubuntu 18)
> 
> Bor block height stop sync and stuck at `0x189d9bf` which is `25811391` at decimal.
> 
> Anyone met this problem? Please assist me, thank you so much.

https://forum.polygon.technology/t/temporary-bor-hot-fix-v0-2-14-tmp-span-hotfix/2354

**Comment by joslee7410** [comment]
> > #### System information
> > Geth version: `v0.2.14` OS & Version: Linux(Ubuntu 18)
> > Bor block height stop sync and stuck at `0x189d9bf` which is `25811391` at decimal.
> > Anyone met this problem? Please assist me, thank you so much.
> 
> https://forum.polygon.technology/t/temporary-bor-hot-fix-v0-2-14-tmp-span-hotfix/2354

Thank you Sir, you solved my problem!
