### ISSUE TITLE
My rpc node can't sync the block height.

### ISSUE THREAD

**Issue by daichuanliang** [maticnetwork/bor#352]
#### System information

Geth version: v0.2.14-tmp-span-hotfix
OS & Version: Linuc
Commit hash : (if `develop`)

My server is in Japan.
I use new bor version v0.2.14-tmp-span-hotfix to fix polygon stop producing block problem, but  the block height I go always 0.

#### Logs
WARN [03-12|03:17:03.098] Served eth_chainId                       conn=127.0.0.1:44300 reqid=45     t="88.981µs"  err="chain not synced beyond EIP-155 replay-protection fork block"
WARN [03-12|03:17:03.390] Served eth_chainId                       conn=127.0.0.1:44318 reqid=48     t="62.437µs"  err="chain not synced beyond EIP-155 replay-protection fork block"
WARN [03-12|03:17:05.104] Served eth_chainId                       conn=127.0.0.1:44324 reqid=197940 t="65.698µs"  err="chain not synced beyond EIP-155 replay-protection fork block"
INFO [03-12|03:17:05.304] Looking for peers                        peercount=1 tried=101 static=0
WARN [03-12|03:17:07.167] Served miner_setEtherbase                conn=127.0.0.1:44336 reqid=1      t="33.94µs"   err="the method miner_setEtherbase does not exist/is not available"
WARN [03-12|03:17:07.895] Served miner_start                       conn=127.0.0.1:44338 reqid=1      t="29.9µs"    err="the method miner_start does not exist/is not available"
WARN [03-12|03:17:08.731] Served miner_start                       conn=127.0.0.1:44348 reqid=1      t="29.673µs"  err="the method miner_start does not exist/is not available"
WARN [03-12|03:17:09.101] Served eth_chainId                       conn=127.0.0.1:44352 reqid=197943 t="64.774µs"  err="chain not synced beyond EIP-155 replay-protection fork block"
WARN [03-12|03:17:09.569] Served miner_start                       conn=127.0.0.1:44356 reqid=1      t="30.907µs"  err="the method miner_start does not exist/is not available"

**Comment by daichuanliang** [comment]
My server is in Japan.

**Comment by 0xalmanac** [comment]
Honestly, I gave up on Polygon, you should consider that

**Comment by 0xKrishna** [comment]
Don't use the temp branch, Use 0.2.14 and build from the source, It will work.
