### ISSUE TITLE
My node is behind by 100 blocks from yesterday

### ISSUE THREAD

**Issue by slashramin** [maticnetwork/bor#353]
Hi 
from yesterday my node is behind by 100 blocks
this node was working fine for 5 month 
any ideas how to solve this?

**Comment by Fortunate25** [comment]
<!Doctype>

**Comment by 0xKrishna** [comment]
Can you please connect to ipc and send us response of `eth.syncing` ?

**Comment by slashramin** [comment]
> Can you please connect to ipc and send us response of `eth.syncing` ?
HI Thanks for your reply
it done now by rolling back with :
`debug.setHead("0x........")`
