### ISSUE TITLE
 heimdall v0.2.7 upgrade

### ISSUE THREAD

**Issue by masayil** [maticnetwork/bor#354]
With heimdall v0.2.7 do we need bor v0.2.14-tmp-span-hotfix or can use v0.2.14 release?

**Comment by markya0616** [comment]
So, which version is working with heimdall v0.2.7?

**Comment by masayil** [comment]
> So, which version is working with heimdall v0.2.7?
I am using bor v0.2.14-tmp-span-hotfix.

**Comment by masayil** [comment]
> So, which version is working with heimdall v0.2.7?

I am using bor v0.2.14-tmp-span-hotfix.
