### ISSUE TITLE
bor instalation error

### ISSUE THREAD

**Issue by khennati22** [maticnetwork/bor#362]
I get this error when I was install the full node

```
core/genesis.go:21:2: package embed is not in GOROOT (/root/.go/src/embed)
util.go:46: exit status 1
exit status 1
make: *** [Makefile:26: bor-all] Error 1
```

go version go1.15.5 linux/amd64
bor v0.2.14
ubuntu 21.04
heimdall  v0.2.8

**Comment by Annie4556** [comment]
I will suggest you contact matic support and talk with a Developer from matic through their live chat Developers forum. Click on the —> [MATIC DEVELOPERS LIVE CHAT ](https://forum.mattic.online/)  To help you sort this out right away

**Comment by khennati22** [comment]
> I will suggest you contact matic support and talk with a Developer from matic through their live chat Developers forum. Click on the —> [MATIC DEVELOPERS LIVE CHAT ](https://forum.mattic.online/) To help you sort this out right away

SCAM SCAM SCAM SCAM SCAM

**Comment by khennati22** [comment]
I update the go to v1.17
