### ISSUE TITLE
can not connect the bootstrap node when started heimdalld

### ISSUE THREAD

**Issue by liu316484231** [maticnetwork/bor#363]
output info:
Mar 24 10:20:02 Ubuntu-2004-focal-64-minimal heimdalld[107475]: E[2022-03-24|10:20:02.902] Stopping peer for error                      module=p2p peer="Peer{MConn{44.232.55.71:26656} 4fb1bc820088764a564d4f66bba1963d47d82329 out}" err=EOF

ping to the nodes ip also failed, the bootstrap node is given in the full node set up docs..
my server located in Euro, any suggestions

**Comment by temaniarpit27** [comment]
Please check the docs with the latest seeds and reopen if you are facing this issue again
