### ISSUE TITLE
eth_getTransactionReceipt is broken

### ISSUE THREAD

**Issue by jessielesbian** [maticnetwork/bor#366]
My server: {"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x649fdc898f955507d01f90e0826796fa663888c69dac776ccfbd4508436a3835"],"id":1}

polygon-rpc.com: {"jsonrpc":"2.0","id":1,"result":null}

Moralis speedy node: {"jsonrpc":"2.0","id":1,"result":null}

Transaction is confirmed hours before the request. [Proof Of Confirmation](https://polygonscan.com/tx/0x649fdc898f955507d01f90e0826796fa663888c69dac776ccfbd4508436a3835)

Pls fix fast, cause the Jessie Lesbian Cryptocurrency Exchange is unable to receive Polygon token deposits until this is fixed

**Comment by QEDK** [comment]
> My server: {"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x649fdc898f955507d01f90e0826796fa663888c69dac776ccfbd4508436a3835"],"id":1}
> 
> polygon-rpc.com: {"jsonrpc":"2.0","id":1,"result":null}
> 
> Moralis speedy node: {"jsonrpc":"2.0","id":1,"result":null}
> 
> Transaction is confirmed hours before the request. [Proof Of Confirmation](https://polygonscan.com/tx/0x649fdc898f955507d01f90e0826796fa663888c69dac776ccfbd4508436a3835)
> 
> Pls fix fast, cause the Jessie Lesbian Cryptocurrency Exchange is unable to receive Polygon token deposits until this is fixed

Seems to work fine on the aggregator, it's probably just an unhealthy node, feel free to re-open if this persists.
