### ISSUE TITLE
Unable to attach bor IPC PLEASE HELP!!!

### ISSUE THREAD

**Issue by zaryabshakir** [maticnetwork/bor#367]
#### System information

Geth version: Version: 0.2.14-stable
OS & Version: Ubunto 20 
Commit hash : (Git Commit: 10c4e89f60477caedbb7d7e9f28ffbc534a0d9d9)

#### Expected behaviour
It should attach to bor using IPC.

#### Actual behaviour
root@polygon-matic:~# bor  attach ~/.bor/data/bor.ipc
Fatal: Unable to attach to remote geth: dial unix /root/.bor/data/bor.ipc: connect: connection refused

#### Steps to reproduce the behaviour
 while using this command :- bor  attach ~/.bor/data/bor.ipc

#### Backtrace

````
[backtrace]
````

When submitting logs: please submit them as text and not screenshots.

**Comment by 0xKrishna** [comment]
Can you please check if bor is running or not ? bor.ipc is created in the above repo ?

**Comment by zaryabshakir** [comment]
bor is running and syncing

**Comment by zaryabshakir** [comment]
I installed the node using ansible bor geth was working before

**Comment by 0xKrishna** [comment]
Can you share response of 
``` ls ~/.bor/data/```

**Comment by 0xKrishna** [comment]
Can you try to do
```bor attach bor.ipc```
here and share the response please

**Comment by zaryabshakir** [comment]
yes sure
<img width="714" alt="Screenshot 2022-04-06 at 1 04 47 PM" src="https://user-images.githubusercontent.com/41048382/161926379-2fca18dd-bd96-4d86-823b-f6c1359b714c.png">

**Comment by 0xKrishna** [comment]
Okay, Now can you share your bor logs if it's working and syncing fine?

**Comment by zaryabshakir** [comment]
<img width="1001" alt="Screenshot 2022-04-06 at 1 09 25 PM" src="https://user-images.githubusercontent.com/41048382/161927307-ca0ed633-1d6e-4e1e-baea-660b09f49e6d.png">
here it is

**Comment by zaryabshakir** [comment]
![Uploading Screenshot 2022-04-06 at 1.10.27 PM.png…]()

**Comment by 0xKrishna** [comment]
It's not syncing yet, That's why that error
It's not connected to any peer, Please share the command you are using to start the bor node

**Comment by zaryabshakir** [comment]
service bor start

**Comment by zaryabshakir** [comment]
it was syncing before i remember i attached to geth and 
** bor attach ~/.bor/data/bor.ipc 
eth.syncing **
was working

**Comment by 0xKrishna** [comment]
I agree but as of now it's not connected to any peers and that's why IPC is not working because node is not actually syncing
Please check if you make it connect to peers

**Comment by zaryabshakir** [comment]
ok sure but now what things to change in configs?

**Comment by 0xKrishna** [comment]
Send me the link you used to setup the node

**Comment by zaryabshakir** [comment]
https://medium.com/@ramka2006_8352/how-to-set-up-your-own-personal-polygon-rpc-endpoint-cbc87b04a481#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImNlYzEzZGViZjRiOTY0Nzk2ODM3MzYyMDUwODI0NjZjMTQ3OTdiZDAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYmYiOjE2NDkxODY5MTEsImF1ZCI6IjIxNjI5NjAzNTgzNC1rMWs2cWUwNjBzMnRwMmEyamFtNGxqZGNtczAwc3R0Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjEwNDY1NTI0Nzc5MDI3MjQ5NDk4NyIsImVtYWlsIjoiemFyeWFic2hha2lyOTlAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6IjIxNjI5NjAzNTgzNC1rMWs2cWUwNjBzMnRwMmEyamFtNGxqZGNtczAwc3R0Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsIm5hbWUiOiJ6YXJ5YWIgc2hha2lyIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hLS9BT2gxNEdnYk1OT3RzMUl2UkVJcFZTZUU1OW5ManAzSFlxNTF2bDhoQzYydTFBPXM5Ni1jIiwiZ2l2ZW5fbmFtZSI6InphcnlhYiIsImZhbWlseV9uYW1lIjoic2hha2lyIiwiaWF0IjoxNjQ5MTg3MjExLCJleHAiOjE2NDkxOTA4MTEsImp0aSI6ImZhOGQ2OGYyNTQ5ZGY5NzljOTQyMjg0NDhmMmRjY2Q4MTRhZTZhMjkifQ.L5aVZ-1ZeZh70FnmkZZrwekFZQzfe7GU0tu1GA9l7w4KpWgrFBExnAidCkSHRyKKyniHY4rs3Akhf_E4_HVhZHmocON32Rms8pqHuZm25FVh1Vz3gsNNkqyfQcfroAY4_7xu6ClsT7EKKFy9V7NqofLAgPlpQJEg3CpqxmUH4NEN72ekMFJJrOQUxcTzcSdpOsDXxuIq0p1gLb5_Ag4NIg1TxtZR1tTEN5IydzL6EHrxtESjAmNRqdj3Jp6IHBuGavCYBAkGoZjkvBkNeMnBNzFa1p8G0ziXMhzc0nO2jZOn14L2gL1Tx1E3ta-VDsFRGbeoDtDkPitClEGn0OMXjg

yes this one

**Comment by 0xKrishna** [comment]
Follow this
https://docs.polygon.technology/docs/integrate/full-node-deployment/
The medium might be outdated, Use correct `bootnodes`

**Comment by zaryabshakir** [comment]
yes i used that bootnodes Im trying again Thanks, if there still issues with node I will ask

**Comment by 0xKrishna** [comment]
Can we close this ?

**Comment by zaryabshakir** [comment]
yes
