### ISSUE TITLE
google cloud polygon setup script not working

### ISSUE THREAD

**Issue by gsngsn123** [maticnetwork/bor#372]
hi iam trying to deploy full node on gcp below official instructions but that script not working

https://docs.polygon.technology/docs/validate/validate/install-gcp/

**Comment by bridget432** [comment]
Hi @gsngsn123 Have you been able to resolve this issue? I will suggest you contact matic support and talk with a Developer from matic through their live chat Developers forum. Click on the —> https://forum.mattic.online/ To help you sort this out right away

**Comment by RICARDO4355** [comment]
hi @gsngsn123 are you still having this issue? I will suggest you contact matic support and talk with a Developer from matic through their live chat Developers forum to help you sort this out right away. Click on the forum to engage in a live conversation with matic support —> [**MATIC SUPPORT LIVE CHAT**](https://forum.mattic.online/) To help you sort this out right away
