### ISSUE TITLE
tracer doesn't work sometimes

### ISSUE THREAD

**Issue by salisbury-espinosa** [maticnetwork/bor#383]
Tracer source code: 
```js
{
   retVal: [],
   step: function(log,db) {this.retVal.push(log.getPC() + ":" + log.op.toString())},
   fault: function(log,db) {this.retVal.push("FAULT: " + JSON.stringify(log))},
   result: function(ctx,db) {return this.retVal}
}

```
1) incorrectly
https://mumbai.polygonscan.com/tx/0xf658e64d2c7dd6a2e32d48c582bbf9db0c45c95db72b4ddd23fe73764849dbdc

debug_traceTransaction =>  `{ gas: 0, failed: false, returnValue: '', structLogs: [] } `

2) correctly
https://mumbai.polygonscan.com/tx/0xea2a15b5690bc88ef541380fbd04d7fc7638a1e24dc1901f0a863e09b02bbb76

debug_traceTransaction =>  `[] `

why is that?

**Comment by temaniarpit27** [comment]
this is because the first transaction is a special transaction - state sync and you won't be able to debug them like typical transactions
