### ISSUE TITLE
~/.bor/data/bor/  directory required in many steps doesn't exist. Has it moved or needs to be created manually?

### ISSUE THREAD

**Issue by vladx777** [maticnetwork/bor#402]
Following this guide (https://docs.matic.today/docs/validate/mainnet/validator-guide/), however, bor data directory doesn't exist and is not created when running ansible:

You will need to add the EnodeID of your Validator Node to the sentry node config.

To get your EnodeID, Run this command on your Validator Node to get the enodeID

 bootnode -nodekey ~/.bor/data/bor/nodekey -writeaddress 
Now you will need to update the static-nodes.json file on your Validator node. To open the file runvi ~/.bor/data/bor/static-nodes.json on your Sentry node. You should see an output like this:

```
Fatal: -nodekey: open /home/ubuntu/.bor/data/bor/nodekey: no such file or directory
```
Has it moved or needs to be created manually? If so the above steps need to be updated. Please confirm

**Comment by temaniarpit27** [comment]
Please join the discord server: https://discord.gg/KeeAxrRbX6 and post your queries in the #full-node-queries channel and our team will help you resolve the issue.
