### ISSUE TITLE
The total number of transactions obtained by graphql is inconsistent with the eth_getBlockByNumber of RPC

### ISSUE THREAD

**Issue by tangbinyeer** [maticnetwork/bor#408]
#### System information
Bor version: 0.2.14-stable
OS & Version: Linux

#### Expected behaviour
The number of transactions is the same

#### Actual behaviour
block: 24800000
eth_getBlockByNumber get 136
graphql get 135, tx: 0x725e0be909539e0aaa51c69ec3cfb7dcc7286bcad7accafcdf2ea8a449319243 is missing

graphql_sql = """
{
  block(number:"24800000"){
    difficulty
    extraData
    gasLimit
    gasUsed
    hash
    miner{
      address
    }
    mixHash
    nonce
    number
    parent{
      hash
    }
    receiptsRoot
	stateRoot
    timestamp
    totalDifficulty
    uncles : ommers{
      hash
    }
    transactions {
      createdContract{
        address
      }
      index
      status
      gasUsed
      gasPrice
      gas
      cumulativeGasUsed
      hash
      status
	  inputData
      nonce
      value
      from{
        address
      }
      to{
        address
      }
      logs{
        account{
          address
        }
        topics
       	data
        index
      }
    }
    stateRoot
    transactionsRoot
  }
}
"""

**Comment by 0xKrishna** [comment]
How is this related to bor code ? I think this space is to raise issues with bor code and not graphql.
Closing for now, Re-open with more details if you think this is still related to bor code.
