### ISSUE TITLE
Transaction ID of Sync-State does not match Keccak-256(RLP(nonce,gasPrice,gasLimit,to,value,data,v,r,s)

### ISSUE THREAD

**Issue by zimbabao** [maticnetwork/bor#411]
Polygon have special “Sync-State” transactions added to the blocks https://polygonscan.com/address/0x0000000000000000000000000000000000000000 .
Transaction hash returned by eth_getBlockByNumber does not match Keccak-256(RLP(nonce,gasPrice,gasLimit,to,value,data,v,r,s).

Any of you have any insight on this?.

**Comment by 0xKrishna** [comment]
because we don't do it like that
Refer here for more info, We have a bor specific way to generate txnHash for state-syncs
https://github.com/maticnetwork/bor/blob/master/core/rawdb/bor_receipt.go#L208
