### ISSUE TITLE
Debug callTracer incorrect output, but only sometimes

### ISSUE THREAD

**Issue by quickchase** [maticnetwork/bor#413]
#### System information

Geth version: `bor/v0.2.14-stable-10c4e89f/linux-amd64/go1.17`
OS & Version: `Ubuntu 20.04.3`
Commit hash : (if `develop`)

#### Expected behaviour
There should be only 2 transactions that are reverted in the results

#### Actual behaviour
Sometimes there are 3 transaction that are reverted in the results

#### Steps to reproduce the behaviour
```
DATA='{
    "jsonrpc": "2.0",
    "method": "debug_traceBlockByHash",
    "params": ["0x988901bd289a103dfb34694019d8335007e4bba3f0ceb27cfd1f8cdf366ce52b", {"tracer":"callTracer", "timeout": "300s"}],
    "id": 0
}'

curl -s -H 'Content-Type: application/json' -d $DATA "http://localhost:8545" | jq . > ./output.json
grep revert output.json | wc -l
```

The output is usually 2 but sometimes it's 3. I have multiple `bor` archive nodes and they all behave this same way. You may have to place the node under load to produce the result of 3, I'm not sure. It doesn't make a lot of sense but I can definitely reproduce it by just running the call a bunch of times.

**Comment by MysticRyuujin** [comment]
Possible it's related to this

https://github.com/ethereum/go-ethereum/issues/23205?

**Comment by temaniarpit27** [comment]
Please use the latest bor version.
Closing this for now.
Reopen if required
