### ISSUE TITLE
bor highest blocks are not syncing

### ISSUE THREAD

**Issue by pamarthisai** [maticnetwork/bor#434]
> eth.syncing
{
  currentBlock: 29596160,
  highestBlock: 29756043,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 29593586
}
> eth.syncing
{
  currentBlock: 29596165,
  highestBlock: 29756043,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 29593586
}
> eth.syncing
{
  currentBlock: 29596173,
  highestBlock: 29756043,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 29593586
}
> eth.syncing
{
  currentBlock: 29596180,
  highestBlock: 29756043,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 29593586
}
> eth.syncing
{
  currentBlock: 29596189,
  highestBlock: 29756043,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 29593586
}
> eth.syncing
{
  currentBlock: 29596200,
  highestBlock: 29756043,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 29593586
}
> eth.syncing
{
  currentBlock: 29596638,
  highestBlock: 29756043,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 29593586

**Comment by JekaMas** [comment]
I am not sure, how much time passed between you measurements. Could you give us more data?

In a given data I see that your node syncked blocks from 29596160 to 29596638, which is about 500 blocks.

**Comment by pamarthisai** [comment]
when currentblock reach highest block stop syncing

**Comment by binggao** [comment]
@JekaMas I guess what @pamarthisai is asking is why the highest block never got updated over time. I have the same issue with my bor during syncing (not done yet as of now). It's been a few days the currentBlock keeps growing but highestBlock stays at 29987874 for me. Does this sound correct?
> eth.syncing
{
  currentBlock: 16110566,
  healedBytecodeBytes: 0,
  healedBytecodes: 0,
  healedTrienodeBytes: 0,
  healedTrienodes: 0,
  healingBytecode: 0,
  healingTrienodes: 0,
  highestBlock: 29987874,
  startingBlock: 63,
  syncedAccountBytes: 0,
  syncedAccounts: 0,
  syncedBytecodeBytes: 0,
  syncedBytecodes: 0,
  syncedStorage: 0,
  syncedStorageBytes: 0
}

**Comment by JekaMas** [comment]
@binggao @pamarthisai  If it is like that that it might be an issue. Could you check how many peers you have?
Do you have a full log file from the node?

**Comment by 0xKrishna** [comment]
Any update @pamarthisai ?
