### ISSUE TITLE
Address is required as argument

### ISSUE THREAD

**Issue by IanMoroney** [maticnetwork/bor#460]
Apologies if this isn't the right place for this issue, but I can't get bor to start.

The instructions for fullnode setup [here](https://docs.polygon.technology/docs/develop/network-details/full-node-deployment) just mention adding the bootnodes to the start params, which I did, and then says to just `sudo service bor start`.
When I start bor, it fails:

```
Jul 20 06:59:46 testnetfullnode systemd[1]: Starting bor...
Jul 20 06:59:46 testnetfullnode systemd[1]: Started bor.
Jul 20 06:59:46 testnetfullnode bash[258078]: + '[' -z '' ']'
Jul 20 06:59:46 testnetfullnode bash[258078]: + echo 'Address is required as argument'
Jul 20 06:59:46 testnetfullnode bash[258078]: Address is required as argument
Jul 20 06:59:46 testnetfullnode bash[258078]: + exit 1
Jul 20 06:59:46 testnetfullnode systemd[1]: bor.service: Main process exited, code=exited, status=1/FAILURE
Jul 20 06:59:46 testnetfullnode systemd[1]: bor.service: Failed with result 'exit-code'.
```

I understand that the start script is calling for an `ADDRESS` to be specified, but neither the documentation [here](https://docs.polygon.technology/docs/develop/network-details/full-node-deployment) nor [here](https://docs.polygon.technology/docs/develop/network-details/full-node-binaries/) mention any kind of address that needs to be specified.

The version of bor i'm running is:

```
user@testnetfullnode:~$ bor version
Bor
Version: 0.2.16-stable
Git Commit: f083705e00b6497e575a6e6c800aad661a4a2eca
Architecture: amd64
Go Version: go1.18.1
Operating System: linux
GOPATH=/home/user/go
GOROOT=/home/user/.go
```

And maybe since the documentation was written, something has changed in the requirements to run it, but in any case:

- What address am I meant to be specifying as part of the start?
- Where would I find that address?

Thank you

**Comment by 0xKrishna** [comment]
Please reach out to support team on Discord, This place is for technical issues or any bug in bor code.
