### ISSUE TITLE
bor cannot sync

### ISSUE THREAD

**Issue by jaykeatlas** [maticnetwork/bor#464]
qa

validator bor node logs stopped at here. how fix it

Transaction pool price threshold updated price=30,000,000,000
Jul 22 10:47:46 polygon bash[1138598]: INFO [07-22|10:47:46.942] Etherbase automatically configured       address=0x3036442C95784f9eA52b169575b4b9c07B3D9927
Jul 22 10:47:46 polygon bash[1138598]: ERROR[07-22|10:47:46.942] Failed to prepare header for sealing     err="Signer 0xxxxxxxxxxxx is not a part of the producer set at block 30847749"

**Comment by 0xKrishna** [comment]
Are you trying to mine from non validator node ?
Also this is not a technical error, If you need support then please reach out using discord support team.
