### ISSUE TITLE
bor not work

### ISSUE THREAD

**Issue by brunokelo** [maticnetwork/bor#508]
This should only be used in very rare cases e.g. if you are not 100% sure if something is a bug or asking a question that leads to improving the documentation. 

Hello, I did the installation following the official documentation, (https://docs.polygon.technology/docs/develop/network-details/full-node-binaries)
I downloaded the snapshots, and waited for all blocks to be updated, but when I start bor, nothing happens, the rpc and ws ports do not go up, and there is no error in the log,

+ BOR_DIR=/home/ubuntu/.bor
+ DATA_DIR=/home/ubuntu/.bor/data
+ bor --datadir /home/ubuntu/.bor/data --port 30303 --http --http.addr 0.0.0.0 --http.vhosts * --http.corsdomain * --http.port 8545 --ipcpath /home/ubuntu/.bor/data/bor.ipc --http.api eth,net,web3,txpool,bor --syncmode full --networkid 137 --miner.gaslimit 20000000 --miner.gastarget 20000000 --txpool .nolocals --txpool.accountslots 16 --txpool.globalslots 131072 --txpool.accountqueue 64 --txpool.globalqueue 131072 --txpool.lifetime 1h30m0s --maxpeers 200 --metrics --ws --ws.port 8546 -- ws.addr 0.0.0.0 --ws.origins * --pprof --pprof.port 7071 --pprof.addr 0.0.0.0 --bootnodes enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@ 159.203.9.164:30303
INFO [09-03|13:22:06.721] Starting pprof server addr=http://0.0.0.0:7071/debug/pprof
INFO [09-03|13:22:06.721] Enabling metrics collection
INFO [09-03|13:22:06.722] Maximum peer count ETH=200 LES=0 total=200
INFO [09-03|13:22:06.722] Smartcard socket not found, disabling err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [09-03|13:22:06.722] Found deprecated node list file /home/ubuntu/.bor/data/bor/static-nodes.json, please use the TOML config file instead.
ERROR[09-03|13:22:06.722] Node URL <replace with enode://validator_machine_enodeID@validator_machine_ip:30303>: missing 'enr:' prefix for base64-encoded record
 
ERROR[09-03|13:22:06.722] Node URL <replace with enode://other_public_machine_enode@sentry_machine_ip:30303>: missing 'enr:' prefix for base64-encoded record
 
WARN [09-03|13:22:06.722] The generic --miner.gastarget flag is deprecated and will be removed in the future!
INFO [09-03|13:22:06.723] Set global gas cap cap=50,000,000
INFO [09-03|13:22:06.723] Allocated trie memory caches clean=154.00MiB dirty=256.00MiB
INFO [09-03|13:22:06.723] Allocated cache and file handles database=/home/ubuntu/.bor/data/bor/chaindata cache=512.00MiB handles=524,288

can someone help me? thank you

**Comment by temaniarpit27** [comment]
Hey
Can you send more logs?
What happens after these logs? Is it stuck or proceeds with an error

**Comment by 0xKrishna** [comment]
@brunokelo Any update ?

**Comment by brunokelo** [comment]
hello I ended up deleting the chaindata and completely synchronizing it again, with that the problem was solved.

thanks
