### ISSUE TITLE
invalid merkle root

### ISSUE THREAD

**Issue by PPianAIC** [maticnetwork/bor#510]
How to solve this problem

Error: invalid merkle root (remote: 0a8d89ab7ce415e3d3f775aeef3b2cfd7251030765a2f9e3327056efa6f0c491 local: 03302202214e590861586b4b16d4d1859c42c95d2e4746fda9cc46c486c56626)
##############################
 
WARN [09-06|09:41:12.382] Synchronisation failed, dropping peer    peer=f32f29ef5fd8b0e8e3fe8ee7f2ff3ecbecf6bccc3262b3e420c7f76cebb5391e err="retrieved hash chain is invalid: invalid merkle root (remote: 0a8d89ab7ce415e3d3f775aeef3b2cfd7251030765a2f9e3327056efa6f0c491 local: 03302202214e590861586b4b16d4d1859c42c95d2e4746fda9cc46c486c56626)"

this is heimdall/bor version
[root@ip-172-31-19-169 polygon-1]# heimdalld version
0.2.11
[root@ip-172-31-19-169 polygon-1]# bor version
Bor
Version: 0.2.16-stable
Architecture: arm64
Go Version: go1.18.3
Operating System: linux
GOPATH=
GOROOT=go

**Comment by PPianAIC** [comment]
Now, I have this problem.
########## BAD BLOCK #########
Chain config: {ChainID: 137 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Arrow Glacier: <nil>, MergeFork: <nil>, Terminal TD: <nil>, Engine: bor}

Number: 32377427
Hash: 0x50ab2335e81345881c8a5c332a51f79ac60e7c12e845d2bd711b5645218fae1d

Error: could not apply tx 0 [0x7da3e170ef92f9fc0d7e38315472759896d69f5f9942271d7179f90283976c77]: nonce too high: address 0x000002Cba8DfB0a86A47a415592835E17fac080a, tx: 136441 state: 0
##############################
 
WARN [09-07|07:36:55.801] Synchronisation failed, dropping peer    peer=dd88a2c91ef929fd681193eabbb8d658726578e0dd4391af634c070dbd046c1e err="retrieved hash chain is invalid: could not apply tx 0 [0x7da3e170ef92f9fc0d7e38315472759896d69f5f9942271d7179f90283976c77]: nonce too high: address 0x000002Cba8DfB0a86A47a415592835E17fac080a, tx: 136441 state: 0"

**Comment by danielkokobt** [comment]
https://docs.polygon.technology/docs/maintain/validate/faq/known-issues/
https://github.com/maticnetwork/bor/issues/374
https://github.com/maticnetwork/bor/issues/357
https://github.com/maticnetwork/bor/issues/356
https://github.com/maticnetwork/bor/issues/340

**Comment by PPianAIC** [comment]
I used them of https://docs.polygon.technology/docs/maintain/validate/faq/known-issues/, restart is invalid. 
The bad block is 32485184, I set debug.setHead("0x1efaaa0"), then I have this problem of "Error: could not apply tx 0 "

**Comment by PPianAIC** [comment]
@danielkokobt 
I have another question，I saw someone say that start your bor after heimdalld is completely synced. Must I do this? 
Now my heimdalld is running. I think it will take a long time to completely sync. Or I can start bor now.
I[2022-09-08|08:48:37.772] Committed state                              module=state height=10075779 txs=0 appHash=2059D43ED77851F54BDDDDB6429E0087B6D7D1E5C8742BA55857ED1AC9579B4C
I[2022-09-08|08:48:37.877] Executed block                               module=state height=10075780 validTxs=0 invalidTxs=0
I[2022-09-08|08:48:37.900] Committed state                              module=state height=10075780 txs=0 appHash=C6FB450F9E6BB5679701F79081899B1D6CBF60281EEEC3755034BEAB124456F2
I[2022-09-08|08:48:37.987] Executed block                               module=state height=10075781 validTxs=0 invalidTxs=0
I[2022-09-08|08:48:38.010] Committed state                              module=state height=10075781 txs=0 appHash=C6FB450F9E6BB5679701F79081899B1D6CBF60281EEEC3755034BEAB124456F2
I[2022-09-08|08:48:38.113] Executed block                               module=state height=10075782 validTxs=0 invalidTxs=0
I[2022-09-08|08:48:38.131] Committed state                              module=state height=10075782 txs=0 appHash=C6FB450F9E6BB5679701F79081899B1D6CBF60281EEEC3755034BEAB124456F2
I[2022-09-08|08:48:38.200] Executed block                               module=state height=10075783 validTxs=0 invalidTxs=0
I[2022-09-08|08:48:38.224] Committed state                              module=state height=10075783 txs=0 appHash=C6FB450F9E6BB5679701F79081899B1D6CBF60281EEEC3755034BEAB124456F2
I[2022-09-08|08:48:38.301] Executed block                               module=state height=10075784 validTxs=0 invalidTxs=0

**Comment by PPianAIC** [comment]
I tried again n times in the standard way, and just succeeded. It's so sci-fi
