### ISSUE TITLE
bor ignores kill signal when trying to reach heimdall

### ISSUE THREAD

**Issue by danielkokobt** [maticnetwork/bor#514]
#### **System information**

Bor client version: v0.2.16

Heimdall client version: any version

OS & Version: Linux

Environment: All environments

Type of node: Validator

Additional Information: 

#### **Overview of the problem**

Normally while bor is running it can be stopped with `sudo service bor stop`, which is equivalent to `pkill -INT bor`.

However, while bor is trying to reach heimdall using `HeimdallClient.FetchWithRetry()` it does not respond to the SIGINT signal. It continues to display this message without acknowledging that it should shut down.
```
INFO [09-07|14:55:41.679] Retrying again in 5 seconds to fetch data from Heimdall path=clerk/event-record/list attempt=238
```

#### **Reproduction Steps**

1. Start bor with an invalid heimdall URL, wait for it to start displaying the "Retrying again in 5 seconds" message
2. Try to shut down bor and observe that it does not respond (it does not handle the SIGINT signal)

#### **Logs / Traces / Output / Error Messages**
 
described in overview

**Additional Information**

**Comment by JekaMas** [comment]
Thank you for the report!

Could you try the same scenario on develop branch, which is bor 0.3.0?

**Comment by 0xKrishna** [comment]
Any update on this @danielkokobt ?

**Comment by temaniarpit27** [comment]
Closing this as no update.
Please reopen if required or contact official discord for more support
