### ISSUE TITLE
eth_getLogs doesn't return the StateSync transaction's event log

### ISSUE THREAD

**Issue by jsvisa** [maticnetwork/bor#519]
Our support team has aggregated some common issues and their solutions from past which are faced while running or interacting with a bor client. In order to prevent redundant efforts, we would encourage you to have a look at the [FAQ's section](https://docs.polygon.technology/docs/faq/technical-faqs) of our documentation mentioning the same, before filing an issue here. In case of additional support, you can also join our [discord](https://discord.com/invite/zdwkdvMNY2) server

#### **System information**

Bor client version: [e.g. v0.2.16] 

```
v0.2.17
```

Heimdall client version: [e.g. v0.2.10] 

```
0.2.11
```

OS & Version: Windows / Linux / OSX

Linux

Environment: Polygon Mainnet / Polygon Mumbai / Devnet

Polygon Mainnet

Type of node: Validator / Sentry / Archive

Archive

Additional Information: 

#### **Overview of the problem**

Please describe the issue you experiencing.

the `eth_getLogs` RPC may miss some event logs

#### **Reproduction Steps**

Please mention the steps required to reproduce this issue.

I'd request the logs for [#block 33304320](https://polygonscan.com/block/33304320) with RPC as below:

```
curl http://127.0.0.1:8545 -d
'
{
    "jsonrpc":"2.0",
    "method":"eth_getLogs",
    "params":[{
        "fromBlock": "0x1fc2f00",
        "toBlock": "0x1fc2f00"
    }],
    "id":74
}
'
```

The response as following: [block-0x1fc2f00-logs.json.zip](https://github.com/maticnetwork/bor/files/9609513/block-0x1fc2f00-logs.json.zip)

We can't find [tx 0xf711e3462ad4dbb5f246d3b312e06315960df83c528d89de534c87af9f3be9b1](https://polygonscan.com/tx/0xf711e3462ad4dbb5f246d3b312e06315960df83c528d89de534c87af9f3be9b1)'s event logs.

But if I'm using the `eth_getTransactionReceipt`, the event logs appear:

```
In [20]: w3.eth.get_transaction_receipt( '0xf711e3462ad4dbb5f246d3b312e06315960df83c528d89de534c87af9f3be9b1')
Out[20]:
AttributeDict({'blockHash': HexBytes('0xfdf9fb09a098613087bcf823f74358edb7d738f059d8fd01e149e23f5b07000f'),
 'blockNumber': 33304320,
 'contractAddress': None,
 'cumulativeGasUsed': 0,
 'effectiveGasPrice': 0,
 'from': '0x0000000000000000000000000000000000000000',
 'gasUsed': 0,
 'logs': [AttributeDict({'address': '0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619',
   'topics': [HexBytes('0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'),
    HexBytes('0x0000000000000000000000000000000000000000000000000000000000000000'),
    HexBytes('0x0000000000000000000000006c4d8d3638b157303638a01a4c44225fbbd42d24')],
   'data': '0x00000000000000000000000000000000000000000000000000aa87bee5380000',
   'blockNumber': 33304320,
   'transactionHash': HexBytes('0xf711e3462ad4dbb5f246d3b312e06315960df83c528d89de534c87af9f3be9b1'),
   'transactionIndex': 197,
   'blockHash': HexBytes('0xfdf9fb09a098613087bcf823f74358edb7d738f059d8fd01e149e23f5b07000f'),
   'logIndex': 696,
   'removed': False}),
  ...
 // long log
  ...
  AttributeDict({'address': '0x553bC791D746767166fA3888432038193cEED5E2',
   'topics': [HexBytes('0x320958176930804eb66c2343c7343fc0367dc16249590c0f195783bee199d094'),
    HexBytes('0x000000000000000000000000a0a7c283ee9a851d73f877cbd046b77fa0563f60'),
    HexBytes('0x0000000000000000000000000000000000000000000000000000000000000000')],
   'data': '0x00000000000000000000000000000000000000000000000083d7c640aa60600000000000000000000000000000000000000000000000000082c211a687c51fe60000000000000000000000000000000000000000000000000000018355fe1c6b0000000000000000000000000000000000000000000000000000000000000000',
   'blockNumber': 33304320,
   'transactionHash': HexBytes('0xf711e3462ad4dbb5f246d3b312e06315960df83c528d89de534c87af9f3be9b1'),
   'transactionIndex': 197,
   'blockHash': HexBytes('0xfdf9fb09a098613087bcf823f74358edb7d738f059d8fd01e149e23f5b07000f'),
   'logIndex': 711,
   'removed': False})],
 'logsBloom': HexBytes('0x00000000442000080000000080040000000000000000002000000000060000000200000000000002000020101010010000008000000000000000000800200000000000000000400010008008000000800000040000400000000100000000020000000000020000000202000000000800000000000000040000000010000000000400000000000000000000000000008000010010400000000000004000000000020004000000010000000080000000804040004000000008000000000000004080080002000000000000800000000000000000000008800000108002000020000010020000000000000000000000000080000000000000000010040000100808'),
 'status': 1,
 'to': '0x0000000000000000000000000000000000000000',
 'transactionHash': HexBytes('0xf711e3462ad4dbb5f246d3b312e06315960df83c528d89de534c87af9f3be9b1'),
 'transactionIndex': 197,
 }
```

So does there any special concerns about the StateSync Transaction's LogFilter?

**Comment by quickchase** [comment]
Also, if you take this request:
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "eth_getLogs",
  "params": [
    {
      "fromBlock": "0x1FCB880",
      "toBlock": "0x1FCB880",
      "topics": [
        "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
      ]
    }
  ]
}
```
Looking at the logs that it returns, you can see `0x28f5d28babc3a64650745f5b8fa6580f1b1aab3a4f9d84786bd225fa7be852cf` as the final output in the array.

However, if you create an `eth_newFilter` with the same request and then request the logs from the filter, it's missing...

e.g.
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "eth_newFilter",
  "params": [
    {
      "fromBlock": "0x1FCB880",
      "toBlock": "0x1FCB880",
      "topics": [
        "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"
      ]
    }
  ]
}
```
Followed by:
```
{
  "jsonrpc": "2.0",
  "id": 1,
  "method": "eth_getFilterLogs",
  "params": [
    "0xid"
  ]
}
```
It will not return `0x28f5d28babc3a64650745f5b8fa6580f1b1aab3a4f9d84786bd225fa7be852cf`

**Comment by 0xKrishna** [comment]
Do you  have bor logs enabled ?
```--bor.logs``` ?

**Comment by 0xKrishna** [comment]
https://github.com/maticnetwork/bor/blob/develop/eth/filters/api.go#L349

**Comment by quickchase** [comment]
I have bor.logs, not sure about OP

**Comment by 0xKrishna** [comment]
Yeah, I saw the code and creating new filter doesn't have support for bor logs yet.

**Comment by 0xKrishna** [comment]
@jsvisa Can you confirm if you have `--bor.logs` ?

**Comment by jsvisa** [comment]
@0xKrishna Sorry, doesn't set it before. Thanks for your advice, after this flag is enabled, the `eth_getLogs` seems running ok.
