### ISSUE TITLE
Prune issue

### ISSUE THREAD

**Issue by mikhail-khalizev** [maticnetwork/bor#525]
#### **System information**

Bor client version: v0.2.17
Heimdall client version: v0.2.11
OS & Version: Linux + Docker
Environment: Polygon Mainnet
Type of node: Sentry

#### **Overview of the problem**

When I starting prune, error occurs:

```
# bor --config config.toml snapshot prune-state
<...>
ERROR[09-22|12:49:43.904] Failed to prune state                    err="snapshot not old enough yet: need 128 more blocks"
```
#### **Reproduction Steps**

docker-compose file and configs in the attachments: [polygon docker.zip](https://github.com/maticnetwork/bor/files/9625942/polygon.docker.zip)

#### **Logs / Traces / Output / Error Messages**
 
Logs in the attachments: [bor.logs.zip](https://github.com/maticnetwork/bor/files/9626014/bor.logs.zip)

**Comment by Mrpanhart101** [comment]
Talk to Polygon Support on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.

**Comment by mikhail-khalizev** [comment]
Thanks. Is the url correct?
```
# ping forummaticnetwork.org
ping: forummaticnetwork.org: Name or service not known
```

**Comment by Mrpanhart101** [comment]
> Thanks. Is the url correct?
> 
> ```
> # ping forummaticnetwork.org
> ping: forummaticnetwork.org: Name or service not known
> ```

Yes it's correct, use the live chat icon to talk to an agent
