### ISSUE TITLE
Bor stuck at **### Head state missing, repairing** for a long time

### ISSUE THREAD

**Issue by sylviahuang123** [maticnetwork/bor#566]
suddenly, bor didn't work.

here is my heimdalld.log:
```
I[2022-10-20|10:49:07.568] Executed block                               module=state height=11338932 validTxs=0 invalidTxs=0
I[2022-10-20|10:49:07.583] Committed state                              module=state height=11338932 txs=0 appHash=E3C66C4F48694E3A3E7014E3384548CEFA8090D10288EE83EB2C4C7F6D85F458
E[2022-10-20|10:49:12.061] Stopping peer for error                      module=p2p peer="Peer{MConn{47.250.54.10:26656} 7ae8fda8f5eb092050f0e99e7bb80b792c5f4e12 out}" err=EOF
E[2022-10-20|10:49:12.080] Stopping peer for error                      module=p2p peer="Peer{MConn{147.139.208.251:26656} e8f5bd623345177d0e177f13bec1daa67b5462de out}" err=EOF
E[2022-10-20|10:49:12.113] Stopping peer for error                      module=p2p peer="Peer{MConn{149.129.216.188:26656} ba769bfddb45489573f07e311aa742d40163d0e1 out}" err=EOF
E[2022-10-20|10:49:12.337] Stopping peer for error                      module=p2p peer="Peer{MConn{8.211.130.206:26656} 2bafff07b9fc02ab1a92fe6539a8f41a7679076a out}" err=EOF
E[2022-10-20|10:49:12.381] Stopping peer for error                      module=p2p peer="Peer{MConn{47.245.53.139:26656} 6b15e046fd4ef3d82073cf2e46f663a030fdcfd0 out}" err=EOF
E[2022-10-20|10:49:12.503] Stopping peer for error                      module=p2p peer="Peer{MConn{176.9.16.203:26656} 5d835437973a542cc98cf253679ee156df9efcd9 out}" err=EOF
E[2022-10-20|10:49:12.582] Stopping peer for error                      module=p2p peer="Peer{MConn{37.120.245.165:26656} 2d5bfa7d16a26d058344691df21c39067022afa2 out}" err=EOF
E[2022-10-20|10:49:12.665] Stopping peer for error                      module=p2p peer="Peer{MConn{54.211.41.134:26656} f1df2b5ecb85112a91da6d8caa76d9dd22fdd4cf out}" err=EOF
E[2022-10-20|10:49:12.673] Stopping peer for error                      module=p2p peer="Peer{MConn{18.233.245.160:26656} 7984299ef8e129ae84c693b6c27236cc0e900d7d out}" err=EOF
E[2022-10-20|10:49:12.690] Failed Sanity Check! Cant add old address to new bucket module=p2p book=/data/polygon/heimdall/config/addrbook.json ka="&{Addr:3277d77ded24aee8d54112ececfd37af18ecbc08@93.115.28.53:26656 Src:7ae8fda8f5eb092050f0e99e7bb80b792c5f4e12@0.0.0.0:26656 Attempts:9 LastAttempt:2022-09-16 08:19:43.039166555 +0000 UTC m=+3905792.338276089 LastSuccess:2022-07-13 05:36:50.19375599 +0000 UTC BucketType:2 Buckets:[32]}" bucket=51
E[2022-10-20|10:49:12.708] Stopping peer for error                      module=p2p peer="Peer{MConn{35.199.4.13:26656} 2eadba4be3ce47ac8db0a3538cb923b57b41c927 out}" err=EOF
E[2022-10-20|10:49:12.760] Stopping peer for error                      module=p2p peer="Peer{MConn{15.235.14.28:26656} 19d0adc936984d10e97ace0aa8477d8c960ebe32 out}" err=EOF
E[2022-10-20|10:49:12.773] Stopping peer for error                      module=p2p peer="Peer{MConn{192.41.77.211:26656} baaeabfdb0a3a1d528cc116c502d8c5d39b4bb64 out}" err=EOF
E[2022-10-20|10:49:12.814] Stopping peer for error                      module=p2p peer="Peer{MConn{18.197.47.24:26656} 6eaa6013f357e88fa83330df6e94563edc8b87b5 out}" err=EOF
E[2022-10-20|10:49:13.004] Stopping peer for error                      module=p2p peer="Peer{MConn{18.228.98.237:26656} afc41bd37d549186cec915c5a4feb3071871cdc1 out}" err=EOF
E[2022-10-20|10:49:13.006] Stopping peer for error                      module=p2p peer="Peer{MConn{177.71.163.170:26656} 48daf8805cc572ff555889e8e361768542e3314b out}" err=EOF
```
here is my bor.log
```
INFO [10-20|10:43:09.049] Allocated cache and file handles         database=/data/polygon/bor/bor/chaindata cache=512.00MiB handles=51200
INFO [10-20|10:43:27.723] Opened ancient database                  database=/data/polygon/bor/bor/chaindata/ancient readonly=false
INFO [10-20|10:43:27.739] Initialised chain configuration          config="{ChainID: 137 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Arrow Glacier: <nil>, MergeFork: <nil>, Terminal TD: <nil>, Engine: bor}"
INFO [10-20|10:43:47.741] Gasprice oracle is ignoring threshold set threshold=2
INFO [10-20|10:43:47.748] Initialising Ethereum protocol           network=137 dbversion=8
INFO [10-20|10:43:50.263] Loaded most recent local header          number=34,535,308 hash=99f908..e149f6 td=529,651,530 age=22h56m5s
INFO [10-20|10:43:50.264] Loaded most recent local full block      number=34,535,308 hash=99f908..e149f6 td=529,651,530 age=22h56m5s
INFO [10-20|10:43:50.264] Loaded most recent local fast block      number=34,535,308 hash=99f908..e149f6 td=529,651,530 age=22h56m5s
INFO [10-20|10:43:50.271] Loaded last fast-sync pivot marker       number=21,075,478
WARN [10-20|10:43:50.274] Head state missing, repairing            number=34,535,308 hash=99f908..e149f6 snaproot=6e0df3..fe238e
```
I wonder is it normal?  Many thanks.

**Comment by cromaniuc** [comment]
I had the same issue one week ago, after restarting the docker container. 
To fix it I had to :

- resync from latest bor snapshot (you need to delete first `data/bor/chaindata`) 
- added: `docker run ... --restart unless-stopped`. The issue disappeared, but after restart it tries to resync the blocks since one day ago. Very strange behaviour.

**Comment by masayil** [comment]
Whether it is docker or systemd, when we use the stop command, if the process cannot exit within 10 seconds, then they will force kill the process.When bor runs, some data will not be written to disk immediately . They stored in memory.We need to give it enough time to persist this data to disk.The default time of docker and systemd is not enough.   
docker:`docker stop <container id> -t 600`
systemd: add `TimeoutStopSec=600`

**Comment by masayil** [comment]
I'm not sure if you guys have increased this time limit

**Comment by cromaniuc** [comment]
Thanks for your reply, @masayil !
I've tried as suggested (`docker stop polygon-node -t 600`) and this time it looks a bit better since yesterday when it tried to synch like ~12000 blocks. Now it tries to sync ~3000 blocks.
```
> eth.syncing.highestBlock - eth.syncing.currentBlock
3056
```
Then I increased it to `-t 1200` and it's the same behaviour sync ~3000 blocks. Not sure why it goes back to that number.

**Comment by masayil** [comment]
> Thanks for your reply, @masayil ! I've tried as suggested (`docker stop polygon-node -t 600`) and this time it looks a bit better since yesterday when it tried to synch like ~12000 blocks. Now it tries to sync ~3000 blocks.
> 
> ```
> > eth.syncing.highestBlock - eth.syncing.currentBlock
> 3056
> ```
> 
> Then I increased it to `-t 1200` and it's the same behaviour sync ~3000 blocks. Not sure why it goes back to that number.

After stop the node, pls check its logs.
This is my node's log.  When I restart my node , it sync from the latest block
![1666856963868](https://user-images.githubusercontent.com/65291464/198223260-58f64cf1-dc2d-44a4-b09e-582d1af06182.jpg)

**Comment by masayil** [comment]
After stop the node ,pls check the logs.
This is my node log.  When I restart it , it can sync from the latest block.
![image](https://user-images.githubusercontent.com/65291464/198224170-d0231d31-87f2-41a4-a1d6-b24fdfd1308d.png)

![image](https://user-images.githubusercontent.com/65291464/198224136-9907cf6f-89f0-4776-8bf9-9687b4ba23e2.png)

**Comment by cromaniuc** [comment]
These are the logs after stop:
<img width="1260" alt="node logs" src="https://user-images.githubusercontent.com/5749220/198229316-9d8c856b-ec3e-4346-8d46-51073cd9b165.png">
What configuration are you using to start it?

**Comment by masayil** [comment]
> These are the logs after stop: <img alt="node logs" width="1260" src="https://user-images.githubusercontent.com/5749220/198229316-9d8c856b-ec3e-4346-8d46-51073cd9b165.png"> What configuration are you using to start it?

This The log after run `docker stop` .

**Comment by masayil** [comment]
@cromaniuc 
![image](https://user-images.githubusercontent.com/65291464/198232047-3ff82314-cd62-4742-9b5e-1e809c2b3132.png)

**Comment by sylviahuang123** [comment]
> I'm not sure if you guys have increased this time limit

thanks, but I didn't set this field, does it has default?

**Comment by sylviahuang123** [comment]
update something, after repairing finished, bor service came into healing progress, and importing new block, but healing progress cannot be able to catch up the highest block, as a result that blockNumber response always 0. I wonder whether I should re-build the node or keep waiting.

**Comment by masayil** [comment]
10 seconds. keep waiting

**Comment by masayil** [comment]
> > 10 seconds. keep waiting
> 
> sorry, what does `10 seconds` mean? in addition, it can't catch up, even closer, it works if keep waiting?

Whether it is docker or systemd, when we use the stop command, if the process cannot exit within 10 seconds, then they will force kill the process. If the synchronization has not started for a long time, it is recommended to download the snapshot to  re-build the node

**Comment by sylviahuang123** [comment]
> systemd

systemd service, process no exit more, it's running, both healing and new block importing, it's syncing, for now, the issue is the healing process cannot be able to catch up the latest block, the gap roughly 64~130, no bigger, no smaller

**Comment by cromaniuc** [comment]
I think I've found a solution for this. It's mainly related to running Bor within a Docker container, that's why some of us running it as a `systemd` service are not affected.

For example when running Bor as a runit service within the Docker container,  the termination is handled [with SIGTERM](https://github.com/phusion/baseimage-docker#shutting-down-your-process).
Bor [is expecting](https://github.com/maticnetwork/launch/blob/master/mainnet-v1/service.sh#L29) `SIGINT` instead so the fix consists in setting the termination command for the running container as `pkill -2 bor `(pkill for finding the Bor pid, -2 means SIGINT), which is the same way `systemd` would use to stop the execution of the Bor service.

**Comment by 0xKrishna** [comment]
Looking at the above comment, I think this is resolved now.
