### ISSUE TITLE
Is it possible to use geth to do block synchronization with bor?

### ISSUE THREAD

**Issue by clearest555** [maticnetwork/bor#571]
Hi,

I apologize if I am misguided.
Is it possible to use geth to init the genesis block of bor and specify the chiainID =137 of Polygon's mainnet to synchronize the block with bor?
I plan to use the post-merge geth version (1.10).

**Comment by 0xKrishna** [comment]
I don't think this will work as it will not have bor consensus specific changes.
Only setting chainID to 137 is not enough.
