### ISSUE TITLE
Miner Address always remains 0x00000... in blocks data

### ISSUE THREAD

**Issue by Adeel-trimulabs** [maticnetwork/bor#584]
## Description
I have made a fully synced polygon node using binaries (heimdall and bor) and use its RPC point to get blockchain,s data.
Trying to get information about miner of blocks in polygon. For this I use web3 methods. All information about block from get_blockByNumber, displays as expected except the miner address, the miner hash should be "the address of the beneficiary to whom the mining rewards were given" (or the address of the block's validator).
`0x0000000000000000000000000000000000000000`

## Polygon node environment
 - AWS machine with gp3 storage 
- Made fully synced polygon node to use RPC endpoint 
   `bor version: v0.2.16`
     `heimdall version: v0.2.11`
 - Branch that causes issue `master`

## Steps to reproduce
- Called get_BlockByNumber from RPC endpoint
- Got this response for block 
`````
      "hash": "0x8feb2727e5f7a73fb7b810ae56b6cbffb4eb565e81af3e6768fa7023f2d2ff4d",
      "number": 35629163,
      "extraData": "0xd682021083626f7288676f312e31382e31856c696e75780000000000000000002b4fda3d77825b279b4e2f0d5f04b3ea2f922ecbee2e2b166900c275315a4c8865eb3af7e7d2afaf7b0c58684a23ec1e12a6ee1985d5c67630886ef2c09158ae00",
      "ommerHash": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
      "receiptsRoot": "0xd1438a6c9a7604d5d2f567ee22d01789331679761514ae5e95e521e25dfd151a",
      "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
      "difficulty": "0x16",
      "totalDifficulty": "0x21117e41",
      "gasLimit": 30000000,
      "gasUsed": 9852929,
      "stateRoot": "0x6f071ca6aa633481992df60a996a22fdd7afa5ae29ce30e20e9e4c36f125447c",
      "miner": {
        "address": "0x0000000000000000000000000000000000000000",
      }

`````
## Expected behavior
I expect that I got miners address as we can see in [polyscan](https://polygonscan.com/) that they shows validator of blocks.
It should be like 
`miner: [0xec20607aa654d823dd01beb8780a44863c57ed07]` for block number: 35000222
https://polygonscan.com/block/35000222

## Actual behavior
The miner address is always
`miner: 0x0000000000000000000000000000000000000000` hence I am unable to figure out who mined that block.

## Note
I tried to get the miner from https://github.com/ethereum/go-ethereum/issues/17454 by recovering the pubkey from `extra data ` field in the block headers, I noticed that it doesn't match the record of validator from [polyscan](https://polygonscan.com/)

**Comment by 0xKrishna** [comment]
Fixed here https://github.com/maticnetwork/bor/pull/435
Will be available in next release (Dec OR Jan)

Please reopen if this doesn't answer your issue.
