### ISSUE TITLE
No changelogs and incomprehensible commit messages

### ISSUE THREAD

**Issue by kaber2** [maticnetwork/bor#595]
Guys, I was trying to inform myself about the changes in the just released 0.3.0-beta version, just to make sure I can start any necessary work needed to upgrade on my side early. But, no changelog.

No problem I thought, I'll just check the commit history. Which looks like this:
<img width="518" alt="Bildschirmfoto 2022-11-24 um 01 46 43" src="https://user-images.githubusercontent.com/34914579/203670576-59933f40-460d-436f-9ee6-751cd437d86a.png">
<img width="503" alt="Bildschirmfoto 2022-11-24 um 01 46 51" src="https://user-images.githubusercontent.com/34914579/203670578-4a5cbe23-aca4-49e5-b85d-2872e750ca06.png">
<img width="575" alt="Bildschirmfoto 2022-11-24 um 01 47 02" src="https://user-images.githubusercontent.com/34914579/203670579-392b7ce5-6ea8-4c15-af11-5e73cbd7624f.png">

Seriously guys? "Commit", "Revert some changes", "fix", "op" are not commit messages, you might as well leave them completely empty as they add zero value. How about some professionalism, its really not rocket science to write proper commit messages and not running a blockchain with massive amounts of user funds like a student hobby project seems like something that should be done without having to ask for it.

**Comment by ajb** [comment]
Gotta teach da homies about git squash huh

**Comment by ssandeep** [comment]
@kaber2 @ajb , you are right sers - there were a few occasions where git squash was missed. We will ensure the commit messages are properly written and we squash and merge.
