### ISSUE TITLE
Stuck looking for peers

### ISSUE THREAD

**Issue by Detrous** [maticnetwork/bor#602]
Trying to start sentry node according to this guide: https://wiki.polygon.technology/docs/maintain/validate/run-validator-binaries/#configuring-the-bor-service

bootnodes:
`--bootnodes "enode://320553cda00dfc003f499a3ce9598029f364fbb3ed1222fdc20a94d97dcc4d8ba0cd0bfa996579dcc6d17a534741fb0a5da303a90579431259150de66b597251@54.147.31.250:30303"`

It's just stuck looking for peers:
```Nov 28 00:08:51 matic-sentry bash[204722]: INFO [11-28|00:08:51.946] Looking for peers                        peercount=0 tried=1 static=0

Nov 28 00:38:17 matic-sentry bash[204722]: INFO [11-28|00:38:17.261] Looking for peers                        peercount=0 tried=0 static=0

Nov 28 00:38:52 matic-sentry bash[204722]: INFO [11-28|00:38:52.262] Looking for peers                        peercount=0 tried=1 static=0

Nov 28 01:08:17 matic-sentry bash[204722]: INFO [11-28|01:08:17.565] Looking for peers                        peercount=0 tried=0 static=0

Nov 28 01:08:52 matic-sentry bash[204722]: INFO [11-28|01:08:52.566] Looking for peers                        peercount=0 tried=1 static=0```

**Comment by 0xKrishna** [comment]
@sunilraj228

**Comment by sunilraj228** [comment]
Hi @Detrous 

Thank you for reaching out to us.

Please help us with the following details for better analysis

1. Is your Port 30303 kept open?
2. Could you please share your start.sh file?
3. Also the Bor & Heimdall versions of the node.

Regards,
Sunil Raj Kumar K
Validator Engagement Specialist

**Comment by Detrous** [comment]
After updating to version v0.3.0-beta it works like a charm.
