### ISSUE TITLE
Cannot start new bor client v0.3.0 with datadir.ancient flag

### ISSUE THREAD

**Issue by keksa905** [maticnetwork/bor#605]
**System information**

Bor client version:  v0.3.0

Heimdall client version: v0.3.0

OS & Version:  Linux 

It seems that new version of Bor client is not supporting flag for changing default directory for ancient db (-datadir.ancient), but in my setting it is in the different directory. But it cannot be started without this flag neither. See screenshots with error messages below. 
![polygon-ancient](https://user-images.githubusercontent.com/58939444/204512881-c9281eef-b4b3-4742-a6d9-d9590ba47315.png)
![polygon_ancient2](https://user-images.githubusercontent.com/58939444/204512924-8f416b6c-b878-4f4c-a4e0-00ef17d5ad15.png)

**Comment by pratikpatil024** [comment]
Hi @keksa905, could you please share the steps that lead to this error?
I believe that you are using `start.sh` for running bor. It would be great if you could share that file as well.

**Comment by keksa905** [comment]
> Hi @keksa905, could you please share the steps that lead to this error? I believe that you are using `start.sh` for running bor. It would be great if you could share that file as well.

I am running full node, but lately it started to fall behind most recent data so i wanted to updated Bor and Heimdall to the latest version. So i stopped nodes, updated clients and updated starting scripts according to changelog. But in my setting, ancient DB is separated from the rest.  And these errors occurred when i 
[start_new.txt](https://github.com/maticnetwork/bor/files/10154212/start_new.txt)
wanted to restart Bor node with this setting.  And yes I am using start.sh and I am attaching it here.
[start_new.txt](https://github.com/maticnetwork/bor/files/10154215/start_new.txt)

**Comment by keksa905** [comment]
Thanks @pratikpatil024. It is working now :).
