### ISSUE TITLE
Reason transactions only executed n+2 at best, how can one tweak one's bor node?

### ISSUE THREAD

**Issue by algotradingstrategies** [maticnetwork/bor#608]
Hi, was this isssue (https://github.com/maticnetwork/bor/issues/141) resolved/explained? What is the reason transactions are never excecuted in the next block (n+2 at best, often also only n+3)?

How can I tweak my bor node to speed up the propagation of my transactions to the network?

_Originally posted by @algotradingstrategies in https://github.com/maticnetwork/bor/issues/141

**Comment by 0xKrishna** [comment]
Reopened the original thread
