### ISSUE TITLE
Changelog `--pprof.addr` and `--pprof.port` to `--grpc.addr` seems weird

### ISSUE THREAD

**Issue by maoueh** [maticnetwork/bor#615]
I fail to see the logical rename to this new flag and I'm wondering if it's not an error in the changelog entries as `pprof` and `grpc` have no real relation.

**Comment by manav2401** [comment]
Hey @maoueh, the new-cli which is introduced in the new release uses GRPC to communicate internally with the node. We've added the pprof support as a subcommand to bor (see [this](https://github.com/maticnetwork/bor/blob/develop/docs/cli/debug_pprof.md)). So, technically you don't need any additional flag for pprof as it’s already embedded. Moreover, the other services which pprof used to provide earlier (like telemetry) has been moved to separate flags. Hope this helps.

**Comment by cffls** [comment]
Hi @maoueh , thanks for the feedback. 

The old command of `go tool pprof -http : http://<endpoint>/debug/pprof/goroutine` will not work. An alternative solution in v0.3.0 is to run pprof with two steps:

```shell
bor debug pprof -address 127.0.0.1:3131 -seconds 5 -output pprof_output
go tool pprof -http 0.0.0.0:3000 pprof_output/<folder_created_by_the_command_above>/cpu.prof
```

Do you think this solution suffice your use case?

**Comment by maoueh** [comment]
How is this going to work to investigate a "live" system then? Seems it's not possible anymore. From my understanding this `bor debug pprof` start a standard client, so it means it won't be possible to `pprof` on live system.

I think this changelog's entry should be updated IMO as `--pprof` as they used to work is not possible anymore. If `--gprc.addr` does not open the `pprof` endpoint, I don't see how it's a replacement. My 2 cents.

Closing as I leave the decision to you guys.
