### ISSUE TITLE
txlookuplimit not working

### ISSUE THREAD

**Issue by gabronick** [maticnetwork/bor#622]
#### **System information**

Bor client version: 0.3

Heimdall client version: 0.3

OS & Version: Amazon Linux 2

Environment: Polygon Mumbai

Type of node: Archive

#### **Overview of the problem**

when gcmode=archive, txlookuplimit should be 0, and even setting txlookuplimit =0 still shows "unindexing transactions"

#### **Reproduction Steps**

run the node with or without  txlookuplimit = 0  in the config file

#### **Logs / Traces / Output / Error Messages**
 
![image](https://user-images.githubusercontent.com/54854657/206334093-00a97ba0-a32f-4f20-992e-8d3fe45e0f10.png)

**Comment by the-smooth-operator** [comment]
We are experiencing the same issue since upgrading to 0.3

**Comment by manav2401** [comment]
Hi, thanks for reporting. I tried confirming the logic for the same and also trying setting the `txlookuplimit` to 0 in a devnet and it's working as expected for me. 

Can you help me with some additional context (like the snippet of the config.toml file or flags being used to start bor) to debug further? Thanks!

**Comment by gabronick** [comment]
CONFIG.TOML

`chain = "mumbai"
# identity = "Pratiks-MacBook-Pro.local"
# log-level = "INFO"
datadir = "/external/bor/data"
# keystore = ""
syncmode = "full"
gcmode = "archive"
snapshot = false
# ethstats = ""
txlookuplimit = 0

# ["eth.requiredblocks"]

[p2p]
    maxpeers = 50
    port = 30303
    maxpendpeers = 50
    # bind = "0.0.0.0"
    # nodiscover = false
    # nat = "any"
    # [p2p.discovery]
        # v5disc = false
        # bootnodes = []
        # bootnodesv4 = []
        # bootnodesv5 = []
        # static-nodes = []
        # trusted-nodes = []
        # dns = []

# [heimdall]
    url = "http://localhost:1317"
    # "bor.without" = false
    # grpc-address = ""

[txpool]
    nolocals = true
    accountslots = 16
    globalslots = 131072
    accountqueue = 64
    globalqueue = 131072
    lifetime = "1h30m0s"
    # locals = []
    # journal = ""
    # rejournal = "1h0m0s"
    # pricelimit = 1
    # pricebump = 10

[miner]
    gaslimit = 30000000
    # gasprice = "1000000000"
    # mine = false
    # etherbase = ""
    # extradata = ""

[jsonrpc]
    ipcpath = "/external/bor/bor.ipc"
    # ipcdisable = false
    # gascap = 50000000
    txfeecap = 0
    [jsonrpc.http]
        enabled = true
        port = 8545
        host = "0.0.0.0"
        api = ["eth", "net", "web3", "txpool", "bor","debug"]
        vhosts = ["*"]
        corsdomain = ["*"]
        # prefix = ""
    # [jsonrpc.ws]
        # enabled = false
        # port = 8546
        # prefix = ""
        # host = "localhost"
        # api = ["web3", "net"]
        # origins = ["*"]
    # [jsonrpc.graphql]
        # enabled = false
        # port = 0
        # prefix = ""
        # host = ""
        # vhosts = ["*"]
        # corsdomain = ["*"]

# [gpo]
    # blocks = 20
    # percentile = 60
    # maxprice = "5000000000000"
    # ignoreprice = "2"

[telemetry]
    metrics = true
    # expensive = false
    prometheus-addr = "127.0.0.1:60000"
    # opencollector-endpoint = ""
    # [telemetry.influx]
        # influxdb = false
        # endpoint = ""
        # database = ""
        # username = ""
        # password = ""
        # influxdbv2 = false
        # token = ""
        # bucket = ""
        # organization = ""
    # [telemetry.influx.tags]

# [cache]
    cache = 10240
    # gc = 25
    # snapshot = 10
    # database = 50
    # trie = 15
    # journal = "triecache"
    # rejournal = "1h0m0s"
    # noprefetch = false
    # preimages = false
    

# [accounts]
    # unlock = []
    # password = ""
    # allow-insecure-unlock = false
    # lightkdf = false
    # disable-bor-wallet = false

# [grpc]
    # addr = ":3131"

# [developer]
    # dev = false
    # period = 0`
    
    
    Command:
    
    /usr/bin/bor server -config "/external/bor/config.toml"

**Comment by manav2401** [comment]
The `txlookuplimit` field is a part of the `cache` tag while you've mentioned it outside. That might be causing the issue. Can you please change it and restart?

Reference config.toml can be found [here](https://github.com/maticnetwork/bor/blob/qa/docs/cli/example_config.toml).

**Comment by gabronick** [comment]
same behaviour

**Comment by gabronick** [comment]
I also tried to remove it from the config.toml and put --txlookuplimit as a parameter of the executable

**Comment by manav2401** [comment]
> same behaviour, in fact I moved it because inside "cache" it didn't work
Can you share the config.toml?

> I also tried to remove it from the config.toml and put --txlookuplimit as a parameter of the executable
That won't work as all the flags will be overridden if you provide a config.toml file.

**Comment by the-smooth-operator** [comment]
we don't have a config file but specify all args via cli
```
  exec bor server --datadir "$HOME"/data \
      --port 30303 \
      --http --http.addr '<redacted>' \
      --http.vhosts '*' \
      --http.corsdomain '*' \
      --http.port 8545 \
      --ipcpath "$HOME"/data/bor.ipc \
      --http.api 'debug,eth,net,web3,txpool,bor' \
      --syncmode 'full' \
      --chain "$MATIC_DIR"/genesis.json \
      --gcmode 'archive' \
      --ws --ws.port 8546 --ws.addr 0.0.0.0 --ws.origins '*' \
      --miner.gasprice "$GAS_PRICE" \
      --miner.gaslimit '30000000' \
      --txpool.nolocals \
      --txpool.accountslots 16 \
      --txpool.globalslots "$GLOBAL_SLOTS" \
      --txpool.accountqueue 64 \
      --txpool.globalqueue 131072 \
      --txpool.lifetime '1h30m0s' \
      --txpool.pricelimit "$PRICE_LIMIT" \
      --maxpeers 400 \
      --metrics \
      --grpc.addr "<redacted>" \
      --bor.heimdall '<redacted>' \
      --bootnodes "$BOOTNODES" \
      --snapshot=false \
      --cache="$CACHE_SIZE"
      ```

**Comment by manav2401** [comment]
The parent [cache] tag is still uncommented and hence it won't read the flag correctly.

**Comment by gabronick** [comment]
works !
