### ISSUE TITLE
WebSocket endpoint on new version of Bor (v0.3.0)

### ISSUE THREAD

**Issue by keksa905** [maticnetwork/bor#623]
Hey, recently i updated my sentry Polygon node to the newest version v0.3.0. But now I am not able to subscribe for new blocks with Geth client using 'newHeads' method. So I am wondering if Bor is not EVM compatible anymore? Or is some documentation about these changes? Because i did not find anything. 

Error I am obtaining:
'no \"newHeads\" subscription in eth namespace'

**Comment by soltrac** [comment]
Confirmed here also

**Comment by manav2401** [comment]
Please share some additional context for your setup (like the chain used, config file / flags used to start the node, logs, script used to consume the new heads, etc) to help us debug more.

**Comment by soltrac** [comment]
sorry, forgot to update this.

The problem was that on new config file, eth namespace is not enabled by default on websocket, only on HTTP. Enabled it and fixed it.

**Comment by keksa905** [comment]
> sorry, forgot to update this.
> 
> The problem was that on new config file, eth namespace is not enabled by default on websocket, only on HTTP. Enabled it and fixed it.

Ohh, you are right. I had the same issue, it is working now.

**Comment by dwinurhadia** [comment]
Dear @soltrac 
I've follow this guide to running polygon https://wiki.polygon.technology/docs/develop/network-details/full-node-docker/
I try to enable with this command in docker environment, but still not resolve.

```
docker run -p 30303:30303 -p 8545:8545 -p 8546:8546 -v /home/app/data/bor:/root/.bor:rw --net polygon --name bor -d --restart unless-stopped  0xpolygon/bor:0.3.0 server --bor.heimdall 'http://heimdallrest:1317' \
--http --http.addr '0.0.0.0' --http.vhosts '*' --http.corsdomain '*' --http.port 8545 --http.api 'eth,net,web3,txpool,bor' \
--ws --ws.addr '0.0.0.0' --ws.port 8546 --http.api 'eth,net,web3' \
--ipcpath /root/.bor/bor.ipc \
--syncmode 'full' \
--miner.gasprice '30000000000' --miner.gaslimit '20000000' \
--txpool.nolocals --txpool.accountslots 16 --txpool.globalslots 32768 --txpool.accountqueue 16 --txpool.globalqueue 32768 --txpool.pricelimit '30000000000' --txpool.lifetime '1h30m0s' \
--maxpeers 100 \
--bootnodes "enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303"
```

Port 8546 its already exposed, but when i try to `wscat`, look like `websocket` its doesn't exist in the bor container and the result 404


> sorry, forgot to update this.
> 
> The problem was that on new config file, eth namespace is not enabled by default on websocket, only on HTTP. Enabled it and fixed it.
