### ISSUE TITLE
block-stm：How can others check if the miner provides the wrong dependencies in the block header

### ISSUE THREAD

**Issue by 516108736** [maticnetwork/bor#625]
Looking forward to your reply

**Comment by temaniarpit27** [comment]
@cffls

**Comment by pratikpatil024** [comment]
Hi @516108736, replied [here](https://github.com/maticnetwork/bor/pull/561#issuecomment-1362474982).

**Comment by temaniarpit27** [comment]
Closing the issue for now. Please reopen if required
