### ISSUE TITLE
Unable to run bor init

### ISSUE THREAD

**Issue by krkart** [maticnetwork/bor#626]
I'm unable to get the expected dir structure for bor after executing the below cmd. I'm using docker image ver: 0.3.0 (latest).
What am I doing wrong?

docker run -v /mnt/disk2/bor:/bor-home:rw -it 0xpolygon/bor:latest --datadir=/bor-home init /bor-home/genesis.json

Output:
Usage: bor [--version] [--help] <command> [<args>]

Available commands are:
    account        Interact with accounts
    attach         Connect to Bor via IPC
    bootnode       Start a bootnode
    chain          Interact with the chain
    debug          Get traces of the running client
    dumpconfig     Export configuration file
    fingerprint    Display the system fingerprint
    peers          Interact with peers
    removedb       Remove blockchain and state databases
    server         Run the Bor server
    status         Output the status of the client
    version        Display the Bor version

**Comment by wangtao19911111** [comment]
@krkart  i meet the same trouble, could you tell how to deal with it?
