### ISSUE TITLE
How to start prune in v0.3

### ISSUE THREAD

**Issue by acWyman** [maticnetwork/bor#633]
If you try to enter the prune state with this command, the node synchronization state will be entered 
`./bor server snapshot prune-state --datadir=/data/bor`

If you try to enter with this command, an error will be reported.
`./bor snapshot prune-state --datadir=/data/bor`

**Comment by joslee7410** [comment]
!!! I'm having same problem as well. May i know is it Bor (v0.3.0) not support pruning anymore?

**Comment by keksa905** [comment]
Same here, need this functionality as well.

**Comment by manav2401** [comment]
Hi, we're working on adding support for pruning in the new-cli and it should be available in the immediate next release. ATM, with the new-cli, there's no way to prune but if you'd still like to do it, you can always use your old bor binary (v0.2.x ones) to perform pruning (and then run bor again with the new binary).
