### ISSUE TITLE
How can I reduce the number of files in chaindata?

### ISSUE THREAD

**Issue by mone-d** [maticnetwork/bor#638]
I am running bor on an EC2 instance.
However, I can't get mainnet to start synchronizing from the snapshot to the latest block, and it never ends.
After investigating the cause, I believe the problem is the large number of files in chaindata.
As a test, when I run `cd chaindata/` on the host, it takes about 5 seconds to execute.
I think the cause of the slow file access is the number of files, so I would like to know how to reduce the number of files.
Is there an option to shorten the interval between moves to ancient, etc.?

**Comment by manav2401** [comment]
Hey, the node uses leveldb to store the files in a KV database. The files inside chaindata are leveldb files and that technically is not in our hands. It creates multiple files for fast access for specific range of keys. So, ideally there's no way to reduce those files. 

Can you share some specs of the machine you're using and the type of node you're trying to run?
