### ISSUE TITLE
After upgrading to 0.3, the synchronization speed is very slow

### ISSUE THREAD

**Issue by zhy827827** [maticnetwork/bor#642]
hello, After upgrading to 0.3, the synchronization speed is very slow: the Error Log：

**INFO [12-23|03:34:04.552] Looking for peers                        peercount=1 tried=72  static=0
ERROR[12-23|03:34:14.258] Snapshot extension registration failed   peer=91420c48 err="peer connected on snap without compatible eth support"
INFO [12-23|03:34:14.574] Looking for peers                        peercount=2 tried=91  static=0
INFO [12-23|03:34:34.979] Looking for peers                        peercount=2 tried=104 static=0
WARN [12-23|03:34:44.470] Synchronisation failed, dropping peer    peer=90f851621c230542a91796f4b18e281a9a04fa9340383d3cd45541f0d783a519 err=timeout
INFO [12-23|03:34:48.238] Looking for peers                        peercount=2 tried=177 static=0
ERROR[12-23|03:34:50.925] Snapshot extension registration failed   peer=6a0bcd3f err="peer connected on snap without compatible eth support"
WARN [12-23|03:35:03.393] unable to whitelist checkpoint           err="missing checkpoint blocks"
ERROR[12-23|03:35:48.011] Snapshot extension registration failed   peer=91420c48 err="peer connected on snap without compatible eth support"
WARN [12-23|03:35:54.471] Synchronisation failed, dropping peer    peer=6afc6df4a90ff8ca749d12013d10d1768a000e72ee7bfd390c309093c8e64004 err=timeout
ERROR[12-23|03:35:55.380] Snapshot extension registration failed   peer=7501eaab err="peer connected on snap without compatible eth support"
ERROR[12-23|03:36:05.469] Expired request does not exist           peer=54eecec892be33402924f7ac252e882b86f5f6dfd22d4e08a42701c9632baa8d
ERROR[12-23|03:36:13.348] Expired request does not exist           peer=18392b685ea7375d074ae971a86615a62757df350469804a318573bff5b4c71a
ERROR[12-23|03:36:13.680] Expired request does not exist           peer=108137219d6350af6431008d2913c505614f9b1bb9cb6c52c04c9fbd8ca4b948
ERROR[12-23|03:36:23.030] Expired request does not exist           peer=61dc8506e2b0e3b7d340cadab5a09ef78878afb96970e80f6accdb8d669db8ed**
 
Unable to synchronize block~!

**the bor config.toml :**

chain = "mainnet"
identity = "mainnet-polygon-node-02"
log-level = "INFO"
datadir = "/var/lib/bor/data"
syncmode = "full"
"bor.logs" = true
["eth.requiredblocks"]
[p2p]
  maxpeers = 200
  port = 30303
[heimdall]
[txpool]
  nolocals = true
  pricelimit = 30000000000
  accountslots = 16
  globalslots = 32768
  accountqueue = 16
  globalqueue = 32768
  lifetime = "1h30m0s"
[miner]
  gaslimit = 30000000
  gasprice = "30000000000"
[jsonrpc]
  ipcpath = "/var/lib/bor/bor.ipc"
  [jsonrpc.http]
    enabled = true
    port = 8545
    host = "0.0.0.0"
    api = ["eth", "net", "web3", "txpool", "bor", "debug"]
    vhosts = ["*"]
    corsdomain = ["*"]
[gpo]
   ignoreprice = "30000000000"
[telemetry]
[cache]
   cache = 4096
[accounts]
[grpc]
[developer]

Is there any problem with my configuration file?

**Comment by manav2401** [comment]
Hi, from the logs and config files you've shared, it seems difficult to deduce exact reasons. But, a minor suggestion would be to compare the flags you used earlier (for v0.2.x) with the flags in current config.toml file. 

Also, note that the with v0.3.0 of bor, only the interaction layer (i.e. the cli) has changed and it does not change the internal working of the node (which includes sync as well). So, technically, the speed should (and is for our internal nodes) same. 

It would be good if you can share some more contextual logs (or comparison of sync speeds from prev. versions) to debug this further.

**Comment by zhy827827** [comment]
Because the synchronization is too slow, and there are always tens of thousands of blocks diff mainet, I delete the data and then download the snapshot to resynchronize.
I will upload the log later。

**Comment by zhy827827** [comment]
Two hours after synchronization, Synchronous error：

Dec 28 06:59:23 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: INFO [12-28|06:59:23.271] Imported new chain segment               blocks=10         txs=483           mgas=153.398 elapsed=8.008s       mgasps=19.153 number=37,312,689 hash=0c374f..74fe96 age=1d10h17m dirty=810.78MiB
Dec 28 06:59:23 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: ERROR[12-28|06:59:23.993] Snapshot extension registration failed   peer=101502b5 err="peer connected on snap without compatible eth support"
Dec 28 06:59:24 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: INFO [12-28|06:59:24.991] Indexing transactions                    blocks=18,028,969 txs=1,677,390,123 tail=16,920,496 total=34,949,465 elapsed=2h42m18.958s
Dec 28 06:59:28 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: WARN [12-28|06:59:28.537] Database compacting, degraded performance database=/var/lib/bor/data/bor/chaindata
Dec 28 06:59:46 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: ERROR[12-28|06:59:46.406] Snapshot extension registration failed   peer=bc8af532 err="peer connected on snap without compatible eth support"
Dec 28 07:00:27 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: WARN [12-28|07:00:27.218] unable to whitelist checkpoint           err="missing checkpoint blocks"
Dec 28 07:00:28 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: WARN [12-28|07:00:28.545] Database compacting, degraded performance database=/var/lib/bor/data/bor/chaindata
Dec 28 07:00:51 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: ERROR[12-28|07:00:51.735] Snapshot extension registration failed   peer=101502b5 err="peer connected on snap without compatible eth support"
Dec 28 07:01:14 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: ERROR[12-28|07:01:14.232] Snapshot extension registration failed   peer=c5b271da err="peer connected on snap without compatible eth support"
Dec 28 07:01:15 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: ERROR[12-28|07:01:15.504] Snapshot extension registration failed   peer=2b236036 err="peer connected on snap without compatible eth support"
Dec 28 07:01:28 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: WARN [12-28|07:01:28.555] Database compacting, degraded performance database=/var/lib/bor/data/bor/chaindata
Dec 28 07:01:30 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: ERROR[12-28|07:01:30.934] Snapshot extension registration failed   peer=bb7714c1 err="peer connected on snap without compatible eth support"
Dec 28 07:01:42 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: ERROR[12-28|07:01:42.767] Snapshot extension registration failed   peer=101502b5 err="peer connected on snap without compatible eth support"
Dec 28 07:02:07 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: WARN [12-28|07:02:07.217] unable to whitelist checkpoint           err="missing checkpoint blocks"
Dec 28 07:02:28 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: WARN [12-28|07:02:28.562] Database compacting, degraded performance database=/var/lib/bor/data/bor/chaindata
Dec 28 07:02:38 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: ERROR[12-28|07:02:38.388] Snapshot extension registration failed   peer=101502b5 err="peer connected on snap without compatible eth support"



Dec 28 07:03:28 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: WARN [12-28|07:03:28.572] Database compacting, degraded performance database=/var/lib/bor/data/bor/chaindata
Dec 28 07:03:44 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: ERROR[12-28|07:03:44.906] Snapshot extension registration failed   peer=101502b5 err="peer connected on snap without compatible eth support"
Dec 28 07:03:47 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: WARN [12-28|07:03:47.218] unable to whitelist checkpoint           err="missing checkpoint blocks"
Dec 28 07:04:12 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: ERROR[12-28|07:04:12.975] Snapshot extension registration failed   peer=04dfa983 err="peer connected on snap without compatible eth support"
Dec 28 07:04:28 rockx-mainnet-polygon-ovh-node-02 bor[3134677]: WARN [12-28|07:04:28.585] Database compacting, degraded performance database=/var/lib/bor/data/bor/chaindata

**Comment by temaniarpit27** [comment]
Closing this for now. Please reopen if required
