### ISSUE TITLE
How to prune data in v0.3

### ISSUE THREAD

**Issue by zhy827827** [maticnetwork/bor#643]
with bor v0.2.*，pruned data:  bor --datadir=/opt/rockx/data snapshot prune-state

but bor-v0.3  I don't know how to prune the data.

**Comment by manav2401** [comment]
Hi, at the moment there's no way to prune your data in the new-cli in v0.3.0 (I am assuming you're talking about mainnet). We've already added that feature and it should be available in the immediate next release. 

However, if you still want to prune your data, here's a workaround for that. 
1. Stop current bor (running with new-cli v0.3.0)
2. Clone, and build bor binary at a separate location (using the tag v0.2.17)
3. Use the prune command using the old (v0.2.x) bor binary
4. Restart the original bor service (running with new-cli v0.3.0)

**Comment by zhy827827** [comment]
thank you~~~
