### ISSUE TITLE
where is docker image maticnetwork/bor:v0.3.0 ?

### ISSUE THREAD

**Issue by wangtao19911111** [maticnetwork/bor#645]
Our support team has aggregated some common issues and their solutions from past which are faced while running or interacting with a bor client. In order to prevent redundant efforts, we would encourage you to have a look at the [FAQ's section](https://docs.polygon.technology/docs/faq/technical-faqs) of our documentation mentioning the same, before filing an issue here. In case of additional support, you can also join our [discord](https://discord.com/invite/zdwkdvMNY2) server

#### **System information**

Bor client version: [e.g. v0.2.16] 

Heimdall client version: [e.g. v0.2.10] 

OS & Version: Windows / Linux / OSX

Environment: Polygon Mainnet / Polygon Mumbai / Devnet

Type of node: Validator / Sentry / Archive

Additional Information: 

#### **Overview of the problem**

Please describe the issue you experiencing.

#### **Reproduction Steps**

Please mention the steps required to reproduce this issue. 

#### **Logs / Traces / Output / Error Messages**
 
Please post any logs/traces/output/error messages (as text and not screenshots) which you believe may have caused the issue. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue.

**Additional Information**

In order to debug the issue faster, we would stongly encourage if you can provide some of the details mentioned below (whichever seems relevant to your issue)

1. Your `start.sh` file or `bor.service`, if you're facing some peering issue or unable to use some service (like `http` endpoint) as expected. Moreover, if possible mention the chain configuration printed while starting the node which looks something like `Initialised chain configuration config="{ChainID: 137, ..., Engine: bor}"`

2. The result of `eth.syncing`, `admin.peers.length`, `admin.nodeInfo`, value of the `maxpeers` flag in start.sh, and bootnodes/static nodes (if any) is you're facing some syncing issue.

3. Your `heimdall-config.toml` parameters for checking the ETH and BOR RPC url's, incase of issue with bor heimdall communication. 

4. The CURL request (for that specific error) if you're facing any issues or identify a bug while making RPC request.

**Comment by manav2401** [comment]
This info is mentioned in the forum post. Posting it here as well: https://hub.docker.com/r/0xpolygon/bor/tags
