### ISSUE TITLE
`--verbosity` is broken

### ISSUE THREAD

**Issue by ngotchac** [maticnetwork/bor#668]
It seems that this PR: https://github.com/maticnetwork/bor/pull/446/files#diff-330686dc447b6523e8cbb02ae01e63ed53f3b214274ecc0da55c978965dda5dd broke the `--verbosity` flag by shifting everything by 1. The result is that by default the level `3` is actually WARNING, whereas it should (and be the default) be the INFO level.

**Comment by pratikspatil024** [comment]
Hi @ngotchac, thanks for reporting this. In the new cli (version 0.3.0 onwards), we use the `--log-level` flag for this.
We support `TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR`, and `CRIT` logging levels with the `bor server` command.
I agree that our codebase has some instances of `--verbosity`, and we will work on fixing them.

**Comment by ngotchac** [comment]
Yeah I was actually wondering whether to close this issue, when I found out that this bug doesn't exist with the new `bor` command. So I'll let you choose :)

**Comment by pratikspatil024** [comment]
Cool, thanks again for reporting. I will close this issue, and we'll remove other _removable_ instances of `verbosity`.
