### ISSUE TITLE
Bad block in Mumbai, height 30575996

### ISSUE THREAD

**Issue by fmira21** [maticnetwork/bor#669]
Hi guys!
I am trying to start Bor with Heimdall in Mumbai. I downloaded following snapshots:
- https://matic-blockchain-snapshots.s3-accelerate.amazonaws.com/matic-mumbai/bor-fullnode-snapshot-2023-01-05.tar.gz
- https://matic-blockchain-snapshots.s3-accelerate.amazonaws.com/matic-mumbai/heimdall-snapshot-2023-01-05.tar.gz

After this, I waited until Heimdall fully synced and started Bor. But it did not sync at all:

```
########## BAD BLOCK #########
Chain config: {ChainID: 80001 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 2722000, Muir Glacier: 2722000, Berlin: 13996000, London: 22640000, Arrow Glacier: <nil>, MergeFork: <nil>, Terminal TD: <nil>, Engine: bor}
Number: 30575996
Hash: 0x35c98387e9cdbe99566448e15586b731ede0a62a740e73214d29068a2849d0b4
Error: invalid baseFee: have 15, want 16, parentBaseFee 16, parentGasUsed 1302274
##############################
```

I tried all variants from here: https://wiki.polygon.technology/docs/maintain/validate/faq/known-issues/
Nothing helped. Can you please help me to figure it out?

Thank you in advance!

**Comment by manav2401** [comment]
Thanks for reporting this. 

Can you let me know few things?
1. Was it working well till this block and suddenly stopped working? If yes, was any change made to config to run bor/heimdall?
2. Is bor connected well to heimdall i.e. is heimdall endpoint given correctly?
3. Did you try rewinding the bor chain to few blocks? If not, can you do so?

**Comment by fmira21** [comment]
Hi @manav2401 
I've managed to run the node via the latest snapshot:)
So I can close the issue.
