### ISSUE TITLE
Bor Doesn't Work with Non-Default Ports

### ISSUE THREAD

**Issue by joesixpack** [maticnetwork/bor#67]
#### System information

Bor version: 1.9.0-stable
OS & Version: Ubuntu 18.04 LTS

#### Expected behaviour

Bor should sign and achieve checkpoints.

#### Actual behaviour

0% checkpoints.

#### Steps to reproduce the behaviour

Change p2p port to 30703 and rpcport to 8555 in bor.service

Either one or the other or both being reset back to default clears the issue.

**Comment by jdkanani** [comment]
@joesixpack Did you reload service after bor.service changes?

```bash
sudo systemctl reload bor.service
sudo systemctl restart bor.service
```

**Comment by joesixpack** [comment]
Of course.

**Comment by joesixpack** [comment]
As Shai on Discord discovered, heimdall-config.toml has a bor_rpc_url that needs to be edited to point to any custom ports.

**Comment by jdkanani** [comment]
Ah yes. Need to update Heimdall config.

**Comment by joesixpack** [comment]
Having similar or same problem again with CS-2008:

# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

##### RPC and REST configs #####

# RPC endpoint for ethereum chain
eth_rpc_url = "https://goerli.infura.io/v3/c5e9d133b68042a988eed77ccda1e9b8"

# RPC endpoint for bor chain
bor_rpc_url = "http://localhost:8555"

# RPC endpoint for tendermint
tendermint_rpc_url = "http://0.0.0.0:26757"

# Heimdall REST server endpoint
heimdall_rest_server = "http://0.0.0.0:1317"

#### Bridge configs ####

# MQTT endpoint
amqp_url = "amqp://guest:guest@localhost:5672/"

## Bridge Poll Intervals
checkpoint_poll_interval = "5m0s"
syncer_poll_interval = "1m0s"
noack_poll_interval = "16m50s"
clerk_poll_interval = "10s"
span_poll_interval = "1m0s"

#### gas limits ####
main_chain_gas_limit = "5000000"

##### Timeout Config #####
no_ack_wait_time = "30m0s"


● bor.service - bor
   Loaded: loaded (/etc/systemd/system/bor.service; static; vendor preset: enabled)
   Active: active (running) since Thu 2020-06-04 08:53:15 CEST; 5min ago
  Process: 11577 ExecStartPre=/bin/chmod +x /etc/bor/start.sh (code=exited, status=0/SUCCESS)
 Main PID: 11578 (bash)
    Tasks: 20 (limit: 4915)
   CGroup: /system.slice/bor.service
           ├─11578 /bin/bash /etc/bor/start.sh 2008 0x2F6102a60813aF809C8dA5f46Ceb1D022dd718f2 validator-without-sentry
           └─11579 /usr/bin/bor --datadir /etc/bor/dataDir --port 30703 --rpc --rpcaddr 0.0.0.0 --rpcvhosts * --rpccorsdomain * --rpcport 8555 --ipcpath /etc/bor/bor.ipc --rpcapi db,eth,net,web3,txpool,bor --net

Jun 04 08:58:44 andromeda bash[11578]: INFO [06-04|08:58:44.626] Retrying again in 5 seconds for next Heimdall span path=bor/span/68
Jun 04 08:58:46 andromeda bash[11578]: INFO [06-04|08:58:46.671] Retrying again in 5 seconds for next Heimdall span path=bor/span/68
Jun 04 08:58:49 andromeda bash[11578]: INFO [06-04|08:58:49.629] Retrying again in 5 seconds for next Heimdall span path=bor/span/68
Jun 04 08:58:51 andromeda bash[11578]: INFO [06-04|08:58:51.675] Retrying again in 5 seconds for next Heimdall span path=bor/span/68
Jun 04 08:58:54 andromeda bash[11578]: INFO [06-04|08:58:54.633] Retrying again in 5 seconds for next Heimdall span path=bor/span/68
Jun 04 08:58:56 andromeda bash[11578]: INFO [06-04|08:58:56.678] Retrying again in 5 seconds for next Heimdall span path=bor/span/68
Jun 04 08:58:59 andromeda bash[11578]: INFO [06-04|08:58:59.636] Retrying again in 5 seconds for next Heimdall span path=bor/span/68
Jun 04 08:59:01 andromeda bash[11578]: INFO [06-04|08:59:01.686] Retrying again in 5 seconds for next Heimdall span path=bor/span/68
Jun 04 08:59:04 andromeda bash[11578]: INFO [06-04|08:59:04.640] Retrying again in 5 seconds for next Heimdall span path=bor/span/68
Jun 04 08:59:06 andromeda bash[11578]: INFO [06-04|08:59:06.689] Retrying again in 5 seconds for next Heimdall span path=bor/span/68
