### ISSUE TITLE
Bor 0.3.3 pending block is the same as latest

### ISSUE THREAD

**Issue by recidive** [maticnetwork/bor#670]
I'm trying to get the pending block with ethers like this:

```javascript
const websocketProvider = new ethers.providers.WebSocketProvider(
  WEBSOCKET_URL,
  'matic',
)
websocketProvider.on('block', async (number) => {
  console.log(`New block ${number}`)

  const pendingBlock = await websocketProvider.getBlock('pending')
  console.log(`Pending block number: ${pendingBlock.number}`)
  console.log(`Pending block base fee: ${pendingBlock.baseFeePerGas}`)
})
```

But it's returning the latest block, not the pending block. QuickNode websocket returns the correct pending block, it looks like a bug in Bor 0.3.3 or am I missing something?

**Comment by recidive** [comment]
Hi @manav2401, perhaps I can help with fixing this if you give me some guidance. I'm not too much into Go, but whiling to help. Thanks!

**Comment by manav2401** [comment]
Hi @recidive, thanks for reporting this. I have been trying this out on few of our internals machines and I think you're correct. For external endpoints (like alchemy/quicknode), it also works well and gives the 'latest+1' block in response of 'pending' block. But for some of internal machines it either gives the same block as 'latest' or an old block to me. 

I am looking into the code and it seems that it reaches out to the miner module for getting the pending block. It might be the case that the for non-validator nodes (sentry / full), the miner module might not have correct (update) data and hence they give either a past block or the same block as latest. 

Can you let me know, which kind of node you tried this on? If by any chance, you have both of them can you compare the results in them and let me know? Meanwhile, I will do more experiments and report them back here. Thanks a lot!

**Comment by manav2401** [comment]
Thanks for the info. No, that won't be possible. Anyways, I am testing it so no worries.

**Comment by temaniarpit27** [comment]
Please reopen if required
