### ISSUE TITLE
Resuming Bor tasks rewinds synchronized blocks

### ISSUE THREAD

**Issue by moneohara** [maticnetwork/bor#672]
First of all, I apologize.
Since a translation tool was used to create this text, some sentences may be incorrect.

After Bor has been stopped for some reason, when it is restarted, blocks that were already synchronized are rewound.

Normally, when bor synchronizes a new block, it should output a log starting with the following

`Imported new chain segment blocks=1 txs=21...`

The log shows the number of the block that was synchronized, and the fact that the log is output means that synchronization has been completed up to that block.
The same log is output after restart, but the block numbers are those of blocks that have been synchronized in the past.

I have tried several times to intentionally stop Bor and restart it, but in each case the block rolls back.
On average, about 100,000 blocks are being rolled back.

Since blocks are constantly being generated on the network, when rewinding occurs, it takes time to synchronize up to the latest block.
We are also having trouble because we cannot send transactions through Bor during this time.

Is there any workaround for this block rewinding phenomenon?

**Comment by 0xsharma** [comment]
Hi @moneohara , every time bor is stopped or restarted, latest block state and other data is pushed to the persistent disk. If there is unclean shutdown on bor ( process stopped/ panic/ error ), the blockchain will rewind till last available state in persistent disk. We are increasing the frequency of storing the states on persistent disk here https://github.com/maticnetwork/bor/pull/671, so that we don't see big rewinds in case of unclean shutdowns.

**Comment by moneohara** [comment]
Thank you for your response.
I hope https://github.com/maticnetwork/bor/pull/671 will resolve this issue.

Just to confirm one point, if bor is not a clean shutdown, am I correct in interpreting that it will return to the state it was in 60 minutes ago at the maximum?
In other words, it is not related to the speed of block generation on the network, but whether it is affected by the bor's block synchronization state when it is shut down.

**Comment by moneohara** [comment]
@0xsharma 
Thank you for your response.
I hope https://github.com/maticnetwork/bor/pull/671 will resolve this issue.

Just to confirm one point, if bor is not a clean shutdown, am I correct in interpreting that it will return to the state it was in 60 minutes ago at the maximum?
In other words, it is not related to the speed of block generation on the network, but whether it is affected by the bor's block synchronization state when it is shut down.

**Comment by 0xsharma** [comment]
Yes, if the writes to disk were successful on previous shutdown, it should return to block with a state that was 60 minutes ago. No, its not related to the blocktime or sync, its related to the frequency of block state writes to persistent memory.

Please let us know if you still face any issues. Thank you 💜
