### ISSUE TITLE
unable to whitelist checkpoint, err="missing checkpoint blocks"

### ISSUE THREAD

**Issue by KypMon** [maticnetwork/bor#680]
Hi,

I am using the bor 0.3.3 image, but after start the bor service, it starts to give the error like in the title:

>  WARN [01-17|08:57:12.636] unable to whitelist checkpoint           err="missing checkpoint blocks"

this issue is also described into https://forum.polygon.technology/t/bor-heimdall-mainnet-upgrade-v0-3-0-action-required/10691

> Unable to whitelist checkpoint
Bor leverages the checkpointing mechanism to stay connect to honest peers and it won’t connect to peers which are on wrong fork for large range of blocks (technically beyond the last checkpoint sent). For this, it will reach out to heimdall periodically to ask for latest checkpoints. Before it whitelists any checkpoint, it will perform some checks like do we have blocks for the checkpoint which we’re about to whitelist or not? If any of them fails, it won’t be able to whitelist them. A common scenario where this error is expected is when you’re syncing and have not yet reached the last check-pointed block. Once done, bor will eventually stop throwing this error.

but I don't quite get the idea showing here, my heimdall is already synced showing `catching_up: false`, what else should I do to solve this issue?

**Comment by manav2401** [comment]
Hi, this log means that your bor node is running behind. Until bor is syncing, you can ignore it. It will go away once it is fully in sync. 

It basically means that it tries to whitelist some blocks which were posted as checkpoint by heimdall, but as your local nodes doesn't have those blocks yet, it isn't able to. Hence the error. Hope this helps. Thanks!

**Comment by temaniarpit27** [comment]
Please reopen if required

**Comment by KypMon** [comment]
Hi Manav, thanks for the info, I presume the process is that before the bor get checkpoint posted from heimdall, the syncing wouldn't start, and this process is quite unavoidable and every bor instance need to go through period of time of showing `missing checkpoint blocks`, this is my understanding correct? My very first bor node finally start syncing after 48 hrs, but my other nodes are syncing undergoing this even I download the full snapshot. 

Also if that so, is there any way to speed the process up? Thanks for your help again!

**Comment by manav2401** [comment]
Hi @KypMon, no that's not the case. Even if bor doesn't get a checkpoint from heimdall it would still keep running. It's just that it would not perform any additional checks while importing any chains from other peers. 

Basically "missing checkpoint blocks" means that it tried whitelisting a checkpoint which is already submitted to ethereum but couldn't as there's nothing locally in it's db to validate it against. So, if the checkpoint is from block n to n+512, it should have those blocks available locally. It should technically not affect the syncing process. Hope this clarifies. 

Also, I believe you're seeing a slow syncing process. Do you have any additional metrics (like the rate of blocks imported before vs after the update), or any CPU stats of any performance degradation? Thanks!
