### ISSUE TITLE
the method `eth_syncing` does not exist for `https://polygon-rpc.com/`

### ISSUE THREAD

**Issue by mxsur** [maticnetwork/bor#682]
Hello Bor team!

We started to experience the following RPC error `The method eth_syncing does not exist` for `https://polygon-rpc.com/` since Tue Jan 17 2023 20:00 GMT+0000 +/- although the other orthogonal method `eth_blockNumber` works
```
❯ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":12}' https://polygon-rpc.com/
{"jsonrpc":"2.0","error":{"code":-32601,"message":"the method eth_syncing does not exist/is not available"},"id":12}

❯ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' https://polygon-rpc.com/
{"jsonrpc":"2.0","id":1,"result":"0x246b4d2"}

```

**Comment by manav2401** [comment]
Hi, the endpoint `https://polygon-rpc.com/` is handled by [ankr](https://www.ankr.com/) team and they've disabled it. As there are multiple nodes behind a load balancer serving requests behind this RPC, it doesn't makes sense to keep that info publicly available. Other endpoints should work as expected.
