### ISSUE TITLE
 error: no "newPendingTransactions" subscription in eth namespace

### ISSUE THREAD

**Issue by CRossel87a** [maticnetwork/bor#683]
Hi,

After the recent Bor version, it is no longer possible to subscribe to pending transactions:

 error: no "newPendingTransactions" subscription in eth namespace

Code to replicate:

var add = 'ws://server:port'
var Web3 = require('web3');
var web3 = new Web3(new Web3.providers.WebsocketProvider(add));
const subscription = web3.eth.subscribe('pendingTransactions', (err, res) => {
    if (err) console.error(err);
});
subscription.on('data', (txHash) => {
    setTimeout(async () => {
         try {
             let tx = await web3.eth.getTransaction(txHash);
             if (tx) {
		 console.log(JSON.stringify(tx));
             }
         } catch (err) {
             console.error(err);
         }
    })
});

**Comment by keksa905** [comment]
Check if you have 'eth' namespace enabled for websocket in the config file for bor, because it is not enabled by default. See https://github.com/maticnetwork/bor/issues/623#issuecomment-1349323286
