### ISSUE TITLE
How can I make config.toml from github repo?

### ISSUE THREAD

**Issue by hitchhooker** [maticnetwork/bor#684]
How can I make config.toml from github repo? How can I find flags that bor accepts? client help seems very lacking in comparison to other networks

**Comment by manav2401** [comment]
Hi, all the flags and the default config files have been documented [here](https://github.com/maticnetwork/bor/tree/develop/docs). Also, this info has been made available in the forum post. Please find it [here](https://forum.polygon.technology/t/bor-heimdall-mainnet-upgrade-v0-3-0-action-required/10691).
