### ISSUE TITLE
Bor v. 0.3.3: long synchronisation

### ISSUE THREAD

**Issue by fmira21** [maticnetwork/bor#685]
Hi guys!
I updated my nodes prior to the hardfork. But already for a day, it cannot sync at all.
I use the Docker images of Bor and Heimdall. Heimdall is synced in full. But after I started Bor, it cannot get to the chain tip.

Logs:

```
INFO [01-18|09:53:46.425] Imported new chain segment               blocks=4          txs=287           mgas=52.420  elapsed=10.026s      mgasps=5.228  number=38,211,608 hash=edb914..609829 age=9h23m1s  dirty=0.00B
INFO [01-18|09:53:56.324] Imported new chain segment               blocks=5          txs=346           mgas=70.087  elapsed=9.899s       mgasps=7.080  number=38,211,613 hash=25a7f4..379fda age=9h23m1s  dirty=0.00B
INFO [01-18|09:53:59.786] Deep froze chain segment                 blocks=25         elapsed=42.319ms     number=38,121,613 hash=a4bdc0..9dcae1
INFO [01-18|09:54:07.849] Fetching state updates from Heimdall     fromID=2,542,815 to=2023-01-18T00:30:29Z
INFO [01-18|09:54:07.849] Fetching state sync events               queryParams="from-id=2542815&to-time=1674001829&limit=50"
INFO [01-18|09:54:07.852] StateSyncData                            gas=0         number=38,211,616 lastStateID=2,542,814 total records=0  fetch time=3   process time=0
INFO [01-18|09:54:08.010] Imported new chain segment               blocks=3          txs=234           mgas=58.659  elapsed=11.685s      mgasps=5.020  number=38,211,616 hash=900522..09ac17 age=9h23m5s  dirty=0.00B
INFO [01-18|09:54:17.081] Imported new chain segment               blocks=6          txs=411           mgas=59.671  elapsed=9.070s       mgasps=6.578  number=38,211,622 hash=88bd90..c01b43 age=9h23m2s  dirty=0.00B
INFO [01-18|09:54:28.562] Imported new chain segment               blocks=3          txs=278           mgas=59.431  elapsed=11.481s      mgasps=5.176  number=38,211,625 hash=fe829c..8df8d8 age=9h23m7s  dirty=0.00B
INFO [01-18|09:54:38.537] Imported new chain segment               blocks=4          txs=298           mgas=59.192  elapsed=9.974s       mgasps=5.934  number=38,211,629 hash=25a8b7..ec9461 age=9h23m9s  dirty=0.00B
INFO [01-18|09:54:49.687] Fetching state updates from Heimdall     fromID=2,542,815 to=2023-01-18T00:31:03Z
INFO [01-18|09:54:49.687] Fetching state sync events               queryParams="from-id=2542815&to-time=1674001863&limit=50"
INFO [01-18|09:54:49.690] StateSyncData                            gas=0         number=38,211,632 lastStateID=2,542,814 total records=0  fetch time=3   process time=0
INFO [01-18|09:54:49.925] Imported new chain segment               blocks=3          txs=315           mgas=59.049  elapsed=11.388s      mgasps=5.185  number=38,211,632 hash=ce6e39..9f2bcb age=9h23m12s dirty=0.00B
WARN [01-18|09:54:58.833] unable to whitelist checkpoint           err="missing checkpoint blocks"
INFO [01-18|09:54:59.449] Imported new chain segment               blocks=3          txs=275           mgas=70.742  elapsed=9.523s       mgasps=7.428  number=38,211,635 hash=7e0829..15b601 age=9h23m16s dirty=0.00B
INFO [01-18|09:54:59.820] Deep froze chain segment                 blocks=22         elapsed=34.014ms     number=38,121,635 hash=8d72ae..010e57
INFO [01-18|09:55:08.965] Imported new chain segment               blocks=3          txs=195           mgas=61.485  elapsed=9.516s       mgasps=6.461  number=38,211,638 hash=eb69f6..b594ba age=9h23m19s dirty=0.00B
INFO [01-18|09:55:13.374] Imported new chain segment               blocks=2          txs=145           mgas=28.144  elapsed=4.409s       mgasps=6.383  number=38,211,640 hash=64372e..f312ce age=9h23m20s dirty=0.00B
INFO [01-18|09:55:13.379] Downloader queue stats                   receiptTasks=0 blockTasks=10512 itemSize=57.76KiB  throttle=4539
INFO [01-18|09:55:13.392] Unindexed transactions                   blocks=36         txs=2959          tail=35,861,641 elapsed=17.204ms
WARN [01-18|09:55:13.430] Synchronisation failed, retrying         peer=dc4fdabc85a0d9a27649520f8cc117a1310858cd6a86a1eccaa7146f61ece2ba err="retrieved hash chain is invalid: received future chain of unacceptable length"
2023/01/18 09:55:15 max retry time elapsed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4317: connect: connection refused"
INFO [01-18|09:55:22.841] Imported new chain segment               blocks=4          txs=289           mgas=49.708  elapsed=8.786s       mgasps=5.657  number=38,211,644 hash=e51298..440272 age=9h23m21s dirty=0.00B
INFO [01-18|09:55:31.560] Imported new chain segment               blocks=3          txs=221           mgas=53.333  elapsed=8.719s       mgasps=6.117  number=38,211,647 hash=9739c1..e4fad0 age=9h23m24s dirty=0.00B
```

You can see that the block age does not decrease.
What can I do?

Thank you in advance!

**Comment by manav2401** [comment]
Hi, can you let us know the settings under which the nodes were started (i.e. the config.toml) and how many peers your node is connected to?

**Comment by fmira21** [comment]
Hi @manav2401 
Yes, sure!

I start the node with following CLI parameters:

```
server
      --datadir /bor-home
      --port 30303
      --bor.heimdall 'http://matic-heimdall-rest:1317'
      --http
      --http.addr '0.0.0.0'
      --http.vhosts "*"
      --http.corsdomain "*"
      --http.port 8945
      --ipcpath /bor-home/bor.ipc
      --http.api 'eth,net,web3,txpool,bor,debug'
      --syncmode "full"
      --miner.gasprice '30000000000'
      --miner.gaslimit '20000000'
      --txpool.nolocals
      --txpool.accountslots 16
      --txpool.globalslots 32768
      --txpool.accountqueue 16
      --txpool.globalqueue 32768
      --txpool.pricelimit '30000000000'
      --txpool.lifetime '1h30m0s'
      --maxpeers 1000
      --bootnodes enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303,enode://3178257cd1e1ab8f95eeb7cc45e28b6047a0432b2f9412cff1db9bb31426eac30edeb81fedc30b7cd3059f0902b5350f75d1b376d2c632e1b375af0553813e6f@35.221.13.28:30303,enode://16d9a28eadbd247a09ff53b7b1f22231f6deaf10b86d4b23924023aea49bfdd51465b36d79d29be46a5497a96151a1a1ea448f8a8666266284e004306b2afb6e@35.199.4.13:30303,enode://ef271e1c28382daa6ac2d1006dd1924356cfd843dbe88a7397d53396e0741ca1a8da0a113913dee52d9071f0ad8d39e3ce87aa81ebc190776432ee7ddc9d9470@35.230.116.151:30303,enode://8669d5c9c07513c84436e54025b32cb3b418ecd66ebaf114f900e4cddf5daeb40d0d0ba28b209f73e1c2e97611cf834c22844e78f60a1f95ad87c7baeed134e8@50.116.61.119:30303
      --chain mainnet
      --snapshot=false
      --gcmode "archive"
      --bor.logs
      --gpo.blocks 20
      --gpo.percentile 60
      --ws.api "eth,net,web3"
      --ws
      --cache 12288
      --ws.addr=0.0.0.0
      --ws.origins *
      --ws.port 8946
      --log-level 3
      --rpc.txfeecap=0
      --metrics
      --metrics.prometheus-addr 0.0.0.0
      --metrics.expensive
```

Last peer message:

```
INFO [01-18|11:32:54.472] Looking for peers                        peercount=2 tried=181 static=0
```

**Comment by fmira21** [comment]
Status:

```
/var/lib/bor # bor status
General
Num peers = 30
Sync mode = full

Current Header
Hash   = 0xcc28dd03db3ed352f2c638bdc54baa23d029a5ba75cb31e1f6b2f0c4f556a362
Number = 38213854

Current Block
Hash   = 0xcc28dd03db3ed352f2c638bdc54baa23d029a5ba75cb31e1f6b2f0c4f556a362
Number = 38213854

Syncing
Current block  = 38213854
Highest block  = 38229334
Starting block = 38213776

Forks
Name            Block     Enabled
Homestead       0         true
EIP150          0         true
EIP155          0         true
EIP158          0         true
Byzantium       0         true
Constantinople  0         true
Petersburg      0         true
Istanbul        3395000   true
MuirGlacier     3395000   true
Berlin          14750000  true
London          23850000  true
ArrowGlacier    0         false
MergeFork       0         false
Jaipur          23850000  true
Delhi           38189056  true
```

**Comment by manav2401** [comment]
The setting looks fine to me. It might be possible that your node is getting disconnected from honest/correct peers which might serve you some useful data. I'd recommend using a config.toml based setting to run bor because that will allow you to add static nodes (under the p2p section). That would help your node reconnect to honest peers if disconnected.

**Comment by lsdbitrue** [comment]
I can confirm this issue.

@manav2401 Do you have a static node list for me?

**Comment by lsdbitrue** [comment]
https://wiki.polygon.technology/docs/maintain/validate/run-validator-binaries#configuring-the-bor-service

there are 5 items I'm using

**Comment by the-smooth-operator** [comment]
we are also experiencing issues with nodes falling out of sync. We run several replicas.

Our configuration is mostly default values, running in archive mode, with 128GB of memory (--cache) and bumping max peers to 400.
We are definitely not resource constraint: we have plenty of memory, CPU and disk IOPS & bandwidth available.

The graph below shows the drift between our multiple replicas, and between our highest replica VS an explorer.
This is for the last 7 days, as you can see, nodes fall out of sync all the time 
![image](https://user-images.githubusercontent.com/9251788/215056029-2eeb53a3-dab5-4385-b91a-5879e0e0c9c2.png)

Here you can see the number of peers connected to 2 of our nodes. They suddenly drop their connected peers to 0, which is one of the causes of nodes falling behind, but it's not always the case.
![image](https://user-images.githubusercontent.com/9251788/215056229-280ece09-126d-44af-8c74-e01e18cf879f.png)

**Comment by JekaMas** [comment]
Working on that.
Thank you for the information and raising the issue @the-smooth-operator @mkykadir @sunilraj228 @fmira21 

Could you run profiling for us? Or at least give us CPU data at the moment of slow sync.

**Comment by cromaniuc** [comment]
This is exactly what happened to me as well over the weekend. The nodes were running for 4 months so far without any issues.
What I did to solve this was to:

- run with `--snapshot=false` since I had it with true and that is not needed after sync from snapshot since it's affecting the performance.
- increased the cache as well, but from default 1GB to 4GB and I think it will be fine
- Increased max peers to 400
- added more bootnodes from https://wiki.polygon.technology/docs/maintain/validate/run-validator-binaries/#configuring-the-bor-service

**Comment by cromaniuc** [comment]
Happened again 2 times 19-20 Feb, any idea what caused this?

**Comment by felddoteth** [comment]
I'm hitting this as well. This was never a problem before 0.3.3

**Comment by manav2401** [comment]
Hi all, can you try running the new bor version (v0.3.4) (See the release notes [here](https://github.com/maticnetwork/bor/releases/tag/v0.3.4)). We haven't made an official forum post to this but it includes some fixes and optimisations which might resolve the issue. The steps to update remains the same as they were for v0.3.0 to v0.3.3 upgrade. Thanks!

**Comment by felddoteth** [comment]
I am only seeing a slight improvement. Instead of falling farther behind it's catching up, but it's so slow I estimate it will take weeks at this rate.

**Comment by felddoteth** [comment]
It took 2 weeks for it to finally catch up, about a full month since bootstrapping from snapshot.

Now that it has caught up the CPU usage is really high -- higher than when it was syncing, and we're not even querying this node yet.

m6a.xlarge
EBS GP3, 3000 IOPS, usage rarely goes over 2500 combined read/write

**Comment by pratikspatil024** [comment]
Hi @felddoteth could you please provide more details and data on the high CPU usage part?
Also, it will be better to get pprof data during the slow sync, if possible.
Thank you.

**Comment by pratikspatil024** [comment]
Also, please have a look at this document: https://wiki.polygon.technology/docs/maintain/validate/kb/known-issues/#3-issue-bor-synchronisation-is-slow. Seems like your system requirements are low.

**Comment by manav2401** [comment]
Alright. Then I believe it must be a peering issue. 

Can you grep some of the logs saying "Synchronisation failed" and post them here with the full error message. I'd like to see the frequency of peers getting dropped.

**Comment by manav2401** [comment]
Moreover, I'd suggest using a config.toml which has an option to pass "staticnodes". You can pass some good/honest peers to that list to make sure that your node reconnects to them even if they're disconnected. Can you try that as it might solve the peering issue and even if it doesn't work it eliminates this possibility?

**Comment by manav2401** [comment]
Closing this for now, feel free to reopen.
