### ISSUE TITLE
nil *StateSyncData calls panic

### ISSUE THREAD

**Issue by xdfdm** [maticnetwork/bor#686]
Our support team has aggregated some common issues and their solutions from past which are faced while running or interacting with a bor client. In order to prevent redundant efforts, we would encourage you to have a look at the [FAQ's section](https://docs.polygon.technology/docs/faq/technical-faqs) of our documentation mentioning the same, before filing an issue here. In case of additional support, you can also join our [discord](https://discord.com/invite/zdwkdvMNY2) server

#### **System information**

Bor client version: [e.g. v0.3.3] 

OS & Version: Windows / Linux / OSX

Environment: Polygon Mainnet

Type of node: Validator / Sentry / Archive

Additional Information: 

#### **Overview of the problem**

Please describe the issue you experiencing.

In some cases, nil values are received from stateSyncData chan. That calls panic.
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xdaa44f]

goroutine 896837 [running]:
github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).NewDeposits.func1()
	/go/src/github.com/maticnetwork/bor/eth/filters/bor_api.go:70 +0x16f
created by github.com/ethereum/go-ethereum/eth/filters.(*PublicFilterAPI).NewDeposits
	/go/src/github.com/maticnetwork/bor/eth/filters/bor_api.go:63 +0xea
```

#### **Reproduction Steps**

Case, when eventRecords in CommitStates func (consensus/bor/bor.go) is not zero-length slice

#### **Logs / Traces / Output / Error Messages**
 
Please post any logs/traces/output/error messages (as text and not screenshots) which you believe may have caused the issue. If the log is longer than a few dozen lines, please include the URL to the [gist](https://gist.github.com/) of the log instead of posting it in the issue.

**Additional Information**

In order to debug the issue faster, we would stongly encourage if you can provide some of the details mentioned below (whichever seems relevant to your issue)

1. Your `start.sh` file or `bor.service`, if you're facing some peering issue or unable to use some service (like `http` endpoint) as expected. Moreover, if possible mention the chain configuration printed while starting the node which looks something like `Initialised chain configuration config="{ChainID: 137, ..., Engine: bor}"`

2. The result of `eth.syncing`, `admin.peers.length`, `admin.nodeInfo`, value of the `maxpeers` flag in start.sh, and bootnodes/static nodes (if any) is you're facing some syncing issue.

3. Your `heimdall-config.toml` parameters for checking the ETH and BOR RPC url's, incase of issue with bor heimdall communication. 

4. The CURL request (for that specific error) if you're facing any issues or identify a bug while making RPC request.

**Comment by xdfdm** [comment]
The root of the problem is in /consensus/bor/bor.go in CommitStates func.
```
stateSyncs := make([]*types.StateSyncData, len(eventRecords))
```
initializes a new slice of the given length. If it is a slice with non-zero length, then it will contain default values ​​(nil).

**Comment by manav2401** [comment]
Please track the PR here: https://github.com/maticnetwork/bor/pull/695

**Comment by manav2401** [comment]
Closing this as the PR has been merged. Thanks!
