### ISSUE TITLE
Bor crashes with "panic: runtime error: index out of range [-1]"

### ISSUE THREAD

**Issue by Andrew-Pohl** [maticnetwork/bor#688]
#### **System information**

Bor client version: v0.3.3

Heimdall client version: v0.3.0

OS & Version: Linux Ubuntu 20.04

Environment: Polygon Mainnet

Type of node: Full node (RPC node)

#### **Overview of the problem**

Nodes regularly crash with the error "panic: runtime error: index out of range [-1]" we see this happening on all of our polygon nodes since upgrading to v0.3.3. Nodes restart fine and catch sync again but since the blocks aren't offloaded to disk they tend to have a little catching up to do.

#### **Logs / Traces / Output / Error Messages**
 
output of stack trace

Jan 17 22:54:41 ryzen-3 bor[2016306]: goroutine 36893181 [running]:
Jan 17 22:54:41 ryzen-3 bor[2016306]: github.com/ethereum/go-ethereum/core.(*txSortedMap).lastElement(0xc01b91e600)
Jan 17 22:54:41 ryzen-3 bor[2016306]:/home/ryzen-3/bor/core/tx_list.go:376 +0x1ed
Jan 17 22:54:41 ryzen-3 bor[2016306]: github.com/ethereum/go-ethereum/core.(*txSortedMap).LastElement(...)
Jan 17 22:54:41 ryzen-3 bor[2016306]:/home/ryzen-3/bor/core/tx_list.go:390
Jan 17 22:54:41 ryzen-3 bor[2016306]: github.com/ethereum/go-ethereum/core.(*txList).LastElement(...)
Jan 17 22:54:41 ryzen-3 bor[2016306]:/home/ryzen-3/bor/core/tx_list.go:568
Jan 17 22:54:41 ryzen-3 bor[2016306]: github.com/ethereum/go-ethereum/core.(*TxPool).runReorg.func1.6.4({0x2212a60?, 0xc0f993b7c0?}, {0x1?, 0x1?})
Jan 17 22:54:41 ryzen-3 bor[2016306]:/home/ryzen-3/bor/core/tx_pool.go:1575 +0xf6
Jan 17 22:54:41 ryzen-3 bor[2016306]: github.com/ethereum/go-ethereum/common/tracing.ElapsedTime({0x3066008?, 0xc0bce270b0?}, {0x3074d80?, 0xc13fdad800?}, {0x24599d6, 0xe}, 0xc0e32af858?)
Jan 17 22:54:41 ryzen-3 bor[2016306]:/home/ryzen-3/bor/common/tracing/context.go:91 +0xd1
Jan 17 22:54:41 ryzen-3 bor[2016306]: github.com/ethereum/go-ethereum/core.(*TxPool).runReorg.func1.6({0x1805b40?, 0xc13fdad800?}, {0x3074d80, 0xc13fdad800})
Jan 17 22:54:41 ryzen-3 bor[2016306]:/home/ryzen-3/bor/core/tx_pool.go:1573 +0x1df
Jan 17 22:54:41 ryzen-3 bor[2016306]: github.com/ethereum/go-ethereum/common/tracing.ElapsedTime({0x3066008?, 0xc0bce270b0?}, {0x3074d80?, 0xc13fdad800?}, {0x245139e, 0x9}, 0xc0e32afb28?)
Jan 17 22:54:41 ryzen-3 bor[2016306]:/home/ryzen-3/bor/common/tracing/context.go:91 +0xd1
Jan 17 22:54:41 ryzen-3 bor[2016306]: github.com/ethereum/go-ethereum/core.(*TxPool).runReorg.func1({0x3066008, 0xc0bce270b0}, {0x3074d80?, 0xc13fdad800?})
Jan 17 22:54:41 ryzen-3 bor[2016306]:/home/ryzen-3/bor/core/tx_pool.go:1543 +0x97d
Jan 17 22:54:41 ryzen-3 bor[2016306]: github.com/ethereum/go-ethereum/common/tracing.Exec({0x3065f98, 0xc0000560a0}, {0x2454668, 0xb}, {0x24575f3, 0xc}, {0xc0e32aff50, 0x1, 0xc0000b97d0?})
Jan 17 22:54:41 ryzen-3 bor[2016306]: /home/ryzen-3/bor/common/tracing/context.go:70 +0x20e
Jan 17 22:54:41 ryzen-3 bor[2016306]: github.com/ethereum/go-ethereum/core.(*TxPool).runReorg(0x0?, {0x3065f98?, 0xc0000560a0?}, 0xb75032?, 0xc0d55f81e8?, 0xc0f1522450?, 0xc0a92f0360?)
Jan 17 22:54:41 ryzen-3 bor[2016306]: /home/ryzen-3/bor/core/tx_pool.go:1461 +0xb2
Jan 17 22:54:41 ryzen-3 bor[2016306]: created by github.com/ethereum/go-ethereum/core.(*TxPool).scheduleReorgLoop
Jan 17 22:54:41 ryzen-3 bor[2016306]: /home/ryzen-3/bor/core/tx_pool.go:1403 +0x1fb

**Comment by manav2401** [comment]
Hi, looks like you're running a different version of bor. Can you confirm if the branch/tag being used is `v0.3.3`? I think these changes are in our `develop` branch and I can't trace them in `v0.3.3` as they don't exist here. Specifically the `tracing.Exec` ones.

**Comment by Andrew-Pohl** [comment]
Hey @manav2401 thanks for the reply it is built against 56d3058561002ce689cd8ac4c840c701bc91ca3f which is the commit tagged as v0.3.3. 

I will try:

1. a fresh rebuild
2. the prebuilt package to check if it is an issue with my build

**Comment by temaniarpit27** [comment]
Closing this for now. Please reopen if required
