### ISSUE TITLE
Incorrect output for eth_getTransactionByBlockHashAndIndex

### ISSUE THREAD

**Issue by quickchase** [maticnetwork/bor#689]
#### **System information**

Bor client version: `bor/v0.3.3-stable/linux-amd64/go1.19.4`

OS & Version: Linux

Environment: Polygon Mainnet

Type of node: Archive

#### **Overview of the problem**

The output of `eth_getTransactionByBlockHashAndIndex` is incorrect.

#### **Reproduction Steps**

Correct hash returned by `eth_getBlockByHash`:
```
'{"jsonrpc":"2.0","id":1,"method":"eth_getBlockByHash","params":["0xbcba847d541055da03e56c9ece85f477bc2ab3158ba209d10780d84e7ebefad0",true]}' | jq '.result.transactions[0].hash'

0xac14379f12becd31c1e2b1d89aebe8b33f1f6c6341cfe48e59fbda0f381a8688
```

Incorrect output from `eth_getTransactionByBlockHashAndIndex`:
```
'{"jsonrpc": "2.0", "id": 1, "method": "eth_getTransactionByBlockHashAndIndex", "params": ["0xbcba847d541055da03e56c9ece85f477bc2ab3158ba209d10780d84e7ebefad0", "0x0"]}' | jq '.result.hash'

0xe79e4719c6770b41405f691c18be3346b691e220d730d6b61abb5dd3ac9d71f0
```

#### **Logs / Traces / Output / Error Messages**

**Additional Information**

Erigon `v0.0.5` returns the correct value

https://polygonscan.com/txs?block=38217600

**Comment by temaniarpit27** [comment]
Closing this as it will be released soon. Please check above PR

**Comment by marcello33** [comment]
Hey @jiezhang 
The code changes are included in the latest release.
Please compare the PR to the code in `v0.3.9`
In you meant the release notes' changelog, it was embedded in "bugfixes", but I just added it explicitly.
Thanks

**Comment by marcello33** [comment]
Hey @jiezhang the fix is there. The file also reports additional changes not related to this issue.
Please, feel free to test and get back to us.
We just ran the query on an updated node running `v0.3.9-stable`, following the results:
```
curl -X POST \
>      -H 'Content-Type: application/json' \
>      -d '{"jsonrpc":"2.0","id":1,"method":"eth_getBlockByHash","params":["0xbcba847d541055da03e56c9ece85f477bc2ab3158ba209d10780d84e7ebefad0",true]}' \
>      http://localhost:8545/ | jq '.result.transactions[0].hash'
"0xac14379f12becd31c1e2b1d89aebe8b33f1f6c6341cfe48e59fbda0f381a8688"

curl -X POST \
>      -H 'Content-Type: application/json' \
>      -d '{"jsonrpc": "2.0", "id": 1, "method": "eth_getTransactionByBlockHashAndIndex", "params": ["0xbcba847d541055da03e56c9ece85f477bc2ab3158ba209d10780d84e7ebefad0", "0x0"]}' \
>      http://localhost:8545/ | jq '.result.hash'
"0xac14379f12becd31c1e2b1d89aebe8b33f1f6c6341cfe48e59fbda0f381a8688"
```
