### ISSUE TITLE
Error: Block 38189056 was created too soon. Signer turn-ness number is 1

### ISSUE THREAD

**Issue by Adeel-trimulabs** [maticnetwork/bor#690]
I am facing BAD BLOCK error while syncing bor chain. Heimdall chain is fully synced.

#### **System information**

Bor client version: [e.g. v0.2.17] 

Heimdall client version: [e.g. v0.2.9] 

OS & Version: Linux 

Environment: Polygon Mainnet 

Type of node: Archive

  Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
  CPU(s):                  4

#### **Overview of the problem**
````
 INFO [01-18|19:06:51.576] Skip duplicated bad block                number=38,189,056 hash=19bcd5..d632d6
 ERROR[01-18|19:06:51.577]
 ########## BAD BLOCK #########
Chain config: {ChainID: 137 Homestead: 0 DAO: <nil> DAOSupport: false EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Arrow Glacier: <nil>, MergeFork: <nil>, Terminal TD: <nil>, Engine: bor}
 Number: 38189056
Hash: 0x19bcd5f19d3f928aae2b582b0e005c963a8ef0bfd005d1b639a5b0b5dbd632d6
 Error: Block 38189056 was created too soon. Signer turn-ness number is 1
 ##############################

WARN [01-18|19:06:51.586] Synchronisation failed, dropping peer    peer=bc71f4028f1138ba1c672b76989fefd37c780e19f12c34de7a686b9c38b20496 err="retrieved hash chain is invalid: Block 38189056 was created too soon. Signer turn-ness number is 1\n"
````

#### **Normal Behaviour**

As heimdall chain is synced so normally bor chain start on syncing.

#### **Things I have tried**
- set bor chain header to 100 block back but it will stuck at this block again.
- restart heimdall chain.
- download latest snapshots of heimdall chain. 

nothing work for me. Please help me to figure it out. Thanking in advance.

**Comment by cffls** [comment]
Hi @Adeel-trimulabs , 38189056 was a hardfork, which changes the sprint length from 64 to 16. Since you were using bor v0.2.17, it still believes that the sprint shouldn't change at block 38189056. To resolve this issue, please upgrade bor to v0.3.3 and heimdall to v0.3.0. You can find the guide in this forum post: https://forum.polygon.technology/t/bor-mainnet-upgrade-v0-3-3-action-required/10851

**Comment by temaniarpit27** [comment]
Please reopen if required
