### ISSUE TITLE
Is there a way to reduce the amount of blocks to be synchronized??

### ISSUE THREAD

**Issue by nomotobori** [maticnetwork/bor#709]
Although We use a snapshot, it takes a long time to fully sync for the Heimdall and Bor services.
Is there a way to reduce the amount of blocks to be synchronized??
Also, Please let me know how to set that up.

Supplementation
Why do we need a lot of blocks to be synchronized for Heimdall and Bor services.
If the amount of blocks is small, the storage size clould be smaller and Heimdall and Bor clould full sync as soon as possible.

https://github.com/maticnetwork/heimdall/issues/941

**Comment by temaniarpit27** [comment]
Syncing blocks on bor and heimdall services depends upon various conditions like -
1. Number of healthy peers connected to.
2. Machine configuration
3. Network latency etc.
We suggest you use the recommended specs for better results.

**Comment by temaniarpit27** [comment]
Closing this for now. Please reopen if required
