### ISSUE TITLE
go.mod - incorrect module declaration

### ISSUE THREAD

**Issue by danielkokobt** [maticnetwork/bor#713]
#### **System information**

Bor client version: v0.3.3

#### **Overview of the problem**

In this project's `go.mod` it declares itself as `go-ethereum`. This prevents this repo from being imported as a dependency of other projects. When trying to include it, it produces the error:

```
go: /path/to/project imports
	github.com/maticnetwork/bor/accounts/abi: github.com/maticnetwork/bor@v0.3.3: parsing go.mod:
	module declares its path as: github.com/ethereum/go-ethereum
	        but was required as: github.com/maticnetwork/bor
```

https://github.com/maticnetwork/bor/blob/develop/go.mod#L1

```
module github.com/ethereum/go-ethereum
```

This is wrong. It should be 

```
module github.com/maticnetwork/bor
```

**Comment by mrwormhole** [comment]
I think this is a good catch, is there a good reason why go.mod is still pointing to the old fork repository? if not, I think anyone is happy to submit a PR @0xsharma

**Comment by 0xKrishna** [comment]
If we switch it to use `module github.com/maticnetwork/bor` it creates multiple problems with upstream changes and other dependencies, The way we are dealing with this is by using `replace`

https://github.com/maticnetwork/heimdall/blob/develop/go.mod#L64

**Comment by temaniarpit27** [comment]
Closing this for now. Reopen if required
