### ISSUE TITLE
validator

### ISSUE THREAD

**Issue by dg123lzk** [maticnetwork/bor#716]
如何获取爆块收益地址

**Comment by manav2401** [comment]
Can you elaborate more on the issue?

**Comment by dg123lzk** [comment]
> 

The block miner obtained from the full node is 0 address, how can I get the real miner address

**Comment by temaniarpit27** [comment]
You can get the value from IPC/RPC call - `bor.getAuthor()`
Let me know if this helps.

**Comment by temaniarpit27** [comment]
Closing this for now. Reopen if required
