### ISSUE TITLE
What value of `bor.heimdall` should be used for mumbai?

### ISSUE THREAD

**Issue by paymog** [maticnetwork/bor#723]
https://github.com/maticnetwork/bor/pull/185 mentions that `bor.heimdall` should be used when heimdall isn't running locally. I've found that `--bor.heimdall=https://heimdall.api.matic.network` can be used with `--bor-mainnet` but I can't seem to find the correct heimdall url when running on mumbai. 

Does anyone have the heimdall url for mumbai handy?

**Comment by paymog** [comment]
as usual, found the answer immediately after asking: https://heimdall-api-testnet.polygon.technology/

**Comment by pratikspatil024** [comment]
Hi @paymog, I see that you've found the answer. Therefore closing this. Re-open if required.
