### ISSUE TITLE
BlockByNumber returns the wrong hash if querying against erigon via ws or http json-rpc

### ISSUE THREAD

**Issue by faraonc** [maticnetwork/bor#735]
## Repro:
`go.mod`  is updated to use `bor`
```
replace github.com/ethereum/go-ethereum v1.10.25 => github.com/maticnetwork/bor v0.3.3
```
`main.go`
```go
package main

import (
	"context"
	"fmt"
	"github.com/ethereum/go-ethereum/ethclient"
	"github.com/ethereum/go-ethereum/rpc"
	"math/big"
	"os"
)

func main() {
	r, err := rpc.DialWebsocket(context.Background(), "ws://localhost:8545", "")
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}
	client := ethclient.NewClient(r)
	//blockNumber := big.NewInt(12424135)
	blockNumber := big.NewInt(39000227)
	b, err := client.BlockByNumber(context.TODO(), blockNumber)
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}
	fmt.Println(blockNumber.Int64())
	fmt.Println(b.Hash())
} 
```

This returns the following:
```
39000227
0x8daf7f2399eea1f049736ae2d0fd4d644ba5c006629a1d68b64580f0f0162a7a
```

The hash does not match https://polygonscan.com/block/39000227 and running a direct `curl` request e.g. using blocknumber in hexadecimal ` 0x25318A3` (39000227 hexadecimal equivalent)

![image](https://user-images.githubusercontent.com/16410475/217707994-90292729-79cb-4b19-ac65-41f5fc912491.png)

EDIT: This is running against a full archive erigon using https://github.com/maticnetwork/erigon/releases/tag/v0.0.5. Everything else is the same, but the hash

**Comment by 0xKrishna** [comment]
I am bit confused, You are saying that on bor it gives correct response and on erigon the block hash is different ?

**Comment by anshalshukla** [comment]
This will fix the issue.
