### ISSUE TITLE
Cannot set rpc.evmtimeout

### ISSUE THREAD

**Issue by quickchase** [maticnetwork/bor#737]
On the latest version of bor `v0.3.3` we can no longer set `rpc.evmtimeout`

The `bor server` does not expose this flag and complains when it is added...

It's still a flag listed in the flags.go file but I can't see a way to set it.

Also the `example_config.toml` does not include this as an option anywhere.

How can we set `rpc.evmtimeout` in the newer versions?

**Comment by pratikspatil024** [comment]
Hi, @quickchase thank you for bringing this to our notice.

We have added support for this flag [here](https://github.com/maticnetwork/bor/commit/ba0cca0feb1d5f1204afdf7e203489a783ef3122) and will include this in the next release. Thank you.

**Comment by quickchase** [comment]
Hey guys, you forgot to include this in the release 😆

**Comment by pratikspatil024** [comment]
Hi @quickchase the 0.3.5 release was a higher-priority one, and we didn't want to wait further to release it.
These changes were not included in it intentionally. That being said, we will include in it v0.3.6. Thank you.
