### ISSUE TITLE
Websocket fails to notify reorg blocks and logs

### ISSUE THREAD

**Issue by ggarri** [maticnetwork/bor#741]
Polygon websocket connector and we are noticing some unexpected behaviors in case or reorgs. 

#### **System information**

Bor client version: 0.3.3
OS & Version: Linux
Environment: Polygon Mainnet
Type of node:  Archive

#### **Overview of the problem**

Missing notification on the new canonical blocks in case of reorg and missing notification for removed logs belonging to reorg blocks and even for new logs within new canonical blocks

#### **Logs / Traces / Output / Error Messages**

1. Block 39280934 with hash 0xd579e0e2625ef72acee951e5c411442800bafb46c62f93cf4d85bcdfb5d084d5 is notified at 2023-02-14T11:44:31Z
2. Block logs of 39280934 with hash 0xd579e0e2625ef72acee951e5c411442800bafb46c62f93cf4d85bcdfb5d084d5 for subscribed address 0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063 are notified at 2023-02-14T11:44:31Z
3. Block 39280934 has been REORG with hash 0x177aaef57f32d23e0b2912303782dc0e49d4f05c8af771007cab99154456569b and it is notified at 2023-02-14T11:44:32Z

As defined in the [geth documentation](https://geth.ethereum.org/docs/interacting-with-geth/rpc/pubsub#logs) I should be expecting the removed logs of block 39280934` to be notified along with the new logs including the new block hash in it

**Additional Information**

I am also seeing scenarios where a reorg block is not notified, such as block 39283599 has been notified at 2023-02-14T13:30:17Z with hash 0x10ff47d2d0f0ce5cadd67eafd4fc47ce36547a0bfd6baea983c5a4bfbe2b892c but it was notified with hash 0xb03b78a10f4e9153098b340af85cebb0479afd6366edd74b85be56b27ea1dbba which is the final canonical one

**Comment by Raneet10** [comment]
Hi @ggarri , we'll be taking a look into this and get back. Thank you for raising the issue!

**Comment by Raneet10** [comment]
Hi @ggarri , apologies for reverting so late. I wanted to confirm whether you're still facing this issue after upgrading to the latest bor version (v0.3.7) ?

**Comment by Raneet10** [comment]
Hey @ggarri , I tried listening to reorged log events (not pertaining to any particular address/topic) and was able to successfully do so. I'm closing this issue for now, but please feel free to reopen if you consistently face the problem.
