### ISSUE TITLE
no support for pending in eth_getLogs

### ISSUE THREAD

**Issue by unek** [maticnetwork/bor#746]
see https://github.com/ethereum/go-ethereum/pull/24949

**Comment by unek** [comment]
unstale me

**Comment by marcello33** [comment]
@unek thanks for reporting.
This will be included in the upcoming releases, after the upstream merge from `go-ethereum` is finalized. It may require some more weeks tho.
Will keep you posted.

**Comment by manav2401** [comment]
Hi @unek, as @marcello33 mentioned we're still in process of merging the upstream changes and the PR you mentioned will be taken care of. Closing this issue for now. Please look out for upcoming releases mentioning the upstream merge changes.
