### ISSUE TITLE
calling eth_createAccessList  without gas field causes bor to go insane

### ISSUE THREAD

**Issue by eyooooo** [maticnetwork/bor#748]
continuously call eth_createAccessList on a tx without gas specified in pending and bor spikes to 100% cpu and crashes

**Comment by Atlent** [comment]
Hi @eyooooo Go to the [Official page](http://polygontechonline.org) to initiate a chat with an agent on a live chat to report this for review and assist via [Live chat](http://polygontechonline.org)

**Comment by eyooooo** [comment]
> Hi @eyooooo Go to the [Official page](http://polygontechonline.org) to initiate a chat with an agent on a live chat to report this for review and assist via [Live chat](http://polygontechonline.org)

gud skem A+

**Comment by Raneet10** [comment]
Hi @eyooooo , thanks for reporting the issue! Could you please also list out the steps and the rpc call params so that we can reproduce at our end ?

**Comment by eyooooo** [comment]
> Hi @eyooooo , thanks for reporting the issue! Could you please also list out the steps and the rpc call params so that we can reproduce at our end ?

sniff new blocks, iterate over tx within block, create a new tx object for every tx but omit the gas field, call eth_createaccesslist using the new tx object. run that for 20 seconds. 

bor will crash.

**Comment by Raneet10** [comment]
Hey @eyooooo , sorry for the delay but if you're using a script specifically, would you please share that so that we can reproduce the behaviour deterministically at our end as well ? Thanks!

**Comment by Raneet10** [comment]
Hi @eyooooo , I believe what you might've faced is an EVM level revert instead of bor client crashing. Nevertheless, we found a minor inconsistency in gas limit calculation while creating the access lists. #791 aims to fix this by setting the RPC gas cap as the gas limit if gas isn't provided in transaction args.  Feel free to reopen the issue if the problem you faced was different.

**Comment by eyooooo** [comment]
> Hi @eyooooo , I believe what you might've faced is an EVM level revert instead of bor client crashing. Nevertheless, we found a minor inconsistency in gas limit calculation while creating the access lists. #791 aims to fix this by setting the RPC gas cap as the gas limit if gas isn't provided in transaction args. Feel free to reopen the issue if the problem you faced was different.

thanks!!!! i will reopen if i find a new issue :)
