### ISSUE TITLE
GetTransactionByHash not work for old tx

### ISSUE THREAD

**Issue by BillyTsangGC** [maticnetwork/bor#756]
I am a node in full and archive mode, and the data is now 26T. When I upgrade from v0.2.17 to v0.3.3, etc_ GetTransactionByHash and eth_ The getTransactionReceipt method cannot retrieve the previous old data, such as the transaction list data with a height of 35000000. The return is null, etc_ GetBlockByNumber is normal.

**Comment by 0xsharma** [comment]
Hey @BillyTsangGC , 
Can you please check the following : 

- Your node is synced. ( check using `eth_blockNumber`).
- Tell us the `transactionHash` that you're not able to retrieve. 
- Check `--txlookuplimit` flag in your config and tell us its value if custom value is used.

Kindly revert with the above and we shall resolve it.
Thank you 💜

**Comment by ntauth** [comment]
Same issue here, when calling `eth_getBlockByHash`, I get empty `UncleHashes` but I do see transactions. The issue is that the underlying transactions are `nil`

<img width="546" alt="Screenshot 2023-03-06 at 19 43 16" src="https://user-images.githubusercontent.com/13150392/223202328-a22d889d-475b-4467-86a8-d2c5d85818a6.png">

**Comment by jsvisa** [comment]
Seems the transaction is not indexed or removed, does the node run archive mode from genesis block or not?

**Comment by BillyTsangGC** [comment]
> Hey @BillyTsangGC , Can you please check the following :
> 
> * Your node is synced. ( check using `eth_blockNumber`).
> * Tell us the `transactionHash` that you're not able to retrieve.
> * Check `--txlookuplimit` flag in your config and tell us its value if custom value is used.
> 
> Kindly revert with the above and we shall resolve it. Thank you 💜

thank you very much! This problem has been solved with setting `--txlookuplimit=0`.
