### ISSUE TITLE
Pruned snapshot not available anymore and fullnode snapshot is syncing very slowly

### ISSUE THREAD

**Issue by suggalla** [maticnetwork/bor#757]
We were previously using the following S3 bucket (https://matic-blockchain-snapshots.s3-accelerate.amazonaws.com/matic-mainnet/') to pull pruned snapshots but it is not available any more. We've opted to using the full node snapshots (https://snapshots.polygon.technology/) which is still syncing the node from scratch and incredibly slowly.

**Comment by RomainParracone** [comment]
We are running into the same issue, is there any plan to provide pruned snapshots again?

**Comment by 0xKrishna** [comment]
Hi Guys, I have discussed this with my devops team and they have said that the bor snapshots on our snapshot website are pruned by default.

```

bor-mainnet-fullnode | https://snapshot-download.polygon.technology/bor-mainnet-fullnode-2023-02-27.tar.gz | 1412.51 GB | 2023-02-28 | dd0bceaa2da5657d819e2fe53ad1dfe1
-- | -- | -- | -- | --



```

**Comment by 0x090909** [comment]
Can you publish the version that also is ancient pruned? Its a big mess to download and extract at the same time 1.3T of data
