### ISSUE TITLE
Any issue with heimdall.api.matic.network

### ISSUE THREAD

**Issue by gitmewai** [maticnetwork/bor#764]
Is there any problem with the FQDN of `heimdall.api.matic.network`?

Since Mar 03 07:41:21 UTC our erigon `v0.0.5` node cannot connect to `bor-mainnet` any more.

```
Mar 03 07:41:21 polygon-erigon-1 polygon[2053]: bor    | [INFO] [03-03|07:41:21.073] Retrying again in 5 seconds for next Heimdall span path=clerk/event-record/list
Mar 03 07:41:26 polygon-erigon-1 polygon[2053]: bor    | [INFO] [03-03|07:41:26.074] Retrying again in 5 seconds for next Heimdall span path=clerk/event-record/list
Mar 03 07:41:31 polygon-erigon-1 polygon[2053]: bor    | [INFO] [03-03|07:41:31.075] Retrying again in 5 seconds for next Heimdall span path=clerk/event-record/list
Mar 03 07:41:36 polygon-erigon-1 polygon[2053]: bor    | [INFO] [03-03|07:41:36.081] Retrying again in 5 seconds for next Heimdall span path=clerk/event-record/list
Mar 03 07:41:41 polygon-erigon-1 polygon[2053]: bor    | [INFO] [03-03|07:41:41.082] Retrying again in 5 seconds for next Heimdall span path=clerk/event-record/list
Mar 03 07:41:46 polygon-erigon-1 polygon[2053]: bor    | [INFO] [03-03|07:41:46.084] Retrying again in 5 seconds for next Heimdall span path=clerk/event-record/list
```

```
nslookup heimdall.api.matic.network 1.1.1.1
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
*** Can't find heimdall.api.matic.network: No answer
```

Thanks

**Comment by dwjorgeb** [comment]
I think they changed the URL to https://heimdall-api.polygon.technology , according to the doc here: https://wiki.polygon.technology/docs/operate/endpoints

I had the same issue with one of our nodes

**Comment by MakC-Ukr** [comment]
Does the new link not support any requests for the /checkpoint module? Any kind of request from the `/checkpoint` module shows a 404 error. For example :
- [https://heimdall-api.polygon.technology/checkpoint/buffer](https://heimdall-api.polygon.technology/checkpoint/buffer)
- [https://heimdall-api.polygon.technology/checkpoint/list](https://heimdall-api.polygon.technology/checkpoint/list)
- [https://heimdall-api.polygon.technology/checkpoint/latest-checkpoint](https://heimdall-api.polygon.technology/checkpoint/latest-checkpoint)

I am trying the  list of /checkpoint module's methods from [here](https://wiki.polygon.technology/docs/pos/heimdall/modules/checkpoint#rest-apis)

However, some other modules are working fine. For example, following links are working:
- [https://heimdall-api.polygon.technology/chainmanager/params](https://heimdall-api.polygon.technology/chainmanager/params)
- [https://heimdall-api.polygon.technology/blocks/latest](https://heimdall-api.polygon.technology/blocks/latest)

**Comment by pratikspatil024** [comment]
Hey, @gitmewai thank you for the query. As @dwjorgeb pointed out the URL has changed to https://heimdall-api.polygon.technology/.

@MakC-Ukr - you can use this [link](https://heimdall-api.polygon.technology/swagger-ui/#/checkpoint) to find the updated endpoints and the params expected by that endpoint. Thank you.

**Comment by pratikspatil024** [comment]
Updated the wiki page. Thank you. Reopen this issue/create a new one if you still have questions.
