### ISSUE TITLE
documentation: why is opening port 22 to necessary

### ISSUE THREAD

**Issue by OliverNChalk** [maticnetwork/bor#775]
I was unable to find any documentation on why opening port 22 is necessary? For instance, on what networks is bor listening for traffic to port 22?

**Comment by pratikspatil024** [comment]
Hi, @OliverNChalk [this](https://wiki.polygon.technology/docs/maintain/validate/kb/additional-info/port-config) will give you some information regarding `Port 22`. Thanks.

**Comment by OliverNChalk** [comment]
Thanks for the reply @pratikspatil024 , however, the documentation just says opening port 22 is risky, it does not say what maticnetwork uses it for?

**Comment by OliverNChalk** [comment]
Ahh, I see now. Port 22 is only required for node's servicing validators. I misunderstood the guide, I think the wording might be okay though when I read through I was left thinking port 22 was required for node operation.

![image](https://user-images.githubusercontent.com/11343499/225353676-4bc6af72-4cc0-4a57-ae00-bb14099d7d07.png)

Perhaps this line could become:
```
22 - Open this port if you node is servicing validators. You will likely want to restrict what traffic can access this port as it is a sensitive port.
```

**Comment by pratikspatil024** [comment]
Thanks for the feedback @OliverNChalk. Will let the right person know about this. Closing this for now.
