### ISSUE TITLE
bor 0.3.6 is so slow that the sync will never reach the tip; 0.3.3 runs very fast

### ISSUE THREAD

**Issue by egorFiNE** [maticnetwork/bor#784]
#### **System information**

Bor client version: v0.3.6

Heimdall client version: v0.3.0

OS & Version: Ubuntu 22.04 amd64

Environment: Polygon Mainnet 

Type of node: ?? not sure, just a node

#### **Overview of the problem**

Bor syncs few blocks per minute. 

#### **Reproduction Steps**

1. Make sure heimdall is running and is synced. 
2. Download snapshop from https://snapshots.polygon.technology
3. Run bor with the attached config file 
4. Wait 5-30 minutes
5. Bor will eventually start syncing but it only syncs like 40 blocks every few minutes

This speed makes it impossible to follow the tip. 

#### **Logs / Traces / Output / Error Messages**

See logs attached as collected from the bor launch until the first batch of blocks were synced. 

#### **Additional information**
 
The hardware is more than enough: 64GB RAM, local NVM SSD, 12 cores. `top` shows at least 50% CPU idle. 

[config-s.toml.txt](https://github.com/maticnetwork/bor/files/11009029/config-s.toml.txt)
[bor.log](https://github.com/maticnetwork/bor/files/11009078/bor.log)

**Comment by JekaMas** [comment]
@VAIBHAVJINDAL3012 could you take a look on the issue?

**Comment by egorFiNE** [comment]
I did a fresh start. Downloaded latest snapshot and launched bor with the same `config-s.toml` as attached above. 

It indexes a couple of blocks per minute. 

I've got plenty of CPU, plenty of disk i/o, plenty of RAM and plenty of network bandwidth. 

Log attached. 

What could be done to actually run a node?
[freshstart.log](https://github.com/maticnetwork/bor/files/11016949/freshstart.log)

**Comment by egorFiNE** [comment]
alright, about 7k blocks synced today. Again, this will never reach the tip.

**Comment by 0xKrishna** [comment]
Can you share more logs ?
From the above logs it's looking fine to me
```INFO [03-20|10:47:41.751] Imported new chain segment               blocks=14  txs=1021 mgas=219.955 elapsed=8.480s    mgasps=25.936 number=40,479,436 hash=5f0bec..b4b011 age=2d4h19m  dirty=38.02MiB
```
mgas above 200 is really good.

**Comment by egorFiNE** [comment]
@0xKrishna that's all the logs I have. The problem is in the time: new chain segments are imported once every few *minutes*.

**Comment by 0xKrishna** [comment]
With the same config ?

**Comment by egorFiNE** [comment]
@0xKrishna yep.

**Comment by 0xKrishna** [comment]
Okay, Thanks for reporting, Will surely take a look on our internal nodes as well.
cc @manav2401 @cffls

**Comment by egorFiNE** [comment]
@0xKrishna shall I try 0.3.4 and 0.3.5?

**Comment by jsvisa** [comment]
Could you please first confirms the `net_peerCount` is enough?

**Comment by egorFiNE** [comment]
...aaaaaand it's gone

> Error: invalid merkle root (remote: 0041b7f2b1e5e4eb690f1240e0c9633c3fd5dd0cdec39ab6812066dbe6a7e2f1 local: 7da5c0f63c2a20af4eb86a4dbcfdc0a3d373ff9b7d8df485c8a80ebd840a0dfc)

And that's it. Full stop, no more sync past block 40564255. 

Should I abandon?

**Comment by egorFiNE** [comment]
@jsvisa yes, tens of peers, I was watching that.

**Comment by egorFiNE** [comment]
Lucky me, I have saved a btrfs snapshot of the initial downloaded and extracted snapshot from https://snapshots.polygon.technology. 

Restarting now on 0.3.3. Although likely it will fail again.

**Comment by egorFiNE** [comment]
> could you please provide more metrics via /debug/metrics/prometheus

Please let me know how to do this. I have never used this.

**Comment by egorFiNE** [comment]
@jsvisa will do later, thanks! Meanwhile 0.3.3 is happily gulping blocks, I'm afraid to touch it

**Comment by egorFiNE** [comment]
@petejkim thanks! Indeed heimdall died.

**Comment by egorFiNE** [comment]
So, 0.3.3 synced perfectly fine and quite fast once I have fixed heimdall. 

Now the question is: should I even attempt to run 0.3.4+? I have used 0.3.6 before and it constantly lagged behind even on a fully synced 0.3.3 database. Shall I now start 0.3.6 with Prometheus, @jsvisa?

**Comment by 0xKrishna** [comment]
Don't use v0.3.6, Closing this as the core issue is now resolved as we can also confirm that current v0.3.6 is not stable and we are woking on it.

**Comment by egorFiNE** [comment]
Thanks. 

@0xKrishna just a quick question: 0.3.4 and 0.3.5 are fine or should I stay on 0.3.3?

**Comment by 0xKrishna** [comment]
Upto v0.3.5 is fine, We are working v0.3.6
But I would suggest to stay on v0.3.4 or 3 till the official announcement.

**Comment by egorFiNE** [comment]
@0xKrishna is 0.3.7 the fix?

**Comment by 0xKrishna** [comment]
Please wait for the official announcement, We are still testing v0.3.7

**Comment by egorFiNE** [comment]
@0xKrishna given the proliferation of different Polygon accounts on social media, what would be the best place to look for the official announcement?

**Comment by 0xKrishna** [comment]
https://forum.polygon.technology/c/polygon-pos-updates/announcements/77

**Comment by egorFiNE** [comment]
@0xKrishna so does 0.3.7 fix this issue?
