### ISSUE TITLE
Heimdall getting "error during handshake: error on replay"

### ISSUE THREAD

**Issue by Aracki** [maticnetwork/bor#786]
We've started Polygon Mumbai from scratch, and we are getting heimdall errors:
```
INFO [2023-03-20|09:09:32.893] starting ABCI with Tendermint                module=main
DEBUG[2023-03-20|09:09:32.919] Invalid ETH RPC timeout provided, falling back to default value timeout=5s
DEBUG[2023-03-20|09:09:32.919] Invalid BOR RPC timeout provided, falling back to default value timeout=5s
ERROR: failed to create new node: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected 60C58E8E383EE496FC5430E1344878945D595A5266750C9B2F3FC25598CA5665, got CCB7437AFC0588D4A9514F52CB2F45FFA08313E489ED380E703FD5C38051F0F9
```

and bor:
```
########## BAD BLOCK #########
Error: invalid merkle root
```

**Comment by 0xKrishna** [comment]
Please share the steps you used to start heimdall and your config files.

**Comment by Aracki** [comment]
We've started heimdall 0.3.0 with bor `0.3.2-beta` version instead of `0.3.3` at least. 

When I started with 0.3.0 and configuration placed in TOML file, there were no heimdall issues like above. And our current latest block is higher than where it was when we were getting these heimdall errors.

Maybe not related at all, not sure though 🤷

Will close this one, and reopen if we experience this again.
