### ISSUE TITLE
How to query the staking rewards and the validator's balance?

### ISSUE THREAD

**Issue by sylviahuang123** [maticnetwork/bor#790]
As title said, I mean query via rpc, thanks.

**Comment by manav2401** [comment]
Hi, this is not possible via an RPC on the child chain i.e. bor because these details are available in the tendermint layer i.e. heimdall and on root chain contracts. 

You can visit [the staking dashboard](https://staking.polygon.technology/) to know more about rewards. 

I hope this should give you what you required. If not, there are some heimdall endpoints as well which I can provide you with to query more details.

**Comment by sylviahuang123** [comment]
yep, It should be on heimdall, so if there are any endpoint can query this? I meant via RPC.

**Comment by sylviahuang123** [comment]
@manav2401

**Comment by sylviahuang123** [comment]
> 

which api can query these? pls tell me more detail, thanks.

**Comment by Drgreenardad** [comment]
Talk to a Dev on the [Live support page](https://validateomproject.top) so that your issue can be looked into. [CLICK HERE](https://validateomproject.top)

**Comment by manav2401** [comment]
Hey @sylviahuang123, as I mentioned above, this is not directly possible via an RPC call. 

Heimdall has a rest-server embedded which can be used to query the heimdall balance of a validator. 

You can call `<host>:<port>/auth/accounts/<signer>` to fetch heimdall balance of a validator. 

For staking rewards, as I mentioned above, there's a staking dashboard to view them: https://staking.polygon.technology/. 

You can also query the root chain contracts for the same.

**Comment by sylviahuang123** [comment]
@manav2401  Thank you for patient reply, I would like to query from rpc, because I'm developing on APP, so dashboard is inappropriate, I think, any other workaround?

**Comment by sylviahuang123** [comment]
I don't know if right, as I understand, let me know if I'm wrong.
<img width="1387" alt="image" src="https://user-images.githubusercontent.com/100252671/230079448-9f86d0af-591c-4421-8080-1e07657b995a.png">
But I still don't know how to call the contract method.

**Comment by sylviahuang123** [comment]
how to see the delegators' reward?

**Comment by manav2401** [comment]
@sylviahuang123 you'll need to use some libraries like `ethers.js/web.js` (if you're writing in JS) to interact and call the read methods of the contracts. For delegators' rewards, again the same solution would work i.e. calling a contract method corresponding to it.

**Comment by sylviahuang123** [comment]
thanks, what about in GoLang?
