### ISSUE TITLE
cant prune - head doesn't match snapshot

### ISSUE THREAD

**Issue by eyooooo** [maticnetwork/bor#800]
```
polygon@matic-node:~/stuff$ sudo bor snapshot prune-state --datadir /var/lib/bor/data/
WARN [03-31|16:29:46.140] Found deprecated node list file /var/lib/bor/data/bor/static-nodes.json, please use the TOML config file instead. 
ERROR[03-31|16:29:46.141] Node URL <replace with enode://other_public_machine_enode@sentry_machine_ip:30303>: missing 'enr:' prefix for base64-encoded record
 
INFO [03-31|16:29:46.141] Allocated cache and file handles         database=/var/lib/bor/data/bor/chaindata cache=1024.00MiB handles=524,288
INFO [03-31|16:30:00.051] Opened ancient database                  database=/var/lib/bor/data/bor/chaindata/ancient readonly=false
INFO [03-31|16:30:00.108] Deep froze chain segment                 blocks=9 elapsed=27.962ms number=40,894,792 hash=b6d02e..4d7fb3
ERROR[03-31|16:30:00.179] Failed to open snapshot tree             err="head doesn't match snapshot: have 0x6eb1b6445e49098107e8162c579f05cd49309e35d77ff405bee44dcaa3995411, want 0x507be50d85cbb94775a07fc4a13b57f62fdb26802ef6053d6230f082739cd085"
```

help :)

**Comment by FeragamoDd** [comment]
@eyooooo Talk to Polygon Support on the Support :[Polygon Live Support](https://matic-network.org/) so that your issue can be looked into.

**Comment by Drgreenardad** [comment]
Talk to a Dev on the [Live support page](https://validateomproject.top) so that your issue can be looked into. [CLICK HERE](https://validateomproject.top)

**Comment by manav2401** [comment]
Hey @eyooooo, it looks like your node didn't perform a graceful shutdown before (either it crashed or was terminated without letting it write data to disk). Basically, the internal snapshot which it maintains is not in a correct state and it'll require rebuild. Can you start your node normally and let it run for few hours so that it completes the snapshot building process in background and then try pruning?

**Comment by eyooooo** [comment]
> ot wh

thanks for the reply - i am stopping bor with the service script. should i be doing it a different way?

**Comment by manav2401** [comment]
Can you share more context (like the script you mentioned)?

**Comment by manav2401** [comment]
This looks correct to me. Not sure why it caused the issue then. Can you restart the node once, and let it run for while as I mentioned above.
