### ISSUE TITLE
Should Bor be stopped when Heimdall falls out of sync?

### ISSUE THREAD

**Issue by RomainParracone** [maticnetwork/bor#802]
The [documentation](https://wiki.polygon.technology/docs/operate/full-node-binaries) explicitly states that Bor should be started only once Heimdall is fully synced:

> Now, you need to make sure that Heimdall is synced completely, and then only start Bor. If you start Bor without Heimdall syncing completely, you will run into issues frequently.

It is not clear what should be done if, after operating for some time, Heimdall falls out of sync. Should Bor be stopped until Heimdall syncs again?

**Comment by manav2401** [comment]
Hey @RomainParracone, so bor relies on heimdall for processing few bridge transactions. If heimdall is out of sync, bor would keep waiting for processing a block until it gets data from heimdall. Basically, it won't be able to progress. 

You can stop bor meanwhile, but note that it would then take time to start back. Instead I'd suggest keep it running and it should automatically proceed once heimdall is in sync. 

Also, heimdall going out of sync is a very less frequent event.

**Comment by manav2401** [comment]
Closing this for now. Feel free to reopen if required. Thanks!

**Comment by RomainParracone** [comment]
Thank you for your answer!
