### ISSUE TITLE
Does 0.3.7 fix the slow sync bug? 

### ISSUE THREAD

**Issue by egorFiNE** [maticnetwork/bor#816]
Re #784. @0xKrishna suggested to wait for the official announcement and indeed 0.3.7 announcement came up on the forum. However it doesn't mention the fix of that bug. 

Is it already safe to upgrade to `bor` > 0.3.3 in production?

**Comment by manav2401** [comment]
Hey @egorFiNE, it fixes a bug which was introduced in it's previous release i.e. v0.3.6 (which caused slow sync). v0.3.7 fixes that bug. So, yes. If you're using v0.3.6, I'd recommend updating to v0.3.7.

**Comment by egorFiNE** [comment]
>  I'd recommend updating to v0.3.7.

Thank you!

**Comment by creater-zhys** [comment]
bor has been updated to v0.3.7. but it still sync slow and Intermittently.

**Comment by jiangbo0216** [comment]
for now，I am use 0.5.0-beta-4, and each day I reduce the time gap to the latest node by 2 hours compared to the previous day.
