### ISSUE TITLE
When I use get_blocknumber, transactions return null.

### ISSUE THREAD

**Issue by Liamlu28** [maticnetwork/bor#820]
Node Type: Full node
Node version: 0.3.3-stable

curl --location 'http://127.0.0.1:8545' \
--header 'Accept: application/json, text/plain, */*' \
--header 'Content-Type: application/json;charset=UTF-8' \
--data '[
  {
    "method": "eth_getBlockByNumber",
    "params": ["0x8C0", true],
    "id": 1,
    "jsonrpc": "2.0"
  }
]'

[{"jsonrpc":"2.0","id":1,"result":{"difficulty":"0x7","extraData":"0xd58301090083626f7286676f312e3133856c696e7578000000000000000000003dd3e4d8af06b8e8a915a3f1f6141549b2381b54683aadeeaa5b5aec49bc1d67133926b374af57a530ad29296c13e3f1a2b79b66d2a410ce6285ae9f09d0bc7b00","gasLimit":"0x1312d00","gasUsed":"0x0","hash":"0xf5d6089907b8f37f71b072334fddc70ed1b17cafc72451f006dd7eb4e22f2f1d","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x0000000000000000000000000000000000000000","mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000","nonce":"0x0000000000000000","number":"0x8c0","parentHash":"0x3e8473b735bc9de3048d5b1bb5a902c204d9bdd398da3714c1097144476902e2","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","size":"0x261","stateRoot":"0x8147110e73e04fa39dbbb257f99d91e5c17ac041ed389a889d5a5a9766b4b4a5","timestamp":"0x5ed29c12","totalDifficulty":"0x3d41","transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[]}}]

**Comment by pratikspatil024** [comment]
Hi @Liamlu28, can you check if your block number 2240 ("0x8C0") has transactions in it and is not empty?

You can use the below method to check that.
`"method":"eth_getBlockTransactionCountByNumber","params":["0x8C0"]`

**Comment by Liamlu28** [comment]
> eth_getBlockTransactionCountByNumber

Yeah.This returns null, but I can see Transaction Details on the scan
https://polygonscan.com/txs?block=2240

bor@mainnet-bornode01-bor-full-0:/$ curl --location 'http://127.0.0.1:8545' --header 'Accept: application/json, text/plain, */*' --header 'Content-Type: application/json;charset=UTF-8'  --data '[
  {
    "method": "eth_getBlockTransactionCountByNumber",
    "params": ["0x8C0"],
    "id": 1,
    "jsonrpc": "2.0"
  }
]'
[{"jsonrpc":"2.0","id":1,"result":"0x0"}]
bor@mainnet-bornode01-bor-full-0:/$

**Comment by pratikspatil024** [comment]
Hi @Liamlu28, could you check if your node is functioning properly? Because I could see the transaction on Ploygon-RPC (see the request and result below).

```
$ curl https://polygon-rpc.com/ -X POST -H "Content-Type: application/json" --data '{"method":"eth_getBlockByNumber","params":["0x8C0",true],"id":1,"jsonrpc":"2.0"}'          

{
"jsonrpc":"2.0",
"id":1,
"result":{
"difficulty":"0x7",
"extraData":"0xd58301090083626f7286676f312e3133856c696e7578000000000000000000003dd3e4d8af06b8e8a915a3f1f6141549b2381b54683aadeeaa5b5aec49bc1d67133926b374af57a530ad29296c13e3f1a2b79b66d2a410ce6285ae9f09d0bc7b00",
"gasLimit":"0x1312d00",
"gasUsed":"0x0",
"hash":"0xf5d6089907b8f37f71b072334fddc70ed1b17cafc72451f006dd7eb4e22f2f1d",
"logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
"miner":"0x0000000000000000000000000000000000000000",
"mixHash":"0x0000000000000000000000000000000000000000000000000000000000000000",
"nonce":"0x0000000000000000",
"number":"0x8c0",
"parentHash":"0x3e8473b735bc9de3048d5b1bb5a902c204d9bdd398da3714c1097144476902e2",
"receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
"sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
"size":"0x261",
"stateRoot":"0x8147110e73e04fa39dbbb257f99d91e5c17ac041ed389a889d5a5a9766b4b4a5",
"timestamp":"0x5ed29c12",
"totalDifficulty":"0x3d41",
"transactions":[{"blockHash":"0xf5d6089907b8f37f71b072334fddc70ed1b17cafc72451f006dd7eb4e22f2f1d","blockNumber":"0x8c0","from":"0x0000000000000000000000000000000000000000","gas":"0x0","gasPrice":"0x0","hash":"0x451ea74363975f0f991a4ab484fe95b164ff70367c6765ad5d3d91fb6fb37203","input":"0x","nonce":"0x0","to":"0x0000000000000000000000000000000000000000","transactionIndex":"0x0","value":"0x0","type":"0x0","chainId":"0x0","v":"0x0","r":"0x0","s":"0x0"}],
"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
"uncles":[]
}
}
```

Btw, I am also getting `[{"jsonrpc":"2.0","id":1,"result":"0x0"}]` as the output of `"method":"eth_getBlockTransactionCountByNumber","params":["0x8C0"]` and that is because that transaction is a [StateSync transaction](https://wiki.polygon.technology/docs/pos/state-sync/state-sync/), and is not counted here.

**Comment by pratikspatil024** [comment]
Closing this, for now, reopen it if this is still an issue.

**Comment by MRabenda** [comment]
Hey @pratikspatil024 we are facing exactly the same issue with v0.3.9 for block https://polygonscan.com/txs?block=1595584 also result is []

Also if I will call eth_getLogs - there are no logs in a response even if State Sync transaction returned them
