### ISSUE TITLE
Can't start bor 

### ISSUE THREAD

**Issue by zhy827827** [maticnetwork/bor#829]
when start bor:

$ /usr/bin/bor server -config "/var/lib/bor/config.toml"
WARN [04-20|03:48:42.526] Config File provided, this will overwrite the cli flags path=/var/lib/bor/config.toml
INFO [04-20|03:48:42.527] GRPC Server started                      addr=[::]:3131
INFO [04-20|03:48:42.527] Set global gas cap                       cap=50,000,000
INFO [04-20|03:48:42.527] Allocated trie memory caches             clean=1023.00MiB dirty=1024.00MiB
INFO [04-20|03:48:42.527] Allocated cache and file handles         database=/var/lib/bor/data/bor/chaindata cache=2.00GiB handles=32767
INFO [04-20|03:48:43.591] Opened ancient database                  database=/var/lib/bor/data/bor/chaindata/ancient readonly=false
gap (#40780019) in the chain between ancients and leveldb

bor.service: Main process exited, code=exited, status=1/FAILURE

bor version:0.3.7-stable
heimdall version:v0.3.3
use snapshot: https://snapshot-download.polygon.technology/bor-mainnet-fullnode-2023-04-18.tar.zst

**Comment by ssandeep** [comment]
Can you post your config file in `/var/lib/bor/config.toml ` ?

**Comment by zhy827827** [comment]
The problem with the data may be due to data corruption during the decompression process
