### ISSUE TITLE
CORS misconfiguration vulnerability in puppeth module

### ISSUE THREAD

**Issue by PandaTea** [maticnetwork/bor#83]
Bor implement newCorsHandler function to tell browsers to give a web application running at one origin, access to selected resources from a different origin.
but a mis-configuration in newCorsHandler make Bor allows any domain on the web to access local node's resources.

in summary, adversary could make a CSRF (Cross-site request forgery) attack to induce Bor users send HTTP-requests to bor Server side without their knowledge. which make a severity potential security risk

#### System information

Geth version: eth65
OS & Version: MacOS catalina 10.15.6
Commit hash : a1b7e2fcbbd753210e2c264bac633e2acd61839c

#### Expected behaviour
Bor should deny any website to access local node's resources

#### Actual behaviour
Bor allows any domain on the web to access local node's resources actually.

#### Steps to reproduce the behaviour
code for CORS configuration is location to bor/node/rpcstack.go,L40-L52:
```go
func newCorsHandler(srv http.Handler, allowedOrigins []string) http.Handler {
	// disable CORS support if user has not specified a custom CORS configuration
	if len(allowedOrigins) == 0 {
		return srv
	}
	c := cors.New(cors.Options{
		AllowedOrigins: allowedOrigins,
		AllowedMethods: []string{http.MethodPost, http.MethodGet},
		MaxAge:         600,
		AllowedHeaders: []string{"*"},
	})
	return c.Handler(srv)
}
```
 cors.New generate a configuration with `allowCredentials == true`
and the AllowedOrigins was set into "*" in bor/cmd/puppeth/module_explorer.go,L38-L39:
```sh
echo $'geth --networkid {{.NetworkID}} --syncmode "full" --gcmode "archive" --port {{.EthPort}} --bootnodes {{.Bootnodes}} --ethstats \'{{.Ethstats}}\' --cache=512 --http --http.api "net,web3,eth,shh,debug" --http.corsdomain "*" --http.vhosts "*" --ws --ws.origins "*" --exitwhensynced' >> explorer.sh && \
echo $'exec geth --networkid {{.NetworkID}} --syncmode "full" --gcmode "archive" --port {{.EthPort}} --bootnodes {{.Bootnodes}} --ethstats \'{{.Ethstats}}\' --cache=512 --http --http.api "net,web3,eth,shh,debug" --http.corsdomain "*" --http.vhosts "*" --ws --ws.origins "*" &' >> explorer.sh && \
```
that mean any website on public network has access to call the interface of puppeth module of the local Bor node.
its a representative CORS mis-configuration vulnerability.

maybe we could modify http.corsdomain params into a few specified site in bor/cmd/puppeth/module_explorer.go,L38-L39

**Comment by jdkanani** [comment]
Are you talking about default behavior in puppeth? If yes, puppeth won't work with bor since bor needs genesis contracts.

**Comment by PandaTea** [comment]
hmmmm, okay
thank u
