### ISSUE TITLE
`debug_traceCall` tracer integer overflow

### ISSUE THREAD

**Issue by dancoombs** [maticnetwork/bor#833]
#### **System information**

Bor client version: 0.3.5

OS & Version: Linux

Environment: Polygon Mumbai

Type of node: Validator

#### **Overview of the problem**

Tracing seems to have issues with numbers over 32 bits in size. Those numbers overflow and are sent to the tracer incorrectly.

Theory as to why:

See:
https://github.com/maticnetwork/bor/blob/6dee9b5f4016cc58d3b470ecdcd0092ee4ba9fd3/eth/tracers/js/tracer.go#L603

These functions call `Duktape` `Context.PushUint`

https://github.com/olebedev/go-duktape/blob/650f7c85444083d383394f0ac179080ae3b94325/api.go#L1120

```
func (d *Context) PushUint(val uint) {
	C.duk_push_uint(d.duk_context, C.duk_uint_t(val))
}
```

Looking at the compilation of `C.duk_uint_t(val)`

```
type _Ctype_duk_uint_t = _Ctype_uint
type _Ctype_uint uint32
```

The `uint` values are getting converted to `uint32` values.

Potential solution:

Convert values to `float64` and use `PushNumber`.

#### **Reproduction Steps**

Run a `debug_traceCall` with a very high gasLimit (> 2^32), call a contract that makes a `STATICCALL`, and capture the `gas` and `cost` fields in the tracer.

Any issues go a way if using a gasLimit below 2^32

**Comment by Raneet10** [comment]
Hey @dancoombs , thanks for sharing this interesting find! I guess when we take the upstream merge from geth, duktape should be replaced by goja and hopefully address this concern.

**Comment by dancoombs** [comment]
@manav2401 I saw that this was closed. Is there any timeline for this to be fixed?

**Comment by manav2401** [comment]
Hey @dancoombs, we've already started the upstream merge and as raneet mentioned it should have the fix. As there are lot of conflicts, I can't commit a time but the next major release will be that only.
