### ISSUE TITLE
Transactor have enough funds, but got error "insufficient funds for gas * price + value"

### ISSUE THREAD

**Issue by fwhappy** [maticnetwork/bor#836]
I ran a full node.
I confirm that the Transactor have enough funcs, but the node still rejected the transaction.
Returned "insufficient funds for gas * price + value" error.

The probability of this occurring is very low.

**Comment by Raneet10** [comment]
Hey @fwhappy , can you share a bit more details on the transaction you were trying to send ? Also , was your node fully synced when you ran this transaction ?

**Comment by fwhappy** [comment]
There were less than 100 blocks behind in synchronization

**Comment by Raneet10** [comment]
Can you verify whether the sender had the enough balance around that time ? It could've been possible that the balance wasn't enough until later on, and your node hadn't caught up to that block.

**Comment by temaniarpit27** [comment]
@fwhappy : Please provide us with all the details/logs/screenshots so that we can look into the issue.

**Comment by Ishmaello** [comment]
Me too when I was using polygonscan.com proxy "transferFrom" external, but the node Alchemy on metamask had 18 MATIC mainnet transactions returned internal JASON ERROR until but I lost that wallet when I ask for help to some guy here:
Hello Polygon support.currently I own no PC so while I was looking for a friend who own one, as I couldn't find him around I tried to use my phone hauwei to set up Google play store to allow metamask operate in crome. I found a link with metamask the page had all metamask services for including import wallet where I put my passphrases but it failed and suddenly p opped up help support, Verona a consultant who said "open metamask in crome" I I responded it not working then he replied asking for passphrases to let him continue on my behalf, that moment I was trying to fix Google play store on the other side. The time fix Google play completed I got back to Verona I told him play store is now working but when I go check my wallet my Polygon funds that I deposited to perform transactions were gone, checking on Polygonscan I don't know that receiver 🤦‍♂️ now metamask is working on crome current device is Huawei nova Y60 I was hoping it may
![Screenshot_20230415_081221_io metamask](https://user-images.githubusercontent.com/121644333/235754800-b2ecd2e8-4011-4cbe-8d3f-6c4edd7ac67e.jpg)
![Screenshot_20230415_081013_com wallet crypto trustapp](https://user-images.githubusercontent.com/121644333/235754819-7fd0cd35-b604-4a5e-b689-a0378d07accd.jpg)
![Screenshot_20230415_091753_com wallet crypto trustapp](https://user-images.githubusercontent.com/121644333/235754828-eecc0f25-d638-473a-afd9-932eeb4532f6.jpg)
![Screenshot_20230415_094846_com kiwibrowser browser](https://user-images.githubusercontent.com/121644333/235754830-e6b0103d-2ae7-4d2c-8d2f-e0725b9dbe45.jpg)
![Screenshot_20230417_170731_io metamask](https://user-images.githubusercontent.com/121644333/235754836-beb9e196-0121-434e-87e8-7dbe89a711a7.jpg)
![Screenshot_20230418_213931_com wallet crypto trustapp](https://user-images.githubusercontent.com/121644333/235754839-91cc6c5d-e032-4ad1-97da-ac8aa991d7f2.jpg)
![Screenshot_20230418_213510_com wallet crypto trustapp](https://user-images.githubusercontent.com/121644333/235754844-89ee3037-0a57-4335-a6fc-cff023df483c.jpg)
![Screenshot_20230417_170749_org mozilla firefox](https://user-images.githubusercontent.com/121644333/235754848-a4cc47ff-16c0-4606-a831-41f6a7b1bec7.jpg)
![Screenshot_20230415_080935_com wallet crypto trustapp](https://user-images.githubusercontent.com/121644333/235754852-080a9d31-05ab-48d7-9233-a84df1bf44a8.jpg)
![Screenshot_20230415_080908_com wallet crypto trustapp](https://user-images.githubusercontent.com/121644333/235754859-ae389142-e012-425d-85bd-dbd766cd5ae9.jpg)
![Screenshot_20230415_080955_com wallet crypto trustapp](https://user-images.githubusercontent.com/121644333/235754861-ea6db8c8-6827-49c1-9653-0513f9ff8aa9.jpg)

**Comment by manav2401** [comment]
Hi, can you post the transaction fields like base fee and priority fee you're using while sending the transaction? It might be possible that you're sending too high fee and you don't own that much funds. 

Also, in one of the screenshots, I can see that the contract reverted with insufficient funds error. This is a contract level issue which means you don't have funds to call the `transferFrom` function.

**Comment by Ishmaello** [comment]
The wallet I was connected to ![235754830-e6b0103d-2ae7-4d2c-8d2f-e0725b9dbe45](https://user-images.githubusercontent.com/121644333/236611181-3dcf1677-5990-4a8e-966b-6b53e7b6fa06.jpg)
And Polygonscan connect to web3 as proxy transactions were made as 
![Screenshot_20230417_170749_org mozilla firefox](https://user-images.githubusercontent.com/121644333/236611412-10e0a46a-0399-4b4a-9c7b-d795ac5d0035.jpg)

But some responses showed internal Jason RPC error instead and yes I only had 20 matic on metamask that time the browser was  fire fox

**Comment by marcello33** [comment]
I guess there is something wrong with the settings on the tx on metamask
Closing it
