### ISSUE TITLE
Many blocks with 0 transactions

### ISSUE THREAD

**Issue by 0x090909** [maticnetwork/bor#842]
My service that listens for new blocks is returning many times the error in the following picture, by watching the logs of bor I see many times new chain segment imported but transactions = 0

![Screenshot 2023-05-01 at 16 09 46](https://user-images.githubusercontent.com/16927059/235464372-968d4c3d-3319-47e3-9920-f4dbfb680326.png)

**Comment by temaniarpit27** [comment]
Hi,
Thanks a lot for reporting this. We are working on improving upon empty blocks occurring frequently and are in the testing phase. We will keep the community updated as we are ready to release it.

**Comment by marcello33** [comment]
Closing it until fix is released
