### ISSUE TITLE
How to speed up bor sync?

### ISSUE THREAD

**Issue by letspesl** [maticnetwork/bor#843]
I asked a question on discord but didn't get a proper answer so I'm leaving an issue.

I set up a new instance with the specifications recommended in the document like below.
RAM 64 GB / CPU 16-core / 5 TB SSD / Bandwidth 1 Gbps

And I started syncing using the snapshot below.
https://snapshots.polygon.technology

I did download the snapshot at the point the snapshot was created and uncompress it and start syncing, it will start ones of thousands of blocks ago. (Because it takes time to download and unzip)

However, it is not synchronized to the latest block and it is getting slower. Currently, it is over 190,000 blocks behind.

My node uses the configuration file below.
https://github.com/maticnetwork/launch/blob/master/mainnet-v1/sentry/sentry/bor/config.toml

Currently, heimdall has the latest sync done, but bor is still slow.
bor currently has 33 peers connected, and among them, it seems that there are Geth or Erigon peers that are not bor, so we are continuously removing them.

I added the list below to see if it would be different if I set the boot node separately.
https://monitor.stakepool.dev.br/bootnodes
But even that doesn't make much of a difference.

My question is below.

1. Is there a separate stable peer list for bor? Or are there other ways to facilitate peer connectivity?

2. Is there a way to set config to speed up bor's synchronization?
(Please tell me the value of the config file that syncs well. Documentation with detailed explanation of each flag is also good.)

3. Please let us know if you have any further optimization tips.

I want to quickly complete the full node configuration. Please help me!

**Comment by lijie9703** [comment]
Brother, is the problem solved, I also encountered such a problem

**Comment by marcello33** [comment]
Hey @letspesl what version of `bor` are you running?
What is the current peers length?

**Comment by joslee7410** [comment]
I'm encountered same problem here 

My bor version: bor/v0.3.7-stable/linux-amd64/go1.20.2
peers length : 380 ~ 400

**Comment by marcello33** [comment]
Hey @letspesl 
Can you please provide logs around the sync issue (maybe `Synchronization failed` if it pops up)? 
Thanks

**Comment by letspesl** [comment]
Logs related to synchronization failures do not appear.
It's just that synchronization is slow.

`INFO [05-11|10:31:19.150] Imported new chain segment               blocks=4    txs=198     mgas=57.199  elapsed=15.339s     mgasps=3.729  number=42,230,011 hash=73cd1d..bd60e2 age=1w1d13h  dirty=373.85MiB
INFO [05-11|10:31:27.157] Imported new chain segment               blocks=2    txs=96      mgas=31.789  elapsed=8.006s      mgasps=3.970  number=42,230,013 hash=9a9f34..44e635 age=1w1d13h  dirty=376.05MiB`

**Comment by marcello33** [comment]
This may due to several reasons, from hardware specs or network setup to quality of peers
Without specific logs we can't help much, or reproduce the issue, unfortunately.

**Comment by letspesl** [comment]
> This may due to several reasons, from hardware specs or network setup to quality of peers Without specific logs we can't help much, or reproduce the issue, unfortunately.

There is nothing unusual in the log, but the sync is still slow, so I have to take action anyway.

I would like to know if there is something to be modified in the config file.

Are the settings below optimized?
https://github.com/maticnetwork/launch/blob/master/mainnet-v1/sentry/sentry/bor/config.toml

There are a lot of peer connections, but when I look at the client versions, there are cases of geth and erigon.
Can you provide a stable peer?

**Comment by pratikspatil024** [comment]
Hi @letspesl, regarding the config file, I would recommend not taking reference of the launch repo, as it is not constantly updated. Instead, would recommend you have a look at the `packaging/templates` folder in bor. Here's the [updated config file](https://github.com/maticnetwork/bor/blob/develop/packaging/templates/mainnet-v1/sentry/sentry/bor/config.toml).

**Comment by Sreeram1993** [comment]
I am also facing a similar issue, I have setup a BOR node which is set to ARCHIVAL sync. Using a 16 TB Ultra SSD to get the data synced. I am running it in an AKS with the below specs - {"cpu":10,"memory":"70Gi"} Up until 1 year 11 month back data got synced properly but then it is getting stalled. 

INFO [05-26|06:34:53.280] → committing new state eventRecord="id 433444, contract 0xD9c7C4ED4B66858301D0cb28Cc88bf655Fe34861, data: 0x0000000000000000000000009fd4904a07a96ad1330991b122528c169caf749c0000000000000000000000007d1afa7b718fb893db30a3abc0cfc608aacfebb0000000000000000000000000000000000000000000000000e8866da08ca0000000000000000000000000000000000000000000000000000000000000085fdc3c, txHash: 0x45ea6f1ad80cfaa22a4fd96f05c2d68fab4b994c0ee36dd9dfb701f700bb4232, logIndex: 130, chainId: 137, time 2021-06-17T00:59:22Z, gasUsed 50288"
INFO [05-26|06:34:53.280] StateSyncData gas=1,074,269 number=15,802,624 lastStateID=433,444 total records=20 fetch time=11 process time=10
INFO [05-26|06:34:53.491] Imported new chain segment blocks=23 txs=6544 mgas=459.839 elapsed=3.790s mgasps=121.305 number=15,802,625 hash=e108f3..6b5dcb age=1y11mo2w dirty=0.00B

Any idea what can be done to increase the speed ?

**Comment by pratikspatil024** [comment]
Hey @Sreeram1993, looking at your logs, I can see that it is importing 23 blocks in 3.7s, this is good speed.

**Comment by git-ljm** [comment]
We also have similar problems.

**Comment by manav2401** [comment]
Hey @letspesl, was this problem solved in your case? If not, can you try updating to the latest version as it has some fixes and improvements. 

@Sreeram1993, as Pratik mentioned, the syncing speed you're seeing looks normal and I think good for an archival node. I think archive node are very resource intensive and there might be lot of factors playing in which might lead to slow sync. It would be good if you can send some more metrics/flags you're using. Also, for an archive node, we'd also suggest exploring https://github.com/ledgerwatch/erigon/ client as an option as we're actively supporting it. 

@git-ljm can you send more details about the problem. Thanks!

**Comment by letspesl** [comment]
Synchronization is still lagging.
Trying to re-sync by re-downloading the snapshot is taking a lot of time...
What is the latest version you recommend?
And can you explain which fixes help with the sync speed issue?

**Comment by rmlcu** [comment]
having the same issue: due to the prunning node was offline a couple of hours, catching to the latest block took almost 20 hours

hardware not an issue as we have 8 vcpu 32 ram with raid10 samsung EVO ssds - memory almost never was filled more than half, so the CPU usage and LA rarely showed high load

**Comment by manav2401** [comment]
@rmlcu, from these logs, it's looks good to me. Note that there's no specific average sync speed as it varies based on the block you're trying to import and also the machine specs and you DB levels. 

If you're importing certain big blocks (full 30M gas), it might take time to process.

**Comment by manav2401** [comment]
Will be closing this next week if the issue is resolved.

**Comment by fylsan3** [comment]
```
Jun 29 08:33:36 172-20-192-98 bash[824046]: INFO [06-29|08:33:36.134] Aborting state snapshot generation       root=75cf62..95e94f in=ff8ffc..43f134 at=d7edb8..56d503 accounts=52,975,865 slots=1,343,301,015 storage=100.54GiB elapsed=11m20.631s  eta=30.199s
Jun 29 08:33:36 172-20-192-98 bash[824046]: INFO [06-29|08:33:36.139] Resuming state snapshot generation       root=333ec4..b3ad38 in=ff8ffc..43f134 at=d7edb8..56d503 accounts=52,975,865 slots=1,343,301,015 storage=100.54GiB elapsed=11m20.636s  eta=30.199s
Jun 29 08:33:36 172-20-192-98 bash[824046]: INFO [06-29|08:33:36.386] Aborting state snapshot generation       root=333ec4..b3ad38 in=ff8ffc..43f134 at=d86e74..5837fc accounts=52,975,865 slots=1,343,309,438 storage=100.54GiB elapsed=11m20.883s  eta=30.21s
Jun 29 08:33:36 172-20-192-98 bash[824046]: INFO [06-29|08:33:36.394] Resuming state snapshot generation       root=c005d2..c9b203 in=ff8ffc..43f134 at=d86e74..5837fc accounts=52,975,865 slots=1,343,309,438 storage=100.54GiB elapsed=11m20.891s  eta=30.211s
Jun 29 08:33:36 172-20-192-98 bash[824046]: INFO [06-29|08:33:36.617] Aborting state snapshot generation       root=c005d2..c9b203 in=ff8ffc..43f134 at=d8ee4b..98c290 accounts=52,975,865 slots=1,343,317,745 storage=100.54GiB elapsed=11m21.114s  eta=30.22s
Jun 29 08:33:36 172-20-192-98 bash[824046]: INFO [06-29|08:33:36.622] Resuming state snapshot generation       root=64ee1a..f033b4 in=ff8ffc..43f134 at=d8ee4b..98c290 accounts=52,975,865 slots=1,343,317,745 storage=100.54GiB elapsed=11m21.119s  eta=30.221s
Jun 29 08:33:36 172-20-192-98 bash[824046]: INFO [06-29|08:33:36.875] Aborting state snapshot generation       root=64ee1a..f033b4 in=ff8ffc..43f134 at=d91e1e..ccdc05 accounts=52,975,865 slots=1,343,320,906 storage=100.54GiB elapsed=11m21.372s  eta=30.232s
Jun 29 08:33:36 172-20-192-98 bash[824046]: INFO [06-29|08:33:36.878] Resuming state snapshot generation       root=df7115..599c7a in=ff8ffc..43f134 at=d91e1e..ccdc05 accounts=52,975,865 slots=1,343,320,906 storage=100.54GiB elapsed=11m21.375s  eta=30.232s
Jun 29 08:33:38 172-20-192-98 bash[824046]: WARN [06-29|08:33:38.556] Database compacting, degraded performance database=/data/polygon/.bor/data/bor/chaindata
Jun 29 08:33:47 172-20-192-98 bash[824046]: WARN [06-29|08:33:47.808] Peer stalling, dropping                  peer=d39da660 waited=2m1.304s
Jun 29 08:33:59 172-20-192-98 bash[824046]: WARN [06-29|08:33:59.483] unable to whitelist checkpoint           err="missing checkpoint blocks"
Jun 29 08:34:38 172-20-192-98 bash[824046]: WARN [06-29|08:34:38.565] Database compacting, degraded performance database=/data/polygon/.bor/data/bor/chaindata
Jun 29 08:35:37 172-20-192-98 bash[824046]: WARN [06-29|08:35:37.684] unable to whitelist checkpoint           err="missing checkpoint blocks"
Jun 29 08:35:41 172-20-192-98 bash[824046]: WARN [06-29|08:35:41.554] Database compacting, degraded performance database=/data/polygon/.bor/data/bor/chaindata
Jun 29 08:36:41 172-20-192-98 bash[824046]: WARN [06-29|08:36:41.625] Database compacting, degraded performance database=/data/polygon/.bor/data/bor/chaindata
Jun 29 08:37:17 172-20-192-98 bash[824046]: WARN [06-29|08:37:17.316] unable to whitelist checkpoint           err="missing checkpoint blocks"
Jun 29 08:37:44 172-20-192-98 bash[824046]: WARN [06-29|08:37:44.591] Database compacting, degraded performance database=/data/polygon/.bor/data/bor/chaindata
Jun 29 08:38:44 172-20-192-98 bash[824046]: WARN [06-29|08:38:44.596] Database compacting, degraded performance database=/data/polygon/.bor/data/bor/chaindata
Jun 29 08:38:57 172-20-192-98 bash[824046]: WARN [06-29|08:38:57.289] unable to whitelist checkpoint           err="missing checkpoint blocks"
Jun 29 08:39:44 172-20-192-98 bash[824046]: WARN [06-29|08:39:44.612] Database compacting, degraded performance database=/data/polygon/.bor/data/bor/chaindata
Jun 29 08:40:36 172-20-192-98 bash[824046]: WARN [06-29|08:40:36.932] unable to whitelist checkpoint           err="missing checkpoint blocks"
Jun 29 08:40:44 172-20-192-98 bash[824046]: WARN [06-29|08:40:44.627] Database compacting, degraded performance database=/data/polygon/.bor/data/bor/chaindata
Jun 29 08:40:55 172-20-192-98 bash[824046]: ERROR[06-29|08:40:55.616] Snapshot extension registration failed   peer=5778b638 err="peer connected on snap without compatible eth support"
Jun 29 08:40:59 172-20-192-98 bash[824046]: ERROR[06-29|08:40:59.111] Snapshot extension registration failed   peer=57355e8c err="peer connected on snap without compatible eth support"
Jun 29 08:41:47 172-20-192-98 bash[824046]: WARN [06-29|08:41:47.622] Database compacting, degraded performance database=/data/polygon/.bor/data/bor/chaindata
Jun 29 08:42:16 172-20-192-98 bash[824046]: WARN [06-29|08:42:16.935] unable to whitelist checkpoint           err="missing checkpoint blocks"
Jun 29 08:42:47 172-20-192-98 bash[824046]: WARN [06-29|08:42:47.636] Database compacting, degraded performance database=/data/polygon/.bor/data/bor/chaindata


Jun 29 08:43:47 172-20-192-98 bash[824046]: WARN [06-29|08:43:47.656] Database compacting, degraded performance database=/data/polygon/.bor/data/bor/chaindata
Jun 29 08:43:57 172-20-192-98 bash[824046]: WARN [06-29|08:43:57.281] unable to whitelist checkpoint           err="missing checkpoint blocks"
Jun 29 08:44:50 172-20-192-98 bash[824046]: WARN [06-29|08:44:50.668] Database compacting, degraded performance database=/data/polygon/.bor/data/bor/chaindata
Jun 29 08:45:37 172-20-192-98 bash[824046]: WARN [06-29|08:45:37.390] unable to whitelist checkpoint           err="missing checkpoint blocks"
Jun 29 08:45:50 172-20-192-98 bash[824046]: WARN [06-29|08:45:50.678] Database compacting, degraded performance database=/data/polygon/.bor/data/bor/chaindata
Jun 29 08:46:53 172-20-192-98 bash[824046]: WARN [06-29|08:46:53.673] Database compacting, degraded performance database=/data/polygon/.bor/data/bor/chaindata
Jun 29 08:47:17 172-20-192-98 bash[824046]: WARN [06-29|08:47:17.916] unable to whitelist checkpoint           err="missing checkpoint blocks"
Jun 29 08:47:53 172-20-192-98 bash[824046]: WARN [06-29|08:47:53.679] Database compacting, degraded performance database=/data/polygon/.bor/data/bor/chaindata
Jun 29 08:48:53 172-20-192-98 bash[824046]: WARN [06-29|08:48:53.712] Database compacting, degraded performance database=/data/polygon/.bor/data/bor/chaindata
Jun 29 08:48:57 172-20-192-98 bash[824046]: WARN [06-29|08:48:57.725] unable to whitelist checkpoint           err="missing checkpoint blocks"
Jun 29 08:49:56 172-20-192-98 bash[824046]: WARN [06-29|08:49:56.726] Database compacting, degraded performance database=/data/polygon/.bor/data/bor/chaindata
Jun 29 08:50:37 172-20-192-98 bash[824046]: WARN [06-29|08:50:37.668] unable to whitelist checkpoint           err="missing checkpoint blocks"
Jun 29 08:50:59 172-20-192-98 bash[824046]: WARN [06-29|08:50:59.784] Database compacting, degraded performance database=/data/polygon/.bor/data/bor/chaindata
```
我的归档数据已经有16TB了，现在高度29857737   我需要所有的历史数据，但我在同步的时候经常会这样卡住，然后卡住很久，如果我重启的话它会快速同步一段时间，然后又会卡住

**Comment by manav2401** [comment]
Hey @fylsan3, the logs above suggest that your node had an unclean shutdown and hence it was regenerating the state snapshot initially. The logs "Database compacting" suggests that bor process is trying to write more than leveldb (the underlying database bor uses) can handle. It basically means that your machine specs aren't sufficient to run an archive node. Try using more performant machines with high cores, ram and I/O. 

Moreover, if you're running an archive node, I'd suggest having a look at the [erigon](https://github.com/ledgerwatch/erigon/) client which takes up a lot less space as compared to bor.
