### ISSUE TITLE
error in the log: "2023/05/15 14:03:32 traces exporter is disconnected from the server 127.0.0.1:4317", how to fix it?

### ISSUE THREAD

**Issue by rmlcu** [maticnetwork/bor#865]
hi there,

after update to bor-v0.3.7-amd64 I begun to see a lot of errors in the log. 
what entity must listening on port 4317?

`2023/05/15 14:03:32 traces exporter is disconnected from the server 127.0.0.1:4317: max retry time elapsed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:4317: connect: connection refused"`

how to fix it?

**Comment by 0xsharma** [comment]
Hi @rmlcu , 

This error comes up when the telemetry trace collector endpoint is not online/not set up. The default collector listening address is `127.0.0.1:4317` and returns error when it is not able to find the same. You can `ignore` these logs at the moment. We should be taking this up and improve the logging in the future releases. 

Thank you for notifying ! 💜
