### ISSUE TITLE
parallel evm

### ISSUE THREAD

**Issue by lurais** [maticnetwork/bor#874]
Hello, why should build the dag in the method executeParallelWithCheck, is the deps array is enough to explain the dependency tree? And the method core/blockstm/executor.go:Step is not easy to understand could you add some note to it or write some article to explain that?
@cffls

**Comment by cffls** [comment]
Hi @lurais , if you are referring to the DAG [here](https://github.com/maticnetwork/bor/blob/develop/core/blockstm/executor.go#L171), it is not necessary as part of block mining or validation. The DAG was only generated when [profile](https://github.com/maticnetwork/bor/blob/develop/core/blockstm/executor.go#L561) is set to true. We only use it to analyze tx dependencies in a block, e.g. longest execution path. During block validation, the dependencies of a transaction are calculated and added to [a dependency array](https://github.com/maticnetwork/bor/blob/develop/core/blockstm/status.go#L28) in its corresponding task manager.

The step function basically does two things: validating transaction results and scheduling tasks. The implementation is inspired by [this paper](https://arxiv.org/abs/2203.06871). We may publish a technical blog post for block-stm in the future.

**Comment by lurais** [comment]
so ,will you plan to support parallel exec transaction in block producing period in the future? why not use parallel exec in block producing period now?

**Comment by cffls** [comment]
It is on the roadmap. Additional works are required to enable parallel execution in block mining, which may change how fee mechanism work.

**Comment by lurais** [comment]
> It is on the roadmap. Additional works are required to enable parallel execution in block mining, which may change how fee mechanism work.

Hello , where I can find the roadmap? And do you have some test about the effect in block mining?

**Comment by cffls** [comment]
The research of parallel execution in block mining is still in very early stage, and there isn't a roadmap at the moment. We will post more information once we have some sharable results.

**Comment by manav2401** [comment]
Closing this, feel free to reopen if you have more questions.
