### ISSUE TITLE
Following up on the release of the fix for a previous Issue(#582)

### ISSUE THREAD

**Issue by chaoyandy** [maticnetwork/bor#877]
Hi team, my previous raised [issue](https://github.com/maticnetwork/bor/issues/582) has been fixed by a [PR](https://github.com/maticnetwork/bor/pull/822) over a month ago, thanks for putting efforts to get this done!

I'm wondering when will this change gets into the upcoming release? It is a critical feature for us to get author data right and there're few downstream user integrations blocking from this. Really appreciate the help here!

**Comment by Raneet10** [comment]
Hey @chaoyandy apologies for missing your previous comment! Our next release should be around in June so I believe the changes will be clubbed in that. Thanks again for your patience!
