### ISSUE TITLE
Add support for PUSH0 opcode

### ISSUE THREAD

**Issue by CodeSandwich** [maticnetwork/bor#886]
# Rationale

The Shanghai fork of Ethereum introduced the PUSH0 opcode. It started being supported in Solidity 0.8.20 and it significantly reduces the bytecode size allowing putting more logic into contracts and reducing the usage cost.

# Implementation

> Do you have ideas regarding the implementation of this feature? (Mention reference links if any)

No.

> Any alternative solutions or features you've considered?

There's none, it's a new opcode.

> Are you willing to implement this feature?

No, sorry.

**Comment by manav2401** [comment]
Hey, thanks for raising this issue. We're already in process of merging the upstream changes from geth and this change is already accounted in it.

**Comment by SKYBITDev3** [comment]
I compiled a contract with Solidity 0.8.21 and tried to deploy it onto both Mumbai and Polygon, but got the invalid opcode error.

It worked fine on zkEVM testnet as expected after your announcement about `PUSH0` support on zkEVM:
[Polygon zkEVM: Dragon Fruit Upgrade (with New Opcode) Coming to Mainnet Beta](https://polygon.technology/blog/polygon-zkevm-dragon-fruit-upgrade-with-new-opcode-coming-to-mainnet-beta). But please also support it on your other blockchains.

**Comment by manav2401** [comment]
Hi @SKYBITDev3, so according to our governance process, we have pushed the milestone hardfork (named Aalborg) first and as it's quite critical, we haven't enabled Shanghai changes into it. We have all the geth upstream changes but the hardfork changes aren't enabled. Those will go in a different hardfork just after the Aalborg one. Hope this clarifies your concern. Thanks!
