### ISSUE TITLE
Bor not staying synced, falling behind.

### ISSUE THREAD

**Issue by concentricspheres** [maticnetwork/bor#887]
#### **System information**

Bor client version: v0.3.9

Heimdall client version: v0.3.3

OS & Version: Linux

Environment: Polygon Mainnet

Type of node: Sentry

Additional Information: 

#### **Overview of the problem**

Over the past few days we've had the node falling behind, while still slowly syncing. 

A restart of bor and heimdall has temporarily fixed the issue but ~24 hours later it starts falling behind again.

Checking logs show Importing of new chain segments but hours old.

#### **Reproduction Steps**

None that we can define.

#### **Logs / Traces / Output / Error Messages**
 
No unusual logs we can provide.

**Additional Information**

1. Your `start.sh` file or `bor.service`, if you're facing some peering issue or unable to use some service (like `http` endpoint) as expected. Moreover, if possible mention the chain configuration printed while starting the node which looks something like `Initialised chain configuration config="{ChainID: 137, ..., Engine: bor}"`

bor server --datadir /var/lib/bor/data --cache ${BOR_CACHE} --ws --ws.port ${BOR_WS_PORT} --ws.addr 0.0.0.0 --ws.origins=* --ws.api eth,net,web3,txpool,bor --port ${BOR_P2P_PORT} --metrics --metrics.prometheus-addr 0.0.0.0:6060 --metrics.expensive --metrics.opencollector-endpoint "" --txpool.locals ${TX_LOCAL_ADDR} --txpool.globalslots "400000" --rpc.txfeecap "0" --txpool.accountslots "256" --bor.heimdall http://heimdallr:1317 --txpool.accountqueue "64" --txpool.globalqueue "131072" --txpool.pricelimit "30000000000" --maxpeers "200" --http --http.addr 0.0.0.0 --http.vhosts=* --http.api eth,net,web3,txpool,bor --http.port ${BOR_RPC_PORT} --chain ${NETWORK} --ethstats ${BOR_NODE_ID}:${NETWORK}@bor-${NETWORK}.vitwit.com:3000

2. The result of `eth.syncing`, `admin.peers.length`, `admin.nodeInfo`, value of the `maxpeers` flag in start.sh, and bootnodes/static nodes (if any) is you're facing some syncing issue.

3. Your `heimdall-config.toml` parameters for checking the ETH and BOR RPC url's, incase of issue with bor heimdall communication. 

4. The CURL request (for that specific error) if you're facing any issues or identify a bug while making RPC request.

**Comment by yorickdowne** [comment]
This server was last fresh-synced Sept 15th 2022. We have seen this issue on two machines, and a fellow node operator on one machine.

We are resyncing one machine from scratch with the new incremental snapshot system to see whether this is related to DB contents at all.

**Comment by cffls** [comment]
Could you provide logs around when bor started falling behind? It would be helpful for us to find potential cause of the issue. Thanks!

**Comment by yorickdowne** [comment]
Shall when this happens again. Unfortunately the machine was restarted before logs were preserved ...

**Comment by concentricspheres** [comment]
[bor-halted-tail.txt](https://github.com/maticnetwork/bor/files/11736253/bor-halted-tail.txt)

We had another instance of bor not syncing. This time it seems to have halted completely, it did not respond to sigterm even after our 3m stop grace time.

**Comment by yorickdowne** [comment]
We don’t see anything obviously wrong in the logs - one moment it’s “submitted transaction” and the next Bor freezes. It’s possible that the content of the tx is triggering that.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yorickdowne** [comment]
Oh that’s interesting. Let me run that by the team that writes the software that makes these calls.

**Comment by cffls** [comment]
Logs attached looked okay. Bor didn't shutdown gracefully so it had to rebuild the snapshot. Do you have any additional logs when bor stalled in the first time when running with heimdall v0.3.4?

**Comment by yorickdowne** [comment]
The attached logs show the stall and should be complete. There is indeed nothing very specific in there that would point at cause.

**Comment by cffls** [comment]
`Head state missing` is an indication of corrupted database, which is usually caused by bor being shutdown ungracefully. It doesn't seem to be a problem caused by Heimdall. 
Also, it is worth mentioning that Heimdall v0.3.4 will return an error when bor request a state sync window that it doesn't know about, instead of returning an empty result (prior v0.3.4). This behavior will keep bor retrying and waiting until Heimdall catches up and returns the correct state sync events. It fixes the issue where bor gets incorrect state sync results, which lead to bad block error and eventually dropping good peers. 
In your case, the reason why bor stalled could be that Heimdall was not catching up, so it had to wait until Heimdall is synced. Again, full logs of heimdall (v0.3.4) and bor around when this happened would be extremely helpful for us to find the root cause.

**Comment by yorickdowne** [comment]
@cffls The logs attached at https://github.com/maticnetwork/bor/issues/887#issuecomment-1600935117 (the gz ones at the bottom) are full logs before restart.

I am syncing a test server and hope to be able to reproduce there.

**Comment by cffls** [comment]
Thanks for the clarification. I don't see anything stands out in the log either. It seems to be a peering issue. If you are able to reproduce this, please try getting the peers and check if the node is connected to any healthy peers.

**Comment by yorickdowne** [comment]
This may be related to Bor being queried. A test server without queries is happy. Let me add it to the rotation and see.

**Comment by yorickdowne** [comment]
Test results so far
- Stable without queries
- Stable with eth_sendRawTransaction queries
- Just enabled eth_call queries and shall see

We had a change to eth_sendRawTransaction on the app side as well. While "things you didn't think about" is always possible, current theories are:

- It was eth_sendRawTransaction, but reducing batch from 250 to 100 fixed it
- It was eth_call and we will see it fail now

We shall know shortly!

**Comment by yorickdowne** [comment]
The test server stayed healthy. Brought one of the main servers over to heimdalld 0.3.4 and bor 0.4.0

**Comment by yorickdowne** [comment]
Main servers stayed healthy. We changed RPC batching in the app from `250` to `100` and that seems to have helped a ton.

This issue can be closed.

**Comment by pratikspatil024** [comment]
Glad to hear that, @yorickdowne!

Thanks for the help, @cffls!
> At 20:33:49, the node served 31 eth_calls in 1 second (the actual number could be more). It seems like a burst of RPC calls caused the lagging of node sync. It might be a good idea to limit the rate of RPC calls to your node

**Comment by jiangbo0216** [comment]
> Main servers stayed healthy. We changed RPC batching in the app from `250` to `100` and that seems to have helped a ton.
> 
> This issue can be closed.

how can I do the same thing?
I am synchronizing the blockchain, and each day I reduce the time gap to the latest node by 2 hours compared to the previous day.

below is the machine specifications:
Standard DS12 v2 (4 vcpu，28 GiB 内存)

![image](https://github.com/maticnetwork/bor/assets/18640629/25a2a3cc-c29d-48ce-9e18-601688ad7bde)

and I am sure network speed is not a bottleneck.

**Comment by git-ljm** [comment]
> > Main servers stayed healthy. We changed RPC batching in the app from `250` to `100` and that seems to have helped a ton.
> > This issue can be closed.
> 
> how can I do the same thing? I am synchronizing the blockchain, and each day I reduce the time gap to the latest node by 2 hours compared to the previous day.
> 
> below is the machine specifications: Standard DS12 v2 (4 vcpu，28 GiB 内存)
> 
> ![image](https://user-images.githubusercontent.com/18640629/260891556-25a2a3cc-c29d-48ce-9e18-601688ad7bde.png)
> 
> and I am sure network speed is not a bottleneck.

I have the same problem.

**Comment by thorsteneb** [comment]
You have a different problem, if you're not pointing an RPC app at the node yet.

Your main issue is that you are under-sized, by a lot, with your hardware. We run ours on OVH Advance-3: 12-core/24-thread Ryzen 5900X, 64 GiB RAM, 7.6 TB NVMe. Baremetal means it's affordable and fast.

If you're married to running this as a cloud instance, you need something comparable for cores, RAM and IOPS.
