### ISSUE TITLE
Issue while syncing Bor

### ISSUE THREAD

**Issue by HiiiiD** [maticnetwork/bor#909]
#### **System information**

Bor client version: 0.3.9

Heimdall client version: 0.3.4

OS & Version: Official Docker Images (Alpine Linux based)

Environment: Polygon Mainnet

Type of node: Archive

Additional Information:

#### **Overview of the problem**

We tried to setup a Polygon Archive Node with Heimdall and Bor.
In order to speed up the syncing process, we tried to restore the state from the official polygon snapshots.
While Heimdall seems to stay in sync with the blockchain, Bor is always failing with multiple different errors:
- `could not apply tx ... nonce too high`
- `could not apply tx ... insufficient funds for gas * price + value`
It's happening on the same block (43113156) and at every restart I see a different error

#### **Reproduction Steps**

None that we can define.

#### **Logs / Traces / Output / Error Messages**
 
```
########## BAD BLOCK #########
Chain config: {ChainID: 137 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Arrow Glacier: <nil>, MergeFork: <nil>, Terminal TD: <nil>, Engine: bor}
Number: 43113156
Hash: 0x04504f4f39e4f95972d07ac9a0acd74cf352d2cf7c8d4f304288524713b8e78a
Error: could not apply tx 13 [0x9ccb696f188a9b367ca9d6992b78beadb5cececb03fd140dc4af3fc6d5af4129]: nonce too high: address 0xad765F98D6584C41D2A4b678bE8d7496d7B85057, tx: 544 state: 0
##############################
```
Or
```
########## BAD BLOCK #########
Chain config: {ChainID: 137 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Arrow Glacier: <nil>, MergeFork: <nil>, Terminal TD: <nil>, Engine: bor}
Number: 43113156
Hash: 0x04504f4f39e4f95972d07ac9a0acd74cf352d2cf7c8d4f304288524713b8e78a
Error: could not apply tx 51 [0x93f5b7d1d83ac287b1c7829fda2511a22383c08a77b773ea1a662539d1ebd4a8]: insufficient funds for gas * price + value: address 0x5412D045f2246c20795f46e280cBA5801e59ff98 have 0 want 182007091730336704000
##############################
```

**Additional Information**

**Comment by 0x090909** [comment]
the database must be corrupted, try to download again

**Comment by Raneet10** [comment]
Hi @HiiiiD are you still facing this issue ?

**Comment by HiiiiD** [comment]
I've ran `bor removedb` but it didn't work because it stopped again at around block 9 milione, so I decided to clear all the folders inside `bor` and then restart again.

**Comment by Raneet10** [comment]
Okay I see. Also hope you used the incremental snapshot mechanism as given [here](https://wiki.polygon.technology/docs/pos/reference/snapshot-instructions-heimdall-bor/) ?

**Comment by HiiiiD** [comment]
For this last attempt I decided to not use any snapshot, but yes, in the first place I used that mechanism
