### ISSUE TITLE
missing checkpoint blocks

### ISSUE THREAD

**Issue by EWIT521** [maticnetwork/bor#928]
bor ,log info:
INFO [07-10|08:49:36.601] TxFetcher                                txArrivalWait=500ms
WARN [07-10|08:49:36.604] unable to whitelist checkpoint - first run err="missing checkpoint blocks"

My question is ,how to set checkpoint blocks?

**Comment by Raneet10** [comment]
Hey @EWIT521 this is a common occurrence when your node is syncing or has fallen behind.

**Comment by leoenes** [comment]
I'm facing the same problem.

**Comment by VAIBHAVJINDAL3012** [comment]
@leones As Raneet mentioned in previous reply, it is common to have such logs when your chain is not in sync.

**Comment by manav2401** [comment]
Hi @EWIT521 @leoenes, as Raneet and Vaibhav mentioned, the log is expected if your node is out of sync. 

Basically, checkpoints are processed on heimdall and sent on Ethereum. Bor fetches the latest checkpoint to whitelist it locally and follow the correct fork. If bor while syncing haven't yet reached the block which is equal or more than the last checkpoint block, it will not whitelist this checkpoint. As it's a background process, it won't harm any additional mechanism in your node. Closing this for now as this seems to be answered, feel free to reopen.
