### ISSUE TITLE
Missing receipts and transactions？

### ISSUE THREAD

**Issue by taoyouxian** [maticnetwork/bor#936]
Our team wants to run a validator node, when bor completes the syncing period, I can not query the receipts or transactions before the number 30000000, but the blocks before have transactions when I use `eth_getBlockByNumber`.

**Comment by Raneet10** [comment]
Hi @taoyouxian what value have you set for `txlookuplimit` ? I guess it's `2350000` by default , so you'll probably have to increase the limit or set to 0 to index txs for the entire chain.
