### ISSUE TITLE
Blocks in testnet stuck at blockheight 38127835 since Jul-20-2023 02:01:01 AM +UTC

### ISSUE THREAD

**Issue by milc0x** [maticnetwork/bor#937]
Blocks in Mumbai has no update since Jul-20-2023 02:01:01 AM +UTC.
The lastest block shown in polygonscan(testnet) is 38127835, and synchronization of my bor nodes also stuck at block 38,127,839.
Did the develop team of polygon detect this problem?
I wannna know when this issue will be restored.

**Comment by maoueh** [comment]
The chain has recovered, but I've seen nowhere explanations of what happened.

**Comment by anshalshukla** [comment]
It was a heimdall P2P issue, more details can be found [here](https://forum.polygon.technology/t/mumbai-downtime-notice/12633)
