### ISSUE TITLE
bor node stuck without any error msg

### ISSUE THREAD

**Issue by RyanWang0811** [maticnetwork/bor#939]
#### **System information**

Bor client version: v0.4.0

Heimdall client version: v0.3.4

OS & Version:  Linux (Ubuntu20.04)

Environment: Polygon Mainnet

Type of node:  Sentry

Additional Information: 

#### **Overview of the problem**

Please describe the issue you experiencing.

After the hard fork upgrade, I upgrade my node from v0.3.3 to v0.4.0.

Sometimes the node is stuck. When the node is stuck, the block number is fixed in number, and I only see the log below.

I keep it for 20 hrs, but it still did not sync any new blocks.

This problem happens once a week.

#### **Reproduction Steps**

Sorry, I can't reproduce it.

#### **Logs / Traces / Output / Error Messages**
 
```
Jul 21 09:35:18 polygon02 bor[3966168]: WARN [07-21|09:35:18.517] Served eth_call                          reqid=151007   duration="178.765µs"  err="header not found"
Jul 21 09:35:38 polygon02 bor[3966168]: WARN [07-21|09:35:38.617] Served eth_call                          reqid=151014   duration="144.447µs"  err="header not found"
Jul 21 09:35:46 polygon02 bor[3966168]: WARN [07-21|09:35:46.515] Served eth_call                          reqid=151018   duration="135.244µs"  err="header not found"
Jul 21 09:35:50 polygon02 bor[3966168]: WARN [07-21|09:35:50.626] Served eth_call                          reqid=151020   duration="115.106µs"  err="header not found"
Jul 21 09:36:02 polygon02 bor[3966168]: WARN [07-21|09:36:02.658] Served eth_call                          reqid=151025   duration="162.55µs"   err="header not found"
Jul 21 09:36:08 polygon02 bor[3966168]: WARN [07-21|09:36:08.926] Served eth_call                          reqid=151029   duration="161.963µs"  err="header not found"
Jul 21 09:36:26 polygon02 bor[3966168]: WARN [07-21|09:36:26.373] Served eth_call                          reqid=151035   duration="160.964µs"  err="header not found"
Jul 21 09:36:40 polygon02 bor[3966168]: WARN [07-21|09:36:40.639] unable to whitelist checkpoint           err="missing checkpoint blocks"
Jul 21 09:36:44 polygon02 bor[3966168]: WARN [07-21|09:36:44.963] Served eth_call                          reqid=151043   duration="160.141µs"  err="header not found"
Jul 21 09:36:52 polygon02 bor[3966168]: WARN [07-21|09:36:52.458] Served eth_call                          reqid=151046   duration="141.194µs"  err="header not found"
Jul 21 09:36:56 polygon02 bor[3966168]: WARN [07-21|09:36:56.564] Served eth_call                          reqid=151048   duration="131.4µs"    err="header not found"
Jul 21 09:36:56 polygon02 bor[3966168]: WARN [07-21|09:36:56.564] Served eth_call                          reqid=151049   duration="153.219µs"  err="header not found"
Jul 21 09:37:00 polygon02 bor[3966168]: WARN [07-21|09:37:00.837] Served eth_call                          reqid=151052   duration="113.528µs"  err="header not found"
Jul 21 09:37:18 polygon02 bor[3966168]: WARN [07-21|09:37:18.552] Served eth_call                          reqid=151059   duration="144.569µs"  err="header not found"
Jul 21 09:37:20 polygon02 bor[3966168]: WARN [07-21|09:37:20.620] Served eth_call                          reqid=151060   duration="129.117µs"  err="header not found"
Jul 21 09:37:24 polygon02 bor[3966168]: WARN [07-21|09:37:24.519] Served eth_call                          reqid=151063   duration="161.161µs"  err="header not found"
Jul 21 09:37:26 polygon02 bor[3966168]: WARN [07-21|09:37:26.568] Served eth_call                          reqid=151064   duration="127.583µs"  err="header not found"
Jul 21 09:37:42 polygon02 bor[3966168]: WARN [07-21|09:37:42.642] Served eth_call                          reqid=151071   duration="134.231µs"  err="header not found"
Jul 21 09:37:52 polygon02 bor[3966168]: WARN [07-21|09:37:52.532] Served eth_call                          reqid=151075   duration="154.626µs"  err="header not found"
Jul 21 09:37:54 polygon02 bor[3966168]: WARN [07-21|09:37:54.700] Served eth_call                          reqid=151077   duration="120.84µs"   err="header not found"
Jul 21 09:38:00 polygon02 bor[3966168]: WARN [07-21|09:38:00.427] Served eth_call                          reqid=151080   duration="157.269µs"  err="header not found"
Jul 21 09:38:02 polygon02 bor[3966168]: WARN [07-21|09:38:02.360] Served eth_call                          reqid=151081   duration="109.591µs"  err="header not found"
Jul 21 09:38:10 polygon02 bor[3966168]: WARN [07-21|09:38:10.553] Served eth_call                          reqid=151085   duration="164.272µs"  err="header not found"
Jul 21 09:38:14 polygon02 bor[3966168]: WARN [07-21|09:38:14.908] Served eth_call                          reqid=151088   duration="122.192µs"  err="header not found"
Jul 21 09:38:20 polygon02 bor[3966168]: WARN [07-21|09:38:20.639] unable to whitelist checkpoint           err="missing checkpoint blocks"
Jul 21 09:38:28 polygon02 bor[3966168]: WARN [07-21|09:38:28.533] Served eth_call                          reqid=151093   duration="158.249µs"  err="header not found"
Jul 21 09:38:30 polygon02 bor[3966168]: WARN [07-21|09:38:30.541] Served eth_call                          reqid=151095   duration="126.595µs"  err="header not found"
Jul 21 09:38:32 polygon02 bor[3966168]: WARN [07-21|09:38:32.768] Served eth_call                          reqid=151096   duration="123.677µs"  err="header not found"
Jul 21 09:38:34 polygon02 bor[3966168]: WARN [07-21|09:38:34.407] Served eth_call                          reqid=151098   duration="116.196µs"  err="header not found"
Jul 21 09:38:42 polygon02 bor[3966168]: WARN [07-21|09:38:42.519] Served eth_call                          reqid=151102   duration="153.039µs"  err="header not found"
Jul 21 09:38:52 polygon02 bor[3966168]: WARN [07-21|09:38:52.708] Served eth_call                          reqid=151106   duration="155.696µs"  err="header not found"
Jul 21 09:38:58 polygon02 bor[3966168]: WARN [07-21|09:38:58.777] Served eth_call                          reqid=151109   duration="111.044µs"  err="header not found"
Jul 21 09:39:18 polygon02 bor[3966168]: WARN [07-21|09:39:18.826] Served eth_call                          reqid=151117   duration="161.807µs"  err="header not found"

```

**Additional Information**

bor.service

```
[Unit]
  Description=bor
  StartLimitIntervalSec=500
  StartLimitBurst=5

[Service]
  Restart=on-failure
  RestartSec=5s
ExecStart=/usr/bin/bor server --syncmode=full --cache 8192 --datadir=/media/defi/bor --bor.heimdall=http://127.0.0.1:1317 --miner.gaslimit=200000000 --http --http.addr=0.0.0.0 --http.port=8515 --http.api=eth,net,web3,admin,debug,bor --http.corsdomain=* --http.vhosts=* --graphql --graphql.vhosts=* --ws --ws.addr=0.0.0.0 --ws.port=8516 --ws.api=eth,net,web3,admin,debug,bor --ws.origins=* --rpc.txfeecap=50
  Type=simple
  KillSignal=SIGINT
  User=bor
  TimeoutStopSec=120

[Install]
  WantedBy=multi-user.target

```

**Comment by dubuqingfeng** [comment]
I will also encounter similar problems, and restarting will solve them. Why specifically?

**Comment by anshalshukla** [comment]
Can you check your peer count while your node is stuck?

**Comment by RyanWang0811** [comment]
I call the `net_peerCount` method to get the peer count, and the peer count is 50. 
I try to call the `admin_peers` method, which also has 50 peers.

**Comment by anshalshukla** [comment]
Can you also check if Heimdall is in sync? You can curl `http://localhost:1317/syncing` API to check the status.

**Comment by RyanWang0811** [comment]
Heimdall is normal and curl `http://localhost:1317/syncing` return `{"syncing":false}`.

Heimdall still has the `Executed block` and `Committed state` log message.

Is it possible bor node has something locked or goroutine dead without any panic msg?

**Comment by anshalshukla** [comment]
Highly unlikely, can you try restarting the bor node?

**Comment by anshalshukla** [comment]
If that also doesn't work, try adding some bootnodes from [here](https://wiki.polygon.technology/docs/pos/operate/node/full-node-deployment/)

**Comment by RyanWang0811** [comment]
If I restart bor node the node can be synced, but I will get the ` Enabling snapshot recovery ` message, and the block Number start from an earlier block Number than the node stuck.

I set the bootnodes since I created the node.

**Comment by RyanWang0811** [comment]
OK, Thanks for your suggestion. I have set bootnode param today. Let me observe for a few days. If have any issues with it, I will keep updated on this issue.

**Comment by RyanWang0811** [comment]
After a week it still happens the issue...

My polygon bor node is stuck at `2023-08-26 08:13:43 (blocknumber: 46769396)`

I enabled the debug log (`verbosity=4`) and found some messages.

(Normal) After printing `Inserting downloaded chain`, it will start to insert the block and print `Inserted new block`.

```log
Aug 26 08:13:30 DEBUG[08-26|08:13:30.463] Inserting downloaded chain               items=3          firstnum=46,769,389 firsthash=8ead72..d78f07 lastnum=46,769,391 lasthash=a97983..62cc58
Aug 26 08:13:30 DEBUG[08-26|08:13:30.543] Inserted new block                       number=46,769,389 hash=8ead72..d78f07 uncles=0 txs=6    gas=27,865,733 elapsed=79.477ms     root=691da2..18188f
Aug 26 08:13:30 DEBUG[08-26|08:13:30.644] Inserted new block                       number=46,769,390 hash=380f4d..d943bd uncles=0 txs=37   gas=29,857,702 elapsed=99.931ms     root=c77298..000aa9
Aug 26 08:13:30 DEBUG[08-26|08:13:30.701] Inserted new block                       number=46,769,391 hash=a97983..62cc58 uncles=0 txs=34   gas=7,363,752  elapsed=56.717ms     root=75f361..0678cd
```


(stuck) only print `Inserting downloaded chain`, and no `Inserted new block` log until I restart the bor node.

```log
Aug 26 08:13:43 DEBUG[08-26|08:13:43.141] Inserting downloaded chain               items=2          firstnum=46,769,397 firsthash=9ab29f..e4abb2 lastnum=46,769,398 lasthash=aa353d..7f57c7
```

Is it possible something locked during the insert process?

Maybe the lock is happening on this function?

https://github.com/maticnetwork/bor/blob/16746a73faa5dd99ae81f0583cb16ddfd3163d77/core/blockchain.go#L1625-L1633


start cmd:

```sh
/usr/bin/bor server 
    --syncmode=full 
    --cache 8192 
    --datadir=/media/defi/bor 
    --bor.heimdall=http://127.0.0.1:1317 
    --miner.gaslimit=200000000 
    --http 
    --http.addr=0.0.0.0 
    --http.port=8515 
    --http.api=eth,net,web3,admin,debug,bor 
    --http.corsdomain=* 
    --http.vhosts=* 
    --graphql 
    --graphql.vhosts=* 
    --ws 
    --ws.addr=0.0.0.0 
    --ws.port=8516 
    --ws.api=eth,net,web3,admin,debug,bor 
    --ws.origins=* 
    --rpc.txfeecap=50 
    --bootnodes=enode://b8f1cc9c5d4403703fbf377116469667d2b1823c0daf16b7250aa576bacf399e42c3930ccfcb02c5df6879565a2b8931335565f0e8d3f8e72385ecf4a4bf160a@3.36.224.80:30303,enode://8729e0c825f3d9cad382555f3e46dcff21af323e89025a0e6312df541f4a9e73abfa562d64906f5e59c51fe6f0501b3e61b07979606c56329c020ed739910759@54.194.245.5:30303 
    --verbosity=4
```

**Comment by cffls** [comment]
Hi @RyanWang0811 , dead lock could be a potential cause. To help troubleshoot this issue, could you try killing the bor process when it got stuck, using this command "kill -QUIT <pid>", where <pid> is the process id of bor. It will print a stack trace, which tells us what the program was doing when it got stuck.

**Comment by RyanWang0811** [comment]
Yesterday, the node stuck again, and I used the node provides `debug pprof` cmd to dump the pprof traces data.

https://github.com/maticnetwork/bor/blob/develop/docs/cli/debug_pprof.md
 
I used `go tool pprof -http=:6060 mutex.prof `  on  mutex.prof and found  that  `runReorg func` spent a long time Unlock

![image](https://github.com/maticnetwork/bor/assets/17406219/88c17b49-071e-4882-8b41-f30ff8daf011)

Is it normal? Or does It have something deadlock on it?

**Comment by andrewpaulicek** [comment]
We're having the same issue on our 5 nodes.

**Comment by RyanWang0811** [comment]
@andrewpaulicek  Maybe We can share some info with each other and find the possible cause.

- We build the polygon bor node on AWS Tokyo region.
- We use both HTTP and WebSocket endpoints.
- After restart the node usually starts syncing from the far block number and has some log like this
```
Sep  2 05:59:08 : INFO [09-02|05:59:08.442] Loaded most recent local header          number=47,043,854 hash=539f0d..b11760 td=817,996,798 age=13m50s
Sep  2 05:59:08 : INFO [09-02|05:59:08.442] Loaded most recent local full block      number=47,011,951 hash=c65055..ac0f10 td=817,231,772 age=19h29m35s
Sep  2 05:59:08 : INFO [09-02|05:59:08.442] Loaded most recent local fast block      number=47,043,854 hash=539f0d..b11760 td=817,996,798 age=13m50s
```
- I tried to use  `kill -QUIT pid` to dump all goroutine, but not see any suspect code. (See the attachment) 
[coredump.txt](https://github.com/maticnetwork/bor/files/12535683/coredump.txt)

**Comment by RyanWang0811** [comment]
Following the coredump which I uploaded, I found something possible cause.

  - `goroutine 153286905` stop at github.com/ethereum/go-ethereum/event.(*Feed).Send
  - `goroutine 153310582` stop at github.com/ethereum/go-ethereum/internal/syncx.(*ClosableMutex).TryLock(...)
  - `goroutine 153305343` stop at github.com/ethereum/go-ethereum/internal/syncx.(*ClosableMutex).TryLock(...)
  
`goroutine 153310582` and `goroutine 153305343`  are waiting for `goroutine 153286905` process end.

- Tracking where `goroutine 153286905` stops [event/feed.go Send()](https://github.com/maticnetwork/bor/blob/16746a73faa5dd99ae81f0583cb16ddfd3163d77/event/feed.go#L128) There are two goroutines that stop here


  - `goroutine 153286905` called by `importBlocks` and stop at `github.com/ethereum/go-ethereum/event.(*Feed).Send`.
  - `feed.go Send()` called by [core/blockchain.go#L1649](https://github.com/maticnetwork/bor/blob/16746a73faa5dd99ae81f0583cb16ddfd3163d77/core/blockchain.go#L1649)

  ```log
    goroutine 153286905 [select, 13 minutes]:
    runtime.gopark(0xc03e821680?, 0x2?, 0x78?, 0xc2?, 0xc107bc94dc?)
    #011/home/ubuntu/actions-runner/_work/_tool/go/1.19.7/x64/src/runtime/proc.go:363 +0xd6 fp=0xc0816bc250 sp=0xc0816bc230 pc=0x453bb6
    runtime.selectgo(0xc03e821680, 0xc107bc94d8, 0xc000482820?, 0x1, 0xc0816bc3e0?, 0x1)
    #011/home/ubuntu/actions-runner/_work/_tool/go/1.19.7/x64/src/runtime/select.go:328 +0x7bc fp=0xc0816bc390 sp=0xc0816bc250 pc=0x463a9c
    reflect.rselect({0xc0816bc508, 0x2, 0x48e?})
    #011/home/ubuntu/actions-runner/_work/_tool/go/1.19.7/x64/src/runtime/select.go:590 +0x23e fp=0xc0816bc430 sp=0xc0816bc390 pc=0x48141e
    reflect.Select({0xc0143d01a0?, 0x2, 0xa70070?})
    #011/home/ubuntu/actions-runner/_work/_tool/go/1.19.7/x64/src/reflect/value.go:2952 +0xd2 fp=0xc0816bc598 sp=0xc0816bc430 pc=0x5077d2
    github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc000f5d580, {0x219b420?, 0xc16821a630?})
    #011/home/ubuntu/actions-runner/_work/bor/bor/event/feed.go:170 +0x478 fp=0xc0816bc750 sp=0xc0816bc598 pc=0xa52bb8
    github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain.func1()
    #011/home/ubuntu/actions-runner/_work/bor/bor/core/blockchain.go:1649 +0x10f fp=0xc0816bc7e8 sp=0xc0816bc750 pc=0xa7534f
    runtime.deferreturn()
    #011/home/ubuntu/actions-runner/_work/_tool/go/1.19.7/x64/src/runtime/panic.go:476 +0x33 fp=0xc0816bc828 sp=0xc0816bc7e8 pc=0x44f913
    github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc000f5d400, {0xc14c56dcb0, 0x1, 0x1}, 0x1, 0x1)
    #011/home/ubuntu/actions-runner/_work/bor/bor/core/blockchain.go:2004 +0x3bdb fp=0xc0816bd580 sp=0xc0816bc828 pc=0xa73e3b
    github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc000f5d400, {0xc14c56dcb0?, 0x1, 0x1})
    #011/home/ubuntu/actions-runner/_work/bor/bor/core/blockchain.go:1622 +0xb51 fp=0xc0816bd928 sp=0xc0816bd580 pc=0xa70071
    github.com/ethereum/go-ethereum/eth.newHandler.func4({0xc14c56dcb0?, 0x1, 0x1})
    #011/home/ubuntu/actions-runner/_work/bor/bor/eth/handler.go:296 +0x6b9 fp=0xc0816bdc50 sp=0xc0816bd928 pc=0x198ffb9
    github.com/ethereum/go-ethereum/eth/fetcher.(*BlockFetcher).importBlocks.func1()
    #011/home/ubuntu/actions-runner/_work/bor/bor/eth/fetcher/block_fetcher.go:871 +0x5a9 fp=0xc0816bdfe0 sp=0xc0816bdc50 pc=0x197b569
    runtime.goexit()
    #011/home/ubuntu/actions-runner/_work/_tool/go/1.19.7/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0816bdfe8 sp=0xc0816bdfe0 pc=0x485a41
    created by github.com/ethereum/go-ethereum/eth/fetcher.(*BlockFetcher).importBlocks
    #011/home/ubuntu/actions-runner/_work/bor/bor/eth/fetcher/block_fetcher.go:845 +0x3de
  ```


  - `goroutine 153459764` called by `scheduleReorgLoop` and stop at `github.com/ethereum/go-ethereum/event.(*Feed).Send`.
  - `feed.go Send()` called by  [core/tx_pool.go#L1707](https://github.com/maticnetwork/bor/blob/16746a73faa5dd99ae81f0583cb16ddfd3163d77/core/tx_pool.go#L1707)

  ```log
  goroutine 153459764 [select, 11 minutes]:
  runtime.gopark(0xc1109918c0?, 0x2?, 0x59?, 0xb4?, 0xc16d6b998c?)
  #011/home/ubuntu/actions-runner/_work/_tool/go/1.19.7/x64/src/runtime/proc.go:363 +0xd6 fp=0xc00dd972c0 sp=0xc00dd972a0 pc=0x453bb6
  runtime.selectgo(0xc1109918c0, 0xc16d6b9988, 0xc011ec7d40?, 0x1, 0xc00dd97450?, 0x1)
  #011/home/ubuntu/actions-runner/_work/_tool/go/1.19.7/x64/src/runtime/select.go:328 +0x7bc fp=0xc00dd97400 sp=0xc00dd972c0 pc=0x463a9c
  reflect.rselect({0xc00dd97578, 0x2, 0x2a6e458?})
  #011/home/ubuntu/actions-runner/_work/_tool/go/1.19.7/x64/src/runtime/select.go:590 +0x23e fp=0xc00dd974a0 sp=0xc00dd97400 pc=0x48141e
  reflect.Select({0xc02e76fb20?, 0x2, 0xc00dd97680?})
  #011/home/ubuntu/actions-runner/_work/_tool/go/1.19.7/x64/src/reflect/value.go:2952 +0xd2 fp=0xc00dd97608 sp=0xc00dd974a0 pc=0x5077d2
  github.com/ethereum/go-ethereum/event.(*Feed).Send(0xc00da3d738, {0x219b5a0?, 0xc0cb3bff08?})
  #011/home/ubuntu/actions-runner/_work/bor/bor/event/feed.go:170 +0x478 fp=0xc00dd977c0 sp=0xc00dd97608 pc=0xa52bb8
  github.com/ethereum/go-ethereum/core.(*TxPool).runReorg.func1.10({0xc00dd978d0?, 0x464934?}, {0x48518a0?, 0x48623c8?})
  #011/home/ubuntu/actions-runner/_work/bor/bor/core/tx_pool.go:1707 +0x18b fp=0xc00dd978a8 sp=0xc00dd977c0 pc=0xaa85cb
  github.com/ethereum/go-ethereum/common/tracing.ElapsedTime({0x30c3bc8?, 0xc20ca08600?}, {0x30d31c0?, 0xc007108fa0?}, {0x2495426, 0x9}, 0xc00dd97a88?)
  #011/home/ubuntu/actions-runner/_work/bor/bor/common/tracing/context.go:91 +0xd1 fp=0xc00dd979b8 sp=0xc00dd978a8 pc=0x9f86f1
  github.com/ethereum/go-ethereum/core.(*TxPool).runReorg.func1({0x30c3bc8, 0xc20ca08600}, {0x30d31c0?, 0xc007108fa0?})
  #011/home/ubuntu/actions-runner/_work/bor/bor/core/tx_pool.go:1700 +0xb72 fp=0xc00dd97e68 sp=0xc00dd979b8 pc=0xaa83b2
  github.com/ethereum/go-ethereum/common/tracing.Exec({0x30c3b58, 0xc000150040}, {0x2499a76, 0xb}, {0x249ca7f, 0xc}, {0xc00dd97f50, 0x1, 0xc06d3d67d0?})
  #011/home/ubuntu/actions-runner/_work/bor/bor/common/tracing/context.go:70 +0x20e fp=0xc00dd97f08 sp=0xc00dd97e68 pc=0x9f854e
  github.com/ethereum/go-ethereum/core.(*TxPool).runReorg(0xc06d3d67d0?, {0x30c3b58?, 0xc000150040?}, 0x40?, 0xc0f02d8c08?, 0x3?, 0x0?)
  #011/home/ubuntu/actions-runner/_work/bor/bor/core/tx_pool.go:1542 +0xb2 fp=0xc00dd97f98 sp=0xc00dd97f08 pc=0xaa77d2
  github.com/ethereum/go-ethereum/core.(*TxPool).scheduleReorgLoop.func2()
  #011/home/ubuntu/actions-runner/_work/bor/bor/core/tx_pool.go:1484 +0x3e fp=0xc00dd97fe0 sp=0xc00dd97f98 pc=0xaa75fe
  runtime.goexit()
  #011/home/ubuntu/actions-runner/_work/_tool/go/1.19.7/x64/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc00dd97fe8 sp=0xc00dd97fe0 pc=0x485a41
  created by github.com/ethereum/go-ethereum/core.(*TxPool).scheduleReorgLoop
  #011/home/ubuntu/actions-runner/_work/bor/bor/core/tx_pool.go:1484 +0x1fb
  ```

Maybe caused by `goroutine 153286905` 和 `goroutine 153459764` call feed.go Send() at the same time，but [feed.go#L132](https://github.com/maticnetwork/bor/blob/16746a73faa5dd99ae81f0583cb16ddfd3163d77/event/feed.go#L132) should be lock.
There Shouldn't be two goroutines available to call at the same time. Right?

**Comment by fkbenjamin** [comment]
I can also confirm our nodes running into the same issue as described here. Heimdall is fine at the same time. 

We're running the node on virtualized bare metal with plenty of resources, so that doesn't seem to be related to the issue.

**Comment by cffls** [comment]
Thanks @RyanWang0811 for providing the pprof data and core dump. The observation of feed lock is interesting, but goroutine 153286905 and goroutine 153459764 were using different feeds. One (153286905) uses chainHeadFeed and the other (153459764) uses txFeed, so I am not sure if they are causing dead lock here. Anyway, there could be deadlock somewhere else. Will look further into this.

One more thing we can check is the size of your database. Could you check the total size of `chaindata` directory? Sometimes db can grow too big if not pruned frequently, and bor could spend much time in db compaction.

**Comment by RyanWang0811** [comment]
The total size of  `chaindata` directory is 2.7 TB.
```
# du -sh bor/chaindata/
2.7T	bor/chaindata/
```

**Comment by kryptoklob** [comment]
Also experiencing this issue, so I deleted the entire chaindata folder and resynced from the latest snapshot. This did not solve the problem and I'm full @ 250 peers but no syncing.

`/bor/chaindata` size currently 2.5 TB.

Stuck on block 46,969,854

**Comment by andrewpaulicek** [comment]
> @andrewpaulicek Maybe We can share some info with each other and find the possible cause.
> 
> * We build the polygon bor node on AWS Tokyo region.
> * We use both HTTP and WebSocket endpoints.
> * After restart the node usually starts syncing from the far block number and has some log like this
> 
> ```
> Sep  2 05:59:08 : INFO [09-02|05:59:08.442] Loaded most recent local header          number=47,043,854 hash=539f0d..b11760 td=817,996,798 age=13m50s
> Sep  2 05:59:08 : INFO [09-02|05:59:08.442] Loaded most recent local full block      number=47,011,951 hash=c65055..ac0f10 td=817,231,772 age=19h29m35s
> Sep  2 05:59:08 : INFO [09-02|05:59:08.442] Loaded most recent local fast block      number=47,043,854 hash=539f0d..b11760 td=817,996,798 age=13m50s
> ```
> 
> * I tried to use  `kill -QUIT pid` to dump all goroutine, but not see any suspect code. (See the attachment)
>   [coredump.txt](https://github.com/maticnetwork/bor/files/12535683/coredump.txt)

We are seeing the same issue I think. We are also using both ws and HTTP.

I have been trying out this version on a couple of servers https://github.com/maticnetwork/bor/releases/tag/v0.5.0, and it looks a bit better on our side. Can you maybe give it a try as well to see if it helps on your side?

**Comment by kryptoklob** [comment]
Just tried `v0.5.0` and getting the same issue.

<img width="556" alt="image" src="https://github.com/maticnetwork/bor/assets/8293474/affeb55d-1544-49d3-a9ef-757bd5f311c6">

Output is mostly just this.

**Comment by kryptoklob** [comment]
Update: after setting the bootnodes from what I had when I built the node originally (what the instructions said for v0.3.4) to what the site says now (for v0.4.0) it started syncing. It's odd to me that the previously bad bootnodes gave no error indication at all, but happy to be syncing again.

For reference the working bootnodes I used:

```
enode://b8f1cc9c5d4403703fbf377116469667d2b1823c0daf16b7250aa576bacf399e42c3930ccfcb02c5df6879565a2b8931335565f0e8d3f8e72385ecf4a4bf160a@3.36.224.80:30303,enode://8729e0c825f3d9cad382555f3e46dcff21af323e89025a0e6312df541f4a9e73abfa562d64906f5e59c51fe6f0501b3e61b07979606c56329c020ed739910759@54.194.245.5:30303
```

**Comment by kryptoklob** [comment]
> Bootnodes have been recently updated so checking them once would be good.

This was key. Though it's odd the older bootnodes caused it to silently fail / not sync.

**Comment by cffls** [comment]
Thanks @kryptoklob for providing the info. It is important to use the correct bootnode, otherwise the node will have trouble finding good peers. I raised a PR to update default bootnode in bor: https://github.com/maticnetwork/bor/pull/997 

@RyanWang0811 could you try using the bootnodes provided by @kryptoklob in the [above comment](https://github.com/maticnetwork/bor/issues/939#issuecomment-1712960936)?

**Comment by RyanWang0811** [comment]
@cffls According to I [past comment](https://github.com/maticnetwork/bor/issues/939#issuecomment-1695477406) provided start cmd I have already used this bootnodes setting but it still has this issue.

**Comment by andrewpaulicek** [comment]
We are also running our nodes with the correct bootnodes and seeing the issues.

**Comment by andrewpaulicek** [comment]
@RyanWang0811 We have tried running a couple of nodes under systemd with erlang and RabbitMQ installed
(https://wiki.polygon.technology/docs/pos/operate/validator/kb/how-to/#install-rabbitmq), and it looks much more stable for us. Not sure if it's just a coincidence, but after 12 hours we have three running nodes still.

**Comment by andrewpaulicek** [comment]
> @RyanWang0811 We have tried running a couple of nodes under systemd with erlang and RabbitMQ installed (https://wiki.polygon.technology/docs/pos/operate/validator/kb/how-to/#install-rabbitmq), and it looks much more stable for us. Not sure if it's just a coincidence, but after 12 hours we have three running nodes still.

Unfortunately, nodes went down again, so the the new version (v0.5.0) does not contain the fix to our issues :(

**Comment by kryptoklob** [comment]
Update: After setting the correct bootnodes the node ran fine for 2 days, but is no longer syncing. No error messages as usual.

**Comment by RyanWang0811** [comment]
>@RyanWang0811 We have tried running a couple of nodes under systemd with erlang and RabbitMQ installed
>(https://wiki.polygon.technology/docs/pos/operate/validator/kb/how-to/#install-rabbitmq), and it looks much more stable for us. >Not sure if it's just a coincidence, but after 12 hours we have three running nodes still.

In our use case, We don't need Validator node, so maybe this isn't relevant.


>Unfortunately, nodes went down again, so the new version (v0.5.0) does not contain the fix to our issues :(

That is a bad news. :(

> Update: After setting the correct bootnodes the node ran fine for 2 days, but is no longer syncing. No error messages as usual.

Right, so I don't think this issue is about bootnodes setting.

---
I have two little found for this issue. Maybe this is useful for finding the root cause.

1. After adding some logs myself, I found the lock on may happen on this line
    https://github.com/maticnetwork/bor/blob/16746a73faa5dd99ae81f0583cb16ddfd3163d77/core/blockchain.go#L1649
    
    The code run into `chainHeadFeed.Send(ChainHeadEvent{lastCanon})` function and stuck. But I didn't see any ChainHeadEvent sent at the same time, or maybe just I didn't find it.

2. I have another found but I am not very sure, it seems this issue only happens when using the WebSocket to connect the node. If I connect the node only using HTTP, the node will not be stuck, but if I use both HTTP and WS the node will have this issue.

**Comment by RyanWang0811** [comment]
Does anyone try to use the new versions `Bor v1.0.4` and `Heimdall v1.0.1`?

I want to try it, but I found this issue  
https://github.com/maticnetwork/heimdall/issues/1066

**Comment by RyanWang0811** [comment]
I successfully installed new versions `Bor v1.0.4` and `Heimdall v1.0.1`. 

Hope that the new version can solve this issue.

**Comment by cffls** [comment]
Bor v1.0.6 and Heimdall v1.0.2 are released. Please upgrade to these versions and let us know if the issue persists or not.

**Comment by anshalshukla** [comment]
@RyanWang0811 can you close the issue if it is fixed

**Comment by marcello33** [comment]
@RyanWang0811 any update?
Can we close the issue?
Thanks
