### ISSUE TITLE
Stuck at "Head state missing, repairing"

### ISSUE THREAD

**Issue by nining** [maticnetwork/bor#941]
I am running bor in podman container.  After a system restart, the bor container stucked at "Head state missing, repairing"

#### **System information**

Bor client version: 0.4.0

Heimdall client version: 0.3.4

OS & Version: Linux

Environment: Polygon Mainnet

Type of node: Validator

#### **Logs / Traces / Output / Error Messages**
 

> WARN [07-25|02:20:15.940] Config File provided, this will overwrite the cli flags path=/bor-home/config.toml
WARN [07-25|02:20:15.943] Config contains both, verbosity and log-level, log-level will be deprecated soon. Use verbosity only. using=3
INFO [07-25|02:20:15.943] GRPC Server started                      addr=[::]:3131
INFO [07-25|02:20:15.944] Set global gas cap                       cap=50,000,000
INFO [07-25|02:20:15.944] Allocated trie memory caches             clean=153.00MiB dirty=256.00MiB
INFO [07-25|02:20:15.944] Allocated cache and file handles         database=/bor-home/bor/chaindata cache=512.00MiB handles=262,144
INFO [07-25|02:20:15.965] Opened ancient database                  database=/bor-home/bor/chaindata/ancient readonly=false
INFO [07-25|02:20:15.987] Persisted trie from memory database      nodes=12 size=1.86KiB time="30.617µs" gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=0.00B
INFO [07-25|02:20:15.989] Initialised chain configuration          config="{ChainID: 137 Homestead: 0 DAO: <nil> DAOSupport: true EIP150: 0 EIP155: 0 EIP158: 0 Byzantium: 0 Constantinople: 0 Petersburg: 0 Istanbul: 3395000, Muir Glacier: 3395000, Berlin: 14750000, London: 23850000, Arrow Glacier: <nil>, MergeFork: <nil>, Terminal TD: <nil>, Engine: bor}"
INFO [07-25|02:20:15.991] Gasprice oracle is ignoring threshold set threshold=2
INFO [07-25|02:20:15.994] Initialising Ethereum protocol           network=137 dbversion=8
INFO [07-25|02:20:16.002] Loaded most recent local header          number=941,823 hash=9541aa..7e6e02 td=6,592,762 age=3y1mo2w
INFO [07-25|02:20:16.002] Loaded most recent local full block      number=941,823 hash=9541aa..7e6e02 td=6,592,762 age=3y1mo2w
INFO [07-25|02:20:16.002] Loaded most recent local fast block      number=941,823 hash=9541aa..7e6e02 td=6,592,762 age=3y1mo2w
WARN [07-25|02:20:16.007] Head state missing, repairing            number=941,823 hash=9541aa..7e6e02 snaproot=01b797..6c5af4

**Comment by anshalshukla** [comment]
@nining can you share the latest update? Ideally it should automatically recover in some time.

**Comment by manav2401** [comment]
@nining a possible reason for this could be unclean shutdown of bor. It should recover from this state and start syncing in some time. Closing this for now, feel free to reopen.

**Comment by BoogalooLi** [comment]
@nining how did you solve it ？I met the same problem and I reopen the bor in docker container.
