### ISSUE TITLE
Issues with prometheus summaries after 0.4.0 bor upgrade

### ISSUE THREAD

**Issue by Aracki** [maticnetwork/bor#955]
After the upgrade we are having really strange issue with all the _counter metrics in summaries, although _sum works as expected.

The strange issue is that all the _counter metrics always show number 6 for value. 

e.g.
```
rpc_duration_eth_hashrate_success_count 6
rpc_duration_net_peerCount_success_count 6
state_snapshot_dirty_account_hit_depth_count 6
state_snapshot_dirty_storage_hit_depth_count 6
txpool_dropbetweenreorg_count 6
txpool_reheap_count 6
txpool_reorgtime_count 6
# TYPE vflux_server_active_count gauge
vflux_server_active_count 0
# TYPE vflux_server_inactive_count gauge
vflux_server_inactive_count 0
```

**Comment by manav2401** [comment]
Thanks for reporting. Fixed in https://github.com/maticnetwork/bor/pull/965. Closing this for now.
