### ISSUE TITLE
Upgrading bor-v*-*64.deb deletes provided files

### ISSUE THREAD

**Issue by etam** [maticnetwork/bor#957]
#### **System information**

Bor client version: 0.4.0

Heimdall client version: not relevant

OS & Version: Ubuntu 20.04

Environment: not relevant

Type of node: not relevant

#### **Overview of the problem**

The `postrm` script in `bor-v0.4.0-amd64.deb` deletes files managed by dpkg.

#### **Reproduction Steps**

1. Install latest 0.3.* bor package (for example `dpkg -i bor-v0.3.9-amd64.deb`)
2. Update to 0.4.0 (`dpkg -i bor-v0.4.0-amd64.deb`)

#### **Logs / Traces / Output / Error Messages**
 
The result is that file `/usr/bin/bor` do not exist

**Additional Information**

The `bor-v0.4.0-amd64.deb` package contains a [`postrm`](https://github.com/maticnetwork/bor/blob/develop/packaging/deb/bor/DEBIAN/postrm) script, that contains
```sh
sudo rm -rf /usr/bin/bor
```

See also #946

**Comment by 0xsharma** [comment]
This issue was fixed in https://github.com/maticnetwork/bor/pull/951 .
