### ISSUE TITLE
I cannot start bor service with error log

### ISSUE THREAD

**Issue by sylviahuang123** [maticnetwork/bor#986]
bor version v0.4.0
heimdaald version 0.3.4
```
Sep 06 01:15:56  bor[26108]: WARN [09-06|01:15:56.198] IPC opening failed                       url=/var/lib/bor/bor.ipc error="listen unix /var/lib/bor/bor.ipc: bind: address already in use"
Sep 06 01:15:59  bor[26108]: listen unix /var/lib/bor/bor.ipc: bind: address already in use
```

**Comment by RyanWang0811** [comment]
Maybe you have started another bor service?  Try `ps -aux | grep bor` to find another bor service.

**Comment by sylviahuang123** [comment]
nope, it didn't response anything, and the port also not be ocuppied

**Comment by manav2401** [comment]
Hey, the error basically means you already have the IPC occupied by some other process. Can you try deleting the IPC file and restarting bor? Or changing the path to a different location?

**Comment by manav2401** [comment]
Closing this for now, feel free to reopen.
