### ISSUE TITLE
The discord invite links are expired

### ISSUE THREAD

**Issue by bytes032** [maticnetwork/bor#988]
Both this

![CleanShot 2023-09-07 at 5 52 29](https://github.com/maticnetwork/bor/assets/122114333/b851801f-a873-45ce-b41d-c9a51ba47761)

and this:

![CleanShot 2023-09-07 at 5 52 55](https://github.com/maticnetwork/bor/assets/122114333/d018457f-ad74-4039-a19b-42addc17e33b)

lead to 

![CleanShot 2023-09-07 at 5 53 13](https://github.com/maticnetwork/bor/assets/122114333/b8c7ae15-1b44-40fc-be8e-4a9cf8826430)

**Comment by 0xsajal** [comment]
Try this link please: https://discord.gg/XyUYuhkf

**Comment by manav2401** [comment]
@bytes032 could you please check the new link posted above. Thanks!

**Comment by manav2401** [comment]
Updated in https://github.com/maticnetwork/bor/pull/1015.
